/* Real browser + official Pi SDK + published ask_user, on loopback fixture data only. */
import assert from 'node:assert/strict'
import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
const root = resolve(process.env.REMOTE_BROWSER_ROOT || '/tmp/lmm-remote-browser')
const config = JSON.parse(await readFile(resolve(root, 'fixture.json'), 'utf8'))
const browser = await chromium.launch({ headless: true })
try {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 })
  const page = await context.newPage()
  const errors = []
  const wire = []
  page.on('pageerror', error => errors.push(String(error)))
  page.on('request', request => { if (request.method() === 'POST') wire.push(request.postData() || '') })
  await page.goto(config.origin, { waitUntil: 'networkidle' })
  await page.getByLabel('PIN', { exact: true }).fill('wrong-pin')
  await page.getByRole('button', { name: '解锁', exact: true }).click()
  await page.getByRole('alert').filter({ hasText: 'PIN 不正确' }).waitFor()
  await page.getByLabel('PIN', { exact: true }).fill(config.pin)
  await page.getByRole('button', { name: '解锁', exact: true }).click()
  await page.getByTestId('provider').filter({ hasText: 'non-lmm-fixture' }).waitFor()
  console.log('PASS: mobile Chromium rejects an incorrect PIN and unlocks the non-LMM Pi session')
  await page.getByLabel('向 Pi 发送任务', { exact: true }).fill('Run the remote ask_user check')
  await page.getByRole('button', { name: '发送任务', exact: true }).click()
  await page.getByLabel('Pi 终端画面', { exact: true }).filter({ hasText: 'Choose a deployment target' }).waitFor({ timeout: 20000 })
  await page.screenshot({ path: resolve(root, 'remote-mobile-question.png'), fullPage: true })
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'mobile horizontal overflow')
  await page.getByRole('button', { name: 'down', exact: true }).click()
  await page.getByRole('button', { name: 'enter', exact: true }).click({ timeout: 15000 })
  await page.getByLabel('会话记录', { exact: true }).filter({ hasText: 'Remote answer received' }).waitFor({ timeout: 20000 })
  console.log('PASS: the browser sent an encrypted task and answered the real pi-ask-user component')
  await page.getByLabel('Pi 终端画面', { exact: true }).filter({ hasText: 'Stop while waiting' }).waitFor({ timeout: 20000 })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: resolve(root, 'remote-desktop-question.png'), fullPage: true })
  await page.getByRole('button', { name: '停止 Pi', exact: true }).click()
  await page.getByLabel('Pi 终端画面', { exact: true }).waitFor({ state: 'detached', timeout: 20000 })
  await page.getByTestId('provider').filter({ hasText: 'another-model' }).waitFor()
  console.log('PASS: browser Stop interrupted the real tool; model changes did not disconnect control')
  await page.getByRole('button', { name: '锁定', exact: true }).click()
  await page.getByLabel('PIN', { exact: true }).waitFor()
  assert.equal(await page.getByText('Staging test', { exact: true }).count(), 0)
  assert.equal(await page.evaluate(() => Object.keys(localStorage).length + Object.keys(sessionStorage).length), 0)
  assert.ok(wire.every(body => !body.includes(config.pin) && !body.includes('Run the remote ask_user check') && !body.includes('Staging test')))
  assert.deepEqual(errors, [])
  await page.screenshot({ path: resolve(root, 'remote-locked.png'), fullPage: true })
  await writeFile(resolve(root, 'finish'), 'passed')
  await writeFile(resolve(root, 'browser-result.json'), JSON.stringify({ browser: 'Chromium', mobile: [390, 844], desktop: [1440, 1000], checks: 8, pageErrors: errors, encryptedPosts: wire.length }, null, 2))
  console.log('PASS: lock removes the view; no PIN/plaintext on the wire or in browser storage; no page errors')
} finally { await browser.close() }
