package router

import (
	"github.com/LIghtJUNction/api.lmm.best/controller"
	"github.com/LIghtJUNction/api.lmm.best/middleware"
)

// Store routes deliberately do not use ConsoleAccessGate. Public browsing and
// authenticated shopping/selling are available before API console activation.
func setMerchantStoreRouter(parent *assistantRouterGroup) {
	setCommerceImportRoutes(parent)
	setMerchantStoreCollectionRoutes(parent)
	setMerchantStoreCategoryRoutes(parent)
	setMerchantStoreSocialRoutes(parent)
	setMerchantStoreAnalyticsRoutes(parent)
	// The existing refresh cookie is scoped to /api/user/auth. Only these
	// token-specific pickup endpoints may use it without issuing an access token.
	claimSession := parent.Group("/user/auth/store-claim")
	claimSession.Use(middleware.DisableCache(), middleware.TryUserAuth())
	claimSession.GET("/:token", controller.InspectMerchantStoreSessionClaim)
	claimSession.POST("/:token", middleware.RequestBodyLimit(4<<10), middleware.CriticalRateLimit(), controller.ClaimMerchantStoreSessionOrder)

	public := parent.Group("/store")
	public.Use(middleware.DisableCache(), middleware.TryUserAuth())
	public.GET("/merchants/:seller_id", controller.GetMerchantStoreHome)
	public.GET("/announcement", controller.GetMerchantStoreAnnouncement)
	public.GET("/products", controller.ListMerchantStore)
	public.GET("/products/:id", controller.GetPublicMerchantStoreProduct)
	setMerchantStoreAccessPublicRoutes(public)
	public.GET("/products/:id/promotions/resolve", controller.ResolveMerchantStoreDiscountCode)
	public.POST("/products/:id/promotions/quote", middleware.RequestBodyLimit(4<<10), middleware.CriticalRateLimit(), controller.QuoteMerchantStoreDiscountCode)
	public.GET("/config", controller.GetMerchantStoreConfig)
	public.POST("/guest/email/status", middleware.RequestBodyLimit(1<<10), middleware.CriticalRateLimit(), controller.GetMerchantStoreGuestEmailStatus)
	public.POST("/guest/email/verification/send", middleware.RequestBodyLimit(1<<10), middleware.EmailVerificationRateLimit(), middleware.CriticalRateLimit(), controller.SendMerchantStoreGuestEmailVerification)
	public.POST("/guest/email/verification/confirm", middleware.RequestBodyLimit(1<<10), middleware.CriticalRateLimit(), controller.ConfirmMerchantStoreGuestEmailVerification)
	public.GET("/disclaimer", controller.GetMerchantStoreDisclaimer)
	public.GET("/claim/:token", controller.InspectMerchantStoreClaim)
	public.POST("/claim/:token", middleware.RequestBodyLimit(4<<10), middleware.CriticalRateLimit(), controller.ClaimMerchantStoreOrder)
	public.POST("/order-search/email/send", middleware.RequestBodyLimit(1<<10), middleware.EmailVerificationRateLimit(), middleware.CriticalRateLimit(), controller.SendMerchantStoreOrderSearchVerification)
	public.POST("/order-search/email/confirm", middleware.RequestBodyLimit(1<<10), middleware.CriticalRateLimit(), controller.ConfirmMerchantStoreOrderSearchVerification)
	public.POST("/order-search", middleware.RequestBodyLimit(1<<10), middleware.CriticalRateLimit(), controller.ListMerchantStoreOrdersByEmail)
	public.POST("/pickup/refunds/read", middleware.RequestBodyLimit(4<<10), middleware.CriticalRateLimit(), controller.GetMerchantStorePickupRefunds)
	public.POST("/pickup/refunds/request", middleware.RequestBodyLimit(64<<10), middleware.CriticalRateLimit(), controller.RequestMerchantStorePickupRefund)
	public.GET("/order-search/:trade_no", middleware.CriticalRateLimit(), controller.GetMerchantStoreOrderByNumber)

	self := parent.Group("/store")
	self.Use(middleware.UserAuth(), middleware.DisableCache())
	self.POST("/orders", middleware.RequestBodyLimit(8<<10), middleware.CriticalRateLimit(), controller.CreateMerchantStoreOrder)
	self.POST("/disclaimer/accept", middleware.RequestBodyLimit(4<<10), middleware.CriticalRateLimit(), controller.AcceptMerchantStoreDisclaimer)
	self.GET("/email/status", controller.GetMerchantStoreEmailStatus)
	self.POST("/email/verification/send", middleware.RequestBodyLimit(1<<10), middleware.CriticalRateLimit(), controller.SendMerchantStoreEmailVerification)
	self.POST("/email/verification/confirm", middleware.RequestBodyLimit(1<<10), middleware.CriticalRateLimit(), controller.ConfirmMerchantStoreEmailVerification)
	self.GET("/my/home", controller.GetMyMerchantStoreHome)
	self.PUT("/my/home", middleware.RequestBodyLimit(256<<10), middleware.CriticalRateLimit(), controller.SaveMerchantStoreHome)
	self.GET("/my/products", controller.ListMyMerchantStoreProducts)
	self.GET("/my/products/:id", controller.GetMerchantStoreProductDraft)
	self.GET("/my/products/:id/preview", controller.GetMerchantStoreProductPreview)
	self.GET("/products/:id/ai-reviews", controller.ListStoreAIReviews)
	self.POST("/products", middleware.RequestBodyLimit(512<<10), middleware.CriticalRateLimit(), controller.SaveMerchantStoreProduct)
	self.PUT("/products/:id", middleware.RequestBodyLimit(512<<10), middleware.CriticalRateLimit(), controller.SaveMerchantStoreProduct)
	self.POST("/products/:id/submit", middleware.RequestBodyLimit(4<<10), middleware.CriticalRateLimit(), controller.SubmitMerchantStoreProduct)
	self.POST("/products/:id/unlist", middleware.RequestBodyLimit(4<<10), middleware.CriticalRateLimit(), controller.UnlistMerchantStoreProduct)
	self.DELETE("/products/:id", middleware.CriticalRateLimit(), controller.DeleteMerchantStoreProduct)
	self.PUT("/products/:id/paused", middleware.RequestBodyLimit(4<<10), middleware.CriticalRateLimit(), controller.SetMerchantStoreProductPaused)
	self.PUT("/products/:id/sale-limit", middleware.RequestBodyLimit(4<<10), middleware.CriticalRateLimit(), controller.SetMerchantStoreProductSaleLimit)
	self.PUT("/products/:id/sales-availability", middleware.RequestBodyLimit(4<<10), middleware.CriticalRateLimit(), controller.SetMerchantStoreProductRemainingQuota)
	self.PUT("/products/:id/listing", middleware.RequestBodyLimit(4<<10), middleware.CriticalRateLimit(), controller.SetMerchantStoreProductListed)
	self.GET("/products/:id/inventory", controller.ListMerchantStoreInventory)
	self.POST("/products/:id/inventory", middleware.RequestBodyLimit(2<<20), middleware.CriticalRateLimit(), controller.AddMerchantStoreInventory)
	self.DELETE("/products/:id/inventory/:stock_id", middleware.CriticalRateLimit(), controller.DeleteMerchantStoreInventory)
	self.GET("/products/:id/variants/:variant_id/fixed-content", controller.GetMerchantStoreFixedContent)
	self.POST("/products/:id/variants", middleware.RequestBodyLimit(512<<10), middleware.CriticalRateLimit(), controller.CreateMerchantStoreVariant)
	self.PUT("/products/:id/variants/:variant_id", middleware.RequestBodyLimit(512<<10), middleware.CriticalRateLimit(), controller.SaveMerchantStoreVariant)
	self.PUT("/products/:id/variants/:variant_id/enabled", middleware.RequestBodyLimit(4<<10), middleware.CriticalRateLimit(), controller.SetMerchantStoreVariantEnabled)
	self.GET("/products/:id/variants/:variant_id/inventory", controller.ListMerchantStoreVariantInventory)
	self.POST("/products/:id/variants/:variant_id/inventory", middleware.RequestBodyLimit(2<<20), middleware.CriticalRateLimit(), controller.AddMerchantStoreVariantInventory)
	self.DELETE("/products/:id/variants/:variant_id/inventory/:stock_id", middleware.CriticalRateLimit(), controller.DeleteMerchantStoreVariantInventory)
	self.POST("/products/:id/promotion", middleware.RequestBodyLimit(4<<10), middleware.CriticalRateLimit(), controller.PurchaseMerchantStorePromotion)
	self.GET("/products/:id/promotions", controller.ListMerchantStoreDiscountCodes)
	self.POST("/products/:id/promotions", middleware.RequestBodyLimit(8<<10), middleware.CriticalRateLimit(), controller.SaveMerchantStoreDiscountCode)
	self.PUT("/products/:id/promotions/:promotion_id", middleware.RequestBodyLimit(8<<10), middleware.CriticalRateLimit(), controller.SaveMerchantStoreDiscountCode)
	self.DELETE("/products/:id/promotions/:promotion_id", middleware.CriticalRateLimit(), controller.DeleteMerchantStoreDiscountCode)
	self.POST("/products/:id/promotions/batch", middleware.RequestBodyLimit(8<<10), middleware.CriticalRateLimit(), controller.BatchMerchantStoreDiscountCodes)
	self.POST("/products/:id/promotions/cleanup", middleware.RequestBodyLimit(1<<10), middleware.CriticalRateLimit(), controller.CleanupMerchantStoreDiscountCodes)
	self.GET("/my/orders", controller.ListMyMerchantStoreOrders)
	setMerchantStoreAccessSelfRoutes(self)
	self.GET("/orders/:id", controller.GetMerchantStoreOrder)
	self.GET("/orders/:id/refunds", controller.GetMerchantStoreRefunds)
	self.POST("/orders/:id/refunds", middleware.RequestBodyLimit(64<<10), middleware.CriticalRateLimit(), controller.RequestMerchantStoreRefund)
	self.POST("/orders/:id/refunds/proactive", middleware.RequestBodyLimit(64<<10), middleware.CriticalRateLimit(), controller.ProactivelyRefundMerchantStoreOrder)
	self.POST("/orders/:id/refunds/:refund_id/decision", middleware.RequestBodyLimit(8<<10), middleware.CriticalRateLimit(), controller.DecideMerchantStoreRefund)
	self.POST("/orders/:id/refunds/:refund_id/cancel", middleware.CriticalRateLimit(), controller.CancelMerchantStoreRefund)
	self.POST("/orders/:id/refunds/:refund_id/reconcile", middleware.RequestBodyLimit(1<<10), middleware.CriticalRateLimit(), controller.ReconcileMerchantStoreRefund)
	self.GET("/orders/:id/pickup-link", controller.GetMerchantStorePickupLink)
	self.POST("/orders/:id/cancel", middleware.RequestBodyLimit(4<<10), middleware.CriticalRateLimit(), controller.CancelMerchantStoreOrder)
	self.POST("/orders/:id/pay", middleware.RequestBodyLimit(4<<10), middleware.CriticalRateLimit(), controller.RequestMerchantStorePayment)
	self.POST("/orders/:id/reconcile", middleware.RequestBodyLimit(4<<10), middleware.CriticalRateLimit(), controller.ReconcileMerchantStorePayment)
	self.GET("/payments/settings", controller.GetMerchantStorePaymentSettings)
	self.PUT("/payments/settings", middleware.RequestBodyLimit(64<<10), middleware.CriticalRateLimit(), controller.SaveMerchantStorePaymentSettings)
	self.PUT("/payments/categories", middleware.RequestBodyLimit(4<<10), middleware.CriticalRateLimit(), controller.SetMerchantStorePaymentCategories)

	admin := parent.Group("/store")
	admin.Use(middleware.AdminAuth(), middleware.DisableCache())
	admin.PUT("/announcement", middleware.RequestBodyLimit(128<<10), middleware.CriticalRateLimit(), controller.SaveMerchantStoreAnnouncement)
	admin.GET("/reviews", controller.ListMerchantStoreReviews)
	admin.POST("/products/:id/review", middleware.RequestBodyLimit(8<<10), middleware.CriticalRateLimit(), controller.ReviewMerchantStoreProduct)
	admin.PUT("/promotion-config", middleware.RootAuth(), middleware.RequestBodyLimit(4<<10), middleware.CriticalRateLimit(), controller.SetMerchantStorePromotionPrice)
	admin.PUT("/config", middleware.RootAuth(), middleware.RequestBodyLimit(8<<10), middleware.CriticalRateLimit(), controller.SetMerchantStoreConfig)
	admin.PUT("/product-link-presets", middleware.RootAuth(), middleware.RequestBodyLimit(128<<10), middleware.CriticalRateLimit(), controller.SaveMerchantStoreLinkPresets)

	// Dedicated, unauthenticated callbacks are separate from top-up callbacks.
	// Only the service adapter may attest a verified payment to the store model.
	callback := parent.Group("/store/payments")
	callback.Use(middleware.DisableCache())
	callback.GET("/epay/:id/notify", controller.MerchantStoreEpayNotify)
	callback.POST("/epay/:id/notify", middleware.RequestBodyLimit(64<<10), controller.MerchantStoreEpayNotify)
	callback.POST("/pancake/:scope/:seller_id/:env/webhook", middleware.RequestBodyLimit(512<<10), controller.MerchantStorePancakeWebhook)
}
