/*
Copyright (C) 2026 LIghtJUNction

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.
*/
const entries = [
  [
    'API review policy scope',
    'API 审查策略范围',
    'API 審查策略範圍',
    'Portée de la politique de contrôle API',
    'API 審査ポリシーの適用範囲',
    'Область политики проверки API',
    'Phạm vi chính sách kiểm duyệt API',
  ],
  [
    'Account group',
    '账号分组',
    '帳號分組',
    'Groupe du compte',
    'アカウントグループ',
    'Группа аккаунта',
    'Nhóm tài khoản',
  ],
  [
    'Request group',
    '请求分组',
    '請求分組',
    'Groupe de la requête',
    'リクエストグループ',
    'Группа запроса',
    'Nhóm yêu cầu',
  ],
  [
    'Account group uses the user’s account group. Request group uses the trusted group selected for the API request; a missing request group stays off. Changing scope cancels queued API reviews. Assistant reviews always use account groups with the same policy map.',
    '账号分组按用户所属分组匹配策略。请求分组按 API 请求实际选用的可信分组匹配；缺少请求分组时不审查。修改范围会取消已排队的 API 审查。助手始终按账号分组使用同一份分组策略。',
    '帳號分組依使用者所屬分組比對策略。請求分組依 API 請求實際選用的可信分組比對；缺少請求分組時不審查。修改範圍會取消已排隊的 API 審查。助手始終依帳號分組使用同一份分組策略。',
    'Le groupe du compte utilise celui de l’utilisateur. Le groupe de la requête utilise le groupe fiable sélectionné pour la requête API ; sans groupe, le contrôle reste désactivé. Un changement annule les contrôles API en attente. L’assistant utilise toujours le groupe du compte avec les mêmes politiques.',
    'アカウントグループはユーザーの所属グループで方針を選びます。リクエストグループは API リクエストで選択された信頼できるグループを使用し、未指定なら審査しません。範囲の変更で待機中の API 審査はキャンセルされます。アシスタントは常に同じ方針設定をアカウントグループに適用します。',
    'Группа аккаунта определяется по пользователю. Группа запроса берётся из доверенного контекста API; без неё проверка отключена. Изменение области отменяет ожидающие проверки API. Помощник всегда использует группу аккаунта с теми же политиками.',
    'Nhóm tài khoản áp dụng theo nhóm của người dùng. Nhóm yêu cầu dùng nhóm đáng tin cậy đã chọn cho yêu cầu API; thiếu nhóm thì không kiểm duyệt. Đổi phạm vi sẽ hủy các kiểm duyệt API đang chờ. Trợ lý luôn dùng nhóm tài khoản với cùng bộ chính sách.',
  ],
  [
    'Enable private upstream safety identifiers',
    '启用上游隐私安全标识',
    '啟用上游隱私安全識別碼',
    'Activer les identifiants privés de sécurité en amont',
    '上流への非公開安全識別子を有効化',
    'Включить приватные идентификаторы безопасности для провайдера',
    'Bật mã định danh an toàn riêng tư cho nhà cung cấp',
  ],
  [
    'Send a stable private user identifier with supported official OpenAI requests when review is enabled for the selected group policy. Raw user IDs and email addresses are not sent. Disabled by default.',
    '分组策略已启用审查时，在支持此功能的 OpenAI 官方请求中发送稳定的用户隐私标识。不会发送用户原始 ID 或邮箱，默认关闭。',
    '分組策略已啟用審查時，在支援此功能的 OpenAI 官方請求中傳送穩定的使用者隱私識別碼。不會傳送使用者原始 ID 或信箱，預設關閉。',
    'Quand la politique du groupe active le contrôle, les requêtes OpenAI officielles compatibles incluent un identifiant privé stable. L’ID utilisateur brut et l’adresse e-mail ne sont pas envoyés. Désactivé par défaut.',
    '選択したグループ方針で審査が有効な場合、対応する OpenAI 公式リクエストに安定した非公開ユーザー識別子を付けます。元のユーザー ID やメールアドレスは送信しません。初期設定は無効です。',
    'Если политика выбранной группы включает проверку, поддерживаемые официальные запросы OpenAI получают стабильный приватный идентификатор. Исходный ID пользователя и e-mail не передаются. По умолчанию отключено.',
    'Khi chính sách nhóm đã chọn bật kiểm duyệt, gửi mã định danh riêng tư ổn định trong các yêu cầu OpenAI chính thức được hỗ trợ. Không gửi ID gốc hoặc email người dùng. Mặc định tắt.',
  ],
  [
    'Group policies follow the selected API review scope. Assistant reviews always use the account group. The review routing group only selects the moderation channel.',
    '分组策略按所选 API 审查范围匹配；助手审查始终按账号分组匹配。审查路由分组仅用于选择审查渠道。',
    '分組策略依所選 API 審查範圍比對；助手審查始終依帳號分組比對。審查路由分組僅用於選擇審查渠道。',
    'Les politiques suivent la portée API sélectionnée. L’assistant utilise toujours le groupe du compte. Le groupe de routage du contrôle choisit uniquement le canal de modération.',
    'グループ方針は選択した API 審査範囲に従います。アシスタントは常にアカウントグループを使用します。審査のルーティンググループはモデレーションチャネルのみを選択します。',
    'Политики групп следуют выбранной области API. Помощник всегда использует группу аккаунта. Группа маршрутизации проверки выбирает только канал модерации.',
    'Chính sách nhóm theo phạm vi kiểm duyệt API đã chọn. Trợ lý luôn dùng nhóm tài khoản. Nhóm định tuyến kiểm duyệt chỉ chọn kênh kiểm duyệt.',
  ],
  [
    'Content safety review',
    '内容安全审查',
    '內容安全審查',
    'Contrôle de sécurité du contenu',
    'コンテンツ安全審査',
    'Проверка безопасности контента',
    'Kiểm duyệt an toàn nội dung',
  ],
  [
    'Review routing group',
    '审查路由分组',
    '審查路由分組',
    'Groupe de routage du contrôle',
    '審査のルーティンググループ',
    'Группа маршрутизации проверки',
    'Nhóm định tuyến kiểm duyệt',
  ],
  [
    'Moderation model',
    '安全审查模型',
    '安全審查模型',
    'Modèle de modération',
    'モデレーションモデル',
    'Модель модерации',
    'Mô hình kiểm duyệt',
  ],
  [
    'Choose the OpenAI channel group used to send moderation requests.',
    '选择用于发送审查请求的 OpenAI 渠道分组。',
    '選擇用於傳送審查請求的 OpenAI 渠道分組。',
    'Choisissez le groupe de canaux OpenAI pour les demandes de modération.',
    '審査リクエストの送信に使用する OpenAI チャネルグループを選択します。',
    'Выберите группу каналов OpenAI для запросов модерации.',
    'Chọn nhóm kênh OpenAI để gửi yêu cầu kiểm duyệt.',
  ],
  [
    'Example: omni-moderation-latest',
    '示例：omni-moderation-latest',
    '範例：omni-moderation-latest',
    'Exemple : omni-moderation-latest',
    '例：omni-moderation-latest',
    'Пример: omni-moderation-latest',
    'Ví dụ: omni-moderation-latest',
  ],
  [
    'Unable to load moderation models. Try again.',
    '无法加载审查模型，请重试。',
    '無法載入審查模型，請重試。',
    'Impossible de charger les modèles de modération. Réessayez.',
    '審査モデルを読み込めません。再試行してください。',
    'Не удалось загрузить модели модерации. Повторите попытку.',
    'Không thể tải mô hình kiểm duyệt. Hãy thử lại.',
  ],
  [
    'This moderation model is not available through an official OpenAI channel in this group.',
    '此分组没有可用的 OpenAI 官方渠道来调用该审查模型。',
    '此分組沒有可用的 OpenAI 官方渠道來呼叫該審查模型。',
    'Ce modèle n’est pas disponible via un canal OpenAI officiel de ce groupe.',
    'このグループの OpenAI 公式チャネルでは、この審査モデルを利用できません。',
    'Эта модель недоступна через официальный канал OpenAI в данной группе.',
    'Mô hình này không khả dụng qua kênh OpenAI chính thức trong nhóm này.',
  ],
  [
    'Enable assistant moderation',
    '启用助手安全审查',
    '啟用助手安全審查',
    'Activer la modération de l’assistant',
    'アシスタントの安全審査を有効化',
    'Включить модерацию помощника',
    'Bật kiểm duyệt trợ lý',
  ],
  [
    'Review assistant conversations with OpenAI Moderation in the background. Disabled by default.',
    '使用 OpenAI Moderation 在后台审查助手对话，默认关闭。',
    '使用 OpenAI Moderation 在背景審查助手對話，預設關閉。',
    'Contrôlez les conversations de l’assistant en arrière-plan avec OpenAI Moderation. Désactivé par défaut.',
    'OpenAI Moderation でアシスタントの会話をバックグラウンド審査します。初期設定は無効です。',
    'Проверять беседы помощника через OpenAI Moderation в фоне. По умолчанию отключено.',
    'Kiểm duyệt hội thoại trợ lý bằng OpenAI Moderation trong nền. Mặc định tắt.',
  ],
  [
    'User group policies determine whether review is off, warning-only, or strict. Groups without a policy stay off.',
    '用户分组策略决定关闭、仅警告或严格模式；未配置策略的分组保持关闭。',
    '使用者分組策略決定關閉、僅警告或嚴格模式；未設定策略的分組保持關閉。',
    'La politique du groupe utilisateur définit le mode : désactivé, avertissement ou strict. Les groupes sans politique restent désactivés.',
    'ユーザーグループの方針で無効、警告のみ、厳格を選択します。未設定のグループは無効のままです。',
    'Политика группы пользователя определяет отключение, предупреждения или строгий режим. Без политики проверка отключена.',
    'Chính sách nhóm người dùng quyết định tắt, chỉ cảnh báo hoặc nghiêm ngặt. Nhóm chưa có chính sách vẫn tắt.',
  ],
  [
    'Configure group modes and category fines',
    '配置分组模式和分类罚款',
    '設定分組模式與分類罰款',
    'Configurer les modes et les frais par catégorie',
    'グループモードとカテゴリ別の課金を設定',
    'Настроить режимы групп и штрафы по категориям',
    'Cấu hình chế độ nhóm và mức phạt theo danh mục',
  ],
  [
    'Group review policies',
    '分组审查策略',
    '分組審查策略',
    'Politiques de contrôle par groupe',
    'グループ別の審査方針',
    'Политики проверки групп',
    'Chính sách kiểm duyệt theo nhóm',
  ],
  [
    'Use explicit groups, valid modes, and category fees from $0 to $1000 with up to six decimal places.',
    '策略必须指定分组和有效模式；分类金额须为 0–1000 美元，最多六位小数。',
    '策略必須指定分組及有效模式；分類金額須為 0–1000 美元，最多六位小數。',
    'Indiquez des groupes explicites, des modes valides et des montants de 0 à 1000 USD, avec six décimales maximum.',
    'グループと有効なモードを指定し、金額は 0～1000 USD、小数点以下 6 桁までにしてください。',
    'Укажите явные группы, допустимые режимы и суммы от 0 до 1000 USD с максимум шестью десятичными знаками.',
    'Cần nhóm cụ thể, chế độ hợp lệ và số tiền 0–1000 USD, tối đa sáu chữ số thập phân.',
  ],
  [
    'Policies apply to the user’s account group. Every group starts off; the routing group does not select which users are reviewed.',
    '策略按用户账号分组生效，各组默认关闭；路由分组不决定哪些用户接受审查。',
    '策略依使用者帳號分組生效，各組預設關閉；路由分組不決定哪些使用者接受審查。',
    'Les politiques s’appliquent au groupe du compte utilisateur, désactivé par défaut. Le groupe de routage ne choisit pas les utilisateurs contrôlés.',
    '方針はユーザーのアカウントグループに適用され、初期設定は無効です。ルーティンググループは審査対象者を指定しません。',
    'Политики применяются к группе аккаунта, по умолчанию отключены. Группа маршрутизации не определяет проверяемых пользователей.',
    'Chính sách áp dụng theo nhóm tài khoản, mặc định tắt. Nhóm định tuyến không quyết định người dùng được kiểm duyệt.',
  ],
  [
    'Review mode',
    '审查模式',
    '審查模式',
    'Mode de contrôle',
    '審査モード',
    'Режим проверки',
    'Chế độ kiểm duyệt',
  ],
  [
    'Tolerant — warning only',
    '宽容模式：仅警告',
    '寬容模式：僅警告',
    'Tolérant : avertissement seul',
    '寛容：警告のみ',
    'Мягкий: только предупреждение',
    'Khoan dung: chỉ cảnh báo',
  ],
  [
    'Strict — category fine',
    '严格模式：分类罚款',
    '嚴格模式：分類罰款',
    'Strict : frais par catégorie',
    '厳格：カテゴリ別の課金',
    'Строгий: штраф по категории',
    'Nghiêm ngặt: phạt theo danh mục',
  ],
  [
    'No account groups are available. Review stays off.',
    '没有可用的账号分组，审查保持关闭。',
    '沒有可用的帳號分組，審查保持關閉。',
    'Aucun groupe de comptes disponible. Le contrôle reste désactivé.',
    '利用可能なアカウントグループがありません。審査は無効のままです。',
    'Группы аккаунтов недоступны. Проверка остаётся отключённой.',
    'Không có nhóm tài khoản khả dụng. Kiểm duyệt vẫn tắt.',
  ],
  [
    'A flagged input incurs only the highest configured category fine, once. Unset categories cost zero; deductions cannot exceed the positive wallet balance. Flagged outputs do not penalize users or increase their risk score.',
    '违规输入每次仅扣命中类别中的最高金额。未设金额的类别不扣款，扣款不超过钱包正余额；模型输出违规不处罚用户，也不增加风险分。',
    '違規輸入每次僅扣命中類別中的最高金額。未設金額的類別不扣款，扣款不超過錢包正餘額；模型輸出違規不處罰使用者，也不增加風險分。',
    'Une entrée signalée ne facture qu’une fois le montant maximal des catégories concernées. Une catégorie sans tarif vaut zéro ; le débit est limité au solde positif. Une sortie signalée ne pénalise pas l’utilisateur et n’augmente pas son score de risque.',
    '違反入力には該当カテゴリの最高額を一度だけ適用します。未設定は無料で、引き落としは正の残高が上限です。出力の違反でユーザーに課金したりリスクを加算したりしません。',
    'За нарушение во входных данных один раз удерживается максимальный тариф совпавшей категории. Без тарифа сумма равна нулю; удержание не превышает положительный баланс. Нарушения в ответах не штрафуют пользователя и не повышают риск.',
    'Đầu vào vi phạm chỉ bị trừ mức cao nhất trong các danh mục khớp, một lần. Danh mục chưa đặt mức phạt có giá 0; không trừ quá số dư dương. Đầu ra vi phạm không phạt người dùng hoặc tăng điểm rủi ro.',
  ],
  [
    'OpenAI Moderation reviews text in the background. Requests and assistant replies never wait for review. Notifications stay on this site; review failures do not trigger penalties.',
    'OpenAI Moderation 在后台审查文本，请求和助手回复无需等待结果。仅发送站内通知，审查失败不处罚。',
    'OpenAI Moderation 在背景審查文字，請求及助手回覆無須等待結果。僅傳送站內通知，審查失敗不處罰。',
    'OpenAI Moderation contrôle le texte en arrière-plan, sans retarder les requêtes ni les réponses. Notifications internes uniquement ; un échec ne déclenche aucune pénalité.',
    'OpenAI Moderation がテキストを背景で審査し、リクエストや返信を待たせません。通知はサイト内のみで、審査失敗による罰則はありません。',
    'OpenAI Moderation проверяет текст в фоне, не задерживая запросы и ответы. Только уведомления на сайте; сбои проверки не приводят к штрафам.',
    'OpenAI Moderation kiểm duyệt văn bản trong nền, không bắt yêu cầu hay trả lời phải chờ. Chỉ thông báo trong trang; lỗi kiểm duyệt không gây phạt.',
  ],
  [
    'Enable API moderation',
    '启用 API 安全审查',
    '啟用 API 安全審查',
    'Activer la modération API',
    'API 安全審査を有効化',
    'Включить модерацию API',
    'Bật kiểm duyệt API',
  ],
  [
    'Queue API text for safety review. Disabled by default; assistant review is configured separately.',
    '将 API 文本加入安全审查队列，默认关闭；助手审查单独配置。',
    '將 API 文字加入安全審查佇列，預設關閉；助手審查另行設定。',
    'Placez les textes API en file de contrôle, désactivé par défaut. Le contrôle de l’assistant se configure séparément.',
    'API のテキストを審査キューに追加します。初期設定は無効で、アシスタント審査は別途設定します。',
    'Добавлять тексты API в очередь проверки. По умолчанию отключено; проверка помощника настраивается отдельно.',
    'Đưa văn bản API vào hàng đợi kiểm duyệt, mặc định tắt. Kiểm duyệt trợ lý được cấu hình riêng.',
  ],
  [
    'Read the public safety review notice',
    '查看公开安全审查说明',
    '查看公開安全審查說明',
    'Lire l’avis public sur les contrôles',
    '公開の安全審査説明を読む',
    'Открыть публичное описание проверки',
    'Xem thông báo công khai về kiểm duyệt',
  ],
  [
    'Save moderation settings',
    '保存安全审查设置',
    '儲存安全審查設定',
    'Enregistrer la modération',
    '安全審査設定を保存',
    'Сохранить настройки модерации',
    'Lưu cài đặt kiểm duyệt',
  ],
  [
    'Confirm this announcement to continue.',
    '确认此公告后继续。',
    '確認此公告後繼續。',
    'Confirmez cette annonce pour continuer.',
    'このお知らせを確認して続行してください。',
    'Подтвердите это объявление, чтобы продолжить.',
    'Xác nhận thông báo này để tiếp tục.',
  ],
  [
    'Confirm and continue',
    '确认并继续',
    '確認並繼續',
    'Confirmer et continuer',
    '確認して続行',
    'Подтвердить и продолжить',
    'Xác nhận và tiếp tục',
  ],
  [
    'Harassment',
    '骚扰',
    '騷擾',
    'Harcèlement',
    '嫌がらせ',
    'Преследование',
    'Quấy rối',
  ],
  [
    'Threatening harassment',
    '威胁性骚扰',
    '威脅性騷擾',
    'Harcèlement menaçant',
    '脅迫を伴う嫌がらせ',
    'Преследование с угрозами',
    'Quấy rối có đe dọa',
  ],
  ['Hate', '仇恨', '仇恨', 'Haine', '憎悪', 'Ненависть', 'Thù ghét'],
  [
    'Threatening hate',
    '威胁性仇恨',
    '威脅性仇恨',
    'Haine menaçante',
    '脅迫を伴う憎悪',
    'Ненависть с угрозами',
    'Thù ghét có đe dọa',
  ],
  [
    'Illicit activity',
    '违法活动',
    '違法活動',
    'Activités illicites',
    '違法行為',
    'Незаконная деятельность',
    'Hoạt động bất hợp pháp',
  ],
  [
    'Violent illicit activity',
    '暴力违法活动',
    '暴力違法活動',
    'Activités illicites violentes',
    '暴力を伴う違法行為',
    'Насильственная незаконная деятельность',
    'Hoạt động bất hợp pháp có bạo lực',
  ],
  [
    'Self-harm',
    '自伤',
    '自傷',
    'Automutilation',
    '自傷行為',
    'Самоповреждение',
    'Tự làm hại bản thân',
  ],
  [
    'Self-harm intent',
    '自伤意图',
    '自傷意圖',
    'Intention d’automutilation',
    '自傷の意図',
    'Намерение самоповреждения',
    'Ý định tự làm hại',
  ],
  [
    'Self-harm instructions',
    '自伤指导',
    '自傷指引',
    'Instructions d’automutilation',
    '自傷の手順',
    'Инструкции по самоповреждению',
    'Hướng dẫn tự làm hại',
  ],
  [
    'Sexual content',
    '性内容',
    '性內容',
    'Contenu sexuel',
    '性的コンテンツ',
    'Сексуальный контент',
    'Nội dung tình dục',
  ],
  [
    'Sexual content involving minors',
    '涉及未成年人的性内容',
    '涉及未成年人的性內容',
    'Contenu sexuel impliquant des mineurs',
    '未成年者に関する性的コンテンツ',
    'Сексуальный контент с несовершеннолетними',
    'Nội dung tình dục liên quan trẻ vị thành niên',
  ],
  ['Violence', '暴力', '暴力', 'Violence', '暴力', 'Насилие', 'Bạo lực'],
  [
    'Graphic violence',
    '血腥暴力',
    '血腥暴力',
    'Violence explicite',
    '凄惨な暴力',
    'Жестокое насилие',
    'Bạo lực ghê rợn',
  ],
  [
    'OpenAI Moderation',
    'OpenAI 安全审查',
    'OpenAI 安全審查',
    'OpenAI Moderation',
    'OpenAI Moderation',
    'OpenAI Moderation',
    'OpenAI Moderation',
  ],
  [
    'Asynchronous review',
    '异步审查',
    '非同步審查',
    'Contrôle asynchrone',
    '非同期審査',
    'Асинхронная проверка',
    'Kiểm duyệt bất đồng bộ',
  ],
  [
    'Safety reviews use OpenAI official Moderation models in the background. Requests do not wait for the review verdict.',
    '安全审查在后台使用 OpenAI 官方 Moderation 模型，请求无需等待审查结果。',
    '安全審查在背景使用 OpenAI 官方 Moderation 模型，請求無須等待審查結果。',
    'Les contrôles utilisent les modèles officiels OpenAI Moderation en arrière-plan. Les requêtes n’attendent pas le verdict.',
    '安全審査は OpenAI 公式 Moderation モデルで非同期に実行され、リクエストは結果を待ちません。',
    'Проверки выполняются официальными моделями OpenAI Moderation в фоне. Запросы не ждут решения.',
    'Kiểm duyệt dùng mô hình OpenAI Moderation chính thức trong nền. Yêu cầu không chờ kết quả.',
  ],
  [
    'Current Moderation settings',
    '当前安全审查设置',
    '目前安全審查設定',
    'Configuration actuelle de modération',
    '現在の安全審査設定',
    'Текущие настройки модерации',
    'Cài đặt kiểm duyệt hiện tại',
  ],
  [
    'Features and groups are disabled by default. Administrators choose the review mode for each group.',
    '功能和所有分组默认关闭，由管理员为各分组选择审查模式。',
    '功能及所有分組預設關閉，由管理員為各分組選擇審查模式。',
    'Les fonctions et groupes sont désactivés par défaut. L’administrateur choisit le mode de chaque groupe.',
    '機能と全グループは初期設定で無効です。管理者がグループごとにモードを選択します。',
    'Функции и группы по умолчанию отключены. Администратор выбирает режим каждой группы.',
    'Tính năng và các nhóm mặc định tắt. Quản trị viên chọn chế độ cho từng nhóm.',
  ],
  [
    'Security audit Moderation',
    'API 安全审查',
    'API 安全審查',
    'Modération des requêtes API',
    'API の安全審査',
    'Модерация запросов API',
    'Kiểm duyệt yêu cầu API',
  ],
  [
    'AI assistant Moderation',
    'AI 助手安全审查',
    'AI 助手安全審查',
    'Modération de l’assistant IA',
    'AI アシスタントの安全審査',
    'Модерация ИИ-помощника',
    'Kiểm duyệt trợ lý AI',
  ],
  [
    'Moderation settings are not published yet.',
    '尚未公布安全审查设置。',
    '尚未公布安全審查設定。',
    'La configuration de modération n’est pas encore publiée.',
    '安全審査設定はまだ公開されていません。',
    'Настройки модерации ещё не опубликованы.',
    'Cài đặt kiểm duyệt chưa được công bố.',
  ],
  [
    'The server has not returned Moderation configuration. Active groups and fees cannot be confirmed.',
    '服务器未返回安全审查配置，无法确认启用的分组和金额。',
    '伺服器未回傳安全審查設定，無法確認啟用的分組及金額。',
    'Le serveur n’a pas fourni la configuration. Les groupes actifs et tarifs ne peuvent être confirmés.',
    'サーバーから設定が返されていないため、有効なグループや金額を確認できません。',
    'Сервер не вернул настройки. Активные группы и тарифы не подтверждены.',
    'Máy chủ chưa trả cấu hình, nên chưa xác nhận được nhóm đang bật và mức phí.',
  ],
  [
    'Tolerant mode sends a warning through site notifications. Strict mode can also deduct a category fee from the user wallet.',
    '宽容模式仅发送站内警告；严格模式还可按类别从用户钱包扣款。',
    '寬容模式僅傳送站內警告；嚴格模式還可依類別從使用者錢包扣款。',
    'Le mode tolérant envoie un avertissement interne. Le mode strict peut aussi débiter les frais de catégorie du portefeuille.',
    '寛容モードはサイト内で警告します。厳格モードではカテゴリ別の金額をウォレットから差し引く場合があります。',
    'Мягкий режим отправляет уведомление на сайте. Строгий также может удержать штраф категории из кошелька.',
    'Chế độ khoan dung gửi cảnh báo trong trang. Chế độ nghiêm ngặt còn có thể trừ phí danh mục từ ví.',
  ],
  [
    'A strict review charges the largest configured fee among matched categories once. Unset category fees are $0, and reviews never overdraw the wallet.',
    '严格模式每次只扣命中类别的最高配置金额，未设金额的类别为 $0，钱包不会被扣成负数。',
    '嚴格模式每次只扣命中類別的最高設定金額，未設金額的類別為 $0，錢包不會被扣成負數。',
    'Le mode strict facture une seule fois le tarif maximal des catégories concernées. Sans tarif, le coût est de 0 $ ; le portefeuille ne devient jamais négatif.',
    '厳格モードは該当カテゴリの最高額を一度だけ適用します。未設定は $0 で、残高をマイナスにはしません。',
    'Строгий режим один раз удерживает максимальный тариф совпавшей категории. Без тарифа сумма $0; отрицательный баланс не создаётся.',
    'Chế độ nghiêm ngặt chỉ trừ mức cao nhất của danh mục khớp một lần. Chưa đặt mức phí là $0; ví không bị trừ âm.',
  ],
  [
    'Reviewed violations in user input contribute to the account risk score. Model output violations do not charge the user or increase their risk score.',
    '用户输入的审查违规统计会影响账号风险分；模型输出违规不向用户扣款，也不增加其风险分。',
    '使用者輸入的審查違規統計會影響帳號風險分；模型輸出違規不向使用者扣款，也不增加其風險分。',
    'Les violations dans les entrées utilisateur contribuent au score de risque. Les sorties du modèle ne facturent pas l’utilisateur et n’augmentent pas son risque.',
    'ユーザー入力の違反統計はリスク評価に反映されます。モデル出力の違反ではユーザーへの課金もリスク加算もしません。',
    'Нарушения во входных данных влияют на риск аккаунта. Нарушения в ответах модели не удерживают средства и не повышают риск пользователя.',
    'Vi phạm trong đầu vào người dùng ảnh hưởng điểm rủi ro. Đầu ra mô hình vi phạm không trừ tiền hoặc tăng điểm rủi ro của người dùng.',
  ],
  [
    'These reviews currently support text only. Notifications stay inside the site.',
    '目前仅支持文本审查，通知仅在站内发送。',
    '目前僅支援文字審查，通知僅在站內傳送。',
    'Ces contrôles portent uniquement sur le texte. Les notifications restent internes au site.',
    '現在はテキストのみを審査し、通知はサイト内に限られます。',
    'Сейчас проверяется только текст. Уведомления остаются внутри сайта.',
    'Hiện chỉ hỗ trợ kiểm duyệt văn bản. Thông báo chỉ nằm trong trang.',
  ],
  [
    'Moderation group policies',
    '安全审查分组策略',
    '安全審查分組策略',
    'Politiques de modération des groupes',
    'グループ別の安全審査方針',
    'Политики модерации групп',
    'Chính sách kiểm duyệt nhóm',
  ],
  [
    'The following are configured group modes. A disabled feature does not review requests, even when a group mode is configured.',
    '以下为已配置的分组模式。功能关闭时，即使配置了分组模式，也不会执行审查。',
    '以下為已設定的分組模式。功能關閉時，即使設定了分組模式，也不會執行審查。',
    'Voici les modes configurés. Une fonction désactivée ne contrôle aucune requête, même si un mode de groupe est défini.',
    '以下は設定済みのモードです。グループを設定しても、機能が無効なら審査は実行されません。',
    'Ниже настроенные режимы групп. Отключённая функция не проверяет запросы, даже если режим группы задан.',
    'Đây là chế độ nhóm đã cấu hình. Khi tính năng tắt, yêu cầu không được kiểm duyệt dù đã đặt chế độ nhóm.',
  ],
  [
    'Moderation is disabled for this group.',
    '此分组的安全审查已关闭。',
    '此分組的安全審查已關閉。',
    'La modération est désactivée pour ce groupe.',
    'このグループの安全審査は無効です。',
    'Модерация для этой группы отключена.',
    'Kiểm duyệt đã tắt cho nhóm này.',
  ],
  [
    'Flagged user input produces a site notification without a wallet deduction.',
    '用户输入违规时仅发送站内通知，不扣钱包余额。',
    '使用者輸入違規時僅傳送站內通知，不扣錢包餘額。',
    'Une entrée signalée génère une notification interne sans débit du portefeuille.',
    '入力の違反はサイト内通知のみで、残高を差し引きません。',
    'Нарушение во входных данных вызывает уведомление без списания из кошелька.',
    'Đầu vào vi phạm chỉ tạo thông báo trong trang, không trừ tiền ví.',
  ],
  [
    'Flagged user input may incur the configured category fee from the user wallet.',
    '用户输入违规时，可能按已配置的类别金额扣除钱包余额。',
    '使用者輸入違規時，可能依已設定的類別金額扣除錢包餘額。',
    'Une entrée signalée peut entraîner le débit des frais de catégorie configurés.',
    '入力の違反には設定されたカテゴリ別金額が適用される場合があります。',
    'Нарушение во входных данных может привести к удержанию настроенного штрафа категории.',
    'Đầu vào vi phạm có thể bị trừ mức phí danh mục đã cấu hình từ ví.',
  ],
  [
    'No category fees are configured; the review fee is $0.',
    '尚未配置分类罚款，本次审查处罚金额为 $0。',
    '尚未設定分類罰款，本次審查處罰金額為 $0。',
    'Aucun tarif de catégorie configuré ; les frais sont de 0 $.',
    'カテゴリ別の金額が未設定のため、課金額は $0 です。',
    'Штрафы категорий не настроены; сумма удержания $0.',
    'Chưa cấu hình mức phạt danh mục; phí là $0.',
  ],
  [
    'No Moderation groups are configured. Unlisted groups remain disabled.',
    '尚未配置安全审查分组，未列出的分组保持关闭。',
    '尚未設定安全審查分組，未列出的分組保持關閉。',
    'Aucun groupe de modération configuré. Les groupes non listés restent désactivés.',
    '審査グループが未設定です。未登録のグループは無効のままです。',
    'Группы модерации не настроены. Неуказанные группы отключены.',
    'Chưa cấu hình nhóm kiểm duyệt. Nhóm không được liệt kê vẫn tắt.',
  ],
  [
    'Read the safety review notice',
    '查看安全审查说明',
    '查看安全審查說明',
    'Lire l’avis sur les contrôles',
    '安全審査説明を読む',
    'Открыть описание проверки',
    'Xem thông báo kiểm duyệt',
  ],
  [
    'Tolerant mode',
    '宽容模式',
    '寬容模式',
    'Mode tolérant',
    '寛容モード',
    'Мягкий режим',
    'Chế độ khoan dung',
  ],
  [
    'Strict mode',
    '严格模式',
    '嚴格模式',
    'Mode strict',
    '厳格モード',
    'Строгий режим',
    'Chế độ nghiêm ngặt',
  ],
  [
    'OpenAI Moderation audit',
    'OpenAI 安全审查记录',
    'OpenAI 安全審查紀錄',
    'Journal OpenAI Moderation',
    'OpenAI 安全審査記録',
    'Журнал OpenAI Moderation',
    'Nhật ký OpenAI Moderation',
  ],
  [
    'Asynchronous review results and wallet deductions. Request text and credentials are never shown here.',
    '异步审查结果与钱包扣款记录，此处不展示请求原文或凭据。',
    '非同步審查結果與錢包扣款紀錄，此處不顯示請求原文或憑證。',
    'Résultats asynchrones et débits du portefeuille. Les textes des requêtes et identifiants ne sont jamais affichés ici.',
    '非同期の審査結果と残高の引き落とし記録です。リクエスト本文や認証情報は表示しません。',
    'Результаты фоновой проверки и списания. Тексты запросов и учётные данные здесь не отображаются.',
    'Kết quả kiểm duyệt nền và khoản trừ ví. Không hiển thị nội dung yêu cầu hoặc thông tin xác thực.',
  ],
  [
    'API input',
    'API 输入',
    'API 輸入',
    'Entrée API',
    'API 入力',
    'Входные данные API',
    'Đầu vào API',
  ],
  [
    'Assistant input',
    '助手输入',
    '助手輸入',
    'Entrée de l’assistant',
    'アシスタント入力',
    'Входные данные помощника',
    'Đầu vào trợ lý',
  ],
  [
    'Assistant output',
    '助手输出',
    '助手輸出',
    'Sortie de l’assistant',
    'アシスタント出力',
    'Ответ помощника',
    'Đầu ra trợ lý',
  ],
  [
    'Flagged',
    '发现违规',
    '發現違規',
    'Signalé',
    '違反検出',
    'Нарушение обнаружено',
    'Phát hiện vi phạm',
  ],
  [
    'Fined reviews',
    '已扣款审查',
    '已扣款審查',
    'Contrôles facturés',
    '課金済みの審査',
    'Проверки со списанием',
    'Lượt kiểm duyệt bị trừ phí',
  ],
  [
    'Review status',
    '审查状态',
    '審查狀態',
    'État du contrôle',
    '審査状態',
    'Статус проверки',
    'Trạng thái kiểm duyệt',
  ],
  [
    'Requested category fee',
    '应扣分类金额',
    '應扣分類金額',
    'Frais de catégorie prévus',
    'カテゴリ別の請求予定額',
    'Запрошенный штраф категории',
    'Mức phí danh mục yêu cầu',
  ],
  [
    'Wallet deduction',
    '实际钱包扣款',
    '實際錢包扣款',
    'Débit du portefeuille',
    '実際の引き落とし',
    'Списание из кошелька',
    'Khoản trừ ví thực tế',
  ],
  [
    'Fee record ID',
    '扣款记录 ID',
    '扣款紀錄 ID',
    'ID du débit',
    '課金記録 ID',
    'ID записи списания',
    'ID bản ghi phí',
  ],
  [
    'Fee status',
    '扣款状态',
    '扣款狀態',
    'État du débit',
    '課金状態',
    'Статус списания',
    'Trạng thái phí',
  ],
  [
    'Input coverage',
    '输入覆盖情况',
    '輸入涵蓋情況',
    'Couverture de l’entrée',
    '入力の審査範囲',
    'Охват входных данных',
    'Phạm vi đầu vào',
  ],
  [
    'Input was truncated; no penalty applied.',
    '输入超过上限被截断，未处罚。',
    '輸入超過上限被截斷，未處罰。',
    'Entrée tronquée ; aucune pénalité appliquée.',
    '入力が切り詰められたため、罰則は適用されません。',
    'Входные данные обрезаны; штраф не применён.',
    'Đầu vào bị cắt bớt; không áp dụng phạt.',
  ],
  [
    'Review error',
    '审查错误',
    '審查錯誤',
    'Erreur de contrôle',
    '審査エラー',
    'Ошибка проверки',
    'Lỗi kiểm duyệt',
  ],
  [
    'Model output is excluded from user penalties and risk scoring.',
    '模型输出不计入用户处罚和风险分。',
    '模型輸出不計入使用者處罰及風險分。',
    'Les sorties du modèle sont exclues des pénalités et du score de risque utilisateur.',
    'モデル出力はユーザーへの罰則やリスク評価の対象外です。',
    'Ответы модели исключены из штрафов и оценки риска пользователя.',
    'Đầu ra mô hình không tính vào phạt và điểm rủi ro người dùng.',
  ],
  [
    'Unable to load moderation reviews. Try again.',
    '无法加载安全审查记录，请重试。',
    '無法載入安全審查紀錄，請重試。',
    'Impossible de charger les contrôles. Réessayez.',
    '審査記録を読み込めません。再試行してください。',
    'Не удалось загрузить записи проверки. Повторите попытку.',
    'Không thể tải bản ghi kiểm duyệt. Hãy thử lại.',
  ],
  [
    'No moderation reviews match these filters.',
    '没有符合筛选条件的安全审查记录。',
    '沒有符合篩選條件的安全審查紀錄。',
    'Aucun contrôle ne correspond aux filtres.',
    '条件に一致する審査記録がありません。',
    'Нет записей, соответствующих фильтрам.',
    'Không có bản ghi kiểm duyệt phù hợp bộ lọc.',
  ],
  [
    'Historical safety audits and business summaries',
    '历史安全审计与业务总结',
    '歷史安全稽核與業務摘要',
    'Anciens audits et bilans d’activité',
    '過去の安全監査と業務集計',
    'Исторические проверки и бизнес-сводки',
    'Kiểm toán lịch sử và tổng kết hoạt động',
  ],
  [
    'Historical safety rules',
    '历史安全规则',
    '歷史安全規則',
    'Anciennes règles de sécurité',
    '過去の安全ルール',
    'Исторические правила безопасности',
    'Quy tắc an toàn lịch sử',
  ],
  [
    'Historical safety rules and fees',
    '历史安全规则与费用',
    '歷史安全規則與費用',
    'Anciennes règles et frais de sécurité',
    '過去の安全ルールと料金',
    'Исторические правила и сборы',
    'Quy tắc và phí an toàn lịch sử',
  ],
  [
    'Historical rule matching',
    '历史规则匹配',
    '歷史規則比對',
    'Ancienne détection par règles',
    '過去のルール照合',
    'Историческое сопоставление правил',
    'Đối chiếu quy tắc lịch sử',
  ],
  [
    'Retired blocking rules',
    '已停用的阻断规则',
    '已停用的阻擋規則',
    'Règles de blocage retirées',
    '廃止済みのブロックルール',
    'Отменённые правила блокировки',
    'Quy tắc chặn đã ngừng dùng',
  ],
  [
    'Retired',
    '已停用',
    '已停用',
    'Retiré',
    '廃止済み',
    'Отменено',
    'Đã ngừng dùng',
  ],
  [
    'Earlier safety rules used literal pattern matching. Their saved rules remain available for historical reference.',
    '旧安全规则使用文字匹配，已保存的规则仅供历史参考。',
    '舊安全規則使用文字比對，已儲存的規則僅供歷史參考。',
    'Les anciennes règles utilisaient une correspondance littérale. Elles restent accessibles à titre historique.',
    '以前の安全ルールは文字列を照合していました。保存済みルールは履歴として参照できます。',
    'Старые правила использовали буквальное сопоставление. Сохранённые правила доступны только для истории.',
    'Quy tắc cũ đối chiếu văn bản trực tiếp. Quy tắc đã lưu chỉ còn để tham khảo lịch sử.',
  ],
  [
    'Saved legacy block settings do not describe current enforcement. OpenAI Moderation reviews run asynchronously.',
    '旧阻断设置不代表当前执行方式，OpenAI Moderation 审查采用异步执行。',
    '舊阻擋設定不代表目前執行方式，OpenAI Moderation 審查採用非同步執行。',
    'Les anciennes options de blocage ne décrivent pas le fonctionnement actuel. OpenAI Moderation travaille en arrière-plan.',
    '過去のブロック設定は現在の動作を表しません。OpenAI Moderation は非同期に審査します。',
    'Старые настройки блокировки не отражают текущее поведение. OpenAI Moderation работает асинхронно.',
    'Cài đặt chặn cũ không phản ánh cách áp dụng hiện tại. OpenAI Moderation kiểm duyệt bất đồng bộ.',
  ],
  [
    'If you believe a safety review was incorrect, contact support with the request ID. Do not include secrets in a support ticket.',
    '如认为安全审查有误，请提供请求 ID 联系支持；工单中不要包含任何凭据。',
    '若認為安全審查有誤，請提供請求 ID 聯絡支援；工單中不要包含任何憑證。',
    'Si un contrôle vous semble incorrect, contactez l’assistance avec l’ID de requête. Ne joignez aucun secret.',
    '審査結果が誤りだと思う場合は、リクエスト ID を添えて問い合わせてください。認証情報は記載しないでください。',
    'Если проверка ошибочна, обратитесь в поддержку с ID запроса. Не добавляйте секреты в обращение.',
    'Nếu kiểm duyệt sai, hãy liên hệ hỗ trợ kèm ID yêu cầu. Không đưa thông tin bí mật vào phiếu hỗ trợ.',
  ],
  [
    'Historical rule groups',
    '历史规则分组',
    '歷史規則分組',
    'Groupes des anciennes règles',
    '過去のルールグループ',
    'Группы исторических правил',
    'Nhóm quy tắc lịch sử',
  ],
  [
    'These groups belong to the retired literal rules and do not enable current Moderation reviews.',
    '这些分组属于已停用的文字规则，不会启用当前安全审查。',
    '這些分組屬於已停用的文字規則，不會啟用目前安全審查。',
    'Ces groupes appartiennent aux règles retirées et n’activent pas la modération actuelle.',
    'これらは廃止済みの文字ルールのグループで、現在の審査を有効化しません。',
    'Эти группы относятся к отменённым правилам и не включают текущую модерацию.',
    'Các nhóm này thuộc quy tắc văn bản đã ngừng dùng, không bật kiểm duyệt hiện tại.',
  ],
  [
    'Historical risk categories',
    '历史风险类别',
    '歷史風險類別',
    'Anciennes catégories de risque',
    '過去のリスクカテゴリ',
    'Исторические категории риска',
    'Danh mục rủi ro lịch sử',
  ],
  [
    'Historical rule summaries',
    '历史规则摘要',
    '歷史規則摘要',
    'Résumé des anciennes règles',
    '過去のルール概要',
    'Сводки исторических правил',
    'Tóm tắt quy tắc lịch sử',
  ],
  [
    'Historical violation fees',
    '历史违规费用',
    '歷史違規費用',
    'Anciens frais de violation',
    '過去の違反料金',
    'Исторические штрафы',
    'Phí vi phạm lịch sử',
  ],
  [
    'These retired fee entries are kept for reference. Current Moderation fees are published in the group policies above.',
    '这些已停用的费用记录仅供参考；当前安全审查金额见上方分组策略。',
    '這些已停用的費用紀錄僅供參考；目前安全審查金額見上方分組策略。',
    'Ces frais retirés sont conservés pour référence. Les tarifs actuels figurent dans les politiques de groupe ci-dessus.',
    '廃止済みの料金は参考用です。現在の審査料金は上のグループ方針に公開されています。',
    'Отменённые тарифы сохранены для справки. Текущие суммы опубликованы в политиках групп выше.',
    'Các phí đã ngừng dùng chỉ để tham khảo. Phí hiện tại được công bố trong chính sách nhóm phía trên.',
  ],
  [
    'The following legacy rules and settings are kept for historical reference. Current safety reviews use asynchronous OpenAI Moderation.',
    '以下旧规则和设置仅供历史参考；当前安全审查使用异步 OpenAI Moderation。',
    '以下舊規則及設定僅供歷史參考；目前安全審查使用非同步 OpenAI Moderation。',
    'Les anciennes règles ci-dessous sont conservées pour référence. Les contrôles actuels utilisent OpenAI Moderation en arrière-plan.',
    '以下の古い設定は履歴として残されています。現在の安全審査は非同期 OpenAI Moderation を使用します。',
    'Старые правила ниже сохранены для истории. Текущие проверки используют асинхронный OpenAI Moderation.',
    'Quy tắc cũ bên dưới chỉ còn tham khảo lịch sử. Kiểm duyệt hiện tại dùng OpenAI Moderation bất đồng bộ.',
  ],
  [
    'Legacy detection and response',
    '历史检测与处理方式',
    '歷史偵測與處理方式',
    'Anciennes détection et réponse',
    '過去の検出と対応',
    'Исторические обнаружение и реакция',
    'Phát hiện và xử lý trước đây',
  ],
  [
    'This section describes retired rule matching for reference. Current safety reviews do not use these blocking rules.',
    '本节仅介绍已停用的规则匹配；当前安全审查不再使用这些阻断规则。',
    '本節僅介紹已停用的規則比對；目前安全審查不再使用這些阻擋規則。',
    'Cette section présente les règles retirées. Les contrôles actuels n’utilisent plus ces règles de blocage.',
    'この節は廃止済みルールの説明です。現在の審査はこれらのブロックルールを使用しません。',
    'Здесь описаны отменённые правила. Текущие проверки не используют эти правила блокировки.',
    'Phần này mô tả quy tắc đã ngừng dùng. Kiểm duyệt hiện tại không dùng các quy tắc chặn này.',
  ],
  [
    'Literal blocking rules are retired. Configure asynchronous OpenAI Moderation to review content.',
    '文字阻断规则已停用，请配置异步 OpenAI Moderation 审查内容。',
    '文字阻擋規則已停用，請設定非同步 OpenAI Moderation 審查內容。',
    'Les règles de blocage littéral sont retirées. Configurez OpenAI Moderation en arrière-plan.',
    '文字照合のブロックルールは廃止されました。非同期 OpenAI Moderation を設定してください。',
    'Правила буквальной блокировки отменены. Настройте асинхронный OpenAI Moderation.',
    'Quy tắc chặn văn bản đã ngừng dùng. Hãy cấu hình OpenAI Moderation bất đồng bộ.',
  ],
  [
    'Saved legacy rule setting',
    '已保存的旧规则开关',
    '已儲存的舊規則開關',
    'Ancienne activation enregistrée',
    '保存済みの旧ルール設定',
    'Сохранённое старое включение',
    'Trạng thái quy tắc cũ đã lưu',
  ],
  [
    'Saved legacy prompt inspection',
    '已保存的旧输入检查',
    '已儲存的舊輸入檢查',
    'Ancien contrôle d’entrée enregistré',
    '保存済みの旧入力検査',
    'Сохранённая старая проверка ввода',
    'Kiểm tra đầu vào cũ đã lưu',
  ],
  [
    'Saved legacy response action',
    '已保存的旧处理方式',
    '已儲存的舊處理方式',
    'Ancienne action enregistrée',
    '保存済みの旧処理方法',
    'Сохранённая старая реакция',
    'Cách xử lý cũ đã lưu',
  ],
  [
    'Block (legacy saved setting)',
    '阻断（旧配置）',
    '阻擋（舊設定）',
    'Bloquer (ancien réglage)',
    'ブロック（旧設定）',
    'Блокировать (старые настройки)',
    'Chặn (cài đặt cũ)',
  ],
  [
    'Audit (legacy saved setting)',
    '记录审计（旧配置）',
    '記錄稽核（舊設定）',
    'Auditer (ancien réglage)',
    '監査記録（旧設定）',
    'Аудит (старые настройки)',
    'Ghi kiểm toán (cài đặt cũ)',
  ],
  [
    'Historical rule configuration',
    '历史规则配置',
    '歷史規則設定',
    'Configuration des anciennes règles',
    '過去のルール設定',
    'Историческая конфигурация правил',
    'Cấu hình quy tắc lịch sử',
  ],
  [
    'Moderation notifications',
    '安全审查通知',
    '安全審查通知',
    'Notifications de modération',
    '安全審査通知',
    'Уведомления модерации',
    'Thông báo kiểm duyệt',
  ],
  [
    'Safety review warning',
    '安全审查警告',
    '安全審查警告',
    'Avertissement de sécurité',
    '安全審査の警告',
    'Предупреждение проверки',
    'Cảnh báo kiểm duyệt an toàn',
  ],
  [
    'Categories',
    '类别',
    '類別',
    'Catégories',
    'カテゴリ',
    'Категории',
    'Danh mục',
  ],
  [
    'API user input',
    'API 用户输入',
    'API 使用者輸入',
    'Entrée utilisateur API',
    'API ユーザー入力',
    'Ввод пользователя API',
    'Đầu vào người dùng API',
  ],
  [
    'Assistant user input',
    '助手用户输入',
    '助手使用者輸入',
    'Entrée utilisateur de l’assistant',
    'アシスタントへのユーザー入力',
    'Ввод пользователя помощника',
    'Đầu vào người dùng trợ lý',
  ],
  [
    'This warning concerns assistant output; your wallet and risk score are unchanged.',
    '此警告针对助手输出，不影响您的钱包余额或风险分。',
    '此警告針對助手輸出，不影響您的錢包餘額或風險分。',
    'Cet avertissement concerne la sortie de l’assistant ; votre solde et votre risque restent inchangés.',
    'この警告はアシスタント出力に関するもので、残高やリスク評価には影響しません。',
    'Это предупреждение об ответе помощника; баланс и оценка риска не изменились.',
    'Cảnh báo này liên quan đầu ra trợ lý; số dư và điểm rủi ro của bạn không thay đổi.',
  ],
  [
    'Moderation reviews',
    '安全审查次数',
    '安全審查次數',
    'Contrôles de modération',
    '安全審査数',
    'Количество проверок',
    'Số lượt kiểm duyệt',
  ],
  [
    'Flagged user inputs',
    '用户输入违规次数',
    '使用者輸入違規次數',
    'Entrées utilisateur signalées',
    'ユーザー入力の違反数',
    'Нарушения во вводе пользователя',
    'Số đầu vào người dùng vi phạm',
  ],
  [
    'Moderation violations in user input',
    '用户输入存在安全审查违规',
    '使用者輸入存在安全審查違規',
    'Violations dans les entrées utilisateur',
    'ユーザー入力の安全審査違反',
    'Нарушения модерации во вводе',
    'Vi phạm kiểm duyệt trong đầu vào',
  ],
  [
    'Only flagged user input contributes to Moderation risk. Model output is excluded.',
    '仅用户输入违规影响安全审查风险，模型输出不计入。',
    '僅使用者輸入違規影響安全審查風險，模型輸出不計入。',
    'Seules les entrées utilisateur signalées contribuent au risque. Les sorties du modèle sont exclues.',
    'ユーザー入力の違反のみが審査リスクに反映され、モデル出力は除外されます。',
    'На риск влияют только нарушения во вводе; ответы модели исключены.',
    'Chỉ đầu vào người dùng vi phạm ảnh hưởng rủi ro; đầu ra mô hình không tính.',
  ],
  [
    'All-time Moderation statistics',
    '累计安全审查统计',
    '累計安全審查統計',
    'Statistiques cumulées de modération',
    '累計安全審査統計',
    'Общая статистика модерации',
    'Thống kê kiểm duyệt tích lũy',
  ],
  [
    'Completed Moderation reviews',
    '已完成安全审查',
    '已完成安全審查',
    'Contrôles terminés',
    '完了した安全審査',
    'Завершённые проверки',
    'Kiểm duyệt đã hoàn tất',
  ],
  [
    'Flagged Moderation reviews',
    '发现违规的安全审查',
    '發現違規的安全審查',
    'Contrôles signalés',
    '違反を検出した審査',
    'Проверки с нарушениями',
    'Kiểm duyệt phát hiện vi phạm',
  ],
  [
    'Reviews with wallet deductions',
    '产生扣款的审查',
    '產生扣款的審查',
    'Contrôles avec débit',
    '引き落としが発生した審査',
    'Проверки со списанием',
    'Kiểm duyệt có trừ phí',
  ],
  [
    'Failed Moderation reviews',
    '失败的安全审查',
    '失敗的安全審查',
    'Contrôles échoués',
    '失敗した安全審査',
    'Неудачные проверки',
    'Kiểm duyệt thất bại',
  ],
  [
    'Pending reviews',
    '待执行审查',
    '待執行審查',
    'Contrôles en attente',
    '待機中の審査',
    'Ожидающие проверки',
    'Kiểm duyệt đang chờ',
  ],
  [
    'Running reviews',
    '执行中审查',
    '執行中審查',
    'Contrôles en cours',
    '実行中の審査',
    'Выполняемые проверки',
    'Kiểm duyệt đang chạy',
  ],
  [
    'Cancelled reviews',
    '已取消审查',
    '已取消審查',
    'Contrôles annulés',
    '取消済みの審査',
    'Отменённые проверки',
    'Kiểm duyệt đã hủy',
  ],
  [
    'Total Moderation wallet deductions',
    '安全审查累计扣款',
    '安全審查累計扣款',
    'Total des débits de modération',
    '安全審査による累計引き落とし',
    'Общие списания за модерацию',
    'Tổng tiền trừ do kiểm duyệt',
  ],
  [
    'Moderation statistics are not available yet.',
    '暂无安全审查统计。',
    '暫無安全審查統計。',
    'Statistiques de modération indisponibles.',
    '安全審査統計はまだありません。',
    'Статистика модерации пока недоступна.',
    'Chưa có thống kê kiểm duyệt.',
  ],
  [
    'The server has not published Moderation counts. No totals are estimated.',
    '服务器尚未公布安全审查次数，此处不会估算统计。',
    '伺服器尚未公布安全審查次數，此處不會估算統計。',
    'Le serveur n’a pas publié les compteurs. Aucun total n’est estimé.',
    'サーバーが審査数を公開していないため、推定値は表示しません。',
    'Сервер не опубликовал числа проверок. Итоги не оцениваются.',
    'Máy chủ chưa công bố số lượt kiểm duyệt. Không ước tính tổng số.',
  ],
  [
    'Flagged reviews include user input and assistant output. Only user input contributes to account risk.',
    '违规审查包含用户输入与助手输出，只有用户输入影响账号风险。',
    '違規審查包含使用者輸入及助手輸出，只有使用者輸入影響帳號風險。',
    'Les contrôles signalés incluent entrées et sorties. Seules les entrées utilisateur contribuent au risque du compte.',
    '違反件数には入力と出力を含みますが、アカウントのリスクにはユーザー入力のみを反映します。',
    'Нарушения включают ввод и ответы. На риск аккаунта влияет только ввод пользователя.',
    'Lượt vi phạm gồm đầu vào và đầu ra; chỉ đầu vào người dùng ảnh hưởng rủi ro tài khoản.',
  ],
  [
    'Confirm your identity before accessing this sensitive action.',
    '访问此敏感操作前，请先确认身份。',
    '存取此敏感操作前，請先確認身分。',
    'Confirmez votre identité avant cette action sensible.',
    'この機密操作の前に本人確認を行ってください。',
    'Подтвердите личность перед этим чувствительным действием.',
    'Xác nhận danh tính trước khi thực hiện thao tác nhạy cảm này.',
  ],
  [
    'Historical rule matching statistics',
    '历史规则匹配统计',
    '歷史規則比對統計',
    'Statistiques des anciennes règles',
    '過去のルール照合統計',
    'Статистика исторических правил',
    'Thống kê đối chiếu quy tắc cũ',
  ],
  [
    'When enabled, reviewable text is sent to OpenAI for safety classification.',
    '启用后，可审查的文本会发送给 OpenAI 进行安全分类。',
    '啟用後，可審查的文字會傳送給 OpenAI 進行安全分類。',
    'Si activé, le texte à contrôler est envoyé à OpenAI pour classification de sécurité.',
    '有効にすると、審査対象テキストが安全分類のため OpenAI に送信されます。',
    'При включении проверяемый текст отправляется OpenAI для классификации безопасности.',
    'Khi bật, văn bản cần kiểm duyệt được gửi đến OpenAI để phân loại an toàn.',
  ],
  [
    'Deductions round down to the wallet’s smallest supported amount. Smaller fees only trigger a warning.',
    '扣款按钱包支持的最小金额向下取整；不足最小金额仅提醒，不扣款。',
    '扣款依錢包支援的最小金額向下取整；不足最小金額僅提醒，不扣款。',
    'Les débits sont arrondis à l’unité minimale du portefeuille, vers le bas. Les frais inférieurs déclenchent seulement un avertissement.',
    '引き落とし額はウォレットの最小単位に切り捨てます。それ未満の金額では警告のみを行います。',
    'Списания округляются вниз до минимальной суммы кошелька. Меньшие суммы вызывают только предупреждение.',
    'Khoản trừ được làm tròn xuống đơn vị nhỏ nhất của ví. Phí thấp hơn chỉ tạo cảnh báo.',
  ],
  [
    'No deduction',
    '未扣款',
    '未扣款',
    'Aucun débit',
    '引き落としなし',
    'Без списания',
    'Không trừ phí',
  ],
  [
    'Charged',
    '已扣款',
    '已扣款',
    'Débité',
    '課金済み',
    'Списано',
    'Đã trừ phí',
  ],
  [
    'Partially charged',
    '部分扣款',
    '部分扣款',
    'Débit partiel',
    '一部引き落とし',
    'Частично списано',
    'Đã trừ một phần',
  ],
  [
    'Insufficient balance',
    '余额不足',
    '餘額不足',
    'Solde insuffisant',
    '残高不足',
    'Недостаточный баланс',
    'Không đủ số dư',
  ],
  [
    'OpenHuman (removed)',
    'OpenHuman（已移除）',
    'OpenHuman（已移除）',
    'OpenHuman (supprimé)',
    'OpenHuman（削除済み）',
    'OpenHuman (удалён)',
    'OpenHuman (đã loại bỏ)',
  ],
]

export const moderationCopy = Object.fromEntries(
  ['en', 'zh', 'zh-TW', 'fr', 'ja', 'ru', 'vi'].map((locale, index) => [
    locale,
    Object.fromEntries(
      entries.map((entry) => [entry[0], index === 0 ? entry[0] : entry[index]])
    ),
  ])
)
