// This small stdlib-only generator freezes the Unicode categories used by
// current Go's token estimator, independently of Rust's Unicode version.
package main

import (
	"fmt"
	"os"
	"unicode"
)

func main() {
	if len(os.Args) != 2 {
		panic("expected output path")
	}
	out, err := os.Create(os.Args[1])
	if err != nil {
		panic(err)
	}
	defer out.Close()
	fmt.Fprintf(out, "// Generated by tests/behavior-oracle/fixtures/relay_unicode_tables.go.\n// Go Unicode version: %s. Do not hand edit.\n", unicode.Version)
	for _, item := range []struct {
		name  string
		table *unicode.RangeTable
	}{
		{"LETTERS", unicode.L}, {"NUMBERS", unicode.N}, {"HAN", unicode.Han}, {"SPACE", unicode.White_Space},
	} {
		fmt.Fprintf(out, "pub(super) const %s: &[(u32, u32, u32)] = &[\n", item.name)
		for _, r := range item.table.R16 {
			fmt.Fprintf(out, "    (0x%x, 0x%x, %d),\n", r.Lo, r.Hi, r.Stride)
		}
		for _, r := range item.table.R32 {
			fmt.Fprintf(out, "    (0x%x, 0x%x, %d),\n", r.Lo, r.Hi, r.Stride)
		}
		fmt.Fprintln(out, "];")
	}
}
