// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: lmm/core/v1/commands.proto

package corepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreIdentityCommands_RevokeCredential_FullMethodName = "/lmm.core.v1.CoreIdentityCommands/RevokeCredential"
)

// CoreIdentityCommandsClient is the client API for CoreIdentityCommands service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreIdentityCommandsClient interface {
	RevokeCredential(ctx context.Context, in *RevokeCredentialRequest, opts ...grpc.CallOption) (*MutationReceipt, error)
}

type coreIdentityCommandsClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreIdentityCommandsClient(cc grpc.ClientConnInterface) CoreIdentityCommandsClient {
	return &coreIdentityCommandsClient{cc}
}

func (c *coreIdentityCommandsClient) RevokeCredential(ctx context.Context, in *RevokeCredentialRequest, opts ...grpc.CallOption) (*MutationReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationReceipt)
	err := c.cc.Invoke(ctx, CoreIdentityCommands_RevokeCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreIdentityCommandsServer is the server API for CoreIdentityCommands service.
// All implementations must embed UnimplementedCoreIdentityCommandsServer
// for forward compatibility.
type CoreIdentityCommandsServer interface {
	RevokeCredential(context.Context, *RevokeCredentialRequest) (*MutationReceipt, error)
	mustEmbedUnimplementedCoreIdentityCommandsServer()
}

// UnimplementedCoreIdentityCommandsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreIdentityCommandsServer struct{}

func (UnimplementedCoreIdentityCommandsServer) RevokeCredential(context.Context, *RevokeCredentialRequest) (*MutationReceipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeCredential not implemented")
}
func (UnimplementedCoreIdentityCommandsServer) mustEmbedUnimplementedCoreIdentityCommandsServer() {}
func (UnimplementedCoreIdentityCommandsServer) testEmbeddedByValue()                              {}

// UnsafeCoreIdentityCommandsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreIdentityCommandsServer will
// result in compilation errors.
type UnsafeCoreIdentityCommandsServer interface {
	mustEmbedUnimplementedCoreIdentityCommandsServer()
}

func RegisterCoreIdentityCommandsServer(s grpc.ServiceRegistrar, srv CoreIdentityCommandsServer) {
	// If the following call pancis, it indicates UnimplementedCoreIdentityCommandsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreIdentityCommands_ServiceDesc, srv)
}

func _CoreIdentityCommands_RevokeCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreIdentityCommandsServer).RevokeCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreIdentityCommands_RevokeCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreIdentityCommandsServer).RevokeCredential(ctx, req.(*RevokeCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreIdentityCommands_ServiceDesc is the grpc.ServiceDesc for CoreIdentityCommands service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreIdentityCommands_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lmm.core.v1.CoreIdentityCommands",
	HandlerType: (*CoreIdentityCommandsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RevokeCredential",
			Handler:    _CoreIdentityCommands_RevokeCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lmm/core/v1/commands.proto",
}

const (
	CoreLedgerCommands_CaptureVerifiedPayment_FullMethodName = "/lmm.core.v1.CoreLedgerCommands/CaptureVerifiedPayment"
	CoreLedgerCommands_Transfer_FullMethodName               = "/lmm.core.v1.CoreLedgerCommands/Transfer"
	CoreLedgerCommands_Refund_FullMethodName                 = "/lmm.core.v1.CoreLedgerCommands/Refund"
)

// CoreLedgerCommandsClient is the client API for CoreLedgerCommands service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreLedgerCommandsClient interface {
	CaptureVerifiedPayment(ctx context.Context, in *CaptureVerifiedPaymentRequest, opts ...grpc.CallOption) (*MutationReceipt, error)
	Transfer(ctx context.Context, in *TransferFundsRequest, opts ...grpc.CallOption) (*MutationReceipt, error)
	Refund(ctx context.Context, in *RefundFundsRequest, opts ...grpc.CallOption) (*MutationReceipt, error)
}

type coreLedgerCommandsClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreLedgerCommandsClient(cc grpc.ClientConnInterface) CoreLedgerCommandsClient {
	return &coreLedgerCommandsClient{cc}
}

func (c *coreLedgerCommandsClient) CaptureVerifiedPayment(ctx context.Context, in *CaptureVerifiedPaymentRequest, opts ...grpc.CallOption) (*MutationReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationReceipt)
	err := c.cc.Invoke(ctx, CoreLedgerCommands_CaptureVerifiedPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreLedgerCommandsClient) Transfer(ctx context.Context, in *TransferFundsRequest, opts ...grpc.CallOption) (*MutationReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationReceipt)
	err := c.cc.Invoke(ctx, CoreLedgerCommands_Transfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreLedgerCommandsClient) Refund(ctx context.Context, in *RefundFundsRequest, opts ...grpc.CallOption) (*MutationReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationReceipt)
	err := c.cc.Invoke(ctx, CoreLedgerCommands_Refund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreLedgerCommandsServer is the server API for CoreLedgerCommands service.
// All implementations must embed UnimplementedCoreLedgerCommandsServer
// for forward compatibility.
type CoreLedgerCommandsServer interface {
	CaptureVerifiedPayment(context.Context, *CaptureVerifiedPaymentRequest) (*MutationReceipt, error)
	Transfer(context.Context, *TransferFundsRequest) (*MutationReceipt, error)
	Refund(context.Context, *RefundFundsRequest) (*MutationReceipt, error)
	mustEmbedUnimplementedCoreLedgerCommandsServer()
}

// UnimplementedCoreLedgerCommandsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreLedgerCommandsServer struct{}

func (UnimplementedCoreLedgerCommandsServer) CaptureVerifiedPayment(context.Context, *CaptureVerifiedPaymentRequest) (*MutationReceipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CaptureVerifiedPayment not implemented")
}
func (UnimplementedCoreLedgerCommandsServer) Transfer(context.Context, *TransferFundsRequest) (*MutationReceipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Transfer not implemented")
}
func (UnimplementedCoreLedgerCommandsServer) Refund(context.Context, *RefundFundsRequest) (*MutationReceipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refund not implemented")
}
func (UnimplementedCoreLedgerCommandsServer) mustEmbedUnimplementedCoreLedgerCommandsServer() {}
func (UnimplementedCoreLedgerCommandsServer) testEmbeddedByValue()                            {}

// UnsafeCoreLedgerCommandsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreLedgerCommandsServer will
// result in compilation errors.
type UnsafeCoreLedgerCommandsServer interface {
	mustEmbedUnimplementedCoreLedgerCommandsServer()
}

func RegisterCoreLedgerCommandsServer(s grpc.ServiceRegistrar, srv CoreLedgerCommandsServer) {
	// If the following call pancis, it indicates UnimplementedCoreLedgerCommandsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreLedgerCommands_ServiceDesc, srv)
}

func _CoreLedgerCommands_CaptureVerifiedPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureVerifiedPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreLedgerCommandsServer).CaptureVerifiedPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreLedgerCommands_CaptureVerifiedPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreLedgerCommandsServer).CaptureVerifiedPayment(ctx, req.(*CaptureVerifiedPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreLedgerCommands_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferFundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreLedgerCommandsServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreLedgerCommands_Transfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreLedgerCommandsServer).Transfer(ctx, req.(*TransferFundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreLedgerCommands_Refund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundFundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreLedgerCommandsServer).Refund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreLedgerCommands_Refund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreLedgerCommandsServer).Refund(ctx, req.(*RefundFundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreLedgerCommands_ServiceDesc is the grpc.ServiceDesc for CoreLedgerCommands service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreLedgerCommands_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lmm.core.v1.CoreLedgerCommands",
	HandlerType: (*CoreLedgerCommandsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CaptureVerifiedPayment",
			Handler:    _CoreLedgerCommands_CaptureVerifiedPayment_Handler,
		},
		{
			MethodName: "Transfer",
			Handler:    _CoreLedgerCommands_Transfer_Handler,
		},
		{
			MethodName: "Refund",
			Handler:    _CoreLedgerCommands_Refund_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lmm/core/v1/commands.proto",
}

const (
	CoreBillingCommands_Reserve_FullMethodName = "/lmm.core.v1.CoreBillingCommands/Reserve"
	CoreBillingCommands_Settle_FullMethodName  = "/lmm.core.v1.CoreBillingCommands/Settle"
	CoreBillingCommands_Release_FullMethodName = "/lmm.core.v1.CoreBillingCommands/Release"
)

// CoreBillingCommandsClient is the client API for CoreBillingCommands service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreBillingCommandsClient interface {
	Reserve(ctx context.Context, in *ReserveUsageRequest, opts ...grpc.CallOption) (*ReservationReceipt, error)
	Settle(ctx context.Context, in *SettleUsageRequest, opts ...grpc.CallOption) (*MutationReceipt, error)
	Release(ctx context.Context, in *ReleaseUsageRequest, opts ...grpc.CallOption) (*MutationReceipt, error)
}

type coreBillingCommandsClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreBillingCommandsClient(cc grpc.ClientConnInterface) CoreBillingCommandsClient {
	return &coreBillingCommandsClient{cc}
}

func (c *coreBillingCommandsClient) Reserve(ctx context.Context, in *ReserveUsageRequest, opts ...grpc.CallOption) (*ReservationReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReservationReceipt)
	err := c.cc.Invoke(ctx, CoreBillingCommands_Reserve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreBillingCommandsClient) Settle(ctx context.Context, in *SettleUsageRequest, opts ...grpc.CallOption) (*MutationReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationReceipt)
	err := c.cc.Invoke(ctx, CoreBillingCommands_Settle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreBillingCommandsClient) Release(ctx context.Context, in *ReleaseUsageRequest, opts ...grpc.CallOption) (*MutationReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationReceipt)
	err := c.cc.Invoke(ctx, CoreBillingCommands_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreBillingCommandsServer is the server API for CoreBillingCommands service.
// All implementations must embed UnimplementedCoreBillingCommandsServer
// for forward compatibility.
type CoreBillingCommandsServer interface {
	Reserve(context.Context, *ReserveUsageRequest) (*ReservationReceipt, error)
	Settle(context.Context, *SettleUsageRequest) (*MutationReceipt, error)
	Release(context.Context, *ReleaseUsageRequest) (*MutationReceipt, error)
	mustEmbedUnimplementedCoreBillingCommandsServer()
}

// UnimplementedCoreBillingCommandsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreBillingCommandsServer struct{}

func (UnimplementedCoreBillingCommandsServer) Reserve(context.Context, *ReserveUsageRequest) (*ReservationReceipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reserve not implemented")
}
func (UnimplementedCoreBillingCommandsServer) Settle(context.Context, *SettleUsageRequest) (*MutationReceipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Settle not implemented")
}
func (UnimplementedCoreBillingCommandsServer) Release(context.Context, *ReleaseUsageRequest) (*MutationReceipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedCoreBillingCommandsServer) mustEmbedUnimplementedCoreBillingCommandsServer() {}
func (UnimplementedCoreBillingCommandsServer) testEmbeddedByValue()                             {}

// UnsafeCoreBillingCommandsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreBillingCommandsServer will
// result in compilation errors.
type UnsafeCoreBillingCommandsServer interface {
	mustEmbedUnimplementedCoreBillingCommandsServer()
}

func RegisterCoreBillingCommandsServer(s grpc.ServiceRegistrar, srv CoreBillingCommandsServer) {
	// If the following call pancis, it indicates UnimplementedCoreBillingCommandsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreBillingCommands_ServiceDesc, srv)
}

func _CoreBillingCommands_Reserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreBillingCommandsServer).Reserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreBillingCommands_Reserve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreBillingCommandsServer).Reserve(ctx, req.(*ReserveUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreBillingCommands_Settle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreBillingCommandsServer).Settle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreBillingCommands_Settle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreBillingCommandsServer).Settle(ctx, req.(*SettleUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreBillingCommands_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreBillingCommandsServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreBillingCommands_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreBillingCommandsServer).Release(ctx, req.(*ReleaseUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreBillingCommands_ServiceDesc is the grpc.ServiceDesc for CoreBillingCommands service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreBillingCommands_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lmm.core.v1.CoreBillingCommands",
	HandlerType: (*CoreBillingCommandsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reserve",
			Handler:    _CoreBillingCommands_Reserve_Handler,
		},
		{
			MethodName: "Settle",
			Handler:    _CoreBillingCommands_Settle_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _CoreBillingCommands_Release_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lmm/core/v1/commands.proto",
}

const (
	CoreRoutingCommands_ActivateConfiguration_FullMethodName = "/lmm.core.v1.CoreRoutingCommands/ActivateConfiguration"
)

// CoreRoutingCommandsClient is the client API for CoreRoutingCommands service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreRoutingCommandsClient interface {
	ActivateConfiguration(ctx context.Context, in *ActivateConfigurationRequest, opts ...grpc.CallOption) (*MutationReceipt, error)
}

type coreRoutingCommandsClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreRoutingCommandsClient(cc grpc.ClientConnInterface) CoreRoutingCommandsClient {
	return &coreRoutingCommandsClient{cc}
}

func (c *coreRoutingCommandsClient) ActivateConfiguration(ctx context.Context, in *ActivateConfigurationRequest, opts ...grpc.CallOption) (*MutationReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationReceipt)
	err := c.cc.Invoke(ctx, CoreRoutingCommands_ActivateConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreRoutingCommandsServer is the server API for CoreRoutingCommands service.
// All implementations must embed UnimplementedCoreRoutingCommandsServer
// for forward compatibility.
type CoreRoutingCommandsServer interface {
	ActivateConfiguration(context.Context, *ActivateConfigurationRequest) (*MutationReceipt, error)
	mustEmbedUnimplementedCoreRoutingCommandsServer()
}

// UnimplementedCoreRoutingCommandsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreRoutingCommandsServer struct{}

func (UnimplementedCoreRoutingCommandsServer) ActivateConfiguration(context.Context, *ActivateConfigurationRequest) (*MutationReceipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateConfiguration not implemented")
}
func (UnimplementedCoreRoutingCommandsServer) mustEmbedUnimplementedCoreRoutingCommandsServer() {}
func (UnimplementedCoreRoutingCommandsServer) testEmbeddedByValue()                             {}

// UnsafeCoreRoutingCommandsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreRoutingCommandsServer will
// result in compilation errors.
type UnsafeCoreRoutingCommandsServer interface {
	mustEmbedUnimplementedCoreRoutingCommandsServer()
}

func RegisterCoreRoutingCommandsServer(s grpc.ServiceRegistrar, srv CoreRoutingCommandsServer) {
	// If the following call pancis, it indicates UnimplementedCoreRoutingCommandsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreRoutingCommands_ServiceDesc, srv)
}

func _CoreRoutingCommands_ActivateConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreRoutingCommandsServer).ActivateConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreRoutingCommands_ActivateConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreRoutingCommandsServer).ActivateConfiguration(ctx, req.(*ActivateConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreRoutingCommands_ServiceDesc is the grpc.ServiceDesc for CoreRoutingCommands service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreRoutingCommands_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lmm.core.v1.CoreRoutingCommands",
	HandlerType: (*CoreRoutingCommandsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActivateConfiguration",
			Handler:    _CoreRoutingCommands_ActivateConfiguration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lmm/core/v1/commands.proto",
}
