// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: lmm/core/v1/events.proto

package corepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreEvents_Negotiate_FullMethodName   = "/lmm.core.v1.CoreEvents/Negotiate"
	CoreEvents_Pull_FullMethodName        = "/lmm.core.v1.CoreEvents/Pull"
	CoreEvents_Acknowledge_FullMethodName = "/lmm.core.v1.CoreEvents/Acknowledge"
	CoreEvents_Retry_FullMethodName       = "/lmm.core.v1.CoreEvents/Retry"
)

// CoreEventsClient is the client API for CoreEvents service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Durable, service-scoped subscriptions. No user or service secrets in messages.
// Subscriptions are provisioned by core configuration, NOT by this service.
type CoreEventsClient interface {
	Negotiate(ctx context.Context, in *NegotiateEventsRequest, opts ...grpc.CallOption) (*NegotiateEventsResponse, error)
	Pull(ctx context.Context, in *PullEventsRequest, opts ...grpc.CallOption) (*PullEventsResponse, error)
	Acknowledge(ctx context.Context, in *AcknowledgeEventRequest, opts ...grpc.CallOption) (*AcknowledgeEventResponse, error)
	Retry(ctx context.Context, in *RetryEventRequest, opts ...grpc.CallOption) (*RetryEventResponse, error)
}

type coreEventsClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreEventsClient(cc grpc.ClientConnInterface) CoreEventsClient {
	return &coreEventsClient{cc}
}

func (c *coreEventsClient) Negotiate(ctx context.Context, in *NegotiateEventsRequest, opts ...grpc.CallOption) (*NegotiateEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NegotiateEventsResponse)
	err := c.cc.Invoke(ctx, CoreEvents_Negotiate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreEventsClient) Pull(ctx context.Context, in *PullEventsRequest, opts ...grpc.CallOption) (*PullEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullEventsResponse)
	err := c.cc.Invoke(ctx, CoreEvents_Pull_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreEventsClient) Acknowledge(ctx context.Context, in *AcknowledgeEventRequest, opts ...grpc.CallOption) (*AcknowledgeEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeEventResponse)
	err := c.cc.Invoke(ctx, CoreEvents_Acknowledge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreEventsClient) Retry(ctx context.Context, in *RetryEventRequest, opts ...grpc.CallOption) (*RetryEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryEventResponse)
	err := c.cc.Invoke(ctx, CoreEvents_Retry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreEventsServer is the server API for CoreEvents service.
// All implementations must embed UnimplementedCoreEventsServer
// for forward compatibility.
//
// Durable, service-scoped subscriptions. No user or service secrets in messages.
// Subscriptions are provisioned by core configuration, NOT by this service.
type CoreEventsServer interface {
	Negotiate(context.Context, *NegotiateEventsRequest) (*NegotiateEventsResponse, error)
	Pull(context.Context, *PullEventsRequest) (*PullEventsResponse, error)
	Acknowledge(context.Context, *AcknowledgeEventRequest) (*AcknowledgeEventResponse, error)
	Retry(context.Context, *RetryEventRequest) (*RetryEventResponse, error)
	mustEmbedUnimplementedCoreEventsServer()
}

// UnimplementedCoreEventsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreEventsServer struct{}

func (UnimplementedCoreEventsServer) Negotiate(context.Context, *NegotiateEventsRequest) (*NegotiateEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Negotiate not implemented")
}
func (UnimplementedCoreEventsServer) Pull(context.Context, *PullEventsRequest) (*PullEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pull not implemented")
}
func (UnimplementedCoreEventsServer) Acknowledge(context.Context, *AcknowledgeEventRequest) (*AcknowledgeEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Acknowledge not implemented")
}
func (UnimplementedCoreEventsServer) Retry(context.Context, *RetryEventRequest) (*RetryEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Retry not implemented")
}
func (UnimplementedCoreEventsServer) mustEmbedUnimplementedCoreEventsServer() {}
func (UnimplementedCoreEventsServer) testEmbeddedByValue()                    {}

// UnsafeCoreEventsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreEventsServer will
// result in compilation errors.
type UnsafeCoreEventsServer interface {
	mustEmbedUnimplementedCoreEventsServer()
}

func RegisterCoreEventsServer(s grpc.ServiceRegistrar, srv CoreEventsServer) {
	// If the following call pancis, it indicates UnimplementedCoreEventsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreEvents_ServiceDesc, srv)
}

func _CoreEvents_Negotiate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NegotiateEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreEventsServer).Negotiate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreEvents_Negotiate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreEventsServer).Negotiate(ctx, req.(*NegotiateEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreEvents_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreEventsServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreEvents_Pull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreEventsServer).Pull(ctx, req.(*PullEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreEvents_Acknowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreEventsServer).Acknowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreEvents_Acknowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreEventsServer).Acknowledge(ctx, req.(*AcknowledgeEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreEvents_Retry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreEventsServer).Retry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreEvents_Retry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreEventsServer).Retry(ctx, req.(*RetryEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreEvents_ServiceDesc is the grpc.ServiceDesc for CoreEvents service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreEvents_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lmm.core.v1.CoreEvents",
	HandlerType: (*CoreEventsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Negotiate",
			Handler:    _CoreEvents_Negotiate_Handler,
		},
		{
			MethodName: "Pull",
			Handler:    _CoreEvents_Pull_Handler,
		},
		{
			MethodName: "Acknowledge",
			Handler:    _CoreEvents_Acknowledge_Handler,
		},
		{
			MethodName: "Retry",
			Handler:    _CoreEvents_Retry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lmm/core/v1/events.proto",
}
