// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: lmm/core/v1/ledger.proto

package corepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreLedger_PostLedger_FullMethodName       = "/lmm.core.v1.CoreLedger/PostLedger"
	CoreLedger_GetLedgerBalance_FullMethodName = "/lmm.core.v1.CoreLedger/GetLedgerBalance"
)

// CoreLedgerClient is the client API for CoreLedger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Task 02 handoff. Contract only: do not register before user/team/key budgets,
// service permissions and same-transaction outbox integration exist.
type CoreLedgerClient interface {
	PostLedger(ctx context.Context, in *PostLedgerRequest, opts ...grpc.CallOption) (*PostLedgerResponse, error)
	GetLedgerBalance(ctx context.Context, in *GetLedgerBalanceRequest, opts ...grpc.CallOption) (*GetLedgerBalanceResponse, error)
}

type coreLedgerClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreLedgerClient(cc grpc.ClientConnInterface) CoreLedgerClient {
	return &coreLedgerClient{cc}
}

func (c *coreLedgerClient) PostLedger(ctx context.Context, in *PostLedgerRequest, opts ...grpc.CallOption) (*PostLedgerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostLedgerResponse)
	err := c.cc.Invoke(ctx, CoreLedger_PostLedger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreLedgerClient) GetLedgerBalance(ctx context.Context, in *GetLedgerBalanceRequest, opts ...grpc.CallOption) (*GetLedgerBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLedgerBalanceResponse)
	err := c.cc.Invoke(ctx, CoreLedger_GetLedgerBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreLedgerServer is the server API for CoreLedger service.
// All implementations must embed UnimplementedCoreLedgerServer
// for forward compatibility.
//
// Task 02 handoff. Contract only: do not register before user/team/key budgets,
// service permissions and same-transaction outbox integration exist.
type CoreLedgerServer interface {
	PostLedger(context.Context, *PostLedgerRequest) (*PostLedgerResponse, error)
	GetLedgerBalance(context.Context, *GetLedgerBalanceRequest) (*GetLedgerBalanceResponse, error)
	mustEmbedUnimplementedCoreLedgerServer()
}

// UnimplementedCoreLedgerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreLedgerServer struct{}

func (UnimplementedCoreLedgerServer) PostLedger(context.Context, *PostLedgerRequest) (*PostLedgerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostLedger not implemented")
}
func (UnimplementedCoreLedgerServer) GetLedgerBalance(context.Context, *GetLedgerBalanceRequest) (*GetLedgerBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLedgerBalance not implemented")
}
func (UnimplementedCoreLedgerServer) mustEmbedUnimplementedCoreLedgerServer() {}
func (UnimplementedCoreLedgerServer) testEmbeddedByValue()                    {}

// UnsafeCoreLedgerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreLedgerServer will
// result in compilation errors.
type UnsafeCoreLedgerServer interface {
	mustEmbedUnimplementedCoreLedgerServer()
}

func RegisterCoreLedgerServer(s grpc.ServiceRegistrar, srv CoreLedgerServer) {
	// If the following call pancis, it indicates UnimplementedCoreLedgerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreLedger_ServiceDesc, srv)
}

func _CoreLedger_PostLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostLedgerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreLedgerServer).PostLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreLedger_PostLedger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreLedgerServer).PostLedger(ctx, req.(*PostLedgerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreLedger_GetLedgerBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLedgerBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreLedgerServer).GetLedgerBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreLedger_GetLedgerBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreLedgerServer).GetLedgerBalance(ctx, req.(*GetLedgerBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreLedger_ServiceDesc is the grpc.ServiceDesc for CoreLedger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreLedger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lmm.core.v1.CoreLedger",
	HandlerType: (*CoreLedgerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostLedger",
			Handler:    _CoreLedger_PostLedger_Handler,
		},
		{
			MethodName: "GetLedgerBalance",
			Handler:    _CoreLedger_GetLedgerBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lmm/core/v1/ledger.proto",
}
