// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// protoc: proto3 compiler (version header normalized)
// source: lmm/core/v1/payments.proto

package corepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentReceiptState int32

const (
	PaymentReceiptState_PAYMENT_RECEIPT_STATE_UNSPECIFIED             PaymentReceiptState = 0
	PaymentReceiptState_PAYMENT_RECEIPT_STATE_CREDIT_APPLIED          PaymentReceiptState = 1
	PaymentReceiptState_PAYMENT_RECEIPT_STATE_REFUND_HELD             PaymentReceiptState = 2
	PaymentReceiptState_PAYMENT_RECEIPT_STATE_REFUND_COMMITTED        PaymentReceiptState = 3
	PaymentReceiptState_PAYMENT_RECEIPT_STATE_REFUND_RELEASED         PaymentReceiptState = 4
	PaymentReceiptState_PAYMENT_RECEIPT_STATE_EXTERNAL_REFUND_APPLIED PaymentReceiptState = 5
	PaymentReceiptState_PAYMENT_RECEIPT_STATE_REJECTED                PaymentReceiptState = 6
)

// Enum value maps for PaymentReceiptState.
var (
	PaymentReceiptState_name = map[int32]string{
		0: "PAYMENT_RECEIPT_STATE_UNSPECIFIED",
		1: "PAYMENT_RECEIPT_STATE_CREDIT_APPLIED",
		2: "PAYMENT_RECEIPT_STATE_REFUND_HELD",
		3: "PAYMENT_RECEIPT_STATE_REFUND_COMMITTED",
		4: "PAYMENT_RECEIPT_STATE_REFUND_RELEASED",
		5: "PAYMENT_RECEIPT_STATE_EXTERNAL_REFUND_APPLIED",
		6: "PAYMENT_RECEIPT_STATE_REJECTED",
	}
	PaymentReceiptState_value = map[string]int32{
		"PAYMENT_RECEIPT_STATE_UNSPECIFIED":             0,
		"PAYMENT_RECEIPT_STATE_CREDIT_APPLIED":          1,
		"PAYMENT_RECEIPT_STATE_REFUND_HELD":             2,
		"PAYMENT_RECEIPT_STATE_REFUND_COMMITTED":        3,
		"PAYMENT_RECEIPT_STATE_REFUND_RELEASED":         4,
		"PAYMENT_RECEIPT_STATE_EXTERNAL_REFUND_APPLIED": 5,
		"PAYMENT_RECEIPT_STATE_REJECTED":                6,
	}
)

func (x PaymentReceiptState) Enum() *PaymentReceiptState {
	p := new(PaymentReceiptState)
	*p = x
	return p
}

func (x PaymentReceiptState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentReceiptState) Descriptor() protoreflect.EnumDescriptor {
	return file_lmm_core_v1_payments_proto_enumTypes[0].Descriptor()
}

func (PaymentReceiptState) Type() protoreflect.EnumType {
	return &file_lmm_core_v1_payments_proto_enumTypes[0]
}

func (x PaymentReceiptState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentReceiptState.Descriptor instead.
func (PaymentReceiptState) EnumDescriptor() ([]byte, []int) {
	return file_lmm_core_v1_payments_proto_rawDescGZIP(), []int{0}
}

type ExternalPaymentReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Merchant      string                 `protobuf:"bytes,2,opt,name=merchant,proto3" json:"merchant,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Transaction   string                 `protobuf:"bytes,4,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalPaymentReference) Reset() {
	*x = ExternalPaymentReference{}
	mi := &file_lmm_core_v1_payments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalPaymentReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalPaymentReference) ProtoMessage() {}

func (x *ExternalPaymentReference) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_payments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalPaymentReference.ProtoReflect.Descriptor instead.
func (*ExternalPaymentReference) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_payments_proto_rawDescGZIP(), []int{0}
}

func (x *ExternalPaymentReference) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ExternalPaymentReference) GetMerchant() string {
	if x != nil {
		return x.Merchant
	}
	return ""
}

func (x *ExternalPaymentReference) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ExternalPaymentReference) GetTransaction() string {
	if x != nil {
		return x.Transaction
	}
	return ""
}

type ProviderEvidence struct {
	state   protoimpl.MessageState    `protogen:"open.v1"`
	Payment *ExternalPaymentReference `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	// Bounded original bytes and signature from a configured adapter. Core must
	// independently verify signature, merchant, amount, currency, event identity
	// and replay state. No endpoint URL, secret or caller-set 'verified' flag.
	SignedPayload   []byte `protobuf:"bytes,2,opt,name=signed_payload,json=signedPayload,proto3" json:"signed_payload,omitempty"`
	Signature       []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	ProviderEventId string `protobuf:"bytes,4,opt,name=provider_event_id,json=providerEventId,proto3" json:"provider_event_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProviderEvidence) Reset() {
	*x = ProviderEvidence{}
	mi := &file_lmm_core_v1_payments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderEvidence) ProtoMessage() {}

func (x *ProviderEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_payments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderEvidence.ProtoReflect.Descriptor instead.
func (*ProviderEvidence) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_payments_proto_rawDescGZIP(), []int{1}
}

func (x *ProviderEvidence) GetPayment() *ExternalPaymentReference {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *ProviderEvidence) GetSignedPayload() []byte {
	if x != nil {
		return x.SignedPayload
	}
	return nil
}

func (x *ProviderEvidence) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ProviderEvidence) GetProviderEventId() string {
	if x != nil {
		return x.ProviderEventId
	}
	return ""
}

type PrepareTopupRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Mutation         *MutationContext       `protobuf:"bytes,1,opt,name=mutation,proto3" json:"mutation,omitempty"`
	AccountId        int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`                        // core_identity.accounts.id; explicit personal/team account.
	PaymentChannelId int64                  `protobuf:"varint,3,opt,name=payment_channel_id,json=paymentChannelId,proto3" json:"payment_channel_id,omitempty"` // Core-owned allowlisted merchant configuration.
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`                                            // ISO code, e.g. USD. Core validates channel and currency.
	AmountMinor      int64                  `protobuf:"varint,5,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`                  // Requested positive external smallest units, not credit.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PrepareTopupRequest) Reset() {
	*x = PrepareTopupRequest{}
	mi := &file_lmm_core_v1_payments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareTopupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareTopupRequest) ProtoMessage() {}

func (x *PrepareTopupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_payments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareTopupRequest.ProtoReflect.Descriptor instead.
func (*PrepareTopupRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_payments_proto_rawDescGZIP(), []int{2}
}

func (x *PrepareTopupRequest) GetMutation() *MutationContext {
	if x != nil {
		return x.Mutation
	}
	return nil
}

func (x *PrepareTopupRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *PrepareTopupRequest) GetPaymentChannelId() int64 {
	if x != nil {
		return x.PaymentChannelId
	}
	return 0
}

func (x *PrepareTopupRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PrepareTopupRequest) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

type PaymentIntent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IntentId        int64                  `protobuf:"varint,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	AccountId       int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CreatedByUserId int64                  `protobuf:"varint,3,opt,name=created_by_user_id,json=createdByUserId,proto3" json:"created_by_user_id,omitempty"` // Output only, from authenticated identity.
	Provider        string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	Merchant        string                 `protobuf:"bytes,5,opt,name=merchant,proto3" json:"merchant,omitempty"`
	Environment     string                 `protobuf:"bytes,6,opt,name=environment,proto3" json:"environment,omitempty"`
	Currency        string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	AmountMinor     int64                  `protobuf:"varint,8,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	CreditUnits     int64                  `protobuf:"varint,9,opt,name=credit_units,json=creditUnits,proto3" json:"credit_units,omitempty"` // Core-frozen conversion/policy, never Go-calculated.
	CreditUnit      string                 `protobuf:"bytes,10,opt,name=credit_unit,json=creditUnit,proto3" json:"credit_unit,omitempty"`    // credit_500k_usd.
	IdempotencyKey  string                 `protobuf:"bytes,11,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	RequestSha256   []byte                 `protobuf:"bytes,12,opt,name=request_sha256,json=requestSha256,proto3" json:"request_sha256,omitempty"`
	ReceiptId       string                 `protobuf:"bytes,13,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaymentIntent) Reset() {
	*x = PaymentIntent{}
	mi := &file_lmm_core_v1_payments_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentIntent) ProtoMessage() {}

func (x *PaymentIntent) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_payments_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentIntent.ProtoReflect.Descriptor instead.
func (*PaymentIntent) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_payments_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentIntent) GetIntentId() int64 {
	if x != nil {
		return x.IntentId
	}
	return 0
}

func (x *PaymentIntent) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *PaymentIntent) GetCreatedByUserId() int64 {
	if x != nil {
		return x.CreatedByUserId
	}
	return 0
}

func (x *PaymentIntent) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PaymentIntent) GetMerchant() string {
	if x != nil {
		return x.Merchant
	}
	return ""
}

func (x *PaymentIntent) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *PaymentIntent) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentIntent) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *PaymentIntent) GetCreditUnits() int64 {
	if x != nil {
		return x.CreditUnits
	}
	return 0
}

func (x *PaymentIntent) GetCreditUnit() string {
	if x != nil {
		return x.CreditUnit
	}
	return ""
}

func (x *PaymentIntent) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *PaymentIntent) GetRequestSha256() []byte {
	if x != nil {
		return x.RequestSha256
	}
	return nil
}

func (x *PaymentIntent) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

type CreditTopupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mutation      *MutationContext       `protobuf:"bytes,1,opt,name=mutation,proto3" json:"mutation,omitempty"`
	IntentId      int64                  `protobuf:"varint,2,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	Evidence      *ProviderEvidence      `protobuf:"bytes,3,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditTopupRequest) Reset() {
	*x = CreditTopupRequest{}
	mi := &file_lmm_core_v1_payments_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditTopupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditTopupRequest) ProtoMessage() {}

func (x *CreditTopupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_payments_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditTopupRequest.ProtoReflect.Descriptor instead.
func (*CreditTopupRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_payments_proto_rawDescGZIP(), []int{4}
}

func (x *CreditTopupRequest) GetMutation() *MutationContext {
	if x != nil {
		return x.Mutation
	}
	return nil
}

func (x *CreditTopupRequest) GetIntentId() int64 {
	if x != nil {
		return x.IntentId
	}
	return 0
}

func (x *CreditTopupRequest) GetEvidence() *ProviderEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type HoldRefundRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Mutation          *MutationContext       `protobuf:"bytes,1,opt,name=mutation,proto3" json:"mutation,omitempty"`
	IntentId          int64                  `protobuf:"varint,2,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"` // Must locate original credit even if Go lost its response.
	RefundAmountMinor int64                  `protobuf:"varint,3,opt,name=refund_amount_minor,json=refundAmountMinor,proto3" json:"refund_amount_minor,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HoldRefundRequest) Reset() {
	*x = HoldRefundRequest{}
	mi := &file_lmm_core_v1_payments_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldRefundRequest) ProtoMessage() {}

func (x *HoldRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_payments_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldRefundRequest.ProtoReflect.Descriptor instead.
func (*HoldRefundRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_payments_proto_rawDescGZIP(), []int{5}
}

func (x *HoldRefundRequest) GetMutation() *MutationContext {
	if x != nil {
		return x.Mutation
	}
	return nil
}

func (x *HoldRefundRequest) GetIntentId() int64 {
	if x != nil {
		return x.IntentId
	}
	return 0
}

func (x *HoldRefundRequest) GetRefundAmountMinor() int64 {
	if x != nil {
		return x.RefundAmountMinor
	}
	return 0
}

type ResolveRefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mutation      *MutationContext       `protobuf:"bytes,1,opt,name=mutation,proto3" json:"mutation,omitempty"`
	IntentId      int64                  `protobuf:"varint,2,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	HoldReceiptId string                 `protobuf:"bytes,3,opt,name=hold_receipt_id,json=holdReceiptId,proto3" json:"hold_receipt_id,omitempty"`
	// Commit requires verified provider success; release requires verified terminal
	// failure. Missing/unknown evidence MUST NOT release a hold on timeout.
	Evidence      *ProviderEvidence `protobuf:"bytes,4,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRefundRequest) Reset() {
	*x = ResolveRefundRequest{}
	mi := &file_lmm_core_v1_payments_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRefundRequest) ProtoMessage() {}

func (x *ResolveRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_payments_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRefundRequest.ProtoReflect.Descriptor instead.
func (*ResolveRefundRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_payments_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveRefundRequest) GetMutation() *MutationContext {
	if x != nil {
		return x.Mutation
	}
	return nil
}

func (x *ResolveRefundRequest) GetIntentId() int64 {
	if x != nil {
		return x.IntentId
	}
	return 0
}

func (x *ResolveRefundRequest) GetHoldReceiptId() string {
	if x != nil {
		return x.HoldReceiptId
	}
	return ""
}

func (x *ResolveRefundRequest) GetEvidence() *ProviderEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type ExternalRefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mutation      *MutationContext       `protobuf:"bytes,1,opt,name=mutation,proto3" json:"mutation,omitempty"`
	IntentId      int64                  `protobuf:"varint,2,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	Evidence      *ProviderEvidence      `protobuf:"bytes,3,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalRefundRequest) Reset() {
	*x = ExternalRefundRequest{}
	mi := &file_lmm_core_v1_payments_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalRefundRequest) ProtoMessage() {}

func (x *ExternalRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_payments_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalRefundRequest.ProtoReflect.Descriptor instead.
func (*ExternalRefundRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_payments_proto_rawDescGZIP(), []int{7}
}

func (x *ExternalRefundRequest) GetMutation() *MutationContext {
	if x != nil {
		return x.Mutation
	}
	return nil
}

func (x *ExternalRefundRequest) GetIntentId() int64 {
	if x != nil {
		return x.IntentId
	}
	return 0
}

func (x *ExternalRefundRequest) GetEvidence() *ProviderEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type GetPaymentReceiptRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IntentId       int64                  `protobuf:"varint,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // Resolved inside authenticated scope, not global.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPaymentReceiptRequest) Reset() {
	*x = GetPaymentReceiptRequest{}
	mi := &file_lmm_core_v1_payments_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentReceiptRequest) ProtoMessage() {}

func (x *GetPaymentReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_payments_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentReceiptRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentReceiptRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_payments_proto_rawDescGZIP(), []int{8}
}

func (x *GetPaymentReceiptRequest) GetIntentId() int64 {
	if x != nil {
		return x.IntentId
	}
	return 0
}

func (x *GetPaymentReceiptRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type PaymentReceipt struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReceiptId      string                 `protobuf:"bytes,1,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`
	IntentId       int64                  `protobuf:"varint,2,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	RequestSha256  []byte                 `protobuf:"bytes,4,opt,name=request_sha256,json=requestSha256,proto3" json:"request_sha256,omitempty"`
	State          PaymentReceiptState    `protobuf:"varint,5,opt,name=state,proto3,enum=lmm.core.v1.PaymentReceiptState" json:"state,omitempty"`
	JournalId      int64                  `protobuf:"varint,6,opt,name=journal_id,json=journalId,proto3" json:"journal_id,omitempty"` // When posted; cannot infer a credit from this field alone.
	RejectionCode  string                 `protobuf:"bytes,7,opt,name=rejection_code,json=rejectionCode,proto3" json:"rejection_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PaymentReceipt) Reset() {
	*x = PaymentReceipt{}
	mi := &file_lmm_core_v1_payments_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentReceipt) ProtoMessage() {}

func (x *PaymentReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_payments_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentReceipt.ProtoReflect.Descriptor instead.
func (*PaymentReceipt) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_payments_proto_rawDescGZIP(), []int{9}
}

func (x *PaymentReceipt) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

func (x *PaymentReceipt) GetIntentId() int64 {
	if x != nil {
		return x.IntentId
	}
	return 0
}

func (x *PaymentReceipt) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *PaymentReceipt) GetRequestSha256() []byte {
	if x != nil {
		return x.RequestSha256
	}
	return nil
}

func (x *PaymentReceipt) GetState() PaymentReceiptState {
	if x != nil {
		return x.State
	}
	return PaymentReceiptState_PAYMENT_RECEIPT_STATE_UNSPECIFIED
}

func (x *PaymentReceipt) GetJournalId() int64 {
	if x != nil {
		return x.JournalId
	}
	return 0
}

func (x *PaymentReceipt) GetRejectionCode() string {
	if x != nil {
		return x.RejectionCode
	}
	return ""
}

type PaymentStateChangedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipt       *PaymentReceipt        `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentStateChangedEvent) Reset() {
	*x = PaymentStateChangedEvent{}
	mi := &file_lmm_core_v1_payments_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentStateChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentStateChangedEvent) ProtoMessage() {}

func (x *PaymentStateChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_payments_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentStateChangedEvent.ProtoReflect.Descriptor instead.
func (*PaymentStateChangedEvent) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_payments_proto_rawDescGZIP(), []int{10}
}

func (x *PaymentStateChangedEvent) GetReceipt() *PaymentReceipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

func (x *PaymentStateChangedEvent) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

var File_lmm_core_v1_payments_proto protoreflect.FileDescriptor

const file_lmm_core_v1_payments_proto_rawDesc = "" +
	"\n" +
	"\x1almm/core/v1/payments.proto\x12\vlmm.core.v1\x1a\x1almm/core/v1/commands.proto\"\x96\x01\n" +
	"\x18ExternalPaymentReference\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1a\n" +
	"\bmerchant\x18\x02 \x01(\tR\bmerchant\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12 \n" +
	"\vtransaction\x18\x04 \x01(\tR\vtransaction\"\xc4\x01\n" +
	"\x10ProviderEvidence\x12?\n" +
	"\apayment\x18\x01 \x01(\v2%.lmm.core.v1.ExternalPaymentReferenceR\apayment\x12%\n" +
	"\x0esigned_payload\x18\x02 \x01(\fR\rsignedPayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12*\n" +
	"\x11provider_event_id\x18\x04 \x01(\tR\x0fproviderEventId\"\xdb\x01\n" +
	"\x13PrepareTopupRequest\x128\n" +
	"\bmutation\x18\x01 \x01(\v2\x1c.lmm.core.v1.MutationContextR\bmutation\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x12,\n" +
	"\x12payment_channel_id\x18\x03 \x01(\x03R\x10paymentChannelId\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12!\n" +
	"\famount_minor\x18\x05 \x01(\x03R\vamountMinor\"\xc4\x03\n" +
	"\rPaymentIntent\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\x03R\bintentId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x12+\n" +
	"\x12created_by_user_id\x18\x03 \x01(\x03R\x0fcreatedByUserId\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12\x1a\n" +
	"\bmerchant\x18\x05 \x01(\tR\bmerchant\x12 \n" +
	"\venvironment\x18\x06 \x01(\tR\venvironment\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12!\n" +
	"\famount_minor\x18\b \x01(\x03R\vamountMinor\x12!\n" +
	"\fcredit_units\x18\t \x01(\x03R\vcreditUnits\x12\x1f\n" +
	"\vcredit_unit\x18\n" +
	" \x01(\tR\n" +
	"creditUnit\x12'\n" +
	"\x0fidempotency_key\x18\v \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x0erequest_sha256\x18\f \x01(\fR\rrequestSha256\x12\x1d\n" +
	"\n" +
	"receipt_id\x18\r \x01(\tR\treceiptId\"\xa6\x01\n" +
	"\x12CreditTopupRequest\x128\n" +
	"\bmutation\x18\x01 \x01(\v2\x1c.lmm.core.v1.MutationContextR\bmutation\x12\x1b\n" +
	"\tintent_id\x18\x02 \x01(\x03R\bintentId\x129\n" +
	"\bevidence\x18\x03 \x01(\v2\x1d.lmm.core.v1.ProviderEvidenceR\bevidence\"\x9a\x01\n" +
	"\x11HoldRefundRequest\x128\n" +
	"\bmutation\x18\x01 \x01(\v2\x1c.lmm.core.v1.MutationContextR\bmutation\x12\x1b\n" +
	"\tintent_id\x18\x02 \x01(\x03R\bintentId\x12.\n" +
	"\x13refund_amount_minor\x18\x03 \x01(\x03R\x11refundAmountMinor\"\xd0\x01\n" +
	"\x14ResolveRefundRequest\x128\n" +
	"\bmutation\x18\x01 \x01(\v2\x1c.lmm.core.v1.MutationContextR\bmutation\x12\x1b\n" +
	"\tintent_id\x18\x02 \x01(\x03R\bintentId\x12&\n" +
	"\x0fhold_receipt_id\x18\x03 \x01(\tR\rholdReceiptId\x129\n" +
	"\bevidence\x18\x04 \x01(\v2\x1d.lmm.core.v1.ProviderEvidenceR\bevidence\"\xa9\x01\n" +
	"\x15ExternalRefundRequest\x128\n" +
	"\bmutation\x18\x01 \x01(\v2\x1c.lmm.core.v1.MutationContextR\bmutation\x12\x1b\n" +
	"\tintent_id\x18\x02 \x01(\x03R\bintentId\x129\n" +
	"\bevidence\x18\x03 \x01(\v2\x1d.lmm.core.v1.ProviderEvidenceR\bevidence\"`\n" +
	"\x18GetPaymentReceiptRequest\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\x03R\bintentId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\"\x9a\x02\n" +
	"\x0ePaymentReceipt\x12\x1d\n" +
	"\n" +
	"receipt_id\x18\x01 \x01(\tR\treceiptId\x12\x1b\n" +
	"\tintent_id\x18\x02 \x01(\x03R\bintentId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x0erequest_sha256\x18\x04 \x01(\fR\rrequestSha256\x126\n" +
	"\x05state\x18\x05 \x01(\x0e2 .lmm.core.v1.PaymentReceiptStateR\x05state\x12\x1d\n" +
	"\n" +
	"journal_id\x18\x06 \x01(\x03R\tjournalId\x12%\n" +
	"\x0erejection_code\x18\a \x01(\tR\rrejectionCode\"p\n" +
	"\x18PaymentStateChangedEvent\x125\n" +
	"\areceipt\x18\x01 \x01(\v2\x1b.lmm.core.v1.PaymentReceiptR\areceipt\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId*\xbb\x02\n" +
	"\x13PaymentReceiptState\x12%\n" +
	"!PAYMENT_RECEIPT_STATE_UNSPECIFIED\x10\x00\x12(\n" +
	"$PAYMENT_RECEIPT_STATE_CREDIT_APPLIED\x10\x01\x12%\n" +
	"!PAYMENT_RECEIPT_STATE_REFUND_HELD\x10\x02\x12*\n" +
	"&PAYMENT_RECEIPT_STATE_REFUND_COMMITTED\x10\x03\x12)\n" +
	"%PAYMENT_RECEIPT_STATE_REFUND_RELEASED\x10\x04\x121\n" +
	"-PAYMENT_RECEIPT_STATE_EXTERNAL_REFUND_APPLIED\x10\x05\x12\"\n" +
	"\x1ePAYMENT_RECEIPT_STATE_REJECTED\x10\x062\xc6\x04\n" +
	"\fCorePayments\x12L\n" +
	"\fPrepareTopup\x12 .lmm.core.v1.PrepareTopupRequest\x1a\x1a.lmm.core.v1.PaymentIntent\x12K\n" +
	"\vCreditTopup\x12\x1f.lmm.core.v1.CreditTopupRequest\x1a\x1b.lmm.core.v1.PaymentReceipt\x12I\n" +
	"\n" +
	"HoldRefund\x12\x1e.lmm.core.v1.HoldRefundRequest\x1a\x1b.lmm.core.v1.PaymentReceipt\x12N\n" +
	"\fCommitRefund\x12!.lmm.core.v1.ResolveRefundRequest\x1a\x1b.lmm.core.v1.PaymentReceipt\x12O\n" +
	"\rReleaseRefund\x12!.lmm.core.v1.ResolveRefundRequest\x1a\x1b.lmm.core.v1.PaymentReceipt\x12V\n" +
	"\x13ApplyExternalRefund\x12\".lmm.core.v1.ExternalRefundRequest\x1a\x1b.lmm.core.v1.PaymentReceipt\x12W\n" +
	"\x11GetPaymentReceipt\x12%.lmm.core.v1.GetPaymentReceiptRequest\x1a\x1b.lmm.core.v1.PaymentReceiptBLZJgithub.com/TokenNotIncluded/api.lmm.best/extensions/internal/corepb;corepbb\x06proto3"

var (
	file_lmm_core_v1_payments_proto_rawDescOnce sync.Once
	file_lmm_core_v1_payments_proto_rawDescData []byte
)

func file_lmm_core_v1_payments_proto_rawDescGZIP() []byte {
	file_lmm_core_v1_payments_proto_rawDescOnce.Do(func() {
		file_lmm_core_v1_payments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lmm_core_v1_payments_proto_rawDesc), len(file_lmm_core_v1_payments_proto_rawDesc)))
	})
	return file_lmm_core_v1_payments_proto_rawDescData
}

var file_lmm_core_v1_payments_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lmm_core_v1_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_lmm_core_v1_payments_proto_goTypes = []any{
	(PaymentReceiptState)(0),         // 0: lmm.core.v1.PaymentReceiptState
	(*ExternalPaymentReference)(nil), // 1: lmm.core.v1.ExternalPaymentReference
	(*ProviderEvidence)(nil),         // 2: lmm.core.v1.ProviderEvidence
	(*PrepareTopupRequest)(nil),      // 3: lmm.core.v1.PrepareTopupRequest
	(*PaymentIntent)(nil),            // 4: lmm.core.v1.PaymentIntent
	(*CreditTopupRequest)(nil),       // 5: lmm.core.v1.CreditTopupRequest
	(*HoldRefundRequest)(nil),        // 6: lmm.core.v1.HoldRefundRequest
	(*ResolveRefundRequest)(nil),     // 7: lmm.core.v1.ResolveRefundRequest
	(*ExternalRefundRequest)(nil),    // 8: lmm.core.v1.ExternalRefundRequest
	(*GetPaymentReceiptRequest)(nil), // 9: lmm.core.v1.GetPaymentReceiptRequest
	(*PaymentReceipt)(nil),           // 10: lmm.core.v1.PaymentReceipt
	(*PaymentStateChangedEvent)(nil), // 11: lmm.core.v1.PaymentStateChangedEvent
	(*MutationContext)(nil),          // 12: lmm.core.v1.MutationContext
}
var file_lmm_core_v1_payments_proto_depIdxs = []int32{
	1,  // 0: lmm.core.v1.ProviderEvidence.payment:type_name -> lmm.core.v1.ExternalPaymentReference
	12, // 1: lmm.core.v1.PrepareTopupRequest.mutation:type_name -> lmm.core.v1.MutationContext
	12, // 2: lmm.core.v1.CreditTopupRequest.mutation:type_name -> lmm.core.v1.MutationContext
	2,  // 3: lmm.core.v1.CreditTopupRequest.evidence:type_name -> lmm.core.v1.ProviderEvidence
	12, // 4: lmm.core.v1.HoldRefundRequest.mutation:type_name -> lmm.core.v1.MutationContext
	12, // 5: lmm.core.v1.ResolveRefundRequest.mutation:type_name -> lmm.core.v1.MutationContext
	2,  // 6: lmm.core.v1.ResolveRefundRequest.evidence:type_name -> lmm.core.v1.ProviderEvidence
	12, // 7: lmm.core.v1.ExternalRefundRequest.mutation:type_name -> lmm.core.v1.MutationContext
	2,  // 8: lmm.core.v1.ExternalRefundRequest.evidence:type_name -> lmm.core.v1.ProviderEvidence
	0,  // 9: lmm.core.v1.PaymentReceipt.state:type_name -> lmm.core.v1.PaymentReceiptState
	10, // 10: lmm.core.v1.PaymentStateChangedEvent.receipt:type_name -> lmm.core.v1.PaymentReceipt
	3,  // 11: lmm.core.v1.CorePayments.PrepareTopup:input_type -> lmm.core.v1.PrepareTopupRequest
	5,  // 12: lmm.core.v1.CorePayments.CreditTopup:input_type -> lmm.core.v1.CreditTopupRequest
	6,  // 13: lmm.core.v1.CorePayments.HoldRefund:input_type -> lmm.core.v1.HoldRefundRequest
	7,  // 14: lmm.core.v1.CorePayments.CommitRefund:input_type -> lmm.core.v1.ResolveRefundRequest
	7,  // 15: lmm.core.v1.CorePayments.ReleaseRefund:input_type -> lmm.core.v1.ResolveRefundRequest
	8,  // 16: lmm.core.v1.CorePayments.ApplyExternalRefund:input_type -> lmm.core.v1.ExternalRefundRequest
	9,  // 17: lmm.core.v1.CorePayments.GetPaymentReceipt:input_type -> lmm.core.v1.GetPaymentReceiptRequest
	4,  // 18: lmm.core.v1.CorePayments.PrepareTopup:output_type -> lmm.core.v1.PaymentIntent
	10, // 19: lmm.core.v1.CorePayments.CreditTopup:output_type -> lmm.core.v1.PaymentReceipt
	10, // 20: lmm.core.v1.CorePayments.HoldRefund:output_type -> lmm.core.v1.PaymentReceipt
	10, // 21: lmm.core.v1.CorePayments.CommitRefund:output_type -> lmm.core.v1.PaymentReceipt
	10, // 22: lmm.core.v1.CorePayments.ReleaseRefund:output_type -> lmm.core.v1.PaymentReceipt
	10, // 23: lmm.core.v1.CorePayments.ApplyExternalRefund:output_type -> lmm.core.v1.PaymentReceipt
	10, // 24: lmm.core.v1.CorePayments.GetPaymentReceipt:output_type -> lmm.core.v1.PaymentReceipt
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_lmm_core_v1_payments_proto_init() }
func file_lmm_core_v1_payments_proto_init() {
	if File_lmm_core_v1_payments_proto != nil {
		return
	}
	file_lmm_core_v1_commands_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lmm_core_v1_payments_proto_rawDesc), len(file_lmm_core_v1_payments_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lmm_core_v1_payments_proto_goTypes,
		DependencyIndexes: file_lmm_core_v1_payments_proto_depIdxs,
		EnumInfos:         file_lmm_core_v1_payments_proto_enumTypes,
		MessageInfos:      file_lmm_core_v1_payments_proto_msgTypes,
	}.Build()
	File_lmm_core_v1_payments_proto = out.File
	file_lmm_core_v1_payments_proto_goTypes = nil
	file_lmm_core_v1_payments_proto_depIdxs = nil
}
