# Regional availability policy for api.lmm.best.
# DB-IP Lite Country database, licensed CC BY 4.0: https://db-ip.com/db/lite.php
# Only an explicit CN result is gated. Unknown or unavailable lookups pass.
geoip2 /var/lib/geoip2/DBIP-Country-Lite.mmdb {
    auto_reload 5m;
    $lmm_geoip_country_code country iso_code;
}

map $lmm_geoip_country_code $lmm_cn_source {
    default 0;
    CN      1;
}
