// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// protoc: proto3 compiler (version header normalized)
// source: lmm/core/v1/control.proto

package corepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountKind int32

const (
	AccountKind_ACCOUNT_KIND_UNSPECIFIED AccountKind = 0
	AccountKind_ACCOUNT_KIND_PERSONAL    AccountKind = 1
	AccountKind_ACCOUNT_KIND_TEAM        AccountKind = 2
)

// Enum value maps for AccountKind.
var (
	AccountKind_name = map[int32]string{
		0: "ACCOUNT_KIND_UNSPECIFIED",
		1: "ACCOUNT_KIND_PERSONAL",
		2: "ACCOUNT_KIND_TEAM",
	}
	AccountKind_value = map[string]int32{
		"ACCOUNT_KIND_UNSPECIFIED": 0,
		"ACCOUNT_KIND_PERSONAL":    1,
		"ACCOUNT_KIND_TEAM":        2,
	}
)

func (x AccountKind) Enum() *AccountKind {
	p := new(AccountKind)
	*p = x
	return p
}

func (x AccountKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountKind) Descriptor() protoreflect.EnumDescriptor {
	return file_lmm_core_v1_control_proto_enumTypes[0].Descriptor()
}

func (AccountKind) Type() protoreflect.EnumType {
	return &file_lmm_core_v1_control_proto_enumTypes[0]
}

func (x AccountKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountKind.Descriptor instead.
func (AccountKind) EnumDescriptor() ([]byte, []int) {
	return file_lmm_core_v1_control_proto_rawDescGZIP(), []int{0}
}

type CredentialKind int32

const (
	CredentialKind_CREDENTIAL_KIND_UNSPECIFIED CredentialKind = 0
	CredentialKind_CREDENTIAL_KIND_SESSION     CredentialKind = 1
	CredentialKind_CREDENTIAL_KIND_API_KEY     CredentialKind = 2
)

// Enum value maps for CredentialKind.
var (
	CredentialKind_name = map[int32]string{
		0: "CREDENTIAL_KIND_UNSPECIFIED",
		1: "CREDENTIAL_KIND_SESSION",
		2: "CREDENTIAL_KIND_API_KEY",
	}
	CredentialKind_value = map[string]int32{
		"CREDENTIAL_KIND_UNSPECIFIED": 0,
		"CREDENTIAL_KIND_SESSION":     1,
		"CREDENTIAL_KIND_API_KEY":     2,
	}
)

func (x CredentialKind) Enum() *CredentialKind {
	p := new(CredentialKind)
	*p = x
	return p
}

func (x CredentialKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialKind) Descriptor() protoreflect.EnumDescriptor {
	return file_lmm_core_v1_control_proto_enumTypes[1].Descriptor()
}

func (CredentialKind) Type() protoreflect.EnumType {
	return &file_lmm_core_v1_control_proto_enumTypes[1]
}

func (x CredentialKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialKind.Descriptor instead.
func (CredentialKind) EnumDescriptor() ([]byte, []int) {
	return file_lmm_core_v1_control_proto_rawDescGZIP(), []int{1}
}

type TeamRole int32

const (
	TeamRole_TEAM_ROLE_UNSPECIFIED TeamRole = 0
	TeamRole_TEAM_ROLE_OWNER       TeamRole = 1
	TeamRole_TEAM_ROLE_ADMIN       TeamRole = 2
	TeamRole_TEAM_ROLE_MEMBER      TeamRole = 3
)

// Enum value maps for TeamRole.
var (
	TeamRole_name = map[int32]string{
		0: "TEAM_ROLE_UNSPECIFIED",
		1: "TEAM_ROLE_OWNER",
		2: "TEAM_ROLE_ADMIN",
		3: "TEAM_ROLE_MEMBER",
	}
	TeamRole_value = map[string]int32{
		"TEAM_ROLE_UNSPECIFIED": 0,
		"TEAM_ROLE_OWNER":       1,
		"TEAM_ROLE_ADMIN":       2,
		"TEAM_ROLE_MEMBER":      3,
	}
)

func (x TeamRole) Enum() *TeamRole {
	p := new(TeamRole)
	*p = x
	return p
}

func (x TeamRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TeamRole) Descriptor() protoreflect.EnumDescriptor {
	return file_lmm_core_v1_control_proto_enumTypes[2].Descriptor()
}

func (TeamRole) Type() protoreflect.EnumType {
	return &file_lmm_core_v1_control_proto_enumTypes[2]
}

func (x TeamRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TeamRole.Descriptor instead.
func (TeamRole) EnumDescriptor() ([]byte, []int) {
	return file_lmm_core_v1_control_proto_rawDescGZIP(), []int{2}
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_lmm_core_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_control_proto_rawDescGZIP(), []int{0}
}

type CapabilitiesResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProtocolMajor     uint32                 `protobuf:"varint,1,opt,name=protocol_major,json=protocolMajor,proto3" json:"protocol_major,omitempty"`
	IdentityAvailable bool                   `protobuf:"varint,2,opt,name=identity_available,json=identityAvailable,proto3" json:"identity_available,omitempty"`
	Features          []string               `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_lmm_core_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilitiesResponse) GetProtocolMajor() uint32 {
	if x != nil {
		return x.ProtocolMajor
	}
	return 0
}

func (x *CapabilitiesResponse) GetIdentityAvailable() bool {
	if x != nil {
		return x.IdentityAvailable
	}
	return false
}

func (x *CapabilitiesResponse) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

type AuthorizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_lmm_core_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_control_proto_rawDescGZIP(), []int{2}
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          AccountKind            `protobuf:"varint,1,opt,name=kind,proto3,enum=lmm.core.v1.AccountKind" json:"kind,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_lmm_core_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *Account) GetKind() AccountKind {
	if x != nil {
		return x.Kind
	}
	return AccountKind_ACCOUNT_KIND_UNSPECIFIED
}

func (x *Account) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AuthorizeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CredentialId   int64                  `protobuf:"varint,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	CredentialKind CredentialKind         `protobuf:"varint,2,opt,name=credential_kind,json=credentialKind,proto3,enum=lmm.core.v1.CredentialKind" json:"credential_kind,omitempty"`
	UserId         int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlatformLevel  int32                  `protobuf:"varint,4,opt,name=platform_level,json=platformLevel,proto3" json:"platform_level,omitempty"`
	Owner          *Account               `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	// Ordered candidates only. Billing must recheck authority and reserve funds.
	FundingAccounts []*Account `protobuf:"bytes,6,rep,name=funding_accounts,json=fundingAccounts,proto3" json:"funding_accounts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_lmm_core_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *AuthorizeResponse) GetCredentialId() int64 {
	if x != nil {
		return x.CredentialId
	}
	return 0
}

func (x *AuthorizeResponse) GetCredentialKind() CredentialKind {
	if x != nil {
		return x.CredentialKind
	}
	return CredentialKind_CREDENTIAL_KIND_UNSPECIFIED
}

func (x *AuthorizeResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuthorizeResponse) GetPlatformLevel() int32 {
	if x != nil {
		return x.PlatformLevel
	}
	return 0
}

func (x *AuthorizeResponse) GetOwner() *Account {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *AuthorizeResponse) GetFundingAccounts() []*Account {
	if x != nil {
		return x.FundingAccounts
	}
	return nil
}

type ListTeamsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exclusive cursor, nonnegative. Results are ordered by team ID, at most 100.
	AfterId       int64 `protobuf:"varint,1,opt,name=after_id,json=afterId,proto3" json:"after_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamsRequest) Reset() {
	*x = ListTeamsRequest{}
	mi := &file_lmm_core_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsRequest) ProtoMessage() {}

func (x *ListTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsRequest.ProtoReflect.Descriptor instead.
func (*ListTeamsRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *ListTeamsRequest) GetAfterId() int64 {
	if x != nil {
		return x.AfterId
	}
	return 0
}

type Team struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Role              TeamRole               `protobuf:"varint,2,opt,name=role,proto3,enum=lmm.core.v1.TeamRole" json:"role,omitempty"`
	MembershipVersion int64                  `protobuf:"varint,3,opt,name=membership_version,json=membershipVersion,proto3" json:"membership_version,omitempty"`
	CanSpend          bool                   `protobuf:"varint,4,opt,name=can_spend,json=canSpend,proto3" json:"can_spend,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_lmm_core_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *Team) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Team) GetRole() TeamRole {
	if x != nil {
		return x.Role
	}
	return TeamRole_TEAM_ROLE_UNSPECIFIED
}

func (x *Team) GetMembershipVersion() int64 {
	if x != nil {
		return x.MembershipVersion
	}
	return 0
}

func (x *Team) GetCanSpend() bool {
	if x != nil {
		return x.CanSpend
	}
	return false
}

type ListTeamsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Teams []*Team                `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	// Zero means the end; an empty final page is allowed after a full page.
	NextAfterId   int64 `protobuf:"varint,2,opt,name=next_after_id,json=nextAfterId,proto3" json:"next_after_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamsResponse) Reset() {
	*x = ListTeamsResponse{}
	mi := &file_lmm_core_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsResponse) ProtoMessage() {}

func (x *ListTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsResponse.ProtoReflect.Descriptor instead.
func (*ListTeamsResponse) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *ListTeamsResponse) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *ListTeamsResponse) GetNextAfterId() int64 {
	if x != nil {
		return x.NextAfterId
	}
	return 0
}

var File_lmm_core_v1_control_proto protoreflect.FileDescriptor

const file_lmm_core_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x19lmm/core/v1/control.proto\x12\vlmm.core.v1\"\x15\n" +
	"\x13CapabilitiesRequest\"\x88\x01\n" +
	"\x14CapabilitiesResponse\x12%\n" +
	"\x0eprotocol_major\x18\x01 \x01(\rR\rprotocolMajor\x12-\n" +
	"\x12identity_available\x18\x02 \x01(\bR\x11identityAvailable\x12\x1a\n" +
	"\bfeatures\x18\x03 \x03(\tR\bfeatures\"\x12\n" +
	"\x10AuthorizeRequest\"G\n" +
	"\aAccount\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.lmm.core.v1.AccountKindR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"\xab\x02\n" +
	"\x11AuthorizeResponse\x12#\n" +
	"\rcredential_id\x18\x01 \x01(\x03R\fcredentialId\x12D\n" +
	"\x0fcredential_kind\x18\x02 \x01(\x0e2\x1b.lmm.core.v1.CredentialKindR\x0ecredentialKind\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12%\n" +
	"\x0eplatform_level\x18\x04 \x01(\x05R\rplatformLevel\x12*\n" +
	"\x05owner\x18\x05 \x01(\v2\x14.lmm.core.v1.AccountR\x05owner\x12?\n" +
	"\x10funding_accounts\x18\x06 \x03(\v2\x14.lmm.core.v1.AccountR\x0ffundingAccounts\"-\n" +
	"\x10ListTeamsRequest\x12\x19\n" +
	"\bafter_id\x18\x01 \x01(\x03R\aafterId\"\x8d\x01\n" +
	"\x04Team\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12)\n" +
	"\x04role\x18\x02 \x01(\x0e2\x15.lmm.core.v1.TeamRoleR\x04role\x12-\n" +
	"\x12membership_version\x18\x03 \x01(\x03R\x11membershipVersion\x12\x1b\n" +
	"\tcan_spend\x18\x04 \x01(\bR\bcanSpend\"`\n" +
	"\x11ListTeamsResponse\x12'\n" +
	"\x05teams\x18\x01 \x03(\v2\x11.lmm.core.v1.TeamR\x05teams\x12\"\n" +
	"\rnext_after_id\x18\x02 \x01(\x03R\vnextAfterId*]\n" +
	"\vAccountKind\x12\x1c\n" +
	"\x18ACCOUNT_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ACCOUNT_KIND_PERSONAL\x10\x01\x12\x15\n" +
	"\x11ACCOUNT_KIND_TEAM\x10\x02*k\n" +
	"\x0eCredentialKind\x12\x1f\n" +
	"\x1bCREDENTIAL_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CREDENTIAL_KIND_SESSION\x10\x01\x12\x1b\n" +
	"\x17CREDENTIAL_KIND_API_KEY\x10\x02*e\n" +
	"\bTeamRole\x12\x19\n" +
	"\x15TEAM_ROLE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fTEAM_ROLE_OWNER\x10\x01\x12\x13\n" +
	"\x0fTEAM_ROLE_ADMIN\x10\x02\x12\x14\n" +
	"\x10TEAM_ROLE_MEMBER\x10\x032\xfa\x01\n" +
	"\vCoreControl\x12S\n" +
	"\fCapabilities\x12 .lmm.core.v1.CapabilitiesRequest\x1a!.lmm.core.v1.CapabilitiesResponse\x12J\n" +
	"\tAuthorize\x12\x1d.lmm.core.v1.AuthorizeRequest\x1a\x1e.lmm.core.v1.AuthorizeResponse\x12J\n" +
	"\tListTeams\x12\x1d.lmm.core.v1.ListTeamsRequest\x1a\x1e.lmm.core.v1.ListTeamsResponseBLZJgithub.com/TokenNotIncluded/api.lmm.best/extensions/internal/corepb;corepbb\x06proto3"

var (
	file_lmm_core_v1_control_proto_rawDescOnce sync.Once
	file_lmm_core_v1_control_proto_rawDescData []byte
)

func file_lmm_core_v1_control_proto_rawDescGZIP() []byte {
	file_lmm_core_v1_control_proto_rawDescOnce.Do(func() {
		file_lmm_core_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lmm_core_v1_control_proto_rawDesc), len(file_lmm_core_v1_control_proto_rawDesc)))
	})
	return file_lmm_core_v1_control_proto_rawDescData
}

var file_lmm_core_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_lmm_core_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_lmm_core_v1_control_proto_goTypes = []any{
	(AccountKind)(0),             // 0: lmm.core.v1.AccountKind
	(CredentialKind)(0),          // 1: lmm.core.v1.CredentialKind
	(TeamRole)(0),                // 2: lmm.core.v1.TeamRole
	(*CapabilitiesRequest)(nil),  // 3: lmm.core.v1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil), // 4: lmm.core.v1.CapabilitiesResponse
	(*AuthorizeRequest)(nil),     // 5: lmm.core.v1.AuthorizeRequest
	(*Account)(nil),              // 6: lmm.core.v1.Account
	(*AuthorizeResponse)(nil),    // 7: lmm.core.v1.AuthorizeResponse
	(*ListTeamsRequest)(nil),     // 8: lmm.core.v1.ListTeamsRequest
	(*Team)(nil),                 // 9: lmm.core.v1.Team
	(*ListTeamsResponse)(nil),    // 10: lmm.core.v1.ListTeamsResponse
}
var file_lmm_core_v1_control_proto_depIdxs = []int32{
	0,  // 0: lmm.core.v1.Account.kind:type_name -> lmm.core.v1.AccountKind
	1,  // 1: lmm.core.v1.AuthorizeResponse.credential_kind:type_name -> lmm.core.v1.CredentialKind
	6,  // 2: lmm.core.v1.AuthorizeResponse.owner:type_name -> lmm.core.v1.Account
	6,  // 3: lmm.core.v1.AuthorizeResponse.funding_accounts:type_name -> lmm.core.v1.Account
	2,  // 4: lmm.core.v1.Team.role:type_name -> lmm.core.v1.TeamRole
	9,  // 5: lmm.core.v1.ListTeamsResponse.teams:type_name -> lmm.core.v1.Team
	3,  // 6: lmm.core.v1.CoreControl.Capabilities:input_type -> lmm.core.v1.CapabilitiesRequest
	5,  // 7: lmm.core.v1.CoreControl.Authorize:input_type -> lmm.core.v1.AuthorizeRequest
	8,  // 8: lmm.core.v1.CoreControl.ListTeams:input_type -> lmm.core.v1.ListTeamsRequest
	4,  // 9: lmm.core.v1.CoreControl.Capabilities:output_type -> lmm.core.v1.CapabilitiesResponse
	7,  // 10: lmm.core.v1.CoreControl.Authorize:output_type -> lmm.core.v1.AuthorizeResponse
	10, // 11: lmm.core.v1.CoreControl.ListTeams:output_type -> lmm.core.v1.ListTeamsResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_lmm_core_v1_control_proto_init() }
func file_lmm_core_v1_control_proto_init() {
	if File_lmm_core_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lmm_core_v1_control_proto_rawDesc), len(file_lmm_core_v1_control_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lmm_core_v1_control_proto_goTypes,
		DependencyIndexes: file_lmm_core_v1_control_proto_depIdxs,
		EnumInfos:         file_lmm_core_v1_control_proto_enumTypes,
		MessageInfos:      file_lmm_core_v1_control_proto_msgTypes,
	}.Build()
	File_lmm_core_v1_control_proto = out.File
	file_lmm_core_v1_control_proto_goTypes = nil
	file_lmm_core_v1_control_proto_depIdxs = nil
}
