package appcli

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/LIghtJUNction/api.lmm.best/internal/deploymentfence"
	"github.com/jackc/pgx/v5"
)

const merchantStartupBaselineKind = "lmm-startup-baseline-v1"
const merchantStartupAdmissionKind = "lmm-startup-baseline-admission-closed-v1"

// This is one startup provider, not a candidate/retained release pair. The
// ordinary contract validator deliberately rejects its runtime projection.
type productionMerchantStartupBaseline struct {
	Kind               string                           `json:"kind"`
	Provider           productionReleasePackagePlan     `json:"provider"`
	RequiredCapability int                              `json:"required_capability"`
	Role               string                           `json:"role"`
	StatusSHA256       string                           `json:"status_sha256"`
	Closure            productionMerchantStartupClosure `json:"closure"`
	PredecessorSHA256  string                           `json:"predecessor_sha256,omitempty"`
}

type productionMerchantStartupClosure struct {
	Format         int                                    `json:"format"`
	DeploymentID   string                                 `json:"deployment_id"`
	ProviderSHA256 string                                 `json:"provider_sha256"`
	Hosts          []productionMerchantStartupHostCapture `json:"hosts"`
}

// These values are generated by actual local observations, and are reobserved
// through the existing controller SSH transport before sealing. No caller
// supplies an all-closed boolean or selects a receipt/configuration pathname.
type productionMerchantStartupHostCapture struct {
	Format                int                              `json:"format"`
	DeploymentID          string                           `json:"deployment_id"`
	Host                  string                           `json:"host"`
	ProviderSHA256        string                           `json:"provider_sha256"`
	AdmissionSHA256       string                           `json:"admission_sha256"`
	AdmissionBodySHA256   string                           `json:"admission_body_sha256"`
	NginxPID              int                              `json:"nginx_pid"`
	NginxInvocationID     string                           `json:"nginx_invocation_id"`
	NginxGenerationSHA256 string                           `json:"nginx_generation_sha256"`
	StartupBarrierKind    string                           `json:"startup_barrier_kind"`
	StartupBarrierSHA256  string                           `json:"startup_barrier_sha256"`
	LegacyPID             int                              `json:"legacy_pid"`
	LegacyInvocationID    string                           `json:"legacy_invocation_id"`
	LegacyPayloadSHA256   string                           `json:"legacy_payload_sha256"`
	LegacyStartupSHA256   string                           `json:"legacy_startup_sha256"`
	CloseSHA256           string                           `json:"close_sha256"`
	StatusSHA256          string                           `json:"status_sha256"`
	GateBefore            string                           `json:"gate_before"`
	Schema                productionExistingSchemaContract `json:"schema"`
	Role                  string                           `json:"role"`
	RequiredCapability    int                              `json:"required_capability"`
	OtherBusinessClients  int                              `json:"other_business_clients"`
}

// The registered production origins are an existing deployment fact, not an
// operator-controlled host subset. Each is contacted directly through SSH.
var merchantStartupOrigins = []struct{ Alias, Host string }{
	{"ArchDmit", "arch-dmit"}, {"DmitUbuntu", "dmit-ubuntu"},
}

func (b *productionMerchantStartupBaseline) writerIdentity(host string) *productionMerchantStoreWriterContract {
	if b == nil || len(b.Closure.Hosts) == 0 {
		return nil
	}
	var h productionMerchantStartupHostCapture
	for _, captured := range b.Closure.Hosts {
		if captured.Host == host {
			h = captured
		}
	}
	if h.Host == "" {
		return nil
	}
	return &productionMerchantStoreWriterContract{Format: 1, RequiredCapability: b.RequiredCapability,
		SystemIdentifier: h.Schema.SystemIdentifier, Database: h.Schema.Database, DatabaseOID: h.Schema.DatabaseOID,
		Schema: h.Schema.Schema, SchemaOID: h.Schema.SchemaOID, Role: b.Role,
		StartupSHA256: h.Schema.StartupSHA256, SignedUnitSHA256: h.Schema.SignedUnitSHA256,
		RecoveryPolicy: "startup-only", Candidate: productionMerchantStoreWriterTarget{
			Capability: b.Provider.MerchantStoreWriterCapability, PackageSHA256: b.Provider.PackageSHA256,
			PayloadSHA256: b.Provider.PayloadSHA256, SourceRevision: b.Provider.GitRevision,
			ReleaseAssetSHA256: b.Provider.ReleaseAssetSHA256, StatusSHA256: b.StatusSHA256}}
}

func validateMerchantStartupHostCapture(h productionMerchantStartupHostCapture, id, provider string) error {
	if h.Format != 1 || h.DeploymentID != id || h.ProviderSHA256 != provider || !merchantStoreFenceHostPattern.MatchString(h.Host) ||
		!productionSHA256Pattern.MatchString(h.AdmissionSHA256) || !productionSHA256Pattern.MatchString(h.AdmissionBodySHA256) ||
		h.NginxPID <= 1 || !existingSchemaInvocationPattern.MatchString(h.NginxInvocationID) ||
		!productionSHA256Pattern.MatchString(h.NginxGenerationSHA256) || !productionSHA256Pattern.MatchString(h.CloseSHA256) ||
		!productionSHA256Pattern.MatchString(h.LegacyStartupSHA256) || !productionSHA256Pattern.MatchString(h.StatusSHA256) ||
		!productionSHA256Pattern.MatchString(h.StartupBarrierSHA256) || h.LegacyPID <= 1 ||
		!existingSchemaInvocationPattern.MatchString(h.LegacyInvocationID) || !productionSHA256Pattern.MatchString(h.LegacyPayloadSHA256) ||
		(h.GateBefore != "MISSING_PRE_VARIANT" && !strings.HasPrefix(h.GateBefore, "CONFIRMED_BASELINE:")) || h.OtherBusinessClients != 0 || !validMerchantStoreCapability(h.RequiredCapability) {
		return errors.New("startup baseline lacks actual closed pre-activation host evidence")
	}
	if h.StartupBarrierKind != "sealed-pending-hook" {
		return errors.New("startup baseline lacks a persistent fail-closed startup barrier")
	}
	if h.AdmissionBodySHA256 != startupContentSHA256([]byte(merchantStartupAdmissionKind+":"+id)) {
		return errors.New("startup baseline admission identity differs")
	}
	return validateProductionExistingSchemaContract(&h.Schema)
}

func validateMerchantStartupBaseline(b *productionMerchantStartupBaseline) error {
	if b == nil || b.Kind != merchantStartupBaselineKind || b.PredecessorSHA256 != "" && !productionSHA256Pattern.MatchString(b.PredecessorSHA256) ||
		b.Closure.Format != 1 || !productionIDPattern.MatchString(b.Closure.DeploymentID) ||
		b.Closure.ProviderSHA256 != b.Provider.PayloadSHA256 || len(b.Closure.Hosts) != len(merchantStartupOrigins) ||
		!productionSHA256Pattern.MatchString(b.StatusSHA256) {
		return errors.New("startup baseline authority is incomplete or has an unsupported predecessor")
	}
	for i, h := range b.Closure.Hosts {
		if h.Host != merchantStartupOrigins[i].Host || h.Role != b.Role || h.RequiredCapability != b.RequiredCapability || h.StatusSHA256 != b.StatusSHA256 {
			return errors.New("startup baseline omitted/reordered an origin or its actual role/floor differs")
		}
		if err := validateMerchantStartupHostCapture(h, b.Closure.DeploymentID, b.Provider.PayloadSHA256); err != nil {
			return err
		}
		if b.PredecessorSHA256 == "" && (h.GateBefore != "MISSING_PRE_VARIANT" || b.RequiredCapability != 1) ||
			b.PredecessorSHA256 != "" && h.GateBefore != "CONFIRMED_BASELINE:"+b.PredecessorSHA256 {
			return errors.New("startup baseline before/after gate provenance differs")
		}
		left, right := h.Schema, b.Closure.Hosts[0].Schema
		left.StartupSHA256, right.StartupSHA256 = "", ""
		if left != right {
			return errors.New("startup baseline origins do not bind the same physical schema")
		}
	}
	identity := b.writerIdentity(merchantStartupOrigins[0].Host)
	if err := validateMerchantStoreWriterHostIdentity(identity); err != nil {
		return err
	}
	if err := validateMerchantStoreWriterTarget(identity.Candidate, identity.RequiredCapability); err != nil {
		return err
	}
	p := b.Provider
	version, err := packageReleaseVersion(p.Version)
	if err != nil || p.Name != productionAURPackageName || p.Identity != p.Name+" "+p.Version || p.Workflow != "release-go.yml" || p.ReleaseTag != "go-v"+version ||
		!productionContractPattern.MatchString(p.ContractRevision) || !productionSHA256Pattern.MatchString(p.SignatureBundleSHA256) ||
		p.PackagePath != merchantStoreCapsuleAsset("candidate", "pkg.tar.zst") || p.ReleaseAsset != merchantStoreCapsuleAsset("candidate", "release.tar.gz") ||
		p.SignatureBundle != merchantStoreCapsuleAsset("candidate", "sigstore.json") {
		return errors.New("startup baseline provider is not one exact official artifact tuple")
	}
	return nil
}

func validateMerchantStartupBaselineCapsule(c productionMerchantStoreCapsule, paths productionPaths) error {
	if c.Format != 2 || c.Writer != nil || c.Candidate != (productionReleasePackagePlan{}) || c.Rollback != (productionReleasePackagePlan{}) || len(c.SourceFiles) != 0 ||
		!productionIDPattern.MatchString(c.DeploymentID) || c.Root != merchantStoreCapsuleRoot(paths, c.DeploymentID) ||
		c.Service != "lmm-api.service" || c.Service != paths.Service || c.Binary != paths.InstalledBinary || c.ConfigDir != paths.ConfigDir ||
		c.StartupPolicy != "per-start" || c.SchemaMode != productionSchemaModeVerifyExisting || !productionSHA256Pattern.MatchString(c.ControllerPlanSHA256) {
		return errors.New("startup baseline cannot contain an ordinary provider pair or deployment policy")
	}
	if err := validateMerchantStartupBaseline(c.Baseline); err != nil {
		return err
	}
	if c.ControllerPlanSHA256 != merchantStartupAuthoritySHA(c.Baseline) {
		return errors.New("startup baseline authority digest differs from the actual canonical closure")
	}
	if c.DeploymentID != c.Baseline.Closure.DeploymentID || validateProductionExistingSchemaContract(c.ExistingSchemaContract) != nil {
		return errors.New("startup baseline schema/identity is incomplete")
	}
	for _, h := range c.Baseline.Closure.Hosts {
		if h.Host == c.Host {
			if h.Schema != *c.ExistingSchemaContract {
				return errors.New("startup baseline host startup/schema differs")
			}
			return nil
		}
	}
	return errors.New("startup baseline is not for a captured origin")
}

func merchantStartupAuthoritySHA(b *productionMerchantStartupBaseline) string {
	body, err := json.Marshal(b)
	if err != nil {
		return ""
	}
	return startupContentSHA256(body)
}

func canonicalMerchantStartupBaselineCapsule(c productionMerchantStoreCapsule) ([]byte, error) {
	// The wire format has no candidate/retained pair. Runtime projection is
	// deliberately omitted, preserving exactly one signed provider in the seal.
	v := struct {
		Format                 int                                `json:"format"`
		DeploymentID           string                             `json:"deployment_id"`
		ControllerPlanSHA256   string                             `json:"controller_plan_sha256"`
		Root                   string                             `json:"root"`
		Host                   string                             `json:"host"`
		Service                string                             `json:"service"`
		Binary                 string                             `json:"binary"`
		ConfigDir              string                             `json:"config_dir"`
		SchemaMode             string                             `json:"schema_mode"`
		ExistingSchemaContract *productionExistingSchemaContract  `json:"existing_schema_contract"`
		StartupPolicy          string                             `json:"startup_policy"`
		Baseline               *productionMerchantStartupBaseline `json:"startup_baseline"`
	}{c.Format, c.DeploymentID, c.ControllerPlanSHA256, c.Root, c.Host, c.Service, c.Binary, c.ConfigDir, c.SchemaMode, c.ExistingSchemaContract, c.StartupPolicy, c.Baseline}
	body, err := json.MarshalIndent(v, "", "  ")
	return append(body, '\n'), err
}

func merchantStartupAdmissionBody(id string) string { return merchantStartupAdmissionKind + ":" + id }

func merchantStartupAdmissionBarrier(original []byte, id string) ([]byte, error) {
	if !productionIDPattern.MatchString(id) || bytes.Contains(original, []byte(merchantStartupAdmissionKind)) {
		return nil, errors.New("startup admission identity/original config is invalid")
	}
	if _, err := billingBarrierBody(original, merchantStartupAdmissionBody(id)); err != nil {
		return nil, err
	}
	return append([]byte("add_header Retry-After '60' always;\nadd_header X-LMM-Startup-Baseline '"+id+"' always;\nreturn 503 '"+merchantStartupAdmissionBody(id)+"';\n"), original...), nil
}

// Probe this origin's own TLS listener, never one DNS-selected origin. SNI,
// Host, status, canonical headers and body are fixed and enter the capture.
func (runtime *productionRuntime) probeMerchantStartupAdmission(ctx context.Context, id string) error {
	u, err := url.Parse(runtime.paths.PublicBaseURL)
	if err != nil || u.Scheme != "https" || u.Host != "api.lmm.best" || u.Path != "" || u.User != nil {
		return errors.New("startup admission requires the canonical production origin")
	}
	for _, route := range []string{"/api/status", "/api/user/self", "/v1/models"} {
		out, err := runtime.runner.Run(ctx, productionCommand{Name: "/usr/bin/curl", Args: []string{"--silent", "--show-error", "--include", "--max-time", "5", "--noproxy", "*", "--connect-to", "api.lmm.best:443:127.0.0.1:443", "https://api.lmm.best" + route}, Env: []string{"PATH=/usr/bin:/bin", "LANG=C", "LC_ALL=C"}, Timeout: 7 * time.Second, OutputLimit: 32768})
		if err != nil {
			return errors.New("origin-specific startup admission probe failed")
		}
		parts := bytes.SplitN(out, []byte("\r\n\r\n"), 2)
		if len(parts) != 2 || string(parts[1]) != merchantStartupAdmissionBody(id) {
			return errors.New("startup admission body differs")
		}
		lines := strings.Split(string(parts[0]), "\r\n")
		status := strings.Fields(lines[0])
		if len(status) < 2 || status[1] != "503" {
			return errors.New("startup admission status differs")
		}
		headers := map[string]string{}
		for _, line := range lines[1:] {
			k, v, ok := strings.Cut(line, ":")
			if !ok {
				return errors.New("startup admission headers malformed")
			}
			k = strings.ToLower(k)
			if _, duplicate := headers[k]; duplicate {
				return errors.New("startup admission duplicated header")
			}
			headers[k] = strings.TrimSpace(v)
		}
		if headers["retry-after"] != "60" || headers["x-lmm-startup-baseline"] != id {
			return errors.New("startup admission canonical headers differ")
		}
	}
	return nil
}

// The parser delegates to this separate authority instead of manufacturing a
// GoChanged ordinary plan. Commands never accept paths for closure evidence.
func runProductionMerchantStartupBaseline(args []string, stdout, stderr io.Writer) int {
	if len(args) == 0 {
		return ExitUsage
	}
	flags := flag.NewFlagSet("production writer-capsule "+args[0], flag.ContinueOnError)
	flags.SetOutput(stderr)
	id := flags.String("id", "", "fixed first-conversion identity")
	repo := flags.String("repo", "", "clean canonical source checkout for official artifact verification")
	predecessor := flags.String("predecessor-id", "", "previous actually confirmed startup baseline identity")
	if flags.Parse(args[1:]) != nil || flags.NArg() != 0 || !productionIDPattern.MatchString(*id) {
		return ExitUsage
	}
	runtime := defaultProductionRuntime()
	if runtime.effectiveUID() != 0 {
		return ExitError
	}
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Minute)
	defer cancel()
	err := runtime.runMerchantStartupBaseline(ctx, args[0], *id, *repo, *predecessor, stdout)
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "%s startup-baseline: %v\n", DeployProgramName, err)
		return ExitError
	}
	return ExitOK
}

// The checkpoint is produced before the native admission owner changes nginx.
// Only hashes/metadata are persisted. Parsed environment values stay in memory.
type productionMerchantStartupClose struct {
	Format          int                               `json:"format"`
	DeploymentID    string                            `json:"deployment_id"`
	Host            string                            `json:"host"`
	Provider        productionReleasePackagePlan      `json:"provider"`
	Legacy          productionReleasePackagePlan      `json:"legacy"`
	PID             int                               `json:"pid"`
	InvocationID    string                            `json:"invocation_id"`
	StartupSHA256   string                            `json:"startup_sha256"`
	OriginalSHA256  string                            `json:"original_sha256"`
	AdmissionSHA256 string                            `json:"admission_sha256"`
	GateBefore      string                            `json:"gate_before"`
	Database        productionMerchantStartupDatabase `json:"database"`
}

type productionMerchantStartupDatabase struct {
	SystemIdentifier string   `json:"system_identifier"`
	Database         string   `json:"database"`
	DatabaseOID      int64    `json:"database_oid"`
	Schema           string   `json:"schema"`
	SchemaOID        int64    `json:"schema_oid"`
	Role             string   `json:"role"`
	FloorValues      []string `json:"floor_values"`
	PreVariant       bool     `json:"pre_variant"`
	OtherClients     int      `json:"other_clients"`
	ReservedOwners   bool     `json:"reserved_owners"`
}

// One bounded READ ONLY transaction on the actual effective business DSN.
// Checking every remaining client backend in this database also fails closed
// for unclassified workers, including clients with a different SQL role.
func captureMerchantStartupDatabase(ctx context.Context, values map[string]string) (productionMerchantStartupDatabase, error) {
	var d productionMerchantStartupDatabase
	dsn, err := productionDatabaseURL(values)
	if err != nil {
		return d, err
	}
	if err := verifyExistingSchemaLogDatabase(values, dsn); err != nil {
		return d, err
	}
	if err := rejectMerchantStoreAmbientPGEnvironment(values); err != nil {
		return d, err
	}
	parsed, err := url.Parse(dsn)
	if err != nil || parsed.Fragment != "" {
		return d, errors.New("startup capture business PostgreSQL configuration is invalid")
	}
	query, err := url.ParseQuery(parsed.RawQuery)
	if err != nil {
		return d, errors.New("startup capture business PostgreSQL configuration is invalid")
	}
	options, err := productionPostgresRuntimeOptions(query, values)
	if err != nil {
		return d, err
	}
	config, err := pgx.ParseConfig(dsn)
	if err != nil {
		return d, errors.New("startup capture business PostgreSQL configuration is invalid")
	}
	config.RuntimeParams["options"] = options
	config.ConnectTimeout = 10 * time.Second
	config.RuntimeParams["default_transaction_read_only"] = "on"
	config.RuntimeParams["statement_timeout"] = "15000"
	config.RuntimeParams["lock_timeout"] = "3000"
	config.RuntimeParams["application_name"] = "lmm-startup-baseline-capture"
	conn, err := pgx.ConnectConfig(ctx, config)
	if err != nil {
		return d, errors.New("startup capture actual business connection unavailable")
	}
	defer conn.Close(context.Background())
	tx, err := conn.BeginTx(ctx, pgx.TxOptions{IsoLevel: pgx.RepeatableRead, AccessMode: pgx.ReadOnly})
	if err != nil {
		return d, errors.New("startup capture read-only transaction unavailable")
	}
	defer tx.Rollback(context.Background())
	var sessionRole, readonly string
	err = tx.QueryRow(ctx, `SELECT (SELECT system_identifier::text FROM pg_catalog.pg_control_system()),current_database(),
(SELECT oid::bigint FROM pg_catalog.pg_database WHERE datname=current_database()),current_schema(),
(SELECT oid::bigint FROM pg_catalog.pg_namespace WHERE nspname=current_schema()),current_user,session_user,
current_setting('transaction_read_only'),(SELECT count(*)::int FROM pg_catalog.pg_stat_activity WHERE datid=(SELECT oid FROM pg_catalog.pg_database WHERE datname=current_database()) AND backend_type='client backend' AND pid<>pg_backend_pid())`).Scan(&d.SystemIdentifier, &d.Database, &d.DatabaseOID, &d.Schema, &d.SchemaOID, &d.Role, &sessionRole, &readonly, &d.OtherClients)
	if err != nil || readonly != "on" || sessionRole != d.Role || !isDatabaseSchema(d.Schema) {
		return d, errors.New("startup capture physical database/business role/read-only identity unavailable")
	}
	err = tx.QueryRow(ctx, `SELECT COALESCE(array_agg(value ORDER BY value),ARRAY[]::text[]) FROM "`+d.Schema+`".options WHERE key='MerchantStoreMinimumWriterCapability'`).Scan(&d.FloorValues)
	if err != nil {
		return d, errors.New("startup capture gate Option unavailable")
	}
	err = tx.QueryRow(ctx, `SELECT EXISTS(SELECT 1 FROM "`+d.Schema+`".options WHERE `+deploymentfence.PostgreSQLPresencePredicate+`)`).Scan(&d.ReservedOwners)
	if err != nil {
		return d, errors.New("startup capture reserved deployment ownership unavailable")
	}
	err = tx.QueryRow(ctx, `SELECT
 (SELECT count(*) FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname=$1 AND c.relkind IN ('r','p') AND starts_with(c.relname,'merchant_store_'))=15
	 AND NOT EXISTS(SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname=$1 AND c.relname='merchant_store_variants')
 AND NOT EXISTS(SELECT 1 FROM pg_catalog.pg_attribute a JOIN pg_catalog.pg_class c ON c.oid=a.attrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname=$1 AND c.relname IN ('merchant_store_stocks','merchant_store_orders') AND a.attname='variant_id' AND a.attnum>0 AND NOT a.attisdropped)`, d.Schema).Scan(&d.PreVariant)
	if err != nil {
		return d, errors.New("startup capture merchant schema inventory unavailable")
	}
	return d, nil
}

func merchantStartupSameDatabase(a, b productionMerchantStartupDatabase) bool {
	return a.SystemIdentifier == b.SystemIdentifier && a.Database == b.Database && a.DatabaseOID == b.DatabaseOID && a.Schema == b.Schema && a.SchemaOID == b.SchemaOID && a.Role == b.Role
}

func (runtime *productionRuntime) startupBaselineRoot(id string) (string, error) {
	if !productionIDPattern.MatchString(id) {
		return "", errors.New("startup baseline identity invalid")
	}
	root := merchantStoreCapsuleRoot(runtime.paths, id)
	if err := runtime.merchantStorePrivateDirectory(root, false); err != nil {
		return "", err
	}
	return root, nil
}

func merchantStartupJSON(value any) ([]byte, error) {
	raw, err := json.MarshalIndent(value, "", "  ")
	return append(raw, '\n'), err
}

func (runtime *productionRuntime) startupBaselineNewFile(path string, value any) error {
	raw, err := merchantStartupJSON(value)
	if err != nil {
		return err
	}
	return runtime.startupBaselineNewBytes(path, raw)
}

func (runtime *productionRuntime) startupBaselineNewBytes(path string, raw []byte) error {
	if len(raw) == 0 || len(raw) > 1<<20 {
		return errors.New("startup baseline evidence exceeds bounded file size")
	}
	if err := runtime.merchantStorePrivateDirectory(filepath.Dir(path), false); err != nil {
		return err
	}
	f, err := os.OpenFile(path, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
	if err != nil {
		return errors.New("startup baseline evidence already exists or cannot be created")
	}
	_, err = f.Write(raw)
	if err == nil {
		err = f.Sync()
	}
	closeErr := f.Close()
	if err == nil {
		err = closeErr
	}
	return err
}

func (runtime *productionRuntime) startupBaselineRead(path string, value any) ([]byte, error) {
	raw, err := runtime.readExistingSchemaSealedFile(path, true)
	if err != nil || len(raw) > 32768 || !merchantStoreUniqueJSON(raw) {
		return nil, errors.New("startup baseline evidence is absent/unsafe/ambiguous")
	}
	d := json.NewDecoder(bytes.NewReader(raw))
	d.DisallowUnknownFields()
	if d.Decode(value) != nil || d.Decode(&struct{}{}) != io.EOF {
		return nil, errors.New("startup baseline evidence JSON invalid")
	}
	canonical, err := merchantStartupJSON(value)
	if err != nil || !bytes.Equal(canonical, raw) {
		return nil, errors.New("startup baseline evidence noncanonical")
	}
	return raw, nil
}

func (runtime *productionRuntime) startupBaselineProvider(ctx context.Context, root, repo, role string) (productionReleasePackagePlan, error) {
	var zero productionReleasePackagePlan
	if role != "candidate" && role != "preactivation" {
		return zero, errors.New("startup provider role invalid")
	}
	if clean, err := cleanAbsoluteNonRoot(repo); err != nil || clean != repo {
		return zero, errors.New("startup baseline requires canonical source checkout")
	}
	if err := validateBuildRepository(repo); err != nil {
		return zero, err
	}
	for _, kind := range []string{"pkg.tar.zst", "release.tar.gz", "sigstore.json"} {
		if err := runtime.merchantStoreCapsuleFile(filepath.Join(root, merchantStoreCapsuleAsset(role, kind)), 0600); err != nil {
			return zero, err
		}
	}
	r := productionReleaseRuntime{runner: merchantStartupVerificationRunner{runtime.runner}, now: runtime.now}
	p, err := r.verifyStartupBaselinePackageEvidence(ctx, repo, root, runtime, filepath.Join(root, merchantStoreCapsuleAsset(role, "pkg.tar.zst")), filepath.Join(root, merchantStoreCapsuleAsset(role, "release.tar.gz")), filepath.Join(root, merchantStoreCapsuleAsset(role, "sigstore.json")))
	if err != nil {
		return zero, err
	}
	return merchantStoreCapsuleProjection(p, role), nil
}

type merchantStartupVerificationRunner struct{ productionCommandRunner }

func (r merchantStartupVerificationRunner) Run(ctx context.Context, c productionCommand) ([]byte, error) {
	if c.Name == commandGit {
		c.Env = merchantStoreSourceGitEnvironment()
	}
	return r.productionCommandRunner.Run(ctx, c)
}

// The legacy unit is not made verify-only by pretending its defaults changed.
// This captures its real ordered private files and compares the active process.
func (runtime *productionRuntime) startupBaselineLegacyValues(ctx context.Context, loaded map[string]string, pid int) (map[string]string, string, error) {
	if loaded["PassEnvironment"] != "" || loaded["UnsetEnvironment"] != "" {
		return nil, "", errors.New("legacy startup has unchecked environment overrides")
	}
	values, err := parseExistingSchemaLoadedEnvironment(loaded["Environment"])
	if err != nil {
		return nil, "", err
	}
	commands, err := verifyExistingSchemaSealedCommands(loaded, runtime.paths.InstalledBinary)
	if err != nil {
		return nil, "", err
	}
	unit, err := runtime.readExistingSchemaSealedFile(loaded["FragmentPath"], false)
	if err != nil {
		return nil, "", err
	}
	snapshot := existingSchemaStartupSnapshot{Environment: map[string]string{}, FragmentPath: loaded["FragmentPath"], UnitSHA256: startupContentSHA256(unit), Commands: commands}
	for k, v := range values {
		snapshot.Environment[k] = v
	}
	seen := map[string]bool{}
	for i, row := range strings.Split(loaded["EnvironmentFiles"], "\n") {
		m := existingSchemaEnvironmentFilePattern.FindStringSubmatch(row)
		if m == nil || seen[m[1]] || i == 0 && m[1] != filepath.Join(runtime.paths.ConfigDir, "lmm-api-go.env") || i >= 16 {
			return nil, "", errors.New("legacy ordered environment closure invalid")
		}
		seen[m[1]] = true
		raw, err := runtime.readExistingSchemaSealedFile(m[1], true)
		if err != nil {
			return nil, "", err
		}
		entries, err := parseProductionEnvironment(raw)
		if err != nil {
			return nil, "", errors.New("legacy environment malformed")
		}
		for k, v := range entries {
			values[k] = v
		}
		snapshot.Files = append(snapshot.Files, existingSchemaEnvironmentFile{Path: m[1], IgnoreErrors: m[2] == "yes", SHA256: startupContentSHA256(raw)})
	}
	dsn, err := productionDatabaseURL(values)
	if err != nil {
		return nil, "", err
	}
	if err := verifyExistingSchemaLogDatabase(values, dsn); err != nil {
		return nil, "", err
	}
	raw, err := os.ReadFile(filepath.Join("/proc", strconv.Itoa(pid), "environ"))
	if err != nil || len(raw) > 1<<20 {
		return nil, "", errors.New("legacy actual process environment unavailable")
	}
	process := map[string]string{}
	for _, row := range bytes.Split(raw, []byte{0}) {
		if len(row) == 0 {
			continue
		}
		k, v, ok := strings.Cut(string(row), "=")
		if !ok || !productionEnvironmentKeyPattern.MatchString(k) {
			return nil, "", errors.New("legacy process environment malformed")
		}
		if _, exists := process[k]; exists {
			return nil, "", errors.New("legacy process environment duplicate")
		}
		process[k] = v
	}
	actual, err := productionDatabaseURL(process)
	if err != nil || actual != dsn || process["PGOPTIONS"] != values["PGOPTIONS"] || verifyExistingSchemaLogDatabase(process, actual) != nil {
		return nil, "", errors.New("legacy actual process database differs from effective startup")
	}
	for _, key := range existingSchemaFinancialEnvironment {
		if process[key] != "" || values[key] != "" {
			return nil, "", errors.New("legacy startup is under financial maintenance")
		}
	}
	encoded, err := json.Marshal(snapshot)
	return values, startupContentSHA256(encoded), err
}

func (runtime *productionRuntime) startupBaselineAdmission(ctx context.Context, id, expected string) (int, string, string, error) {
	path := filepath.Join(runtime.paths.NginxRoot, "lmm-api-locations.conf")
	raw, err := runtime.readExistingSchemaSealedFile(path, false)
	if err != nil || startupContentSHA256(raw) != expected {
		return 0, "", "", errors.New("startup persistent admission bytes changed")
	}
	before, err := runtime.billingUnitState(ctx, "nginx.service")
	pid, parseErr := strconv.Atoi(before["MainPID"])
	if err != nil || parseErr != nil || pid <= 1 || before["ActiveState"] != "active" || before["SubState"] != "running" || !existingSchemaInvocationPattern.MatchString(before["InvocationID"]) {
		return 0, "", "", errors.New("startup nginx generation unavailable")
	}
	childrenPath := filepath.Join("/proc", strconv.Itoa(pid), "task", strconv.Itoa(pid), "children")
	children, err := os.ReadFile(childrenPath)
	if err != nil || len(strings.Fields(string(children))) == 0 {
		return 0, "", "", errors.New("startup nginx live worker generation unavailable")
	}
	if err := runtime.probeMerchantStartupAdmission(ctx, id); err != nil {
		return 0, "", "", err
	}
	n, err := countBillingConnections()
	if err != nil || n != 0 {
		return 0, "", "", errors.New("startup backend still has accepted sockets")
	}
	after, err := runtime.billingUnitState(ctx, "nginx.service")
	afterChildren, childErr := os.ReadFile(childrenPath)
	current, fileErr := runtime.readExistingSchemaSealedFile(path, false)
	if err != nil || childErr != nil || fileErr != nil || before["MainPID"] != after["MainPID"] || before["InvocationID"] != after["InvocationID"] || after["ActiveState"] != "active" || !bytes.Equal(children, afterChildren) || !bytes.Equal(raw, current) {
		return 0, "", "", errors.New("startup nginx loaded generation changed during direct-origin proof")
	}
	return pid, before["InvocationID"], startupContentSHA256(children), nil
}

type productionMerchantStartupConfirmation struct {
	Format          int    `json:"format"`
	DeploymentID    string `json:"deployment_id"`
	Host            string `json:"host"`
	CapsuleSHA256   string `json:"capsule_sha256"`
	AuthoritySHA256 string `json:"authority_sha256"`
	PID             int    `json:"pid"`
	InvocationID    string `json:"invocation_id"`
	ProviderSHA256  string `json:"provider_sha256"`
}

func (runtime *productionRuntime) startupBaselineConfirmed(id string) (productionMerchantStoreCapsule, string, error) {
	var empty productionMerchantStoreCapsule
	root, err := runtime.startupBaselineRoot(id)
	if err != nil {
		return empty, "", err
	}
	var receipt productionMerchantStartupConfirmation
	if _, err := runtime.startupBaselineRead(filepath.Join(root, "state", "baseline-confirmed.json"), &receipt); err != nil {
		return empty, "", err
	}
	c, err := runtime.loadMerchantStoreCapsule(filepath.Join(root, "capsule.json"), receipt.CapsuleSHA256)
	if err != nil || c.Format != 2 || receipt.Format != 1 || receipt.DeploymentID != id || receipt.Host != c.Host || receipt.AuthoritySHA256 != merchantStartupAuthoritySHA(c.Baseline) || receipt.ProviderSHA256 != c.Candidate.PayloadSHA256 || receipt.PID <= 1 || !existingSchemaInvocationPattern.MatchString(receipt.InvocationID) {
		return empty, "", errors.New("predecessor is not an actually confirmed local startup baseline")
	}
	return c, receipt.CapsuleSHA256, nil
}

func (runtime *productionRuntime) closeMerchantStartupAdmission(ctx context.Context, id, repo, predecessor string) (string, error) {
	root, err := runtime.startupBaselineRoot(id)
	if err != nil {
		return "", err
	}
	if err := runtime.merchantStorePrivateDirectory(filepath.Join(root, "state"), true); err != nil {
		return "", err
	}
	host, err := runtime.hostname()
	if err != nil {
		return "", err
	}
	registered := false
	for _, origin := range merchantStartupOrigins {
		registered = registered || host == origin.Host
	}
	if !registered {
		return "", errors.New("startup close host is not a registered origin")
	}
	p, err := runtime.startupBaselineProvider(ctx, root, repo, "candidate")
	if err != nil {
		return "", err
	}
	if !validMerchantStoreCapability(p.MerchantStoreWriterCapability) {
		return "", errors.New("startup provider has no supported writer gate")
	}
	loaded, err := runtime.loadedExistingSchemaUnit(ctx)
	if err != nil {
		return "", err
	}
	state, err := runtime.billingUnitState(ctx, runtime.paths.Service)
	pid, parseErr := strconv.Atoi(state["MainPID"])
	if err != nil || parseErr != nil || pid <= 1 || state["ActiveState"] != "active" || state["SubState"] != "running" || state["MainPID"] != loaded["MainPID"] || state["InvocationID"] != loaded["InvocationID"] || !existingSchemaInvocationPattern.MatchString(state["InvocationID"]) {
		return "", errors.New("startup close legacy running generation unavailable")
	}
	var legacy productionReleasePackagePlan
	var values map[string]string
	var startup, gate string
	if predecessor == "" {
		legacy, err = runtime.startupBaselineProvider(ctx, root, repo, "preactivation")
		if err != nil {
			return "", err
		}
		values, startup, err = runtime.startupBaselineLegacyValues(ctx, loaded, pid)
		if err != nil {
			return "", err
		}
		unit, err := runtime.runner.Run(ctx, productionCommand{Name: commandBsdtar, Args: []string{"-xOf", filepath.Join(root, legacy.PackagePath), "usr/lib/systemd/system/lmm-api.service"}, OutputLimit: 1 << 20})
		if err != nil {
			return "", errors.New("legacy signed unit unavailable")
		}
		actual, err := runtime.readExistingSchemaSealedFile(loaded["FragmentPath"], false)
		if err != nil || !bytes.Equal(actual, unit) {
			return "", errors.New("legacy loaded fragment differs from exact official preactivation package")
		}
		gate = "MISSING_PRE_VARIANT"
	} else {
		previous, digest, err := runtime.startupBaselineConfirmed(predecessor)
		if err != nil {
			return "", err
		}
		if previous.Candidate != p {
			return "", errors.New("successor startup baseline must retain the same exact official provider")
		}
		if err := runtime.verifyPortableRunningWriter(ctx, previous, digest, "", false); err != nil {
			return "", err
		}
		legacy = previous.Candidate
		values, err = runtime.merchantStoreCapsuleStartup(ctx, previous, digest, loaded)
		if err != nil {
			return "", err
		}
		startup = previous.Writer.StartupSHA256
		gate = "CONFIRMED_BASELINE:" + merchantStartupAuthoritySHA(previous.Baseline)
	}
	if runtime.verifyMerchantStorePortableInstalled(productionMerchantStoreCapsule{Binary: runtime.paths.InstalledBinary}, legacy.PayloadSHA256) != nil || sha256MustEqual(filepath.Join("/proc", strconv.Itoa(pid), "exe"), legacy.PayloadSHA256) != nil {
		return "", errors.New("startup close installed/running legacy provider differs from official evidence")
	}
	db, err := captureMerchantStartupDatabase(ctx, values)
	if err != nil {
		return "", err
	}
	if db.ReservedOwners {
		return "", errors.New("startup close found a live/unknown durable deployment owner")
	}
	if predecessor == "" && (len(db.FloorValues) != 0 || !db.PreVariant) {
		return "", errors.New("first conversion requires actual missing gate and pre-variant schema")
	}
	path := filepath.Join(runtime.paths.NginxRoot, "lmm-api-locations.conf")
	original, err := runtime.readExistingSchemaSealedFile(path, false)
	if err != nil {
		return "", err
	}
	if predecessor != "" && bytes.Contains(original, []byte(merchantStartupAdmissionKind)) {
		previousRoot, err := runtime.startupBaselineRoot(predecessor)
		if err != nil {
			return "", err
		}
		var priorClose productionMerchantStartupClose
		if _, err := runtime.startupBaselineRead(filepath.Join(previousRoot, "state", "baseline-close.json"), &priorClose); err != nil {
			return "", err
		}
		priorOriginal, err := runtime.readExistingSchemaSealedFile(filepath.Join(previousRoot, "state", "admission-original.conf"), true)
		if err != nil {
			return "", err
		}
		priorBarrier, err := merchantStartupAdmissionBarrier(priorOriginal, predecessor)
		if err != nil || startupContentSHA256(priorOriginal) != priorClose.OriginalSHA256 || !bytes.Equal(priorBarrier, original) {
			return "", errors.New("predecessor persistent admission bytes differ")
		}
		original = priorOriginal
	}
	barrier, err := merchantStartupAdmissionBarrier(original, id)
	if err != nil {
		return "", err
	}
	close := productionMerchantStartupClose{Format: 1, DeploymentID: id, Host: host, Provider: p, Legacy: legacy, PID: pid, InvocationID: state["InvocationID"], StartupSHA256: startup, OriginalSHA256: startupContentSHA256(original), AdmissionSHA256: startupContentSHA256(barrier), GateBefore: gate, Database: db}
	// Save exact pre-change facts first. An interrupted close cannot invent the
	// later loaded proof; baseline-capture independently reobserves it.
	if err := runtime.startupBaselineNewBytes(filepath.Join(root, "state", "admission-original.conf"), original); err != nil {
		return "", err
	}
	if err := runtime.startupBaselineNewFile(filepath.Join(root, "state", "baseline-close.json"), close); err != nil {
		return "", err
	}
	if err := runtime.installAdmissionBarrier(ctx, barrier); err != nil {
		return "", err
	}
	if err := runtime.awaitAdmissionDrain(ctx, func(ctx context.Context) bool { return runtime.probeMerchantStartupAdmission(ctx, id) == nil }); err != nil {
		return "", err
	}
	if _, _, _, err := runtime.startupBaselineAdmission(ctx, id, close.AdmissionSHA256); err != nil {
		return "", err
	}
	current, err := runtime.billingUnitState(ctx, runtime.paths.Service)
	if err != nil || current["MainPID"] != state["MainPID"] || current["InvocationID"] != state["InvocationID"] || sha256MustEqual(filepath.Join("/proc", strconv.Itoa(pid), "exe"), legacy.PayloadSHA256) != nil {
		return "", errors.New("legacy generation changed during admission close")
	}
	raw, _ := merchantStartupJSON(close)
	return startupContentSHA256(raw), nil
}

func (runtime *productionRuntime) captureMerchantStartupHost(ctx context.Context, id string) (productionMerchantStartupHostCapture, error) {
	var h productionMerchantStartupHostCapture
	root, err := runtime.startupBaselineRoot(id)
	if err != nil {
		return h, err
	}
	var close productionMerchantStartupClose
	closeRaw, err := runtime.startupBaselineRead(filepath.Join(root, "state", "baseline-close.json"), &close)
	if err != nil {
		return h, err
	}
	host, err := runtime.hostname()
	if err != nil || close.Format != 1 || close.DeploymentID != id || host != close.Host || !productionSHA256Pattern.MatchString(close.StartupSHA256) || !productionSHA256Pattern.MatchString(close.Legacy.PayloadSHA256) {
		return h, errors.New("startup capture does not match this native close owner")
	}
	state, err := runtime.billingUnitState(ctx, runtime.paths.Service)
	if err != nil || state["MainPID"] != "0" || state["ActiveState"] != "inactive" || state["SubState"] != "dead" || state["ControlGroup"] != "" {
		return h, errors.New("startup capture requires a stopped writer and empty cgroup")
	}
	if _, err := os.Stat(filepath.Join("/proc", strconv.Itoa(close.PID))); !errors.Is(err, os.ErrNotExist) {
		return h, errors.New("old writer PID still exists; no PID inference allowed")
	}
	// The service's normal stop result must belong to the captured invocation.
	if state["InvocationID"] != close.InvocationID || cleanBillingUnitExit(state, close.PID) != nil {
		return h, errors.New("old writer did not verifiably exit normally")
	}
	loaded, err := runtime.loadedExistingSchemaUnit(ctx)
	if err != nil {
		return h, err
	}
	path := filepath.Join(root, "capsule.json")
	placeholder := strings.Repeat("0", 64)
	// A literal placeholder is permitted only while stopped and before sealing.
	// It cannot load a nonexistent capsule, and fails closed across reboot.
	commands, err := runtime.merchantStorePortableStartupCommands(loaded, runtime.paths.InstalledBinary, path, placeholder)
	if err != nil {
		return h, err
	}
	values, err := parseExistingSchemaLoadedEnvironment(loaded["Environment"])
	if err != nil || verifyExistingSchemaStartupEnvironment(values, true) != nil {
		return h, errors.New("pending startup does not enforce verify-only")
	}
	values, startup, unit, err := runtime.existingSchemaSealedStartupCommands(ctx, loaded, values, commands)
	if err != nil {
		return h, err
	}
	main, err := runtime.readExistingSchemaSealedFile(filepath.Join(runtime.paths.ConfigDir, "lmm-api-go.env"), true)
	if err != nil {
		return h, err
	}
	configured, err := parseProductionEnvironment(main)
	if err != nil {
		return h, errors.New("startup canonical main environment malformed")
	}
	mainDSN, mainErr := productionDatabaseURL(configured)
	effectiveDSN, effectiveErr := productionDatabaseURL(values)
	if mainErr != nil || effectiveErr != nil || mainDSN != effectiveDSN || verifyExistingSchemaStartupEnvironment(configured, false) != nil {
		return h, errors.New("startup effective database differs from canonical main configuration")
	}
	db, err := captureMerchantStartupDatabase(ctx, values)
	if err != nil {
		return h, err
	}
	if !merchantStartupSameDatabase(db, close.Database) || db.OtherClients != 0 || db.ReservedOwners || len(db.FloorValues) != 1 {
		return h, errors.New("stopped capture found a changed physical database, remaining client, owner or ambiguous gate")
	}
	floor, err := strconv.Atoi(db.FloorValues[0])
	if err != nil || strconv.Itoa(floor) != db.FloorValues[0] || !validMerchantStoreCapability(floor) || close.GateBefore == "MISSING_PRE_VARIANT" && floor != 1 {
		return h, errors.New("post-prepare floor is not the explicit initial/successor gate")
	}
	child, err := runtime.existingSchemaMigrationValues(values, db.Schema)
	if err != nil {
		return h, err
	}
	childValues := map[string]string{}
	for _, row := range child {
		k, v, _ := strings.Cut(row, "=")
		childValues[k] = v
	}
	dsn, env, err := productionDatabaseCommand(childValues)
	if err != nil {
		return h, err
	}
	metadata, err := runtime.runner.Run(ctx, productionCommand{Name: commandPSQL, Args: []string{"-X", "-q", "-v", "ON_ERROR_STOP=1", "--no-align", "--tuples-only", "--dbname", dsn, "--command", existingSchemaMetadataQuery(db.Schema)}, Env: env, Sensitive: true, Timeout: 30 * time.Second, OutputLimit: 8 << 20})
	if err != nil {
		return h, errors.New("startup capture actual schema metadata unavailable")
	}
	schema, err := decodeExistingSchemaSnapshot(metadata)
	if err != nil {
		return h, err
	}
	schema.StartupSHA256, schema.SignedUnitSHA256 = startup, unit
	npid, ninv, ngeneration, err := runtime.startupBaselineAdmission(ctx, id, close.AdmissionSHA256)
	if err != nil {
		return h, err
	}
	// The package verifier below repeats official issuer/layout/unit/hash checks;
	// source reachability was verified by the native close owner before mutation.
	identity := &productionMerchantStoreWriterContract{Format: 1, RequiredCapability: floor, SystemIdentifier: db.SystemIdentifier, Database: db.Database, DatabaseOID: db.DatabaseOID, Schema: db.Schema, SchemaOID: db.SchemaOID, Role: db.Role, StartupSHA256: startup, SignedUnitSHA256: unit, RecoveryPolicy: "startup-only", Candidate: productionMerchantStoreWriterTarget{Capability: close.Provider.MerchantStoreWriterCapability, PackageSHA256: close.Provider.PackageSHA256, PayloadSHA256: close.Provider.PayloadSHA256, SourceRevision: close.Provider.GitRevision, ReleaseAssetSHA256: close.Provider.ReleaseAssetSHA256}}
	c := productionMerchantStoreCapsule{Format: 2, Root: root, DeploymentID: id, Host: host, Service: runtime.paths.Service, Binary: runtime.paths.InstalledBinary, ConfigDir: runtime.paths.ConfigDir, Writer: identity, Candidate: close.Provider, ExistingSchemaContract: &schema, StartupPolicy: "per-start", SchemaMode: productionSchemaModeVerifyExisting}
	provider, err := runtime.verifyMerchantStoreCapsuleArtifact(ctx, c, false)
	if err != nil {
		return h, err
	}
	if err := runtime.verifyMerchantStorePortableInstalled(c, close.Provider.PayloadSHA256); err != nil {
		return h, err
	}
	status, err := runVerifiedBinary(ctx, runtime.runner, provider, []string{"merchant-store-writer-gate", "status"}, child, filepath.Dir(provider), 35*time.Second, true)
	actual, parseErr := parseMerchantStoreWriterStatus(status)
	if err != nil || parseErr != nil || actual.RequiredCapability != floor || actual.WriterCapability != close.Provider.MerchantStoreWriterCapability || !actual.NewWritesAllowed {
		return h, errors.New("startup capture actual provider status invalid")
	}
	if err := runtime.verifyMerchantStoreWriterProvider(ctx, merchantStoreCapsuleWorkspace(c), provider, child, "candidate"); err != nil {
		return h, err
	}
	// Recheck remaining clients and unchanged startup/admission after children
	// exited. No long-lived outer lock can deadlock their own verify lock.
	afterDB, err := captureMerchantStartupDatabase(ctx, values)
	if err != nil || !merchantStartupSameDatabase(db, afterDB) || afterDB.OtherClients != 0 || afterDB.ReservedOwners || !stringsEqual(db.FloorValues, afterDB.FloorValues) {
		return h, errors.New("startup capture database changed while verifying provider")
	}
	after, err := runtime.loadedExistingSchemaUnit(ctx)
	if err != nil || after["MainPID"] != "0" || after["ActiveState"] != "inactive" || after["ExecStartPre"] != loaded["ExecStartPre"] || after["ExecStartPreEx"] != loaded["ExecStartPreEx"] || after["DropInPaths"] != loaded["DropInPaths"] || after["Environment"] != loaded["Environment"] || after["EnvironmentFiles"] != loaded["EnvironmentFiles"] {
		return h, errors.New("startup changed during stopped qualification")
	}
	finalCommands, err := runtime.merchantStorePortableStartupCommands(after, runtime.paths.InstalledBinary, path, placeholder)
	if err != nil {
		return h, err
	}
	finalValues, err := parseExistingSchemaLoadedEnvironment(after["Environment"])
	if err != nil {
		return h, err
	}
	_, finalStartup, finalUnit, err := runtime.existingSchemaSealedStartupCommands(ctx, after, finalValues, finalCommands)
	if err != nil || finalStartup != startup || finalUnit != unit {
		return h, errors.New("startup private file bytes changed during provider qualification")
	}
	finalMetadata, err := runtime.runner.Run(ctx, productionCommand{Name: commandPSQL, Args: []string{"-X", "-q", "-v", "ON_ERROR_STOP=1", "--no-align", "--tuples-only", "--dbname", dsn, "--command", existingSchemaMetadataQuery(db.Schema)}, Env: env, Sensitive: true, Timeout: 30 * time.Second, OutputLimit: 8 << 20})
	if err != nil {
		return h, errors.New("startup final schema recheck failed")
	}
	finalSchema, err := decodeExistingSchemaSnapshot(finalMetadata)
	expectedSchema := schema
	expectedSchema.StartupSHA256, expectedSchema.SignedUnitSHA256 = "", ""
	if err != nil || finalSchema != expectedSchema {
		return h, errors.New("startup schema changed during provider qualification")
	}
	finalPID, finalInvocation, finalGeneration, err := runtime.startupBaselineAdmission(ctx, id, close.AdmissionSHA256)
	if err != nil {
		return h, err
	}
	if finalPID != npid || finalInvocation != ninv || finalGeneration != ngeneration {
		return h, errors.New("startup admission loaded generation changed during provider qualification")
	}
	h = productionMerchantStartupHostCapture{Format: 1, DeploymentID: id, Host: host, ProviderSHA256: close.Provider.PayloadSHA256, AdmissionSHA256: close.AdmissionSHA256, AdmissionBodySHA256: startupContentSHA256([]byte(merchantStartupAdmissionBody(id))), NginxPID: npid, NginxInvocationID: ninv, NginxGenerationSHA256: ngeneration, StartupBarrierKind: "sealed-pending-hook", StartupBarrierSHA256: startupContentSHA256(merchantStorePortableHookBytes(runtime.paths.InstalledBinary, path, placeholder)), LegacyPID: close.PID, LegacyInvocationID: close.InvocationID, LegacyPayloadSHA256: close.Legacy.PayloadSHA256, LegacyStartupSHA256: close.StartupSHA256, CloseSHA256: startupContentSHA256(closeRaw), StatusSHA256: startupContentSHA256(status), GateBefore: close.GateBefore, Schema: schema, Role: db.Role, RequiredCapability: floor, OtherBusinessClients: 0}
	return h, validateMerchantStartupHostCapture(h, id, close.Provider.PayloadSHA256)
}

func stringsEqual(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// The same native controller transport derives BOTH live origin facts. It
// never reads a caller-selected closure file or trusts DNS to choose an origin.
func (runtime *productionRuntime) collectMerchantStartupClosure(ctx context.Context, id string, provider productionReleasePackagePlan) ([]productionMerchantStartupHostCapture, error) {
	release := productionReleaseRuntime{runner: runtime.runner, now: runtime.now}
	var hosts []productionMerchantStartupHostCapture
	for _, origin := range merchantStartupOrigins {
		if err := release.assertRemoteHost(ctx, origin.Alias, origin.Host); err != nil {
			return nil, err
		}
		out, err := release.ssh(ctx, origin.Alias, 20*time.Second, "sudo", "-n", "/usr/bin/sha256sum", runtime.paths.InstalledBinary)
		fields := strings.Fields(string(out))
		if err != nil || len(fields) != 2 || fields[0] != provider.PayloadSHA256 || fields[1] != runtime.paths.InstalledBinary {
			return nil, errors.New("remote baseline capture provider is not the exact installed official ELF")
		}
		raw, err := release.ssh(ctx, origin.Alias, 5*time.Minute, "sudo", "-n", runtime.paths.InstalledBinary, "operator", "production", "writer-capsule", "baseline-capture", "--id", id)
		if err != nil || len(raw) > 16384 || !merchantStoreUniqueJSON(raw) {
			return nil, errors.New("remote baseline actual capture failed")
		}
		var h productionMerchantStartupHostCapture
		d := json.NewDecoder(bytes.NewReader(raw))
		d.DisallowUnknownFields()
		if d.Decode(&h) != nil || d.Decode(&struct{}{}) != io.EOF {
			return nil, errors.New("remote baseline capture invalid")
		}
		canonical, _ := merchantStartupJSON(h)
		if !bytes.Equal(canonical, raw) || h.Host != origin.Host || validateMerchantStartupHostCapture(h, id, provider.PayloadSHA256) != nil {
			return nil, errors.New("remote baseline capture host/provider/closed facts differ")
		}
		hosts = append(hosts, h)
	}
	return hosts, nil
}

func (runtime *productionRuntime) sealMerchantStartupBaseline(ctx context.Context, id, repo string, successor bool) (string, error) {
	root, err := runtime.startupBaselineRoot(id)
	if err != nil {
		return "", err
	}
	p, err := runtime.startupBaselineProvider(ctx, root, repo, "candidate")
	if err != nil {
		return "", err
	}
	hosts, err := runtime.collectMerchantStartupClosure(ctx, id, p)
	if err != nil {
		return "", err
	}
	b := &productionMerchantStartupBaseline{Kind: merchantStartupBaselineKind, Provider: p, RequiredCapability: hosts[0].RequiredCapability, Role: hosts[0].Role, StatusSHA256: hosts[0].StatusSHA256, Closure: productionMerchantStartupClosure{Format: 1, DeploymentID: id, ProviderSHA256: p.PayloadSHA256, Hosts: hosts}}
	if strings.HasPrefix(hosts[0].GateBefore, "CONFIRMED_BASELINE:") {
		b.PredecessorSHA256 = strings.TrimPrefix(hosts[0].GateBefore, "CONFIRMED_BASELINE:")
	}
	if successor != (b.PredecessorSHA256 != "") {
		return "", errors.New("initial seal and explicit confirmed successor rebind are separate authorities")
	}
	if err := validateMerchantStartupBaseline(b); err != nil {
		return "", err
	}
	// Reobserve after all verifiers, before immutable output. No origin can
	// disappear or change its startup/DB/admission generation during sealing.
	again, err := runtime.collectMerchantStartupClosure(ctx, id, p)
	if err != nil {
		return "", err
	}
	a, _ := json.Marshal(hosts)
	z, _ := json.Marshal(again)
	if !bytes.Equal(a, z) {
		return "", errors.New("closed origin proof changed during baseline sealing")
	}
	if err := runtime.merchantStorePrivateDirectory(filepath.Join(root, "state"), true); err != nil {
		return "", err
	}
	for _, h := range hosts {
		schema := h.Schema
		c := productionMerchantStoreCapsule{Format: 2, DeploymentID: id, ControllerPlanSHA256: merchantStartupAuthoritySHA(b), Root: root, Host: h.Host, Service: runtime.paths.Service, Binary: runtime.paths.InstalledBinary, ConfigDir: runtime.paths.ConfigDir, SchemaMode: productionSchemaModeVerifyExisting, ExistingSchemaContract: &schema, StartupPolicy: "per-start", Baseline: b}
		if err := validateMerchantStartupBaselineCapsule(c, runtime.paths); err != nil {
			return "", err
		}
		// Controller outputs are fixed new private files. The reviewed native
		// first-conversion owner copies unchanged bytes to each capsule.json.
		if err := runtime.startupBaselineNewFile(filepath.Join(root, "state", "sealed-"+h.Host+".json"), startupBaselineWire(c)); err != nil {
			return "", err
		}
	}
	return merchantStartupAuthoritySHA(b), nil
}

// Marshal through the wire projection so neither runtime candidate nor an
// invented retained provider can be introduced by generic struct encoding.
func startupBaselineWire(c productionMerchantStoreCapsule) json.RawMessage {
	raw, _ := canonicalMerchantStartupBaselineCapsule(c)
	return bytes.TrimSpace(raw)
}

func (runtime *productionRuntime) bindMerchantStartupBaseline(ctx context.Context, id string) (string, error) {
	root, err := runtime.startupBaselineRoot(id)
	if err != nil {
		return "", err
	}
	raw, err := runtime.readExistingSchemaSealedFile(filepath.Join(root, "capsule.json"), true)
	if err != nil {
		return "", err
	}
	digest := startupContentSHA256(raw)
	c, err := runtime.loadMerchantStoreCapsule(filepath.Join(root, "capsule.json"), digest)
	if err != nil || c.Format != 2 {
		return "", errors.New("baseline bind requires the canonical single-provider capsule")
	}
	h, err := runtime.captureMerchantStartupHost(ctx, id)
	if err != nil {
		return "", err
	}
	matched := false
	for _, expected := range c.Baseline.Closure.Hosts {
		if expected.Host == c.Host {
			left, _ := json.Marshal(h)
			right, _ := json.Marshal(expected)
			matched = bytes.Equal(left, right)
		}
	}
	if !matched {
		return "", errors.New("baseline bind current closed capture differs from immutable authority")
	}
	path := filepath.Join(root, "capsule.json")
	hook := merchantStorePortableHookBytes(runtime.paths.InstalledBinary, path, digest)
	dropIn := filepath.Join(runtime.paths.DropInDir, "90-merchant-startup-baseline.conf")
	if err := writeAtomicRegularFile(dropIn, hook, 0644); err != nil {
		return "", err
	}
	if _, err := runtime.runner.Run(ctx, productionCommand{Name: commandSystemctl, Args: []string{"daemon-reload"}, Timeout: 15 * time.Second}); err != nil {
		return "", err
	}
	loaded, err := runtime.loadedExistingSchemaUnit(ctx)
	if err != nil || loaded["MainPID"] != "0" || loaded["ActiveState"] != "inactive" {
		return "", errors.New("writer changed while binding the sealed startup hook")
	}
	if _, err := runtime.merchantStoreCapsuleStartup(ctx, c, digest, loaded); err != nil {
		return "", err
	}
	return digest, nil
}

type productionMerchantStartupSucceeded struct {
	Format        int                               `json:"format"`
	CapsuleSHA256 string                            `json:"capsule_sha256"`
	Owner         productionMerchantStoreFenceOwner `json:"owner"`
	PID           int                               `json:"pid"`
	InvocationID  string                            `json:"invocation_id"`
}

// Called only after the existing holder completed its same-session exact CAS.
// It grants no deletion permission; a missing completion receipt blocks confirm.
func (runtime *productionRuntime) recordMerchantStartupSucceeded(ctx context.Context, c productionMerchantStoreCapsule, digest string, owner productionMerchantStoreFenceOwner) error {
	if c.Format != 2 {
		return nil
	}
	state, err := runtime.billingUnitState(ctx, c.Service)
	pid, parseErr := strconv.Atoi(state["MainPID"])
	if err != nil || parseErr != nil || pid <= 1 || state["ActiveState"] != "active" || state["SubState"] != "running" || state["InvocationID"] != owner.StartInvocationID || owner.Purpose != "start" {
		return errors.New("baseline completion lost actual running generation after CAS")
	}
	return runtime.startupBaselineNewFile(filepath.Join(c.Root, "state", "start-"+owner.StartInvocationID, "startup-succeeded.json"), productionMerchantStartupSucceeded{Format: 1, CapsuleSHA256: digest, Owner: owner, PID: pid, InvocationID: state["InvocationID"]})
}

func validateMerchantStartupCompletion(c productionMerchantStoreCapsule, digest string, state map[string]string, succeeded productionMerchantStartupSucceeded) error {
	o := succeeded.Owner
	w := c.Writer
	if w == nil || succeeded.Format != 1 || succeeded.CapsuleSHA256 != digest || succeeded.InvocationID != state["InvocationID"] || strconv.Itoa(succeeded.PID) != state["MainPID"] || succeeded.PID <= 1 ||
		validateMerchantStoreFenceOwner(o) != nil || o.Purpose != "start" || o.Host != c.Host || o.DeploymentID != c.DeploymentID || o.StartInvocationID != state["InvocationID"] ||
		o.PlanSHA256 != digest || o.ContractSHA256 != merchantStoreFenceContractSHA(w) || o.ProviderSHA256 != c.Candidate.PayloadSHA256 ||
		o.SystemIdentifier != w.SystemIdentifier || o.Database != w.Database || o.DatabaseOID != w.DatabaseOID || o.Schema != w.Schema || o.SchemaOID != w.SchemaOID || o.Role != w.Role {
		return errors.New("startup completion lacks this invocation's exact successful holder/CAS identity")
	}
	return nil
}

func (runtime *productionRuntime) confirmMerchantStartupBaseline(ctx context.Context, id string) (string, error) {
	root, err := runtime.startupBaselineRoot(id)
	if err != nil {
		return "", err
	}
	raw, err := runtime.readExistingSchemaSealedFile(filepath.Join(root, "capsule.json"), true)
	if err != nil {
		return "", err
	}
	digest := startupContentSHA256(raw)
	c, err := runtime.loadMerchantStoreCapsule(filepath.Join(root, "capsule.json"), digest)
	if err != nil || c.Format != 2 {
		return "", errors.New("baseline confirm requires single-provider startup authority")
	}
	if err := runtime.verifyPortableRunningWriter(ctx, c, digest, "", false); err != nil {
		return "", err
	}
	state, err := runtime.billingUnitState(ctx, c.Service)
	if err != nil {
		return "", err
	}
	var succeeded productionMerchantStartupSucceeded
	if _, err := runtime.startupBaselineRead(filepath.Join(root, "state", "start-"+state["InvocationID"], "startup-succeeded.json"), &succeeded); err != nil {
		return "", err
	}
	if err := validateMerchantStartupCompletion(c, digest, state, succeeded); err != nil {
		return "", err
	}
	loaded, err := runtime.loadedExistingSchemaUnit(ctx)
	if err != nil {
		return "", err
	}
	values, err := runtime.merchantStoreCapsuleStartup(ctx, c, digest, loaded)
	if err != nil {
		return "", err
	}
	lease, err := acquireMerchantStartupBaselineFence(ctx, values, c.Baseline, c.Host)
	if err != nil {
		return "", err
	}
	defer lease.Close()
	if err := lease.requireNoDurableOwner(ctx); err != nil {
		return "", err
	}
	admission := ""
	for _, h := range c.Baseline.Closure.Hosts {
		if h.Host == c.Host {
			admission = h.AdmissionSHA256
		}
	}
	if _, _, _, err := runtime.startupBaselineAdmission(ctx, id, admission); err != nil {
		return "", err
	}
	confirmation := productionMerchantStartupConfirmation{Format: 1, DeploymentID: id, Host: c.Host, CapsuleSHA256: digest, AuthoritySHA256: c.ControllerPlanSHA256, PID: succeeded.PID, InvocationID: succeeded.InvocationID, ProviderSHA256: c.Candidate.PayloadSHA256}
	if err := runtime.startupBaselineNewFile(filepath.Join(root, "state", "baseline-confirmed.json"), confirmation); err != nil {
		return "", err
	}
	return digest, nil
}

// Confirmation can be reobserved after an ordinary service retry. The receipt
// remains historical; the current generation must separately pass the same
// installed/running provider, exact status/schema and successful holder proof.
func (runtime *productionRuntime) captureMerchantStartupConfirmed(ctx context.Context, id string) (productionMerchantStartupConfirmation, error) {
	var result productionMerchantStartupConfirmation
	c, digest, err := runtime.startupBaselineConfirmed(id)
	if err != nil {
		return result, err
	}
	if err := runtime.verifyPortableRunningWriter(ctx, c, digest, "", false); err != nil {
		return result, err
	}
	state, err := runtime.billingUnitState(ctx, c.Service)
	if err != nil {
		return result, err
	}
	var succeeded productionMerchantStartupSucceeded
	if _, err := runtime.startupBaselineRead(filepath.Join(c.Root, "state", "start-"+state["InvocationID"], "startup-succeeded.json"), &succeeded); err != nil {
		return result, err
	}
	if err := validateMerchantStartupCompletion(c, digest, state, succeeded); err != nil {
		return result, err
	}
	loaded, err := runtime.loadedExistingSchemaUnit(ctx)
	if err != nil {
		return result, err
	}
	values, err := runtime.merchantStoreCapsuleStartup(ctx, c, digest, loaded)
	if err != nil {
		return result, err
	}
	lease, err := acquireMerchantStartupBaselineFence(ctx, values, c.Baseline, c.Host)
	if err != nil {
		return result, err
	}
	defer lease.Close()
	if err := lease.requireNoDurableOwner(ctx); err != nil {
		return result, err
	}
	pid, _ := strconv.Atoi(state["MainPID"])
	return productionMerchantStartupConfirmation{Format: 1, DeploymentID: id, Host: c.Host, CapsuleSHA256: digest, AuthoritySHA256: c.ControllerPlanSHA256, PID: pid, InvocationID: state["InvocationID"], ProviderSHA256: c.Candidate.PayloadSHA256}, nil
}

func (runtime *productionRuntime) reopenMerchantStartupAdmission(ctx context.Context, id string) (result string, returnErr error) {
	c, digest, err := runtime.startupBaselineConfirmed(id)
	if err != nil {
		return "", err
	}
	loaded, err := runtime.loadedExistingSchemaUnit(ctx)
	if err != nil {
		return "", err
	}
	values, err := runtime.merchantStoreCapsuleStartup(ctx, c, digest, loaded)
	if err != nil {
		return "", err
	}
	// Keep one actual physical shared session across ALL remote generation
	// checks and the local nginx mutation. Returning a short-lived capture
	// receipt is not authority to open after an intervening floor activation.
	lease, err := acquireMerchantStartupBaselineFence(ctx, values, c.Baseline, c.Host)
	if err != nil {
		return "", err
	}
	defer lease.Close()
	if err := lease.requireNoDurableOwner(ctx); err != nil {
		return "", err
	}
	release := productionReleaseRuntime{runner: runtime.runner, now: runtime.now}
	for _, origin := range merchantStartupOrigins {
		if err := release.assertRemoteHost(ctx, origin.Alias, origin.Host); err != nil {
			return "", err
		}
		out, err := release.ssh(ctx, origin.Alias, 20*time.Second, "sudo", "-n", "/usr/bin/sha256sum", runtime.paths.InstalledBinary)
		parts := strings.Fields(string(out))
		if err != nil || len(parts) != 2 || parts[0] != c.Candidate.PayloadSHA256 || parts[1] != runtime.paths.InstalledBinary {
			return "", errors.New("reopen origin provider differs")
		}
		raw, err := release.ssh(ctx, origin.Alias, 3*time.Minute, "sudo", "-n", runtime.paths.InstalledBinary, "operator", "production", "writer-capsule", "baseline-confirmed-capture", "--id", id)
		var receipt productionMerchantStartupConfirmation
		if err != nil || !merchantStoreUniqueJSON(raw) {
			return "", errors.New("reopen requires both actual confirmed origins")
		}
		d := json.NewDecoder(bytes.NewReader(raw))
		d.DisallowUnknownFields()
		if d.Decode(&receipt) != nil || d.Decode(&struct{}{}) != io.EOF {
			return "", errors.New("confirmed origin receipt invalid")
		}
		canonical, _ := merchantStartupJSON(receipt)
		if !bytes.Equal(canonical, raw) || receipt.Format != 1 || receipt.Host != origin.Host || receipt.DeploymentID != id || receipt.AuthoritySHA256 != c.ControllerPlanSHA256 || receipt.ProviderSHA256 != c.Candidate.PayloadSHA256 || receipt.PID <= 1 || !existingSchemaInvocationPattern.MatchString(receipt.InvocationID) {
			return "", errors.New("confirmed origin current authority differs")
		}
	}
	var close productionMerchantStartupClose
	if _, err := runtime.startupBaselineRead(filepath.Join(c.Root, "state", "baseline-close.json"), &close); err != nil {
		return "", err
	}
	original, err := runtime.readExistingSchemaSealedFile(filepath.Join(c.Root, "state", "admission-original.conf"), true)
	if err != nil || startupContentSHA256(original) != close.OriginalSHA256 {
		return "", errors.New("native original admission backup differs")
	}
	if _, _, _, err := runtime.startupBaselineAdmission(ctx, id, close.AdmissionSHA256); err != nil {
		return "", err
	}
	barrier, err := runtime.readExistingSchemaSealedFile(filepath.Join(runtime.paths.NginxRoot, "lmm-api-locations.conf"), false)
	if err != nil || startupContentSHA256(barrier) != close.AdmissionSHA256 {
		return "", errors.New("native closed admission changed before reopen")
	}
	if err := lease.requireNoDurableOwner(ctx); err != nil {
		return "", err
	}
	writeStarted := false
	defer func() {
		if returnErr == nil || !writeStarted {
			return
		}
		// Closing admission is safe even after a physical session fails. Never
		// leave a partially reopened origin on a failed readiness/floor check.
		restoreCtx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()
		restoreErr := runtime.installAdmissionBarrier(restoreCtx, barrier)
		if restoreErr == nil {
			restoreErr = runtime.awaitAdmissionDrain(restoreCtx, func(ctx context.Context) bool { return runtime.probeMerchantStartupAdmission(ctx, id) == nil })
		}
		if restoreErr == nil {
			_, _, _, restoreErr = runtime.startupBaselineAdmission(restoreCtx, id, close.AdmissionSHA256)
		}
		if restoreErr != nil {
			returnErr = errors.New("baseline reopen failed and canonical closed admission restoration was not proved")
		} else {
			returnErr = errors.New("baseline reopen failed; canonical admission was restored closed")
		}
	}()
	// The only reopened bytes are this owner's exact protected original. No
	// financial handoff or caller supplied nginx pathname participates.
	writeStarted = true
	if err := runtime.installAdmissionBarrier(ctx, original); err != nil {
		return "", err
	}
	if err := runtime.verifyPortableRunningWriter(ctx, c, digest, "", false); err != nil {
		return "", err
	}
	if err := lease.requireNoDurableOwner(ctx); err != nil {
		return "", err
	}
	return digest, nil
}

func (runtime *productionRuntime) runMerchantStartupBaseline(ctx context.Context, action, id, repo, predecessor string, stdout io.Writer) error {
	if action != "baseline-close" && predecessor != "" {
		return errors.New("predecessor applies only to an actual native close")
	}
	if action != "baseline-close" && action != "baseline-seal" && action != "baseline-rebind" && repo != "" {
		return errors.New("source checkout applies only to official close/seal verification")
	}
	var digest string
	var err error
	switch action {
	case "baseline-close":
		digest, err = runtime.closeMerchantStartupAdmission(ctx, id, repo, predecessor)
	case "baseline-capture":
		var capture productionMerchantStartupHostCapture
		capture, err = runtime.captureMerchantStartupHost(ctx, id)
		if err == nil {
			raw, _ := merchantStartupJSON(capture)
			_, err = stdout.Write(raw)
		}
		return err
	case "baseline-seal":
		digest, err = runtime.sealMerchantStartupBaseline(ctx, id, repo, false)
	case "baseline-rebind":
		digest, err = runtime.sealMerchantStartupBaseline(ctx, id, repo, true)
	case "baseline-bind":
		digest, err = runtime.bindMerchantStartupBaseline(ctx, id)
	case "baseline-confirm":
		digest, err = runtime.confirmMerchantStartupBaseline(ctx, id)
	case "baseline-confirmed-capture":
		var receipt productionMerchantStartupConfirmation
		receipt, err = runtime.captureMerchantStartupConfirmed(ctx, id)
		if err == nil {
			raw, _ := merchantStartupJSON(receipt)
			_, err = stdout.Write(raw)
		}
		return err
	case "baseline-reopen":
		digest, err = runtime.reopenMerchantStartupAdmission(ctx, id)
	default:
		return errors.New("unknown startup baseline action")
	}
	if err == nil {
		_, err = fmt.Fprintf(stdout, "startup_baseline_sha256=%s\n", digest)
	}
	return err
}
