-- Fresh installation only. The installer supplies the transaction and contract hash.
CREATE SCHEMA core_meta;
CREATE TABLE core_meta.schema_contract (
    singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
    version INTEGER NOT NULL CHECK (version > 0),
    fingerprint BYTEA NOT NULL CHECK (octet_length(fingerprint) = 32),
    installed_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

CREATE SCHEMA core_identity;
CREATE TABLE core_identity.accounts (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL CHECK (kind IN ('personal', 'team')),
    service_level SMALLINT NOT NULL DEFAULT 0 CHECK (service_level BETWEEN 0 AND 4),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (id, kind)
);
CREATE TABLE core_identity.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    personal_account_id BIGINT NOT NULL UNIQUE,
    account_kind TEXT GENERATED ALWAYS AS ('personal'::text) STORED,
    platform_role TEXT NOT NULL DEFAULT 'user'
        CHECK (platform_role IN ('user', 'admin', 'superadmin')),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    auth_version BIGINT NOT NULL DEFAULT 1 CHECK (auth_version > 0),
    FOREIGN KEY (personal_account_id, account_kind) REFERENCES core_identity.accounts(id, kind)
);
CREATE TABLE core_identity.teams (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL UNIQUE,
    account_kind TEXT GENERATED ALWAYS AS ('team'::text) STORED,
    owner_user_id BIGINT NOT NULL REFERENCES core_identity.users(id),
    created_by_user_id BIGINT NOT NULL UNIQUE REFERENCES core_identity.users(id),
    name TEXT NOT NULL DEFAULT 'Team' CHECK (length(btrim(name)) BETWEEN 1 AND 100),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0),
    FOREIGN KEY (account_id, account_kind) REFERENCES core_identity.accounts(id, kind)
);
CREATE INDEX teams_owner ON core_identity.teams(owner_user_id,id);
-- This row is an authorization generation, not a budget counter. Never delete it
-- on removal, and never reset financial usage when the generation changes.
CREATE TABLE core_identity.memberships (
    team_id BIGINT NOT NULL REFERENCES core_identity.teams(id),
    user_id BIGINT NOT NULL REFERENCES core_identity.users(id),
    role TEXT NOT NULL CHECK (role IN ('admin', 'member')),
    can_spend BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0),
    PRIMARY KEY (team_id, user_id)
);
CREATE INDEX memberships_user ON core_identity.memberships(user_id, team_id);
CREATE TABLE core_identity.credentials (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    digest BYTEA NOT NULL UNIQUE CHECK (octet_length(digest) = 32),
    kind TEXT NOT NULL CHECK (kind IN ('session', 'api_key')),
    user_id BIGINT NOT NULL REFERENCES core_identity.users(id),
    user_version BIGINT NOT NULL CHECK (user_version > 0),
    owner_account_id BIGINT NOT NULL REFERENCES core_identity.accounts(id),
    personal_billing_preference TEXT
        CHECK (personal_billing_preference IN ('subscription_first', 'wallet_first', 'subscription_only', 'wallet_only')),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    session_started_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    CHECK (kind = 'api_key' OR personal_billing_preference IS NULL)
);
CREATE INDEX credentials_user ON core_identity.credentials(user_id, id);
CREATE INDEX credentials_owner ON core_identity.credentials(owner_account_id, id);
CREATE TABLE core_identity.key_funding_rules (
    credential_id BIGINT NOT NULL REFERENCES core_identity.credentials(id),
    position SMALLINT NOT NULL CHECK (position BETWEEN 0 AND 15),
    payer_account_id BIGINT NOT NULL REFERENCES core_identity.accounts(id),
    PRIMARY KEY (credential_id, position),
    UNIQUE (credential_id, payer_account_id)
);
CREATE TABLE core_identity.credential_grants (
    credential_id BIGINT NOT NULL REFERENCES core_identity.credentials(id),
    team_id BIGINT NOT NULL REFERENCES core_identity.teams(id),
    team_version BIGINT NOT NULL CHECK (team_version > 0),
    membership_version BIGINT NOT NULL CHECK (membership_version >= 0),
    PRIMARY KEY (credential_id, team_id)
);
CREATE TABLE core_identity.invites (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    digest BYTEA NOT NULL UNIQUE CHECK (octet_length(digest) = 32),
    team_id BIGINT NOT NULL REFERENCES core_identity.teams(id),
    team_version BIGINT NOT NULL CHECK (team_version > 0),
    recipient_user_id BIGINT NOT NULL REFERENCES core_identity.users(id),
    recipient_version BIGINT NOT NULL CHECK (recipient_version >= 0),
    inviter_credential_id BIGINT NOT NULL REFERENCES core_identity.credentials(id),
    inviter_membership_version BIGINT NOT NULL CHECK (inviter_membership_version >= 0),
    role TEXT NOT NULL CHECK (role IN ('admin', 'member')),
    can_spend BOOLEAN NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    accepted_at TIMESTAMPTZ,
    rejected_at TIMESTAMPTZ,
    withdrawn_at TIMESTAMPTZ,
    CHECK (num_nonnulls(accepted_at, rejected_at, withdrawn_at) <= 1)
);
CREATE INDEX invites_recipient ON core_identity.invites(recipient_user_id, id)
    WHERE accepted_at IS NULL AND rejected_at IS NULL AND withdrawn_at IS NULL;
CREATE TABLE core_identity.audit (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT NOT NULL REFERENCES core_identity.users(id),
    credential_id BIGINT REFERENCES core_identity.credentials(id),
    action TEXT NOT NULL CHECK (length(action) BETWEEN 1 AND 128),
    target JSONB NOT NULL CHECK (jsonb_typeof(target) = 'object'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX audit_actor ON core_identity.audit(actor_user_id, id);

-- Account-local subscription/wallet order is not a second ordered list of payers.
-- This is policy only, not a balance table or a completed billing engine.
CREATE SCHEMA core_billing;
CREATE TABLE core_billing.account_policies (
    account_id BIGINT PRIMARY KEY REFERENCES core_identity.accounts(id),
    preference TEXT NOT NULL DEFAULT 'wallet_only'
        CHECK (preference IN ('subscription_first', 'wallet_first', 'subscription_only', 'wallet_only')),
    revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0)
);

-- Enforce ownership at the storage boundary. Current permissions are still
-- checked by Rust on every request; these constraints do not grant authority.
CREATE FUNCTION core_identity.check_credential_owner() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
DECLARE owner_kind TEXT; personal_id BIGINT;
BEGIN
    IF TG_OP = 'UPDATE' AND (NEW.user_id, NEW.owner_account_id, NEW.kind, NEW.digest, NEW.user_version, NEW.session_started_at, NEW.created_at)
        IS DISTINCT FROM (OLD.user_id, OLD.owner_account_id, OLD.kind, OLD.digest, OLD.user_version, OLD.session_started_at, OLD.created_at) THEN
        RAISE EXCEPTION 'credential identity is immutable' USING ERRCODE = '23514';
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.revoked_at IS NOT NULL AND NEW.revoked_at IS DISTINCT FROM OLD.revoked_at THEN
        RAISE EXCEPTION 'revocation is permanent' USING ERRCODE = '23514';
    END IF;
    IF TG_OP = 'UPDATE' AND NEW.expires_at > OLD.expires_at THEN
        RAISE EXCEPTION 'issue a new credential instead of extending expiry' USING ERRCODE = '23514';
    END IF;
    SELECT kind INTO STRICT owner_kind FROM core_identity.accounts WHERE id = NEW.owner_account_id;
    SELECT personal_account_id INTO STRICT personal_id FROM core_identity.users WHERE id = NEW.user_id;
    IF (owner_kind = 'personal' AND NEW.owner_account_id <> personal_id)
        OR (NEW.kind = 'session' AND NEW.owner_account_id <> personal_id)
        OR (owner_kind = 'team' AND NEW.personal_billing_preference IS NOT NULL) THEN
        RAISE EXCEPTION 'invalid credential owner' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER credential_owner BEFORE INSERT OR UPDATE ON core_identity.credentials
    FOR EACH ROW EXECUTE FUNCTION core_identity.check_credential_owner();

CREATE FUNCTION core_identity.check_funding_rule() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
DECLARE key_kind TEXT; owner_id BIGINT; owner_kind TEXT; payer_kind TEXT;
BEGIN
    SELECT c.kind, c.owner_account_id, a.kind INTO STRICT key_kind, owner_id, owner_kind
        FROM core_identity.credentials c JOIN core_identity.accounts a ON a.id = c.owner_account_id
        WHERE c.id = NEW.credential_id;
    SELECT kind INTO STRICT payer_kind FROM core_identity.accounts WHERE id = NEW.payer_account_id;
    IF key_kind <> 'api_key'
        OR (owner_kind = 'team' AND (NEW.position <> 0 OR NEW.payer_account_id <> owner_id))
        OR (payer_kind = 'personal' AND NEW.payer_account_id <> owner_id) THEN
        RAISE EXCEPTION 'invalid funding rule' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER funding_rule BEFORE INSERT OR UPDATE ON core_identity.key_funding_rules
    FOR EACH ROW EXECUTE FUNCTION core_identity.check_funding_rule();

-- Native login names are not email identities. OAuth never links by email.
CREATE TABLE core_identity.password_logins (
    login_name TEXT PRIMARY KEY CHECK (login_name ~ '^[a-z0-9][a-z0-9_.-]{2,63}$'),
    user_id BIGINT NOT NULL UNIQUE REFERENCES core_identity.users(id),
    password_hash TEXT NOT NULL CHECK (length(password_hash) BETWEEN 40 AND 512),
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE core_identity.oauth_identities (
    issuer TEXT NOT NULL CHECK (issuer = 'https://accounts.google.com'),
    subject TEXT NOT NULL CHECK (length(subject) BETWEEN 1 AND 255),
    user_id BIGINT NOT NULL REFERENCES core_identity.users(id),
    PRIMARY KEY (issuer, subject),
    UNIQUE (user_id, issuer)
);
CREATE TABLE core_identity.oauth_flows (
    state_digest BYTEA PRIMARY KEY CHECK (octet_length(state_digest) = 32),
    binding_digest BYTEA NOT NULL CHECK (octet_length(binding_digest) = 32),
    nonce_digest BYTEA NOT NULL CHECK (octet_length(nonce_digest) = 32),
    -- The verifier is required for the one-time code exchange, then deleted.
    pkce_verifier TEXT NOT NULL CHECK (length(pkce_verifier) BETWEEN 43 AND 128),
    expires_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp() + interval '10 minutes'
);
CREATE INDEX oauth_flows_expiry ON core_identity.oauth_flows(expires_at);
CREATE TABLE core_identity.auth_attempts (
    bucket BYTEA PRIMARY KEY CHECK (octet_length(bucket) = 32),
    started_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    attempts INTEGER NOT NULL CHECK (attempts BETWEEN 1 AND 10001)
);
CREATE INDEX auth_attempts_expiry ON core_identity.auth_attempts(started_at);

-- These are fresh-install invariants, not a migration or a second authority.
CREATE FUNCTION core_identity.protect_team() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'close teams instead of deleting their ownership history' USING ERRCODE = '23514';
    END IF;
    IF (NEW.id,NEW.account_id,NEW.created_by_user_id) IS DISTINCT FROM
       (OLD.id,OLD.account_id,OLD.created_by_user_id)
       OR NEW.version < OLD.version
       OR (NOT OLD.active AND NEW.active)
       OR ((NEW.owner_user_id,NEW.active,NEW.name) IS DISTINCT FROM
           (OLD.owner_user_id,OLD.active,OLD.name) AND NEW.version <= OLD.version) THEN
        RAISE EXCEPTION 'invalid team generation or immutable creator' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER protect_team BEFORE UPDATE OR DELETE ON core_identity.teams
    FOR EACH ROW EXECUTE FUNCTION core_identity.protect_team();
CREATE FUNCTION core_identity.protect_membership() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'membership generations cannot be deleted' USING ERRCODE = '23514';
    END IF;
    IF (NEW.team_id,NEW.user_id) IS DISTINCT FROM (OLD.team_id,OLD.user_id)
       OR NEW.version < OLD.version
       OR ((NEW.role,NEW.can_spend,NEW.active) IS DISTINCT FROM
           (OLD.role,OLD.can_spend,OLD.active) AND NEW.version <= OLD.version) THEN
        RAISE EXCEPTION 'invalid membership generation' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER protect_membership BEFORE UPDATE OR DELETE ON core_identity.memberships
    FOR EACH ROW EXECUTE FUNCTION core_identity.protect_membership();
CREATE FUNCTION core_identity.check_owner_membership() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
DECLARE tid BIGINT;
BEGIN
    IF TG_TABLE_NAME = 'teams' THEN tid := NEW.id; ELSE tid := NEW.team_id; END IF;
    IF EXISTS (SELECT 1 FROM core_identity.teams t JOIN core_identity.memberships m
        ON m.team_id=t.id AND m.user_id=t.owner_user_id WHERE t.id=tid AND m.active) THEN
        RAISE EXCEPTION 'owner cannot also have an active membership' USING ERRCODE = '23514';
    END IF;
    RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER team_owner_membership AFTER INSERT OR UPDATE ON core_identity.teams
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION core_identity.check_owner_membership();
CREATE CONSTRAINT TRIGGER member_owner_membership AFTER INSERT OR UPDATE ON core_identity.memberships
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION core_identity.check_owner_membership();
CREATE FUNCTION core_identity.protect_invite_terminal() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
BEGIN
    IF num_nonnulls(OLD.accepted_at,OLD.rejected_at,OLD.withdrawn_at) > 0 AND
       (NEW.accepted_at,NEW.rejected_at,NEW.withdrawn_at) IS DISTINCT FROM
       (OLD.accepted_at,OLD.rejected_at,OLD.withdrawn_at) THEN
        RAISE EXCEPTION 'completed invitations cannot be reopened' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER invite_terminal BEFORE UPDATE ON core_identity.invites
    FOR EACH ROW EXECUTE FUNCTION core_identity.protect_invite_terminal();

-- Account identity and authorization generations cannot be rewound.
CREATE FUNCTION core_identity.protect_user() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
BEGIN
    IF (NEW.id, NEW.personal_account_id) IS DISTINCT FROM (OLD.id, OLD.personal_account_id)
        OR NEW.auth_version < OLD.auth_version THEN
        RAISE EXCEPTION 'invalid user identity or authorization generation' USING ERRCODE = '23514';
    END IF;
    IF (NEW.active, NEW.platform_role) IS DISTINCT FROM (OLD.active, OLD.platform_role)
        AND NEW.auth_version = OLD.auth_version THEN
        NEW.auth_version := OLD.auth_version + 1;
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER user_identity BEFORE UPDATE ON core_identity.users
    FOR EACH ROW EXECUTE FUNCTION core_identity.protect_user();
