/* Copyright (C) 2026 LIghtJUNction; SPDX-License-Identifier: AGPL-3.0-or-later */
/** New copy is centralized for the coordinated Luna translation pass. */
export const MARKET_AI_REVIEW_COPY = {
  title: 'Market AI first review',
  routing: 'Configure the shared content review group and model',
  coverage:
    'Only public listing text is checked. Images and linked pages are not checked.',
  empty: 'No AI first review recorded for this submission',
  loadError: 'Failed to load AI review',
  overridden: 'AI decision superseded by human review',
  toolMode: 'Tool market AI review mode',
  productMode: 'Product market AI review mode',
  off: 'Off',
  assist: 'Assist: suggest for human review',
  auto: 'Automatic: apply the AI decision',
  scope:
    'AI checks submitted content only. Assist mode requires human confirmation. Failures leave submissions pending review.',
  limits:
    'This does not verify product quality, tool behavior, or the authenticity of links.',
  result: 'AI first review',
  queued: 'AI review queued',
  running: 'AI review in progress',
  succeeded: 'AI content check finished',
  failed: 'AI review failed; awaiting human review',
  cancelled: 'AI review cancelled',
  stale: 'AI result belongs to an earlier submission',
  pending: 'No AI decision recorded',
  approve: 'AI suggests approval',
  reject: 'AI suggests rejection',
  manual: 'Awaiting human confirmation',
  applied: 'AI decision applied',
  notApplied: 'AI decision not applied',
  categories: 'Detected content categories',
  noCategories: 'No content categories flagged',
  error: 'AI review error',
  checkedAt: 'Content check time',
  unknown: 'Unknown AI review state',
  disabledError: 'AI first review is disabled',
  staleError: 'The submission changed before AI review finished',
  resubmittedError: 'A newer submission replaced this AI review',
  overriddenError: 'A human review replaced this AI review',
  largeError: 'Submitted text exceeds the AI review limit',
  nonpublicError: 'AI first review covers public listings only',
  validationError: 'Tool connection and definitions still require validation',
  queueError: 'AI review queue is full; awaiting human review',
  leaseError: 'AI review timed out; awaiting human review',
  unavailableError: 'AI review is unavailable; awaiting human review',
  settingsError: 'Shared AI review settings are unavailable',
  routeError: 'The shared AI review route is unavailable',
  providerError: 'The AI review provider is unavailable',
  providerRejectedError: 'The AI review provider rejected the request',
  responseError: 'The AI review response could not be validated',
  traceError: 'The AI review trace is unavailable',
} as const

export const MARKET_AI_REVIEW_ERRORS: Record<string, string> = {
  market_review_disabled: MARKET_AI_REVIEW_COPY.disabledError,
  market_review_stale: MARKET_AI_REVIEW_COPY.staleError,
  market_review_resubmitted: MARKET_AI_REVIEW_COPY.resubmittedError,
  market_review_manual_override: MARKET_AI_REVIEW_COPY.overriddenError,
  market_review_input_too_large: MARKET_AI_REVIEW_COPY.largeError,
  market_review_nonpublic_listing: MARKET_AI_REVIEW_COPY.nonpublicError,
  market_review_validation_required: MARKET_AI_REVIEW_COPY.validationError,
  market_review_queue_full: MARKET_AI_REVIEW_COPY.queueError,
  market_review_lease_expired: MARKET_AI_REVIEW_COPY.leaseError,
  market_review_unavailable: MARKET_AI_REVIEW_COPY.unavailableError,
  moderation_settings_unavailable: MARKET_AI_REVIEW_COPY.settingsError,
  moderation_route_unavailable: MARKET_AI_REVIEW_COPY.routeError,
  moderation_provider_unavailable: MARKET_AI_REVIEW_COPY.providerError,
  moderation_provider_rejected: MARKET_AI_REVIEW_COPY.providerRejectedError,
  moderation_response_invalid: MARKET_AI_REVIEW_COPY.responseError,
  moderation_trace_unavailable: MARKET_AI_REVIEW_COPY.traceError,
}
