use lmm_db_migrate::forward_schema::verify_subscription_payment_refund_schema;
use postgres::{Client, NoTls, Transaction};

const MIGRATION_SQL: &str =
    include_str!("../../../migrations/0009_subscription_payment_refunds.sql");

fn prepare_schema(transaction: &mut Transaction<'_>, schema: &str) {
    let sql = MIGRATION_SQL.replace("__LMM_APP_SCHEMA__", &format!("\"{schema}\""));
    transaction
        .batch_execute(&format!("CREATE SCHEMA {schema}; {sql}"))
        .expect("apply contract-9 migration");
    verify_subscription_payment_refund_schema(transaction, schema)
        .expect("valid contract-9 schema");
}

#[test]
#[ignore = "requires native PostgreSQL and LMM_TEST_DATABASE_URL"]
fn contract_nine_preserves_refund_bindings_and_ledger_uniqueness() {
    let database_url = std::env::var("LMM_TEST_DATABASE_URL").expect("test database URL");
    let schema = format!("lmm_contract_nine_refunds_{}", std::process::id());
    let mut client = Client::connect(&database_url, NoTls).expect("connect to test PostgreSQL");
    let mut transaction = client.transaction().expect("start test transaction");
    prepare_schema(&mut transaction, &schema);
    let sql = MIGRATION_SQL.replace("__LMM_APP_SCHEMA__", &format!("\"{schema}\""));
    transaction
        .batch_execute(&sql)
        .expect("contract-9 migration is idempotent");
    verify_subscription_payment_refund_schema(&mut transaction, &schema)
        .expect("valid schema after repeated migration");
    let count = format!("SELECT COUNT(*) FROM {schema}.subscription_payment_refunds");
    assert_eq!(
        transaction.query_one(&count, &[]).unwrap().get::<_, i64>(0),
        0,
        "the expansion must not invent historical refunds"
    );

    let insert = format!(
        "INSERT INTO {schema}.subscription_payment_refunds \
         (subscription_order_id,subscription_payment_event_id,payment_provider,provider_event_id,\
          currency,amount_micros,quota_revoked,finance_ledger_entry_id,created_time) \
         VALUES ($1,$2,$3,$4,'USD',1000000,500000,$5,1788825601) ON CONFLICT DO NOTHING"
    );
    let order_id = 4_000_000_001_i64;
    let payment_id = 5_000_000_001_i64;
    let ledger_id = 6_000_000_001_i64;
    let next_order_id = order_id + 1;
    let next_payment_id = payment_id + 1;
    let next_ledger_id = ledger_id + 1;
    assert_eq!(
        transaction
            .execute(
                &insert,
                &[
                    &order_id,
                    &payment_id,
                    &"waffo_pancake",
                    &"refund-1",
                    &ledger_id
                ],
            )
            .unwrap(),
        1
    );
    let select = format!(
        "SELECT id,row_to_json(refund)::TEXT FROM {schema}.subscription_payment_refunds AS refund \
         WHERE payment_provider='waffo_pancake' AND provider_event_id='refund-1'"
    );
    let original = transaction.query_one(&select, &[]).unwrap();
    assert_eq!(original.get::<_, i64>(0), 1, "id is generated by BIGSERIAL");
    let original_refund: String = original.get(1);
    assert_eq!(
        transaction
            .execute(
                &insert,
                &[
                    &order_id,
                    &payment_id,
                    &"waffo_pancake",
                    &"refund-1",
                    &ledger_id
                ],
            )
            .unwrap(),
        0,
        "an exact replay cannot create a second refund"
    );
    assert_eq!(
        transaction
            .execute(
                &insert,
                &[
                    &next_order_id,
                    &next_payment_id,
                    &"waffo_pancake",
                    &"refund-1",
                    &next_ledger_id,
                ],
            )
            .unwrap(),
        0,
        "a provider refund cannot be rebound to another order, payment or ledger"
    );
    assert_eq!(
        transaction
            .execute(
                &insert,
                &[
                    &next_order_id,
                    &next_payment_id,
                    &"other_provider",
                    &"refund-other",
                    &ledger_id,
                ],
            )
            .unwrap(),
        0,
        "a finance debit cannot be claimed by another provider refund"
    );
    assert_eq!(
        transaction
            .execute(
                &insert,
                &[
                    &order_id,
                    &payment_id,
                    &"waffo_pancake",
                    &"refund-2",
                    &next_ledger_id,
                ],
            )
            .unwrap(),
        1,
        "one immutable payment may have multiple distinct partial refunds"
    );
    assert_eq!(
        transaction
            .execute(
                &insert,
                &[
                    &order_id,
                    &next_payment_id,
                    &"other_provider",
                    &"refund-1",
                    &(ledger_id + 2),
                ],
            )
            .unwrap(),
        1,
        "refund identity is provider-scoped; order/payment lookup indexes are not unique"
    );
    transaction
        .batch_execute(&sql)
        .expect("reapplying the migration preserves populated evidence");
    verify_subscription_payment_refund_schema(&mut transaction, &schema)
        .expect("valid populated contract-9 schema");
    assert_eq!(
        transaction
            .query_one(&select, &[])
            .unwrap()
            .get::<_, String>(1),
        original_refund,
        "replays and migration must preserve every field of the original refund"
    );
    assert_eq!(
        transaction.query_one(&count, &[]).unwrap().get::<_, i64>(0),
        3
    );
    transaction
        .rollback()
        .expect("roll back contract-9 refund test");
}

#[test]
#[ignore = "requires native PostgreSQL and LMM_TEST_DATABASE_URL"]
fn contract_nine_rejects_column_drift() {
    let database_url = std::env::var("LMM_TEST_DATABASE_URL").expect("test database URL");
    let schema = format!("lmm_contract_nine_columns_{}", std::process::id());
    let mut client = Client::connect(&database_url, NoTls).expect("connect to test PostgreSQL");
    let mut transaction = client.transaction().expect("start test transaction");
    prepare_schema(&mut transaction, &schema);
    let table = format!("{schema}.subscription_payment_refunds");

    for (column, altered_type, unexpected_default) in [
        ("subscription_order_id", "INTEGER", "0"),
        ("subscription_payment_event_id", "INTEGER", "0"),
        ("payment_provider", "VARCHAR(65)", "''"),
        ("provider_event_id", "VARCHAR(256)", "''"),
        ("currency", "VARCHAR(9)", "'USD'"),
        ("amount_micros", "NUMERIC", "0"),
        ("quota_revoked", "INTEGER", "0"),
        ("finance_ledger_entry_id", "INTEGER", "0"),
        ("created_time", "INTEGER", "0"),
    ] {
        for alteration in [
            format!("TYPE {altered_type}"),
            "DROP NOT NULL".to_owned(),
            format!("SET DEFAULT {unexpected_default}"),
        ] {
            let mutation = format!("ALTER TABLE {table} ALTER COLUMN {column} {alteration}");
            transaction.batch_execute("SAVEPOINT mutation").unwrap();
            transaction.batch_execute(&mutation).expect("mutate column");
            let error = verify_subscription_payment_refund_schema(&mut transaction, &schema)
                .expect_err("column type, nullability and default drift must fail verification");
            assert!(
                error
                    .to_string()
                    .contains("column/default contract mismatch"),
                "{mutation}: {error}"
            );
            transaction
                .batch_execute("ROLLBACK TO SAVEPOINT mutation; RELEASE SAVEPOINT mutation")
                .unwrap();
        }
    }
    for mutation in [
        format!("ALTER TABLE {table} ALTER COLUMN id TYPE NUMERIC"),
        format!("ALTER TABLE {table} ALTER COLUMN currency TYPE TEXT"),
        format!(
            "ALTER TABLE {table} DROP COLUMN currency; \
             ALTER TABLE {table} ADD COLUMN currency VARCHAR(8) NOT NULL"
        ),
        format!("ALTER TABLE {table} ADD COLUMN unexpected BIGINT NOT NULL"),
        format!("ALTER TABLE {table} DROP COLUMN created_time"),
        format!("ALTER TABLE {table} RENAME COLUMN created_time TO received_at"),
    ] {
        transaction.batch_execute("SAVEPOINT mutation").unwrap();
        transaction
            .batch_execute(&mutation)
            .expect("mutate column inventory");
        let error = verify_subscription_payment_refund_schema(&mut transaction, &schema)
            .expect_err("the exact ordered column inventory is required");
        assert!(
            error
                .to_string()
                .contains("column/default contract mismatch"),
            "{mutation}: {error}"
        );
        transaction
            .batch_execute("ROLLBACK TO SAVEPOINT mutation; RELEASE SAVEPOINT mutation")
            .unwrap();
    }
    verify_subscription_payment_refund_schema(&mut transaction, &schema)
        .expect("column mutations were rolled back");
    transaction
        .rollback()
        .expect("roll back contract-9 column test");
}

#[test]
#[ignore = "requires native PostgreSQL and LMM_TEST_DATABASE_URL"]
fn contract_nine_rejects_primary_key_sequence_and_foreign_key_drift() {
    let database_url = std::env::var("LMM_TEST_DATABASE_URL").expect("test database URL");
    let schema = format!("lmm_contract_nine_keys_{}", std::process::id());
    let mut client = Client::connect(&database_url, NoTls).expect("connect to test PostgreSQL");
    let mut transaction = client.transaction().expect("start test transaction");
    prepare_schema(&mut transaction, &schema);
    let table = format!("{schema}.subscription_payment_refunds");
    let sequence = format!("{schema}.subscription_payment_refunds_id_seq");

    for mutation in [
        format!("ALTER TABLE {table} ALTER COLUMN id DROP DEFAULT"),
        format!("ALTER TABLE {table} ALTER COLUMN id SET DEFAULT 0"),
        format!(
            "ALTER TABLE {table} ALTER COLUMN id SET DEFAULT nextval('{sequence}'::regclass) + 1"
        ),
        format!(
            "CREATE SEQUENCE {schema}.other_refund_id_seq; \
             ALTER TABLE {table} ALTER COLUMN id SET DEFAULT nextval('{schema}.other_refund_id_seq'::regclass)"
        ),
        format!("ALTER SEQUENCE {sequence} OWNED BY NONE"),
        format!("ALTER SEQUENCE {sequence} OWNED BY {table}.subscription_order_id"),
        format!("ALTER SEQUENCE {sequence} RENAME TO renamed_refund_id_seq"),
        format!("ALTER TABLE {table} DROP CONSTRAINT subscription_payment_refunds_pkey"),
        format!(
            "ALTER TABLE {table} DROP CONSTRAINT subscription_payment_refunds_pkey; \
             ALTER TABLE {table} ADD PRIMARY KEY (id,subscription_payment_event_id)"
        ),
        format!(
            "ALTER TABLE {table} DROP CONSTRAINT subscription_payment_refunds_pkey; \
             ALTER TABLE {table} ADD PRIMARY KEY (subscription_payment_event_id)"
        ),
        format!(
            "ALTER TABLE {table} DROP CONSTRAINT subscription_payment_refunds_pkey; \
             ALTER TABLE {table} ADD PRIMARY KEY (id) INCLUDE (subscription_payment_event_id)"
        ),
    ] {
        transaction.batch_execute("SAVEPOINT mutation").unwrap();
        transaction
            .batch_execute(&mutation)
            .expect("mutate primary key or serial");
        let error = verify_subscription_payment_refund_schema(&mut transaction, &schema)
            .expect_err("serial ownership, default expression and primary key must be exact");
        assert!(
            error.to_string().contains("primary key/sequence mismatch"),
            "{mutation}: {error}"
        );
        transaction
            .batch_execute("ROLLBACK TO SAVEPOINT mutation; RELEASE SAVEPOINT mutation")
            .unwrap();
    }
    transaction
        .batch_execute(&format!(
            "ALTER TABLE {table} ADD CONSTRAINT unexpected_refund_fkey \
             FOREIGN KEY (subscription_payment_event_id) REFERENCES {table}(id)"
        ))
        .expect("add unexpected foreign key");
    let error = verify_subscription_payment_refund_schema(&mut transaction, &schema)
        .expect_err("the GORM refund layout has no foreign keys");
    assert!(
        error.to_string().contains("foreign key mismatch"),
        "{error}"
    );
    transaction
        .rollback()
        .expect("roll back contract-9 key test");
}

#[test]
#[ignore = "requires native PostgreSQL and LMM_TEST_DATABASE_URL"]
fn contract_nine_rejects_inexact_replay_and_lookup_indexes() {
    let database_url = std::env::var("LMM_TEST_DATABASE_URL").expect("test database URL");
    let schema = format!("lmm_contract_nine_indexes_{}", std::process::id());
    let mut client = Client::connect(&database_url, NoTls).expect("connect to test PostgreSQL");
    let mut transaction = client.transaction().expect("start test transaction");
    prepare_schema(&mut transaction, &schema);
    let table = format!("{schema}.subscription_payment_refunds");
    let refund_index = "idx_subscription_provider_refund";
    let ledger_index = "idx_subscription_payment_refunds_finance_ledger_entry_id";
    let order_index = "idx_subscription_payment_refunds_subscription_order_id";
    let payment_index = "idx_subscription_payment_refunds_subscription_payment_event_id";

    for index in [refund_index, ledger_index, order_index, payment_index] {
        transaction.batch_execute("SAVEPOINT mutation").unwrap();
        transaction
            .batch_execute(&format!("DROP INDEX {schema}.{index}"))
            .expect("remove required index");
        let error = verify_subscription_payment_refund_schema(&mut transaction, &schema)
            .expect_err("every replay and lookup index is required");
        assert!(error.to_string().contains(index), "{error}");
        transaction
            .batch_execute("ROLLBACK TO SAVEPOINT mutation; RELEASE SAVEPOINT mutation")
            .unwrap();
    }
    for (index, uniqueness, definition) in [
        (refund_index, "", "(payment_provider,provider_event_id)"),
        (
            refund_index,
            "UNIQUE",
            "(provider_event_id,payment_provider)",
        ),
        (refund_index, "UNIQUE", "(provider_event_id)"),
        (
            refund_index,
            "UNIQUE",
            "(payment_provider,provider_event_id,subscription_payment_event_id)",
        ),
        (
            refund_index,
            "UNIQUE",
            "(lower(payment_provider),provider_event_id)",
        ),
        (
            refund_index,
            "UNIQUE",
            "(payment_provider,provider_event_id) INCLUDE (amount_micros)",
        ),
        (
            refund_index,
            "UNIQUE",
            "(payment_provider,provider_event_id) WHERE amount_micros>0",
        ),
        (ledger_index, "", "(finance_ledger_entry_id)"),
        (
            ledger_index,
            "UNIQUE",
            "(finance_ledger_entry_id,subscription_payment_event_id)",
        ),
        (ledger_index, "UNIQUE", "((finance_ledger_entry_id + 0))"),
        (
            ledger_index,
            "UNIQUE",
            "(finance_ledger_entry_id) INCLUDE (created_time)",
        ),
        (
            ledger_index,
            "UNIQUE",
            "(finance_ledger_entry_id) WHERE finance_ledger_entry_id>0",
        ),
        (order_index, "UNIQUE", "(subscription_order_id)"),
        (order_index, "", "(subscription_payment_event_id)"),
        (order_index, "", "USING hash (subscription_order_id)"),
        (
            order_index,
            "",
            "(subscription_order_id) WHERE quota_revoked>0",
        ),
        (payment_index, "UNIQUE", "(subscription_payment_event_id)"),
        (payment_index, "", "(subscription_order_id)"),
        (
            payment_index,
            "",
            "(subscription_payment_event_id,subscription_order_id)",
        ),
        (
            payment_index,
            "",
            "(subscription_payment_event_id) INCLUDE (subscription_order_id)",
        ),
    ] {
        let mutation = format!(
            "DROP INDEX {schema}.{index}; \
             CREATE {uniqueness} INDEX {index} ON {table} {definition}"
        );
        transaction.batch_execute("SAVEPOINT mutation").unwrap();
        transaction
            .batch_execute(&mutation)
            .expect("mutate index definition");
        let error = verify_subscription_payment_refund_schema(&mut transaction, &schema)
            .expect_err(
                "index uniqueness, ordered keys, expressions, includes and predicates must match",
            );
        assert!(error.to_string().contains(index), "{mutation}: {error}");
        transaction
            .batch_execute("ROLLBACK TO SAVEPOINT mutation; RELEASE SAVEPOINT mutation")
            .unwrap();
    }
    verify_subscription_payment_refund_schema(&mut transaction, &schema)
        .expect("index mutations were rolled back");
    transaction
        .rollback()
        .expect("roll back contract-9 index test");
}
