/*
Copyright (C) 2026 LIghtJUNction
*/
import assert from 'node:assert/strict'
import { test } from 'node:test'

import { DRAWING_IMAGE_BYTES } from './history-storage'
import {
  drawingBase64Blob,
  drawingSource,
  fetchDrawingBlob,
  safeDrawingURL,
} from './image-bytes'

test('base64 responses become actual image bytes, preferring bytes over expiring URLs', async () => {
  const data = btoa('generated bytes')
  assert.equal(await drawingBase64Blob(data).text(), 'generated bytes')
  assert.equal(
    drawingSource({ b64_json: data, url: 'https://example.test/expiring.png' }),
    `data:image/png;base64,${data}`
  )
  assert.throws(() => drawingBase64Blob('%%%'))
  assert.equal(safeDrawingURL('javascript:alert(1)'), undefined)
  assert.equal(safeDrawingURL('http://example.test/a.png'), undefined)
  assert.equal(
    safeDrawingURL('https://user:secret@example.test/a.png'),
    undefined
  )
})

test('URL caching fetches bytes with no credentials/referrer and no redirects', async () => {
  let called = 0
  const fetcher = (async (url, options) => {
    called++
    assert.equal(url, 'https://images.example.test/result.png')
    assert.equal(options?.credentials, 'omit')
    assert.equal(options?.referrerPolicy, 'no-referrer')
    assert.equal(options?.mode, 'cors')
    assert.equal(options?.redirect, 'error')
    return new Response('image pixels', {
      headers: { 'content-type': 'image/png' },
    })
  }) as typeof fetch
  const blob = await fetchDrawingBlob(
    'https://images.example.test/result.png',
    new AbortController().signal,
    fetcher
  )
  assert.equal(await blob.text(), 'image pixels')
  assert.equal(called, 1)
})

test('CORS, non-images, oversized streams and aborts fail locally without retrying', async () => {
  const signal = new AbortController().signal
  let calls = 0
  await assert.rejects(
    fetchDrawingBlob('https://images.example.test/a.png', signal, (async () => {
      calls++
      throw new TypeError('CORS')
    }) as typeof fetch),
    /CORS/
  )
  assert.equal(calls, 1)
  const responseHeaders: Record<string, string>[] = [
    { 'content-type': 'text/html' },
    { 'content-type': 'image/svg+xml' },
    {
      'content-type': 'image/png',
      'content-length': String(DRAWING_IMAGE_BYTES + 1),
    },
  ]
  for (const headers of responseHeaders) {
    await assert.rejects(
      fetchDrawingBlob(
        'https://images.example.test/a.png',
        signal,
        (async () => new Response('not an image', { headers })) as typeof fetch
      )
    )
  }
  let cancelled = false
  const chunk = new Uint8Array(1024 * 1024)
  await assert.rejects(
    fetchDrawingBlob(
      'https://images.example.test/a.png',
      signal,
      (async () =>
        new Response(
          new ReadableStream({
            pull(controller) {
              controller.enqueue(chunk)
            },
            cancel() {
              cancelled = true
            },
          }),
          { headers: { 'content-type': 'image/png' } }
        )) as typeof fetch
    ),
    /limit/
  )
  assert.equal(cancelled, true)
  const aborted = new AbortController()
  aborted.abort()
  await assert.rejects(
    fetchDrawingBlob(
      'https://images.example.test/a.png',
      aborted.signal,
      (async (_url, options) => {
        assert.equal(options?.signal?.aborted, true)
        throw new DOMException('Aborted', 'AbortError')
      }) as typeof fetch
    ),
    /Aborted/
  )
})
