// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// protoc: proto3 compiler (version header normalized)
// source: lmm/core/v1/commands.proto

package corepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Integration contracts, NOT available business implementations. Servers must
// advertise a feature only after its business module and authorization exist.
// Every mutation requires independent service AND current user authorization.
// Recheck user/resource/funding authority in the business transaction, including
// replay. A transport credential or an idempotency key never grants authority.
type MutationContext struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey  string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // 16..128 visible ASCII bytes; stable across retries.
	ExpectedVersion *int64                 `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3,oneof" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MutationContext) Reset() {
	*x = MutationContext{}
	mi := &file_lmm_core_v1_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationContext) ProtoMessage() {}

func (x *MutationContext) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationContext.ProtoReflect.Descriptor instead.
func (*MutationContext) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_commands_proto_rawDescGZIP(), []int{0}
}

func (x *MutationContext) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *MutationContext) GetExpectedVersion() int64 {
	if x != nil && x.ExpectedVersion != nil {
		return *x.ExpectedVersion
	}
	return 0
}

type MutationReceipt struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OperationId     int64                  `protobuf:"varint,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ResourceId      int64                  `protobuf:"varint,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceVersion int64                  `protobuf:"varint,3,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	EventIds        []int64                `protobuf:"varint,4,rep,packed,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MutationReceipt) Reset() {
	*x = MutationReceipt{}
	mi := &file_lmm_core_v1_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationReceipt) ProtoMessage() {}

func (x *MutationReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationReceipt.ProtoReflect.Descriptor instead.
func (*MutationReceipt) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_commands_proto_rawDescGZIP(), []int{1}
}

func (x *MutationReceipt) GetOperationId() int64 {
	if x != nil {
		return x.OperationId
	}
	return 0
}

func (x *MutationReceipt) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *MutationReceipt) GetResourceVersion() int64 {
	if x != nil {
		return x.ResourceVersion
	}
	return 0
}

func (x *MutationReceipt) GetEventIds() []int64 {
	if x != nil {
		return x.EventIds
	}
	return nil
}

type LedgerAmount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Units         int64                  `protobuf:"varint,1,opt,name=units,proto3" json:"units,omitempty"` // Positive integer units, defined by the core's asset registry.
	Asset         string                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`  // Allowlisted asset; no client-selected precision or float.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerAmount) Reset() {
	*x = LedgerAmount{}
	mi := &file_lmm_core_v1_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerAmount) ProtoMessage() {}

func (x *LedgerAmount) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerAmount.ProtoReflect.Descriptor instead.
func (*LedgerAmount) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_commands_proto_rawDescGZIP(), []int{2}
}

func (x *LedgerAmount) GetUnits() int64 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *LedgerAmount) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

type RevokeCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mutation      *MutationContext       `protobuf:"bytes,1,opt,name=mutation,proto3" json:"mutation,omitempty"`
	CredentialId  int64                  `protobuf:"varint,2,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCredentialRequest) Reset() {
	*x = RevokeCredentialRequest{}
	mi := &file_lmm_core_v1_commands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCredentialRequest) ProtoMessage() {}

func (x *RevokeCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_commands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCredentialRequest.ProtoReflect.Descriptor instead.
func (*RevokeCredentialRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_commands_proto_rawDescGZIP(), []int{3}
}

func (x *RevokeCredentialRequest) GetMutation() *MutationContext {
	if x != nil {
		return x.Mutation
	}
	return nil
}

func (x *RevokeCredentialRequest) GetCredentialId() int64 {
	if x != nil {
		return x.CredentialId
	}
	return 0
}

type CaptureVerifiedPaymentRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Mutation *MutationContext       `protobuf:"bytes,1,opt,name=mutation,proto3" json:"mutation,omitempty"`
	// A core-verified payment record fixes payer, amount and external event ID.
	// This request cannot supply a replacement account or credit amount.
	VerifiedPaymentId int64 `protobuf:"varint,2,opt,name=verified_payment_id,json=verifiedPaymentId,proto3" json:"verified_payment_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CaptureVerifiedPaymentRequest) Reset() {
	*x = CaptureVerifiedPaymentRequest{}
	mi := &file_lmm_core_v1_commands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureVerifiedPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureVerifiedPaymentRequest) ProtoMessage() {}

func (x *CaptureVerifiedPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_commands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureVerifiedPaymentRequest.ProtoReflect.Descriptor instead.
func (*CaptureVerifiedPaymentRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_commands_proto_rawDescGZIP(), []int{4}
}

func (x *CaptureVerifiedPaymentRequest) GetMutation() *MutationContext {
	if x != nil {
		return x.Mutation
	}
	return nil
}

func (x *CaptureVerifiedPaymentRequest) GetVerifiedPaymentId() int64 {
	if x != nil {
		return x.VerifiedPaymentId
	}
	return 0
}

type TransferFundsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mutation      *MutationContext       `protobuf:"bytes,1,opt,name=mutation,proto3" json:"mutation,omitempty"`
	Source        *Account               `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination   *Account               `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Amount        *LedgerAmount          `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferFundsRequest) Reset() {
	*x = TransferFundsRequest{}
	mi := &file_lmm_core_v1_commands_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferFundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFundsRequest) ProtoMessage() {}

func (x *TransferFundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_commands_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFundsRequest.ProtoReflect.Descriptor instead.
func (*TransferFundsRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_commands_proto_rawDescGZIP(), []int{5}
}

func (x *TransferFundsRequest) GetMutation() *MutationContext {
	if x != nil {
		return x.Mutation
	}
	return nil
}

func (x *TransferFundsRequest) GetSource() *Account {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *TransferFundsRequest) GetDestination() *Account {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *TransferFundsRequest) GetAmount() *LedgerAmount {
	if x != nil {
		return x.Amount
	}
	return nil
}

type RefundFundsRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Mutation            *MutationContext       `protobuf:"bytes,1,opt,name=mutation,proto3" json:"mutation,omitempty"`
	OriginalOperationId int64                  `protobuf:"varint,2,opt,name=original_operation_id,json=originalOperationId,proto3" json:"original_operation_id,omitempty"`
	Amount              *LedgerAmount          `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"` // Core caps cumulative refunds at the original debit.
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RefundFundsRequest) Reset() {
	*x = RefundFundsRequest{}
	mi := &file_lmm_core_v1_commands_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundFundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundFundsRequest) ProtoMessage() {}

func (x *RefundFundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_commands_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundFundsRequest.ProtoReflect.Descriptor instead.
func (*RefundFundsRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_commands_proto_rawDescGZIP(), []int{6}
}

func (x *RefundFundsRequest) GetMutation() *MutationContext {
	if x != nil {
		return x.Mutation
	}
	return nil
}

func (x *RefundFundsRequest) GetOriginalOperationId() int64 {
	if x != nil {
		return x.OriginalOperationId
	}
	return 0
}

func (x *RefundFundsRequest) GetAmount() *LedgerAmount {
	if x != nil {
		return x.Amount
	}
	return nil
}

type ReserveUsageRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Mutation *MutationContext       `protobuf:"bytes,1,opt,name=mutation,proto3" json:"mutation,omitempty"`
	// Quote and model request are already core-owned. Core selects funding and
	// applies all user/team/key budgets; callers cannot choose a balance to debit.
	QuoteId        int64  `protobuf:"varint,2,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	ModelRequestId string `protobuf:"bytes,3,opt,name=model_request_id,json=modelRequestId,proto3" json:"model_request_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReserveUsageRequest) Reset() {
	*x = ReserveUsageRequest{}
	mi := &file_lmm_core_v1_commands_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveUsageRequest) ProtoMessage() {}

func (x *ReserveUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_commands_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveUsageRequest.ProtoReflect.Descriptor instead.
func (*ReserveUsageRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_commands_proto_rawDescGZIP(), []int{7}
}

func (x *ReserveUsageRequest) GetMutation() *MutationContext {
	if x != nil {
		return x.Mutation
	}
	return nil
}

func (x *ReserveUsageRequest) GetQuoteId() int64 {
	if x != nil {
		return x.QuoteId
	}
	return 0
}

func (x *ReserveUsageRequest) GetModelRequestId() string {
	if x != nil {
		return x.ModelRequestId
	}
	return ""
}

type ReservationReceipt struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Mutation       *MutationReceipt       `protobuf:"bytes,1,opt,name=mutation,proto3" json:"mutation,omitempty"`
	ReservationId  int64                  `protobuf:"varint,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	ChargedAccount *Account               `protobuf:"bytes,3,opt,name=charged_account,json=chargedAccount,proto3" json:"charged_account,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReservationReceipt) Reset() {
	*x = ReservationReceipt{}
	mi := &file_lmm_core_v1_commands_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationReceipt) ProtoMessage() {}

func (x *ReservationReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_commands_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationReceipt.ProtoReflect.Descriptor instead.
func (*ReservationReceipt) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_commands_proto_rawDescGZIP(), []int{8}
}

func (x *ReservationReceipt) GetMutation() *MutationReceipt {
	if x != nil {
		return x.Mutation
	}
	return nil
}

func (x *ReservationReceipt) GetReservationId() int64 {
	if x != nil {
		return x.ReservationId
	}
	return 0
}

func (x *ReservationReceipt) GetChargedAccount() *Account {
	if x != nil {
		return x.ChargedAccount
	}
	return nil
}

type UsageCounters struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InputTokens      int64                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens     int64                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CacheReadTokens  int64                  `protobuf:"varint,3,opt,name=cache_read_tokens,json=cacheReadTokens,proto3" json:"cache_read_tokens,omitempty"`
	CacheWriteTokens int64                  `protobuf:"varint,4,opt,name=cache_write_tokens,json=cacheWriteTokens,proto3" json:"cache_write_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UsageCounters) Reset() {
	*x = UsageCounters{}
	mi := &file_lmm_core_v1_commands_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageCounters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageCounters) ProtoMessage() {}

func (x *UsageCounters) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_commands_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageCounters.ProtoReflect.Descriptor instead.
func (*UsageCounters) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_commands_proto_rawDescGZIP(), []int{9}
}

func (x *UsageCounters) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *UsageCounters) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *UsageCounters) GetCacheReadTokens() int64 {
	if x != nil {
		return x.CacheReadTokens
	}
	return 0
}

func (x *UsageCounters) GetCacheWriteTokens() int64 {
	if x != nil {
		return x.CacheWriteTokens
	}
	return 0
}

type SettleUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mutation      *MutationContext       `protobuf:"bytes,1,opt,name=mutation,proto3" json:"mutation,omitempty"`
	ReservationId int64                  `protobuf:"varint,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	// Only the trusted core relay's validated usage evidence may settle. A Go
	// module/user cannot submit arbitrary usage to reduce the charge.
	VerifiedUsageId int64 `protobuf:"varint,3,opt,name=verified_usage_id,json=verifiedUsageId,proto3" json:"verified_usage_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SettleUsageRequest) Reset() {
	*x = SettleUsageRequest{}
	mi := &file_lmm_core_v1_commands_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleUsageRequest) ProtoMessage() {}

func (x *SettleUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_commands_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleUsageRequest.ProtoReflect.Descriptor instead.
func (*SettleUsageRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_commands_proto_rawDescGZIP(), []int{10}
}

func (x *SettleUsageRequest) GetMutation() *MutationContext {
	if x != nil {
		return x.Mutation
	}
	return nil
}

func (x *SettleUsageRequest) GetReservationId() int64 {
	if x != nil {
		return x.ReservationId
	}
	return 0
}

func (x *SettleUsageRequest) GetVerifiedUsageId() int64 {
	if x != nil {
		return x.VerifiedUsageId
	}
	return 0
}

type ReleaseUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mutation      *MutationContext       `protobuf:"bytes,1,opt,name=mutation,proto3" json:"mutation,omitempty"`
	ReservationId int64                  `protobuf:"varint,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseUsageRequest) Reset() {
	*x = ReleaseUsageRequest{}
	mi := &file_lmm_core_v1_commands_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseUsageRequest) ProtoMessage() {}

func (x *ReleaseUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_commands_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseUsageRequest.ProtoReflect.Descriptor instead.
func (*ReleaseUsageRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_commands_proto_rawDescGZIP(), []int{11}
}

func (x *ReleaseUsageRequest) GetMutation() *MutationContext {
	if x != nil {
		return x.Mutation
	}
	return nil
}

func (x *ReleaseUsageRequest) GetReservationId() int64 {
	if x != nil {
		return x.ReservationId
	}
	return 0
}

type ActivateConfigurationRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Mutation *MutationContext       `protobuf:"bytes,1,opt,name=mutation,proto3" json:"mutation,omitempty"`
	// A staged, validated immutable configuration owned by core. CAS activation
	// must preserve the previous active version on failure. No arbitrary settings.
	ValidatedConfigurationId int64 `protobuf:"varint,2,opt,name=validated_configuration_id,json=validatedConfigurationId,proto3" json:"validated_configuration_id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ActivateConfigurationRequest) Reset() {
	*x = ActivateConfigurationRequest{}
	mi := &file_lmm_core_v1_commands_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateConfigurationRequest) ProtoMessage() {}

func (x *ActivateConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_commands_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateConfigurationRequest.ProtoReflect.Descriptor instead.
func (*ActivateConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_commands_proto_rawDescGZIP(), []int{12}
}

func (x *ActivateConfigurationRequest) GetMutation() *MutationContext {
	if x != nil {
		return x.Mutation
	}
	return nil
}

func (x *ActivateConfigurationRequest) GetValidatedConfigurationId() int64 {
	if x != nil {
		return x.ValidatedConfigurationId
	}
	return 0
}

var File_lmm_core_v1_commands_proto protoreflect.FileDescriptor

const file_lmm_core_v1_commands_proto_rawDesc = "" +
	"\n" +
	"\x1almm/core/v1/commands.proto\x12\vlmm.core.v1\x1a\x19lmm/core/v1/control.proto\"\x7f\n" +
	"\x0fMutationContext\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12.\n" +
	"\x10expected_version\x18\x02 \x01(\x03H\x00R\x0fexpectedVersion\x88\x01\x01B\x13\n" +
	"\x11_expected_version\"\x9d\x01\n" +
	"\x0fMutationReceipt\x12!\n" +
	"\foperation_id\x18\x01 \x01(\x03R\voperationId\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\x03R\n" +
	"resourceId\x12)\n" +
	"\x10resource_version\x18\x03 \x01(\x03R\x0fresourceVersion\x12\x1b\n" +
	"\tevent_ids\x18\x04 \x03(\x03R\beventIds\":\n" +
	"\fLedgerAmount\x12\x14\n" +
	"\x05units\x18\x01 \x01(\x03R\x05units\x12\x14\n" +
	"\x05asset\x18\x02 \x01(\tR\x05asset\"x\n" +
	"\x17RevokeCredentialRequest\x128\n" +
	"\bmutation\x18\x01 \x01(\v2\x1c.lmm.core.v1.MutationContextR\bmutation\x12#\n" +
	"\rcredential_id\x18\x02 \x01(\x03R\fcredentialId\"\x89\x01\n" +
	"\x1dCaptureVerifiedPaymentRequest\x128\n" +
	"\bmutation\x18\x01 \x01(\v2\x1c.lmm.core.v1.MutationContextR\bmutation\x12.\n" +
	"\x13verified_payment_id\x18\x02 \x01(\x03R\x11verifiedPaymentId\"\xe9\x01\n" +
	"\x14TransferFundsRequest\x128\n" +
	"\bmutation\x18\x01 \x01(\v2\x1c.lmm.core.v1.MutationContextR\bmutation\x12,\n" +
	"\x06source\x18\x02 \x01(\v2\x14.lmm.core.v1.AccountR\x06source\x126\n" +
	"\vdestination\x18\x03 \x01(\v2\x14.lmm.core.v1.AccountR\vdestination\x121\n" +
	"\x06amount\x18\x04 \x01(\v2\x19.lmm.core.v1.LedgerAmountR\x06amount\"\xb5\x01\n" +
	"\x12RefundFundsRequest\x128\n" +
	"\bmutation\x18\x01 \x01(\v2\x1c.lmm.core.v1.MutationContextR\bmutation\x122\n" +
	"\x15original_operation_id\x18\x02 \x01(\x03R\x13originalOperationId\x121\n" +
	"\x06amount\x18\x03 \x01(\v2\x19.lmm.core.v1.LedgerAmountR\x06amount\"\x94\x01\n" +
	"\x13ReserveUsageRequest\x128\n" +
	"\bmutation\x18\x01 \x01(\v2\x1c.lmm.core.v1.MutationContextR\bmutation\x12\x19\n" +
	"\bquote_id\x18\x02 \x01(\x03R\aquoteId\x12(\n" +
	"\x10model_request_id\x18\x03 \x01(\tR\x0emodelRequestId\"\xb4\x01\n" +
	"\x12ReservationReceipt\x128\n" +
	"\bmutation\x18\x01 \x01(\v2\x1c.lmm.core.v1.MutationReceiptR\bmutation\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\x03R\rreservationId\x12=\n" +
	"\x0fcharged_account\x18\x03 \x01(\v2\x14.lmm.core.v1.AccountR\x0echargedAccount\"\xb1\x01\n" +
	"\rUsageCounters\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x03R\foutputTokens\x12*\n" +
	"\x11cache_read_tokens\x18\x03 \x01(\x03R\x0fcacheReadTokens\x12,\n" +
	"\x12cache_write_tokens\x18\x04 \x01(\x03R\x10cacheWriteTokens\"\xa1\x01\n" +
	"\x12SettleUsageRequest\x128\n" +
	"\bmutation\x18\x01 \x01(\v2\x1c.lmm.core.v1.MutationContextR\bmutation\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\x03R\rreservationId\x12*\n" +
	"\x11verified_usage_id\x18\x03 \x01(\x03R\x0fverifiedUsageId\"v\n" +
	"\x13ReleaseUsageRequest\x128\n" +
	"\bmutation\x18\x01 \x01(\v2\x1c.lmm.core.v1.MutationContextR\bmutation\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\x03R\rreservationId\"\x96\x01\n" +
	"\x1cActivateConfigurationRequest\x128\n" +
	"\bmutation\x18\x01 \x01(\v2\x1c.lmm.core.v1.MutationContextR\bmutation\x12<\n" +
	"\x1avalidated_configuration_id\x18\x02 \x01(\x03R\x18validatedConfigurationId2n\n" +
	"\x14CoreIdentityCommands\x12V\n" +
	"\x10RevokeCredential\x12$.lmm.core.v1.RevokeCredentialRequest\x1a\x1c.lmm.core.v1.MutationReceipt2\x8e\x02\n" +
	"\x12CoreLedgerCommands\x12b\n" +
	"\x16CaptureVerifiedPayment\x12*.lmm.core.v1.CaptureVerifiedPaymentRequest\x1a\x1c.lmm.core.v1.MutationReceipt\x12K\n" +
	"\bTransfer\x12!.lmm.core.v1.TransferFundsRequest\x1a\x1c.lmm.core.v1.MutationReceipt\x12G\n" +
	"\x06Refund\x12\x1f.lmm.core.v1.RefundFundsRequest\x1a\x1c.lmm.core.v1.MutationReceipt2\xf7\x01\n" +
	"\x13CoreBillingCommands\x12L\n" +
	"\aReserve\x12 .lmm.core.v1.ReserveUsageRequest\x1a\x1f.lmm.core.v1.ReservationReceipt\x12G\n" +
	"\x06Settle\x12\x1f.lmm.core.v1.SettleUsageRequest\x1a\x1c.lmm.core.v1.MutationReceipt\x12I\n" +
	"\aRelease\x12 .lmm.core.v1.ReleaseUsageRequest\x1a\x1c.lmm.core.v1.MutationReceipt2w\n" +
	"\x13CoreRoutingCommands\x12`\n" +
	"\x15ActivateConfiguration\x12).lmm.core.v1.ActivateConfigurationRequest\x1a\x1c.lmm.core.v1.MutationReceiptBLZJgithub.com/TokenNotIncluded/api.lmm.best/extensions/internal/corepb;corepbb\x06proto3"

var (
	file_lmm_core_v1_commands_proto_rawDescOnce sync.Once
	file_lmm_core_v1_commands_proto_rawDescData []byte
)

func file_lmm_core_v1_commands_proto_rawDescGZIP() []byte {
	file_lmm_core_v1_commands_proto_rawDescOnce.Do(func() {
		file_lmm_core_v1_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lmm_core_v1_commands_proto_rawDesc), len(file_lmm_core_v1_commands_proto_rawDesc)))
	})
	return file_lmm_core_v1_commands_proto_rawDescData
}

var file_lmm_core_v1_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_lmm_core_v1_commands_proto_goTypes = []any{
	(*MutationContext)(nil),               // 0: lmm.core.v1.MutationContext
	(*MutationReceipt)(nil),               // 1: lmm.core.v1.MutationReceipt
	(*LedgerAmount)(nil),                  // 2: lmm.core.v1.LedgerAmount
	(*RevokeCredentialRequest)(nil),       // 3: lmm.core.v1.RevokeCredentialRequest
	(*CaptureVerifiedPaymentRequest)(nil), // 4: lmm.core.v1.CaptureVerifiedPaymentRequest
	(*TransferFundsRequest)(nil),          // 5: lmm.core.v1.TransferFundsRequest
	(*RefundFundsRequest)(nil),            // 6: lmm.core.v1.RefundFundsRequest
	(*ReserveUsageRequest)(nil),           // 7: lmm.core.v1.ReserveUsageRequest
	(*ReservationReceipt)(nil),            // 8: lmm.core.v1.ReservationReceipt
	(*UsageCounters)(nil),                 // 9: lmm.core.v1.UsageCounters
	(*SettleUsageRequest)(nil),            // 10: lmm.core.v1.SettleUsageRequest
	(*ReleaseUsageRequest)(nil),           // 11: lmm.core.v1.ReleaseUsageRequest
	(*ActivateConfigurationRequest)(nil),  // 12: lmm.core.v1.ActivateConfigurationRequest
	(*Account)(nil),                       // 13: lmm.core.v1.Account
}
var file_lmm_core_v1_commands_proto_depIdxs = []int32{
	0,  // 0: lmm.core.v1.RevokeCredentialRequest.mutation:type_name -> lmm.core.v1.MutationContext
	0,  // 1: lmm.core.v1.CaptureVerifiedPaymentRequest.mutation:type_name -> lmm.core.v1.MutationContext
	0,  // 2: lmm.core.v1.TransferFundsRequest.mutation:type_name -> lmm.core.v1.MutationContext
	13, // 3: lmm.core.v1.TransferFundsRequest.source:type_name -> lmm.core.v1.Account
	13, // 4: lmm.core.v1.TransferFundsRequest.destination:type_name -> lmm.core.v1.Account
	2,  // 5: lmm.core.v1.TransferFundsRequest.amount:type_name -> lmm.core.v1.LedgerAmount
	0,  // 6: lmm.core.v1.RefundFundsRequest.mutation:type_name -> lmm.core.v1.MutationContext
	2,  // 7: lmm.core.v1.RefundFundsRequest.amount:type_name -> lmm.core.v1.LedgerAmount
	0,  // 8: lmm.core.v1.ReserveUsageRequest.mutation:type_name -> lmm.core.v1.MutationContext
	1,  // 9: lmm.core.v1.ReservationReceipt.mutation:type_name -> lmm.core.v1.MutationReceipt
	13, // 10: lmm.core.v1.ReservationReceipt.charged_account:type_name -> lmm.core.v1.Account
	0,  // 11: lmm.core.v1.SettleUsageRequest.mutation:type_name -> lmm.core.v1.MutationContext
	0,  // 12: lmm.core.v1.ReleaseUsageRequest.mutation:type_name -> lmm.core.v1.MutationContext
	0,  // 13: lmm.core.v1.ActivateConfigurationRequest.mutation:type_name -> lmm.core.v1.MutationContext
	3,  // 14: lmm.core.v1.CoreIdentityCommands.RevokeCredential:input_type -> lmm.core.v1.RevokeCredentialRequest
	4,  // 15: lmm.core.v1.CoreLedgerCommands.CaptureVerifiedPayment:input_type -> lmm.core.v1.CaptureVerifiedPaymentRequest
	5,  // 16: lmm.core.v1.CoreLedgerCommands.Transfer:input_type -> lmm.core.v1.TransferFundsRequest
	6,  // 17: lmm.core.v1.CoreLedgerCommands.Refund:input_type -> lmm.core.v1.RefundFundsRequest
	7,  // 18: lmm.core.v1.CoreBillingCommands.Reserve:input_type -> lmm.core.v1.ReserveUsageRequest
	10, // 19: lmm.core.v1.CoreBillingCommands.Settle:input_type -> lmm.core.v1.SettleUsageRequest
	11, // 20: lmm.core.v1.CoreBillingCommands.Release:input_type -> lmm.core.v1.ReleaseUsageRequest
	12, // 21: lmm.core.v1.CoreRoutingCommands.ActivateConfiguration:input_type -> lmm.core.v1.ActivateConfigurationRequest
	1,  // 22: lmm.core.v1.CoreIdentityCommands.RevokeCredential:output_type -> lmm.core.v1.MutationReceipt
	1,  // 23: lmm.core.v1.CoreLedgerCommands.CaptureVerifiedPayment:output_type -> lmm.core.v1.MutationReceipt
	1,  // 24: lmm.core.v1.CoreLedgerCommands.Transfer:output_type -> lmm.core.v1.MutationReceipt
	1,  // 25: lmm.core.v1.CoreLedgerCommands.Refund:output_type -> lmm.core.v1.MutationReceipt
	8,  // 26: lmm.core.v1.CoreBillingCommands.Reserve:output_type -> lmm.core.v1.ReservationReceipt
	1,  // 27: lmm.core.v1.CoreBillingCommands.Settle:output_type -> lmm.core.v1.MutationReceipt
	1,  // 28: lmm.core.v1.CoreBillingCommands.Release:output_type -> lmm.core.v1.MutationReceipt
	1,  // 29: lmm.core.v1.CoreRoutingCommands.ActivateConfiguration:output_type -> lmm.core.v1.MutationReceipt
	22, // [22:30] is the sub-list for method output_type
	14, // [14:22] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_lmm_core_v1_commands_proto_init() }
func file_lmm_core_v1_commands_proto_init() {
	if File_lmm_core_v1_commands_proto != nil {
		return
	}
	file_lmm_core_v1_control_proto_init()
	file_lmm_core_v1_commands_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lmm_core_v1_commands_proto_rawDesc), len(file_lmm_core_v1_commands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_lmm_core_v1_commands_proto_goTypes,
		DependencyIndexes: file_lmm_core_v1_commands_proto_depIdxs,
		MessageInfos:      file_lmm_core_v1_commands_proto_msgTypes,
	}.Build()
	File_lmm_core_v1_commands_proto = out.File
	file_lmm_core_v1_commands_proto_goTypes = nil
	file_lmm_core_v1_commands_proto_depIdxs = nil
}
