// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// protoc: proto3 compiler (version header normalized)
// source: lmm/core/v1/events.proto

package corepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventRetryReason int32

const (
	EventRetryReason_EVENT_RETRY_REASON_UNSPECIFIED            EventRetryReason = 0
	EventRetryReason_EVENT_RETRY_REASON_HANDLER_FAILURE        EventRetryReason = 1
	EventRetryReason_EVENT_RETRY_REASON_UNSUPPORTED_EVENT      EventRetryReason = 2
	EventRetryReason_EVENT_RETRY_REASON_DEPENDENCY_UNAVAILABLE EventRetryReason = 3
)

// Enum value maps for EventRetryReason.
var (
	EventRetryReason_name = map[int32]string{
		0: "EVENT_RETRY_REASON_UNSPECIFIED",
		1: "EVENT_RETRY_REASON_HANDLER_FAILURE",
		2: "EVENT_RETRY_REASON_UNSUPPORTED_EVENT",
		3: "EVENT_RETRY_REASON_DEPENDENCY_UNAVAILABLE",
	}
	EventRetryReason_value = map[string]int32{
		"EVENT_RETRY_REASON_UNSPECIFIED":            0,
		"EVENT_RETRY_REASON_HANDLER_FAILURE":        1,
		"EVENT_RETRY_REASON_UNSUPPORTED_EVENT":      2,
		"EVENT_RETRY_REASON_DEPENDENCY_UNAVAILABLE": 3,
	}
)

func (x EventRetryReason) Enum() *EventRetryReason {
	p := new(EventRetryReason)
	*p = x
	return p
}

func (x EventRetryReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventRetryReason) Descriptor() protoreflect.EnumDescriptor {
	return file_lmm_core_v1_events_proto_enumTypes[0].Descriptor()
}

func (EventRetryReason) Type() protoreflect.EnumType {
	return &file_lmm_core_v1_events_proto_enumTypes[0]
}

func (x EventRetryReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventRetryReason.Descriptor instead.
func (EventRetryReason) EnumDescriptor() ([]byte, []int) {
	return file_lmm_core_v1_events_proto_rawDescGZIP(), []int{0}
}

type EventClientVersion struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProtocolMajor    uint32                 `protobuf:"varint,1,opt,name=protocol_major,json=protocolMajor,proto3" json:"protocol_major,omitempty"`
	ProtocolMinor    uint32                 `protobuf:"varint,2,opt,name=protocol_minor,json=protocolMinor,proto3" json:"protocol_minor,omitempty"`
	RequiredFeatures []string               `protobuf:"bytes,3,rep,name=required_features,json=requiredFeatures,proto3" json:"required_features,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventClientVersion) Reset() {
	*x = EventClientVersion{}
	mi := &file_lmm_core_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventClientVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventClientVersion) ProtoMessage() {}

func (x *EventClientVersion) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventClientVersion.ProtoReflect.Descriptor instead.
func (*EventClientVersion) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *EventClientVersion) GetProtocolMajor() uint32 {
	if x != nil {
		return x.ProtocolMajor
	}
	return 0
}

func (x *EventClientVersion) GetProtocolMinor() uint32 {
	if x != nil {
		return x.ProtocolMinor
	}
	return 0
}

func (x *EventClientVersion) GetRequiredFeatures() []string {
	if x != nil {
		return x.RequiredFeatures
	}
	return nil
}

type NegotiateEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId    string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	Version       *EventClientVersion    `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NegotiateEventsRequest) Reset() {
	*x = NegotiateEventsRequest{}
	mi := &file_lmm_core_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NegotiateEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NegotiateEventsRequest) ProtoMessage() {}

func (x *NegotiateEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NegotiateEventsRequest.ProtoReflect.Descriptor instead.
func (*NegotiateEventsRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *NegotiateEventsRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *NegotiateEventsRequest) GetVersion() *EventClientVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

type NegotiateEventsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolMajor   uint32                 `protobuf:"varint,1,opt,name=protocol_major,json=protocolMajor,proto3" json:"protocol_major,omitempty"`
	ProtocolMinor   uint32                 `protobuf:"varint,2,opt,name=protocol_minor,json=protocolMinor,proto3" json:"protocol_minor,omitempty"`
	Features        []string               `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`
	MaxBatch        uint32                 `protobuf:"varint,4,opt,name=max_batch,json=maxBatch,proto3" json:"max_batch,omitempty"`
	MaxPayloadBytes uint32                 `protobuf:"varint,5,opt,name=max_payload_bytes,json=maxPayloadBytes,proto3" json:"max_payload_bytes,omitempty"`
	LeaseSeconds    uint32                 `protobuf:"varint,6,opt,name=lease_seconds,json=leaseSeconds,proto3" json:"lease_seconds,omitempty"`
	EventTypes      []string               `protobuf:"bytes,7,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NegotiateEventsResponse) Reset() {
	*x = NegotiateEventsResponse{}
	mi := &file_lmm_core_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NegotiateEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NegotiateEventsResponse) ProtoMessage() {}

func (x *NegotiateEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NegotiateEventsResponse.ProtoReflect.Descriptor instead.
func (*NegotiateEventsResponse) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *NegotiateEventsResponse) GetProtocolMajor() uint32 {
	if x != nil {
		return x.ProtocolMajor
	}
	return 0
}

func (x *NegotiateEventsResponse) GetProtocolMinor() uint32 {
	if x != nil {
		return x.ProtocolMinor
	}
	return 0
}

func (x *NegotiateEventsResponse) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *NegotiateEventsResponse) GetMaxBatch() uint32 {
	if x != nil {
		return x.MaxBatch
	}
	return 0
}

func (x *NegotiateEventsResponse) GetMaxPayloadBytes() uint32 {
	if x != nil {
		return x.MaxPayloadBytes
	}
	return 0
}

func (x *NegotiateEventsResponse) GetLeaseSeconds() uint32 {
	if x != nil {
		return x.LeaseSeconds
	}
	return 0
}

func (x *NegotiateEventsResponse) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

// All IDs are positive signed 64-bit integers. Never pass them through a float.
type EventEnvelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventId         int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventKey        string                 `protobuf:"bytes,2,opt,name=event_key,json=eventKey,proto3" json:"event_key,omitempty"`
	EventType       string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	SchemaVersion   uint32                 `protobuf:"varint,4,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	ResourceId      int64                  `protobuf:"varint,5,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceVersion int64                  `protobuf:"varint,6,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	// Original serialized domain message. Store/forward without re-encoding.
	Payload []byte `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	// Stable digest; algorithm is specified in contracts/proto/README.md.
	ContentSha256 []byte `protobuf:"bytes,8,opt,name=content_sha256,json=contentSha256,proto3" json:"content_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_lmm_core_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *EventEnvelope) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *EventEnvelope) GetEventKey() string {
	if x != nil {
		return x.EventKey
	}
	return ""
}

func (x *EventEnvelope) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventEnvelope) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *EventEnvelope) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *EventEnvelope) GetResourceVersion() int64 {
	if x != nil {
		return x.ResourceVersion
	}
	return 0
}

func (x *EventEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventEnvelope) GetContentSha256() []byte {
	if x != nil {
		return x.ContentSha256
	}
	return nil
}

type EventDelivery struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Event            *EventEnvelope         `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	LeaseToken       []byte                 `protobuf:"bytes,2,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	Attempt          uint32                 `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	LeaseUntilUnixMs int64                  `protobuf:"varint,4,opt,name=lease_until_unix_ms,json=leaseUntilUnixMs,proto3" json:"lease_until_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventDelivery) Reset() {
	*x = EventDelivery{}
	mi := &file_lmm_core_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDelivery) ProtoMessage() {}

func (x *EventDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDelivery.ProtoReflect.Descriptor instead.
func (*EventDelivery) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *EventDelivery) GetEvent() *EventEnvelope {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EventDelivery) GetLeaseToken() []byte {
	if x != nil {
		return x.LeaseToken
	}
	return nil
}

func (x *EventDelivery) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *EventDelivery) GetLeaseUntilUnixMs() int64 {
	if x != nil {
		return x.LeaseUntilUnixMs
	}
	return 0
}

type PullEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId    string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	Version       *EventClientVersion    `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	MaxEvents     uint32                 `protobuf:"varint,3,opt,name=max_events,json=maxEvents,proto3" json:"max_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullEventsRequest) Reset() {
	*x = PullEventsRequest{}
	mi := &file_lmm_core_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullEventsRequest) ProtoMessage() {}

func (x *PullEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullEventsRequest.ProtoReflect.Descriptor instead.
func (*PullEventsRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *PullEventsRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *PullEventsRequest) GetVersion() *EventClientVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *PullEventsRequest) GetMaxEvents() uint32 {
	if x != nil {
		return x.MaxEvents
	}
	return 0
}

type PullEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deliveries    []*EventDelivery       `protobuf:"bytes,1,rep,name=deliveries,proto3" json:"deliveries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullEventsResponse) Reset() {
	*x = PullEventsResponse{}
	mi := &file_lmm_core_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullEventsResponse) ProtoMessage() {}

func (x *PullEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullEventsResponse.ProtoReflect.Descriptor instead.
func (*PullEventsResponse) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *PullEventsResponse) GetDeliveries() []*EventDelivery {
	if x != nil {
		return x.Deliveries
	}
	return nil
}

type AcknowledgeEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId    string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	EventId       int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	LeaseToken    []byte                 `protobuf:"bytes,3,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeEventRequest) Reset() {
	*x = AcknowledgeEventRequest{}
	mi := &file_lmm_core_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeEventRequest) ProtoMessage() {}

func (x *AcknowledgeEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeEventRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeEventRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *AcknowledgeEventRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *AcknowledgeEventRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *AcknowledgeEventRequest) GetLeaseToken() []byte {
	if x != nil {
		return x.LeaseToken
	}
	return nil
}

type AcknowledgeEventResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AlreadyAcknowledged bool                   `protobuf:"varint,1,opt,name=already_acknowledged,json=alreadyAcknowledged,proto3" json:"already_acknowledged,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AcknowledgeEventResponse) Reset() {
	*x = AcknowledgeEventResponse{}
	mi := &file_lmm_core_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeEventResponse) ProtoMessage() {}

func (x *AcknowledgeEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeEventResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgeEventResponse) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *AcknowledgeEventResponse) GetAlreadyAcknowledged() bool {
	if x != nil {
		return x.AlreadyAcknowledged
	}
	return false
}

type RetryEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId    string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	EventId       int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	LeaseToken    []byte                 `protobuf:"bytes,3,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	Reason        EventRetryReason       `protobuf:"varint,4,opt,name=reason,proto3,enum=lmm.core.v1.EventRetryReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryEventRequest) Reset() {
	*x = RetryEventRequest{}
	mi := &file_lmm_core_v1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryEventRequest) ProtoMessage() {}

func (x *RetryEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryEventRequest.ProtoReflect.Descriptor instead.
func (*RetryEventRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_events_proto_rawDescGZIP(), []int{9}
}

func (x *RetryEventRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *RetryEventRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *RetryEventRequest) GetLeaseToken() []byte {
	if x != nil {
		return x.LeaseToken
	}
	return nil
}

func (x *RetryEventRequest) GetReason() EventRetryReason {
	if x != nil {
		return x.Reason
	}
	return EventRetryReason_EVENT_RETRY_REASON_UNSPECIFIED
}

type RetryEventResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AlreadyAcknowledged bool                   `protobuf:"varint,1,opt,name=already_acknowledged,json=alreadyAcknowledged,proto3" json:"already_acknowledged,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RetryEventResponse) Reset() {
	*x = RetryEventResponse{}
	mi := &file_lmm_core_v1_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryEventResponse) ProtoMessage() {}

func (x *RetryEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryEventResponse.ProtoReflect.Descriptor instead.
func (*RetryEventResponse) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_events_proto_rawDescGZIP(), []int{10}
}

func (x *RetryEventResponse) GetAlreadyAcknowledged() bool {
	if x != nil {
		return x.AlreadyAcknowledged
	}
	return false
}

var File_lmm_core_v1_events_proto protoreflect.FileDescriptor

const file_lmm_core_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x18lmm/core/v1/events.proto\x12\vlmm.core.v1\"\x8f\x01\n" +
	"\x12EventClientVersion\x12%\n" +
	"\x0eprotocol_major\x18\x01 \x01(\rR\rprotocolMajor\x12%\n" +
	"\x0eprotocol_minor\x18\x02 \x01(\rR\rprotocolMinor\x12+\n" +
	"\x11required_features\x18\x03 \x03(\tR\x10requiredFeatures\"t\n" +
	"\x16NegotiateEventsRequest\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x129\n" +
	"\aversion\x18\x02 \x01(\v2\x1f.lmm.core.v1.EventClientVersionR\aversion\"\x92\x02\n" +
	"\x17NegotiateEventsResponse\x12%\n" +
	"\x0eprotocol_major\x18\x01 \x01(\rR\rprotocolMajor\x12%\n" +
	"\x0eprotocol_minor\x18\x02 \x01(\rR\rprotocolMinor\x12\x1a\n" +
	"\bfeatures\x18\x03 \x03(\tR\bfeatures\x12\x1b\n" +
	"\tmax_batch\x18\x04 \x01(\rR\bmaxBatch\x12*\n" +
	"\x11max_payload_bytes\x18\x05 \x01(\rR\x0fmaxPayloadBytes\x12#\n" +
	"\rlease_seconds\x18\x06 \x01(\rR\fleaseSeconds\x12\x1f\n" +
	"\vevent_types\x18\a \x03(\tR\n" +
	"eventTypes\"\x9a\x02\n" +
	"\rEventEnvelope\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x1b\n" +
	"\tevent_key\x18\x02 \x01(\tR\beventKey\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12%\n" +
	"\x0eschema_version\x18\x04 \x01(\rR\rschemaVersion\x12\x1f\n" +
	"\vresource_id\x18\x05 \x01(\x03R\n" +
	"resourceId\x12)\n" +
	"\x10resource_version\x18\x06 \x01(\x03R\x0fresourceVersion\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12%\n" +
	"\x0econtent_sha256\x18\b \x01(\fR\rcontentSha256\"\xab\x01\n" +
	"\rEventDelivery\x120\n" +
	"\x05event\x18\x01 \x01(\v2\x1a.lmm.core.v1.EventEnvelopeR\x05event\x12\x1f\n" +
	"\vlease_token\x18\x02 \x01(\fR\n" +
	"leaseToken\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\rR\aattempt\x12-\n" +
	"\x13lease_until_unix_ms\x18\x04 \x01(\x03R\x10leaseUntilUnixMs\"\x8e\x01\n" +
	"\x11PullEventsRequest\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x129\n" +
	"\aversion\x18\x02 \x01(\v2\x1f.lmm.core.v1.EventClientVersionR\aversion\x12\x1d\n" +
	"\n" +
	"max_events\x18\x03 \x01(\rR\tmaxEvents\"P\n" +
	"\x12PullEventsResponse\x12:\n" +
	"\n" +
	"deliveries\x18\x01 \x03(\v2\x1a.lmm.core.v1.EventDeliveryR\n" +
	"deliveries\"v\n" +
	"\x17AcknowledgeEventRequest\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12\x1f\n" +
	"\vlease_token\x18\x03 \x01(\fR\n" +
	"leaseToken\"M\n" +
	"\x18AcknowledgeEventResponse\x121\n" +
	"\x14already_acknowledged\x18\x01 \x01(\bR\x13alreadyAcknowledged\"\xa7\x01\n" +
	"\x11RetryEventRequest\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12\x1f\n" +
	"\vlease_token\x18\x03 \x01(\fR\n" +
	"leaseToken\x125\n" +
	"\x06reason\x18\x04 \x01(\x0e2\x1d.lmm.core.v1.EventRetryReasonR\x06reason\"G\n" +
	"\x12RetryEventResponse\x121\n" +
	"\x14already_acknowledged\x18\x01 \x01(\bR\x13alreadyAcknowledged*\xb7\x01\n" +
	"\x10EventRetryReason\x12\"\n" +
	"\x1eEVENT_RETRY_REASON_UNSPECIFIED\x10\x00\x12&\n" +
	"\"EVENT_RETRY_REASON_HANDLER_FAILURE\x10\x01\x12(\n" +
	"$EVENT_RETRY_REASON_UNSUPPORTED_EVENT\x10\x02\x12-\n" +
	")EVENT_RETRY_REASON_DEPENDENCY_UNAVAILABLE\x10\x032\xd3\x02\n" +
	"\n" +
	"CoreEvents\x12V\n" +
	"\tNegotiate\x12#.lmm.core.v1.NegotiateEventsRequest\x1a$.lmm.core.v1.NegotiateEventsResponse\x12G\n" +
	"\x04Pull\x12\x1e.lmm.core.v1.PullEventsRequest\x1a\x1f.lmm.core.v1.PullEventsResponse\x12Z\n" +
	"\vAcknowledge\x12$.lmm.core.v1.AcknowledgeEventRequest\x1a%.lmm.core.v1.AcknowledgeEventResponse\x12H\n" +
	"\x05Retry\x12\x1e.lmm.core.v1.RetryEventRequest\x1a\x1f.lmm.core.v1.RetryEventResponseBLZJgithub.com/TokenNotIncluded/api.lmm.best/extensions/internal/corepb;corepbb\x06proto3"

var (
	file_lmm_core_v1_events_proto_rawDescOnce sync.Once
	file_lmm_core_v1_events_proto_rawDescData []byte
)

func file_lmm_core_v1_events_proto_rawDescGZIP() []byte {
	file_lmm_core_v1_events_proto_rawDescOnce.Do(func() {
		file_lmm_core_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lmm_core_v1_events_proto_rawDesc), len(file_lmm_core_v1_events_proto_rawDesc)))
	})
	return file_lmm_core_v1_events_proto_rawDescData
}

var file_lmm_core_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lmm_core_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_lmm_core_v1_events_proto_goTypes = []any{
	(EventRetryReason)(0),            // 0: lmm.core.v1.EventRetryReason
	(*EventClientVersion)(nil),       // 1: lmm.core.v1.EventClientVersion
	(*NegotiateEventsRequest)(nil),   // 2: lmm.core.v1.NegotiateEventsRequest
	(*NegotiateEventsResponse)(nil),  // 3: lmm.core.v1.NegotiateEventsResponse
	(*EventEnvelope)(nil),            // 4: lmm.core.v1.EventEnvelope
	(*EventDelivery)(nil),            // 5: lmm.core.v1.EventDelivery
	(*PullEventsRequest)(nil),        // 6: lmm.core.v1.PullEventsRequest
	(*PullEventsResponse)(nil),       // 7: lmm.core.v1.PullEventsResponse
	(*AcknowledgeEventRequest)(nil),  // 8: lmm.core.v1.AcknowledgeEventRequest
	(*AcknowledgeEventResponse)(nil), // 9: lmm.core.v1.AcknowledgeEventResponse
	(*RetryEventRequest)(nil),        // 10: lmm.core.v1.RetryEventRequest
	(*RetryEventResponse)(nil),       // 11: lmm.core.v1.RetryEventResponse
}
var file_lmm_core_v1_events_proto_depIdxs = []int32{
	1,  // 0: lmm.core.v1.NegotiateEventsRequest.version:type_name -> lmm.core.v1.EventClientVersion
	4,  // 1: lmm.core.v1.EventDelivery.event:type_name -> lmm.core.v1.EventEnvelope
	1,  // 2: lmm.core.v1.PullEventsRequest.version:type_name -> lmm.core.v1.EventClientVersion
	5,  // 3: lmm.core.v1.PullEventsResponse.deliveries:type_name -> lmm.core.v1.EventDelivery
	0,  // 4: lmm.core.v1.RetryEventRequest.reason:type_name -> lmm.core.v1.EventRetryReason
	2,  // 5: lmm.core.v1.CoreEvents.Negotiate:input_type -> lmm.core.v1.NegotiateEventsRequest
	6,  // 6: lmm.core.v1.CoreEvents.Pull:input_type -> lmm.core.v1.PullEventsRequest
	8,  // 7: lmm.core.v1.CoreEvents.Acknowledge:input_type -> lmm.core.v1.AcknowledgeEventRequest
	10, // 8: lmm.core.v1.CoreEvents.Retry:input_type -> lmm.core.v1.RetryEventRequest
	3,  // 9: lmm.core.v1.CoreEvents.Negotiate:output_type -> lmm.core.v1.NegotiateEventsResponse
	7,  // 10: lmm.core.v1.CoreEvents.Pull:output_type -> lmm.core.v1.PullEventsResponse
	9,  // 11: lmm.core.v1.CoreEvents.Acknowledge:output_type -> lmm.core.v1.AcknowledgeEventResponse
	11, // 12: lmm.core.v1.CoreEvents.Retry:output_type -> lmm.core.v1.RetryEventResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_lmm_core_v1_events_proto_init() }
func file_lmm_core_v1_events_proto_init() {
	if File_lmm_core_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lmm_core_v1_events_proto_rawDesc), len(file_lmm_core_v1_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lmm_core_v1_events_proto_goTypes,
		DependencyIndexes: file_lmm_core_v1_events_proto_depIdxs,
		EnumInfos:         file_lmm_core_v1_events_proto_enumTypes,
		MessageInfos:      file_lmm_core_v1_events_proto_msgTypes,
	}.Build()
	File_lmm_core_v1_events_proto = out.File
	file_lmm_core_v1_events_proto_goTypes = nil
	file_lmm_core_v1_events_proto_depIdxs = nil
}
