// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// protoc: proto3 compiler (version header normalized)
// source: lmm/core/v1/ledger.proto

package corepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostLedgerRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProtocolMajor     uint32                 `protobuf:"varint,1,opt,name=protocol_major,json=protocolMajor,proto3" json:"protocol_major,omitempty"` // Must be 1; unknown action fails closed.
	Mutation          *MutationContext       `protobuf:"bytes,2,opt,name=mutation,proto3" json:"mutation,omitempty"`
	Unit              string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`                                                    // Exactly credit_500k_usd: 500,000 integer units = USD 1.
	BusinessReference string                 `protobuf:"bytes,4,opt,name=business_reference,json=businessReference,proto3" json:"business_reference,omitempty"` // Stable, bounded reference; not authorization.
	AuditReason       string                 `protobuf:"bytes,5,opt,name=audit_reason,json=auditReason,proto3" json:"audit_reason,omitempty"`                   // Bounded text, no secrets.
	// Scope and actor come from independent service/user authentication, never a
	// supplied actor ID. Each action has a separate ledger.<action> permission.
	//
	// Types that are valid to be assigned to Action:
	//
	//	*PostLedgerRequest_Credit
	//	*PostLedgerRequest_Transfer
	//	*PostLedgerRequest_Charge
	//	*PostLedgerRequest_Reserve
	//	*PostLedgerRequest_Capture
	//	*PostLedgerRequest_Release
	//	*PostLedgerRequest_Refund
	//	*PostLedgerRequest_Reverse
	Action        isPostLedgerRequest_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostLedgerRequest) Reset() {
	*x = PostLedgerRequest{}
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostLedgerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostLedgerRequest) ProtoMessage() {}

func (x *PostLedgerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostLedgerRequest.ProtoReflect.Descriptor instead.
func (*PostLedgerRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *PostLedgerRequest) GetProtocolMajor() uint32 {
	if x != nil {
		return x.ProtocolMajor
	}
	return 0
}

func (x *PostLedgerRequest) GetMutation() *MutationContext {
	if x != nil {
		return x.Mutation
	}
	return nil
}

func (x *PostLedgerRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *PostLedgerRequest) GetBusinessReference() string {
	if x != nil {
		return x.BusinessReference
	}
	return ""
}

func (x *PostLedgerRequest) GetAuditReason() string {
	if x != nil {
		return x.AuditReason
	}
	return ""
}

func (x *PostLedgerRequest) GetAction() isPostLedgerRequest_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *PostLedgerRequest) GetCredit() *LedgerCredit {
	if x != nil {
		if x, ok := x.Action.(*PostLedgerRequest_Credit); ok {
			return x.Credit
		}
	}
	return nil
}

func (x *PostLedgerRequest) GetTransfer() *LedgerTransfer {
	if x != nil {
		if x, ok := x.Action.(*PostLedgerRequest_Transfer); ok {
			return x.Transfer
		}
	}
	return nil
}

func (x *PostLedgerRequest) GetCharge() *LedgerCharge {
	if x != nil {
		if x, ok := x.Action.(*PostLedgerRequest_Charge); ok {
			return x.Charge
		}
	}
	return nil
}

func (x *PostLedgerRequest) GetReserve() *LedgerReserve {
	if x != nil {
		if x, ok := x.Action.(*PostLedgerRequest_Reserve); ok {
			return x.Reserve
		}
	}
	return nil
}

func (x *PostLedgerRequest) GetCapture() *LedgerCapture {
	if x != nil {
		if x, ok := x.Action.(*PostLedgerRequest_Capture); ok {
			return x.Capture
		}
	}
	return nil
}

func (x *PostLedgerRequest) GetRelease() *LedgerRelease {
	if x != nil {
		if x, ok := x.Action.(*PostLedgerRequest_Release); ok {
			return x.Release
		}
	}
	return nil
}

func (x *PostLedgerRequest) GetRefund() *LedgerRefund {
	if x != nil {
		if x, ok := x.Action.(*PostLedgerRequest_Refund); ok {
			return x.Refund
		}
	}
	return nil
}

func (x *PostLedgerRequest) GetReverse() *LedgerReverse {
	if x != nil {
		if x, ok := x.Action.(*PostLedgerRequest_Reverse); ok {
			return x.Reverse
		}
	}
	return nil
}

type isPostLedgerRequest_Action interface {
	isPostLedgerRequest_Action()
}

type PostLedgerRequest_Credit struct {
	Credit *LedgerCredit `protobuf:"bytes,10,opt,name=credit,proto3,oneof"`
}

type PostLedgerRequest_Transfer struct {
	Transfer *LedgerTransfer `protobuf:"bytes,11,opt,name=transfer,proto3,oneof"`
}

type PostLedgerRequest_Charge struct {
	Charge *LedgerCharge `protobuf:"bytes,12,opt,name=charge,proto3,oneof"`
}

type PostLedgerRequest_Reserve struct {
	Reserve *LedgerReserve `protobuf:"bytes,13,opt,name=reserve,proto3,oneof"`
}

type PostLedgerRequest_Capture struct {
	Capture *LedgerCapture `protobuf:"bytes,14,opt,name=capture,proto3,oneof"`
}

type PostLedgerRequest_Release struct {
	Release *LedgerRelease `protobuf:"bytes,15,opt,name=release,proto3,oneof"`
}

type PostLedgerRequest_Refund struct {
	Refund *LedgerRefund `protobuf:"bytes,16,opt,name=refund,proto3,oneof"`
}

type PostLedgerRequest_Reverse struct {
	Reverse *LedgerReverse `protobuf:"bytes,17,opt,name=reverse,proto3,oneof"`
}

func (*PostLedgerRequest_Credit) isPostLedgerRequest_Action() {}

func (*PostLedgerRequest_Transfer) isPostLedgerRequest_Action() {}

func (*PostLedgerRequest_Charge) isPostLedgerRequest_Action() {}

func (*PostLedgerRequest_Reserve) isPostLedgerRequest_Action() {}

func (*PostLedgerRequest_Capture) isPostLedgerRequest_Action() {}

func (*PostLedgerRequest_Release) isPostLedgerRequest_Action() {}

func (*PostLedgerRequest_Refund) isPostLedgerRequest_Action() {}

func (*PostLedgerRequest_Reverse) isPostLedgerRequest_Action() {}

type LedgerCredit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Core-verified record fixes account, amount, conversion and globally unique
	// provider/merchant/environment/transaction. No caller-chosen credit amount.
	VerifiedPaymentId int64 `protobuf:"varint,1,opt,name=verified_payment_id,json=verifiedPaymentId,proto3" json:"verified_payment_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LedgerCredit) Reset() {
	*x = LedgerCredit{}
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerCredit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerCredit) ProtoMessage() {}

func (x *LedgerCredit) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerCredit.ProtoReflect.Descriptor instead.
func (*LedgerCredit) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *LedgerCredit) GetVerifiedPaymentId() int64 {
	if x != nil {
		return x.VerifiedPaymentId
	}
	return 0
}

type LedgerTransfer struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SourceAccountId      int64                  `protobuf:"varint,1,opt,name=source_account_id,json=sourceAccountId,proto3" json:"source_account_id,omitempty"` // core_identity.accounts.id, NOT user/team ID.
	DestinationAccountId int64                  `protobuf:"varint,2,opt,name=destination_account_id,json=destinationAccountId,proto3" json:"destination_account_id,omitempty"`
	Amount               int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"` // Positive units. Check both ownership and treasury scope.
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LedgerTransfer) Reset() {
	*x = LedgerTransfer{}
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerTransfer) ProtoMessage() {}

func (x *LedgerTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerTransfer.ProtoReflect.Descriptor instead.
func (*LedgerTransfer) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *LedgerTransfer) GetSourceAccountId() int64 {
	if x != nil {
		return x.SourceAccountId
	}
	return 0
}

func (x *LedgerTransfer) GetDestinationAccountId() int64 {
	if x != nil {
		return x.DestinationAccountId
	}
	return 0
}

func (x *LedgerTransfer) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type LedgerCharge struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	BillingAuthorizationId int64                  `protobuf:"varint,1,opt,name=billing_authorization_id,json=billingAuthorizationId,proto3" json:"billing_authorization_id,omitempty"` // Core-owned durable single-use grant.
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LedgerCharge) Reset() {
	*x = LedgerCharge{}
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerCharge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerCharge) ProtoMessage() {}

func (x *LedgerCharge) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerCharge.ProtoReflect.Descriptor instead.
func (*LedgerCharge) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *LedgerCharge) GetBillingAuthorizationId() int64 {
	if x != nil {
		return x.BillingAuthorizationId
	}
	return 0
}

type LedgerReserve struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	BillingAuthorizationId int64                  `protobuf:"varint,1,opt,name=billing_authorization_id,json=billingAuthorizationId,proto3" json:"billing_authorization_id,omitempty"` // Fixes payer, amount and all budget holds.
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LedgerReserve) Reset() {
	*x = LedgerReserve{}
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerReserve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerReserve) ProtoMessage() {}

func (x *LedgerReserve) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerReserve.ProtoReflect.Descriptor instead.
func (*LedgerReserve) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *LedgerReserve) GetBillingAuthorizationId() int64 {
	if x != nil {
		return x.BillingAuthorizationId
	}
	return 0
}

type LedgerCapture struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ReservationJournalId int64                  `protobuf:"varint,1,opt,name=reservation_journal_id,json=reservationJournalId,proto3" json:"reservation_journal_id,omitempty"`
	VerifiedUsageId      int64                  `protobuf:"varint,2,opt,name=verified_usage_id,json=verifiedUsageId,proto3" json:"verified_usage_id,omitempty"` // Core computes amount; zero final charge is valid.
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LedgerCapture) Reset() {
	*x = LedgerCapture{}
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerCapture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerCapture) ProtoMessage() {}

func (x *LedgerCapture) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerCapture.ProtoReflect.Descriptor instead.
func (*LedgerCapture) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *LedgerCapture) GetReservationJournalId() int64 {
	if x != nil {
		return x.ReservationJournalId
	}
	return 0
}

func (x *LedgerCapture) GetVerifiedUsageId() int64 {
	if x != nil {
		return x.VerifiedUsageId
	}
	return 0
}

type LedgerRelease struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ReservationJournalId      int64                  `protobuf:"varint,1,opt,name=reservation_journal_id,json=reservationJournalId,proto3" json:"reservation_journal_id,omitempty"`
	TerminalRequestEvidenceId int64                  `protobuf:"varint,2,opt,name=terminal_request_evidence_id,json=terminalRequestEvidenceId,proto3" json:"terminal_request_evidence_id,omitempty"` // Timeout alone does not allow release.
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *LedgerRelease) Reset() {
	*x = LedgerRelease{}
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerRelease) ProtoMessage() {}

func (x *LedgerRelease) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerRelease.ProtoReflect.Descriptor instead.
func (*LedgerRelease) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *LedgerRelease) GetReservationJournalId() int64 {
	if x != nil {
		return x.ReservationJournalId
	}
	return 0
}

func (x *LedgerRelease) GetTerminalRequestEvidenceId() int64 {
	if x != nil {
		return x.TerminalRequestEvidenceId
	}
	return 0
}

type LedgerRefund struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OriginalJournalId int64                  `protobuf:"varint,1,opt,name=original_journal_id,json=originalJournalId,proto3" json:"original_journal_id,omitempty"`
	Amount            int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` // Positive; cumulative cap; destination fixed by original.
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LedgerRefund) Reset() {
	*x = LedgerRefund{}
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerRefund) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerRefund) ProtoMessage() {}

func (x *LedgerRefund) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerRefund.ProtoReflect.Descriptor instead.
func (*LedgerRefund) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_ledger_proto_rawDescGZIP(), []int{7}
}

func (x *LedgerRefund) GetOriginalJournalId() int64 {
	if x != nil {
		return x.OriginalJournalId
	}
	return 0
}

func (x *LedgerRefund) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type LedgerReverse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OriginalJournalId int64                  `protobuf:"varint,1,opt,name=original_journal_id,json=originalJournalId,proto3" json:"original_journal_id,omitempty"` // Narrow reconciliation/admin permission only.
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LedgerReverse) Reset() {
	*x = LedgerReverse{}
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerReverse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerReverse) ProtoMessage() {}

func (x *LedgerReverse) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerReverse.ProtoReflect.Descriptor instead.
func (*LedgerReverse) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_ledger_proto_rawDescGZIP(), []int{8}
}

func (x *LedgerReverse) GetOriginalJournalId() int64 {
	if x != nil {
		return x.OriginalJournalId
	}
	return 0
}

type PostLedgerResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	RequestSha256  []byte                 `protobuf:"bytes,2,opt,name=request_sha256,json=requestSha256,proto3" json:"request_sha256,omitempty"` // Core-computed canonical request, including actor.
	ReceiptId      string                 `protobuf:"bytes,3,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`             // Stable across retries, including permanent rejection.
	// Types that are valid to be assigned to Outcome:
	//
	//	*PostLedgerResponse_Posted
	//	*PostLedgerResponse_Rejected
	Outcome       isPostLedgerResponse_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostLedgerResponse) Reset() {
	*x = PostLedgerResponse{}
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostLedgerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostLedgerResponse) ProtoMessage() {}

func (x *PostLedgerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostLedgerResponse.ProtoReflect.Descriptor instead.
func (*PostLedgerResponse) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_ledger_proto_rawDescGZIP(), []int{9}
}

func (x *PostLedgerResponse) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *PostLedgerResponse) GetRequestSha256() []byte {
	if x != nil {
		return x.RequestSha256
	}
	return nil
}

func (x *PostLedgerResponse) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

func (x *PostLedgerResponse) GetOutcome() isPostLedgerResponse_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *PostLedgerResponse) GetPosted() *LedgerPosted {
	if x != nil {
		if x, ok := x.Outcome.(*PostLedgerResponse_Posted); ok {
			return x.Posted
		}
	}
	return nil
}

func (x *PostLedgerResponse) GetRejected() *LedgerRejected {
	if x != nil {
		if x, ok := x.Outcome.(*PostLedgerResponse_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

type isPostLedgerResponse_Outcome interface {
	isPostLedgerResponse_Outcome()
}

type PostLedgerResponse_Posted struct {
	Posted *LedgerPosted `protobuf:"bytes,10,opt,name=posted,proto3,oneof"`
}

type PostLedgerResponse_Rejected struct {
	Rejected *LedgerRejected `protobuf:"bytes,11,opt,name=rejected,proto3,oneof"`
}

func (*PostLedgerResponse_Posted) isPostLedgerResponse_Outcome() {}

func (*PostLedgerResponse_Rejected) isPostLedgerResponse_Outcome() {}

type LedgerPosted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JournalId     int64                  `protobuf:"varint,1,opt,name=journal_id,json=journalId,proto3" json:"journal_id,omitempty"`
	Unit          string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Entries       []*LedgerEntrySnapshot `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerPosted) Reset() {
	*x = LedgerPosted{}
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerPosted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerPosted) ProtoMessage() {}

func (x *LedgerPosted) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerPosted.ProtoReflect.Descriptor instead.
func (*LedgerPosted) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_ledger_proto_rawDescGZIP(), []int{10}
}

func (x *LedgerPosted) GetJournalId() int64 {
	if x != nil {
		return x.JournalId
	}
	return 0
}

func (x *LedgerPosted) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *LedgerPosted) GetEntries() []*LedgerEntrySnapshot {
	if x != nil {
		return x.Entries
	}
	return nil
}

type LedgerEntrySnapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LedgerAccountId  int64                  `protobuf:"varint,1,opt,name=ledger_account_id,json=ledgerAccountId,proto3" json:"ledger_account_id,omitempty"`
	OwnerAccountId   int64                  `protobuf:"varint,2,opt,name=owner_account_id,json=ownerAccountId,proto3" json:"owner_account_id,omitempty"`
	Delta            int64                  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	ResultingBalance int64                  `protobuf:"varint,4,opt,name=resulting_balance,json=resultingBalance,proto3" json:"resulting_balance,omitempty"`
	Revision         int64                  `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LedgerEntrySnapshot) Reset() {
	*x = LedgerEntrySnapshot{}
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerEntrySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerEntrySnapshot) ProtoMessage() {}

func (x *LedgerEntrySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerEntrySnapshot.ProtoReflect.Descriptor instead.
func (*LedgerEntrySnapshot) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_ledger_proto_rawDescGZIP(), []int{11}
}

func (x *LedgerEntrySnapshot) GetLedgerAccountId() int64 {
	if x != nil {
		return x.LedgerAccountId
	}
	return 0
}

func (x *LedgerEntrySnapshot) GetOwnerAccountId() int64 {
	if x != nil {
		return x.OwnerAccountId
	}
	return 0
}

func (x *LedgerEntrySnapshot) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *LedgerEntrySnapshot) GetResultingBalance() int64 {
	if x != nil {
		return x.ResultingBalance
	}
	return 0
}

func (x *LedgerEntrySnapshot) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type LedgerRejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // Stable domain code; permanent result for this exact key.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerRejected) Reset() {
	*x = LedgerRejected{}
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerRejected) ProtoMessage() {}

func (x *LedgerRejected) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerRejected.ProtoReflect.Descriptor instead.
func (*LedgerRejected) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_ledger_proto_rawDescGZIP(), []int{12}
}

func (x *LedgerRejected) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetLedgerBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // Require ledger.read and current account authorization.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerBalanceRequest) Reset() {
	*x = GetLedgerBalanceRequest{}
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerBalanceRequest) ProtoMessage() {}

func (x *GetLedgerBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetLedgerBalanceRequest) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_ledger_proto_rawDescGZIP(), []int{13}
}

func (x *GetLedgerBalanceRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type GetLedgerBalanceResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AccountId         int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Unit              string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Available         int64                  `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	Held              int64                  `protobuf:"varint,4,opt,name=held,proto3" json:"held,omitempty"`
	AvailableRevision int64                  `protobuf:"varint,5,opt,name=available_revision,json=availableRevision,proto3" json:"available_revision,omitempty"`
	HeldRevision      int64                  `protobuf:"varint,6,opt,name=held_revision,json=heldRevision,proto3" json:"held_revision,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetLedgerBalanceResponse) Reset() {
	*x = GetLedgerBalanceResponse{}
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerBalanceResponse) ProtoMessage() {}

func (x *GetLedgerBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetLedgerBalanceResponse) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_ledger_proto_rawDescGZIP(), []int{14}
}

func (x *GetLedgerBalanceResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *GetLedgerBalanceResponse) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *GetLedgerBalanceResponse) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *GetLedgerBalanceResponse) GetHeld() int64 {
	if x != nil {
		return x.Held
	}
	return 0
}

func (x *GetLedgerBalanceResponse) GetAvailableRevision() int64 {
	if x != nil {
		return x.AvailableRevision
	}
	return 0
}

func (x *GetLedgerBalanceResponse) GetHeldRevision() int64 {
	if x != nil {
		return x.HeldRevision
	}
	return 0
}

type LedgerPostedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReceiptId      string                 `protobuf:"bytes,1,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Posted         *LedgerPosted          `protobuf:"bytes,3,opt,name=posted,proto3" json:"posted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LedgerPostedEvent) Reset() {
	*x = LedgerPostedEvent{}
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerPostedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerPostedEvent) ProtoMessage() {}

func (x *LedgerPostedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_lmm_core_v1_ledger_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerPostedEvent.ProtoReflect.Descriptor instead.
func (*LedgerPostedEvent) Descriptor() ([]byte, []int) {
	return file_lmm_core_v1_ledger_proto_rawDescGZIP(), []int{15}
}

func (x *LedgerPostedEvent) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

func (x *LedgerPostedEvent) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *LedgerPostedEvent) GetPosted() *LedgerPosted {
	if x != nil {
		return x.Posted
	}
	return nil
}

var File_lmm_core_v1_ledger_proto protoreflect.FileDescriptor

const file_lmm_core_v1_ledger_proto_rawDesc = "" +
	"\n" +
	"\x18lmm/core/v1/ledger.proto\x12\vlmm.core.v1\x1a\x1almm/core/v1/commands.proto\"\x9e\x05\n" +
	"\x11PostLedgerRequest\x12%\n" +
	"\x0eprotocol_major\x18\x01 \x01(\rR\rprotocolMajor\x128\n" +
	"\bmutation\x18\x02 \x01(\v2\x1c.lmm.core.v1.MutationContextR\bmutation\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12-\n" +
	"\x12business_reference\x18\x04 \x01(\tR\x11businessReference\x12!\n" +
	"\faudit_reason\x18\x05 \x01(\tR\vauditReason\x123\n" +
	"\x06credit\x18\n" +
	" \x01(\v2\x19.lmm.core.v1.LedgerCreditH\x00R\x06credit\x129\n" +
	"\btransfer\x18\v \x01(\v2\x1b.lmm.core.v1.LedgerTransferH\x00R\btransfer\x123\n" +
	"\x06charge\x18\f \x01(\v2\x19.lmm.core.v1.LedgerChargeH\x00R\x06charge\x126\n" +
	"\areserve\x18\r \x01(\v2\x1a.lmm.core.v1.LedgerReserveH\x00R\areserve\x126\n" +
	"\acapture\x18\x0e \x01(\v2\x1a.lmm.core.v1.LedgerCaptureH\x00R\acapture\x126\n" +
	"\arelease\x18\x0f \x01(\v2\x1a.lmm.core.v1.LedgerReleaseH\x00R\arelease\x123\n" +
	"\x06refund\x18\x10 \x01(\v2\x19.lmm.core.v1.LedgerRefundH\x00R\x06refund\x126\n" +
	"\areverse\x18\x11 \x01(\v2\x1a.lmm.core.v1.LedgerReverseH\x00R\areverseB\b\n" +
	"\x06action\">\n" +
	"\fLedgerCredit\x12.\n" +
	"\x13verified_payment_id\x18\x01 \x01(\x03R\x11verifiedPaymentId\"\x8a\x01\n" +
	"\x0eLedgerTransfer\x12*\n" +
	"\x11source_account_id\x18\x01 \x01(\x03R\x0fsourceAccountId\x124\n" +
	"\x16destination_account_id\x18\x02 \x01(\x03R\x14destinationAccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"H\n" +
	"\fLedgerCharge\x128\n" +
	"\x18billing_authorization_id\x18\x01 \x01(\x03R\x16billingAuthorizationId\"I\n" +
	"\rLedgerReserve\x128\n" +
	"\x18billing_authorization_id\x18\x01 \x01(\x03R\x16billingAuthorizationId\"q\n" +
	"\rLedgerCapture\x124\n" +
	"\x16reservation_journal_id\x18\x01 \x01(\x03R\x14reservationJournalId\x12*\n" +
	"\x11verified_usage_id\x18\x02 \x01(\x03R\x0fverifiedUsageId\"\x86\x01\n" +
	"\rLedgerRelease\x124\n" +
	"\x16reservation_journal_id\x18\x01 \x01(\x03R\x14reservationJournalId\x12?\n" +
	"\x1cterminal_request_evidence_id\x18\x02 \x01(\x03R\x19terminalRequestEvidenceId\"V\n" +
	"\fLedgerRefund\x12.\n" +
	"\x13original_journal_id\x18\x01 \x01(\x03R\x11originalJournalId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"?\n" +
	"\rLedgerReverse\x12.\n" +
	"\x13original_journal_id\x18\x01 \x01(\x03R\x11originalJournalId\"\xfe\x01\n" +
	"\x12PostLedgerResponse\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x0erequest_sha256\x18\x02 \x01(\fR\rrequestSha256\x12\x1d\n" +
	"\n" +
	"receipt_id\x18\x03 \x01(\tR\treceiptId\x123\n" +
	"\x06posted\x18\n" +
	" \x01(\v2\x19.lmm.core.v1.LedgerPostedH\x00R\x06posted\x129\n" +
	"\brejected\x18\v \x01(\v2\x1b.lmm.core.v1.LedgerRejectedH\x00R\brejectedB\t\n" +
	"\aoutcome\"}\n" +
	"\fLedgerPosted\x12\x1d\n" +
	"\n" +
	"journal_id\x18\x01 \x01(\x03R\tjournalId\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12:\n" +
	"\aentries\x18\x03 \x03(\v2 .lmm.core.v1.LedgerEntrySnapshotR\aentries\"\xca\x01\n" +
	"\x13LedgerEntrySnapshot\x12*\n" +
	"\x11ledger_account_id\x18\x01 \x01(\x03R\x0fledgerAccountId\x12(\n" +
	"\x10owner_account_id\x18\x02 \x01(\x03R\x0eownerAccountId\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x03R\x05delta\x12+\n" +
	"\x11resulting_balance\x18\x04 \x01(\x03R\x10resultingBalance\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\x03R\brevision\"$\n" +
	"\x0eLedgerRejected\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"8\n" +
	"\x17GetLedgerBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\"\xd3\x01\n" +
	"\x18GetLedgerBalanceResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\x03R\tavailable\x12\x12\n" +
	"\x04held\x18\x04 \x01(\x03R\x04held\x12-\n" +
	"\x12available_revision\x18\x05 \x01(\x03R\x11availableRevision\x12#\n" +
	"\rheld_revision\x18\x06 \x01(\x03R\fheldRevision\"\x8e\x01\n" +
	"\x11LedgerPostedEvent\x12\x1d\n" +
	"\n" +
	"receipt_id\x18\x01 \x01(\tR\treceiptId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x121\n" +
	"\x06posted\x18\x03 \x01(\v2\x19.lmm.core.v1.LedgerPostedR\x06posted2\xbc\x01\n" +
	"\n" +
	"CoreLedger\x12M\n" +
	"\n" +
	"PostLedger\x12\x1e.lmm.core.v1.PostLedgerRequest\x1a\x1f.lmm.core.v1.PostLedgerResponse\x12_\n" +
	"\x10GetLedgerBalance\x12$.lmm.core.v1.GetLedgerBalanceRequest\x1a%.lmm.core.v1.GetLedgerBalanceResponseBLZJgithub.com/TokenNotIncluded/api.lmm.best/extensions/internal/corepb;corepbb\x06proto3"

var (
	file_lmm_core_v1_ledger_proto_rawDescOnce sync.Once
	file_lmm_core_v1_ledger_proto_rawDescData []byte
)

func file_lmm_core_v1_ledger_proto_rawDescGZIP() []byte {
	file_lmm_core_v1_ledger_proto_rawDescOnce.Do(func() {
		file_lmm_core_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lmm_core_v1_ledger_proto_rawDesc), len(file_lmm_core_v1_ledger_proto_rawDesc)))
	})
	return file_lmm_core_v1_ledger_proto_rawDescData
}

var file_lmm_core_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_lmm_core_v1_ledger_proto_goTypes = []any{
	(*PostLedgerRequest)(nil),        // 0: lmm.core.v1.PostLedgerRequest
	(*LedgerCredit)(nil),             // 1: lmm.core.v1.LedgerCredit
	(*LedgerTransfer)(nil),           // 2: lmm.core.v1.LedgerTransfer
	(*LedgerCharge)(nil),             // 3: lmm.core.v1.LedgerCharge
	(*LedgerReserve)(nil),            // 4: lmm.core.v1.LedgerReserve
	(*LedgerCapture)(nil),            // 5: lmm.core.v1.LedgerCapture
	(*LedgerRelease)(nil),            // 6: lmm.core.v1.LedgerRelease
	(*LedgerRefund)(nil),             // 7: lmm.core.v1.LedgerRefund
	(*LedgerReverse)(nil),            // 8: lmm.core.v1.LedgerReverse
	(*PostLedgerResponse)(nil),       // 9: lmm.core.v1.PostLedgerResponse
	(*LedgerPosted)(nil),             // 10: lmm.core.v1.LedgerPosted
	(*LedgerEntrySnapshot)(nil),      // 11: lmm.core.v1.LedgerEntrySnapshot
	(*LedgerRejected)(nil),           // 12: lmm.core.v1.LedgerRejected
	(*GetLedgerBalanceRequest)(nil),  // 13: lmm.core.v1.GetLedgerBalanceRequest
	(*GetLedgerBalanceResponse)(nil), // 14: lmm.core.v1.GetLedgerBalanceResponse
	(*LedgerPostedEvent)(nil),        // 15: lmm.core.v1.LedgerPostedEvent
	(*MutationContext)(nil),          // 16: lmm.core.v1.MutationContext
}
var file_lmm_core_v1_ledger_proto_depIdxs = []int32{
	16, // 0: lmm.core.v1.PostLedgerRequest.mutation:type_name -> lmm.core.v1.MutationContext
	1,  // 1: lmm.core.v1.PostLedgerRequest.credit:type_name -> lmm.core.v1.LedgerCredit
	2,  // 2: lmm.core.v1.PostLedgerRequest.transfer:type_name -> lmm.core.v1.LedgerTransfer
	3,  // 3: lmm.core.v1.PostLedgerRequest.charge:type_name -> lmm.core.v1.LedgerCharge
	4,  // 4: lmm.core.v1.PostLedgerRequest.reserve:type_name -> lmm.core.v1.LedgerReserve
	5,  // 5: lmm.core.v1.PostLedgerRequest.capture:type_name -> lmm.core.v1.LedgerCapture
	6,  // 6: lmm.core.v1.PostLedgerRequest.release:type_name -> lmm.core.v1.LedgerRelease
	7,  // 7: lmm.core.v1.PostLedgerRequest.refund:type_name -> lmm.core.v1.LedgerRefund
	8,  // 8: lmm.core.v1.PostLedgerRequest.reverse:type_name -> lmm.core.v1.LedgerReverse
	10, // 9: lmm.core.v1.PostLedgerResponse.posted:type_name -> lmm.core.v1.LedgerPosted
	12, // 10: lmm.core.v1.PostLedgerResponse.rejected:type_name -> lmm.core.v1.LedgerRejected
	11, // 11: lmm.core.v1.LedgerPosted.entries:type_name -> lmm.core.v1.LedgerEntrySnapshot
	10, // 12: lmm.core.v1.LedgerPostedEvent.posted:type_name -> lmm.core.v1.LedgerPosted
	0,  // 13: lmm.core.v1.CoreLedger.PostLedger:input_type -> lmm.core.v1.PostLedgerRequest
	13, // 14: lmm.core.v1.CoreLedger.GetLedgerBalance:input_type -> lmm.core.v1.GetLedgerBalanceRequest
	9,  // 15: lmm.core.v1.CoreLedger.PostLedger:output_type -> lmm.core.v1.PostLedgerResponse
	14, // 16: lmm.core.v1.CoreLedger.GetLedgerBalance:output_type -> lmm.core.v1.GetLedgerBalanceResponse
	15, // [15:17] is the sub-list for method output_type
	13, // [13:15] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_lmm_core_v1_ledger_proto_init() }
func file_lmm_core_v1_ledger_proto_init() {
	if File_lmm_core_v1_ledger_proto != nil {
		return
	}
	file_lmm_core_v1_commands_proto_init()
	file_lmm_core_v1_ledger_proto_msgTypes[0].OneofWrappers = []any{
		(*PostLedgerRequest_Credit)(nil),
		(*PostLedgerRequest_Transfer)(nil),
		(*PostLedgerRequest_Charge)(nil),
		(*PostLedgerRequest_Reserve)(nil),
		(*PostLedgerRequest_Capture)(nil),
		(*PostLedgerRequest_Release)(nil),
		(*PostLedgerRequest_Refund)(nil),
		(*PostLedgerRequest_Reverse)(nil),
	}
	file_lmm_core_v1_ledger_proto_msgTypes[9].OneofWrappers = []any{
		(*PostLedgerResponse_Posted)(nil),
		(*PostLedgerResponse_Rejected)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lmm_core_v1_ledger_proto_rawDesc), len(file_lmm_core_v1_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lmm_core_v1_ledger_proto_goTypes,
		DependencyIndexes: file_lmm_core_v1_ledger_proto_depIdxs,
		MessageInfos:      file_lmm_core_v1_ledger_proto_msgTypes,
	}.Build()
	File_lmm_core_v1_ledger_proto = out.File
	file_lmm_core_v1_ledger_proto_goTypes = nil
	file_lmm_core_v1_ledger_proto_depIdxs = nil
}
