#!/usr/bin/env bash
# Isolated real-TCP Go/Rust differential for GET /api/status only.
set -euo pipefail
set +x
repo_root=$(git rev-parse --show-toplevel)
legacy_revision=5418ce6b6d45ed69167b0aad53f2f595e5bc8de9
legacy_root=${LMM_GO_ORACLE_ROOT:-}
[[ -n $legacy_root ]] || { echo "LMM_GO_ORACLE_ROOT is required; set it to an absolute external immutable Go oracle tree ($legacy_revision)" >&2; exit 2; }
[[ $legacy_root == /* && -d $legacy_root && ! -L $legacy_root ]] || { echo 'LMM_GO_ORACLE_ROOT must be an absolute, non-symlink directory' >&2; exit 2; }
legacy_root=$(realpath -e -- "$legacy_root")
case "$legacy_root" in "$repo_root"|"$repo_root"/*) echo 'LMM_GO_ORACLE_ROOT must be external to the current repository' >&2; exit 2 ;; esac
approval_mode=${LMM_STATUS_APPROVAL:-0}; probe_only=${LMM_STATUS_PROBE_ONLY:-0}; keep_runtime=${LMM_KEEP_STATUS_LISTENER_RUNTIME:-0}; hold_on_fail=${LMM_STATUS_HOLD_ON_FAIL:-0}; curl_connect_timeout=2; curl_max_time=12
case "$approval_mode:$probe_only" in 0:0|1:0|0:1) ;; *) echo 'approval mode refuses probe-only' >&2; exit 2;; esac
for command in cargo curl flock git go initdb jq pg_ctl postgres psql ss valkey-cli valkey-server od sha256sum; do command -v "$command" >/dev/null || exit 1; done
[[ $(postgres --version) == *'PostgreSQL) 18.'* && -f "$legacy_root/SHA256SUMS" && -f "$legacy_root/GIT-LS-FILES-S.tsv" ]] || exit 1
(cd "$legacy_root" && sha256sum --check --status SHA256SUMS) || exit 1
go_hash=$(sha256sum "$legacy_root/SHA256SUMS" "$legacy_root/GIT-LS-FILES-S.tsv" | sha256sum | awk '{print $1}'); build_input_hash(){ (cd "$repo_root" && { printf '%s\0' apps/api-rust/Cargo.toml apps/api-rust/Cargo.lock apps/api-rust/Cargo.toml; [[ ! -f apps/api-rust/build.rs ]] || printf '%s\0' apps/api-rust/build.rs; git ls-files -co --exclude-standard -z -- apps/api-rust/src apps/api-rust/assets apps/api-rust/crates; } | while IFS= read -r -d '' path; do [[ -f $path ]] && sha256sum "$path"; done | LC_ALL=C sort | sha256sum | awk '{print $1}'); }; rust_hash=$(build_input_hash)
if [[ $probe_only == 1 ]]; then jq -cn --arg go "$go_hash" --arg rust "$rust_hash" '{test:"status-listener-differential",mode:"probe",approval_eligible:false,frozen_go_manifest_sha256:$go,rust_source_sha256:$rust,result:"passed"}'; exit 0; fi
runtime=$(mktemp -d /tmp/lmm-status-listener.XXXXXX); build=$(mktemp -d "${TMPDIR:-/tmp}/lmm-status-go.XXXXXX"); go_pid=''; rust_pid=''; go_valkey_pid=''; rust_valkey_pid=''; pg_pid=''; cleanup_started=false
exec 9>/tmp/lmm-listener-differential-heavy.lock
flock -n 9 || { echo 'another listener differential owns the heavy lock' >&2; exit 1; }
# shellcheck disable=SC2034 # start times are accessed through deliberate indirection.
start(){ awk '{print $22}' "/proc/$1/stat"; }; keep(){ local n=$1 p=$2 s; s=$(start "$p") || return; printf -v "$n" %s "$p"; printf -v "${n}_start" %s "$s"; }; alive(){ local n=$1 p s expected; p=${!n:-}; s=${n}_start; expected=${!s:-}; [[ -n $p && $(start "$p" 2>/dev/null || true) == "$expected" ]] && kill -0 "$p" 2>/dev/null; }; process_state(){ local n=$1 port=${2:-} p actual want line; p=${!n:-}; want=${n}_start; want=${!want:-}; actual=$(start "$p" 2>/dev/null || true); [[ -z $actual ]] && { echo child-exited; return; }; [[ $actual != "$want" ]] && { echo pid-start-time-mismatch; return; }; if [[ -n $port ]]; then line=$(ss -H -ltnp "sport = :$port" 2>/dev/null || true); if [[ -n $line ]] && ! owns "$port" "$p"; then echo port-owned-by-other; return; fi; fi; [[ -n $port && -z $line ]] && { echo child-not-listening; return; }; echo child-not-owned; }; stop(){ local n=$1 port=${2:-} p; p=${!n:-}; if [[ -n $p ]] && alive "$n"; then kill "$p" 2>/dev/null || true; wait "$p" 2>/dev/null || true; elif [[ -n $p ]]; then echo "cleanup: $n: refusing to signal state=$(process_state "$n" "$port") pid=$p" >&2; fi; printf -v "$n" ''; printf -v "${n}_start" ''; }; stop_pg(){ if [[ -n ${pg_pid:-} ]] && alive pg_pid && owns "$pg_port" "$pg_pid"; then pg_ctl -D "$runtime/pg" -m fast -w stop >/dev/null 2>&1 || true; elif [[ -n ${pg_pid:-} ]]; then echo "cleanup: PostgreSQL: refusing to signal state=$(process_state pg_pid "$pg_port") pid=$pg_pid" >&2; fi; pg_pid=''; }; cleanup(){ local exit_code=$? preserve=0; [[ $cleanup_started == false ]] || return "$exit_code"; cleanup_started=true; [[ $exit_code -ne 0 || $hold_on_fail == 1 || $keep_runtime == 1 ]] && preserve=1; stop go_pid "$go_port"; stop rust_pid "$rust_port"; stop go_valkey_pid "$go_valkey_port"; stop rust_valkey_pid "$rust_valkey_port"; stop_pg; if [[ $preserve == 1 ]]; then echo "runtime retained at $runtime" >&2; else case "$runtime" in /tmp/lmm-status-listener.*) rm -rf "$runtime";; esac; fi; case "$build" in "${TMPDIR:-/tmp}"/lmm-status-go.*) rm -rf "$build";; esac; return "$exit_code"; }; trap cleanup EXIT INT TERM
port(){ local p; while :; do p=$((20000 + 0x$(od -An -N2 -tx2 /dev/urandom|tr -d ' ')%35000)); [[ -z $(ss -H -ltn "sport = :$p") ]] && { echo "$p"; return; }; done; }; pg_port=$(port); go_port=$(port); rust_port=$(port); go_valkey_port=$(port); rust_valkey_port=$(port); [[ $(printf '%s\n' "$pg_port" "$go_port" "$rust_port" "$go_valkey_port" "$rust_valkey_port"|sort -u|wc -l) == 5 ]] || exit 1; port_free(){ [[ -z $(ss -H -ltn "sport = :$1" 2>/dev/null) ]]; }; for p in "$pg_port" "$go_port" "$rust_port" "$go_valkey_port" "$rust_valkey_port"; do port_free "$p" || exit 1; done
owns(){ local p=$1 id=$2 x; x=$(ss -H -ltnp "sport = :$p" 2>/dev/null||true); [[ $(wc -l<<<"$x") == 1 && $x == *"pid=$id,"* ]]; }; go_redis_startup_diagnostics(){ local ping=failed; if VALKEYCLI_AUTH="$go_secret" valkey-cli --no-auth-warning --command-timeout 1 -h 127.0.0.1 -p "$go_valkey_port" ping >/dev/null 2>&1; then ping=ok; fi; { echo 'Go listener startup diagnostics (credentials redacted):'; echo "go_http_endpoint=127.0.0.1:$go_port"; echo "go_redis_endpoint=127.0.0.1:$go_valkey_port"; echo "go_redis_authenticated_ping=$ping"; echo 'go_redis_listener_state:'; ss -H -ltnp "sport = :$go_valkey_port" 2>/dev/null || true; echo 'go_redis_connection_state:'; ss -H -tnp "sport = :$go_valkey_port or dport = :$go_valkey_port" 2>/dev/null || true; echo 'go.log tail:'; tail -n 120 "$runtime/go.log" 2>/dev/null || true; echo 'go-valkey.log tail:'; tail -n 80 "$runtime/go-valkey.log" 2>/dev/null || true; } >&2; }; wait_http(){ local p=$1 path=$2 id=$3 code; for _ in {1..240}; do if owns "$p" "$id" && code=$(curl --connect-timeout "$curl_connect_timeout" --max-time "$curl_max_time" --write-out '%{http_code}' --output /dev/null "http://127.0.0.1:$p$path" 2>/dev/null || true) && [[ $code == 200 ]]; then return; fi; sleep .05; done; if [[ ${LMM_STATUS_DEBUG_HTTP:-0} == 1 ]]; then tail -n 120 "$runtime/rust.log" >&2; fi; return 1; }
go_secret=$(od -An -N32 -tx1 /dev/urandom | tr -d ' \n'); rust_secret=$(od -An -N32 -tx1 /dev/urandom | tr -d ' \n'); go_valkey_config="$runtime/go-valkey.conf"; rust_valkey_config="$runtime/rust-valkey.conf"; umask 077; printf 'bind 127.0.0.1\nport %s\nrequirepass %s\nsave ""\nappendonly no\ndir %s\n' "$go_valkey_port" "$go_secret" "$runtime" >"$go_valkey_config"; printf 'bind 127.0.0.1\nport %s\nrequirepass %s\nsave \"\"\nappendonly no\ndir %s\n' "$rust_valkey_port" "$rust_secret" "$runtime" >"$rust_valkey_config"; valkey-server "$go_valkey_config" >"$runtime/go-valkey.log" 2>&1 & keep go_valkey_pid "$!"; valkey-server "$rust_valkey_config" >"$runtime/rust-valkey.log" 2>&1 & keep rust_valkey_pid "$!"; for _ in {1..120}; do owns "$go_valkey_port" "$go_valkey_pid" && owns "$rust_valkey_port" "$rust_valkey_pid" && valkey-cli --no-auth-warning -h 127.0.0.1 -p "$go_valkey_port" -a "$go_secret" ping >/dev/null && valkey-cli --no-auth-warning -h 127.0.0.1 -p "$rust_valkey_port" -a "$rust_secret" ping >/dev/null && break; sleep .05; done; valkey-cli --no-auth-warning -h 127.0.0.1 -p "$go_valkey_port" -a "$go_secret" ping >/dev/null; valkey-cli --no-auth-warning -h 127.0.0.1 -p "$rust_valkey_port" -a "$rust_secret" ping >/dev/null
cargo build --manifest-path "$repo_root/apps/api-rust/Cargo.toml" -p lmm-api-rs --locked; [[ $(build_input_hash) == "$rust_hash" ]] || { echo 'Rust build inputs changed during differential' >&2; exit 1; }; rust_binary_sha256=$(sha256sum "$repo_root/apps/api-rust/target/debug/lmm-api-rs"|awk '{print $1}'); cp -a "$legacy_root/." "$build/source"; mkdir -p "$build/source/web/dist"; : >"$build/source/web/dist/index.html"; (cd "$build/source" && GOTOOLCHAIN=local CGO_ENABLED=1 go build -buildvcs=false -o "$runtime/go" .)
SQLITE_PATH="$runtime/go.db" PORT="$go_port" REDIS_CONN_STRING="" SESSION_SECRET='status-differential-synthetic-X!FixedLongSecretKey0123456789' GLOBAL_API_RATE_LIMIT_ENABLE=false TRUSTED_PROXIES=none GIN_MODE=release "$runtime/go" >"$runtime/go.log" 2>&1 & go_child=$!; if ! keep go_pid "$go_child" || ! wait_http "$go_port" /api/status "$go_pid"; then go_redis_startup_diagnostics; exit 1; fi
initdb --no-locale --encoding=UTF8 --auth=trust -D "$runtime/pg" >/dev/null; pg_ctl -D "$runtime/pg" -l "$runtime/pg.log" -o "-h 127.0.0.1 -p $pg_port -k $runtime" -w start >/dev/null; keep pg_pid "$(head -n 1 "$runtime/pg/postmaster.pid")"; owns "$pg_port" "$pg_pid" || exit 1; createdb -h 127.0.0.1 -p "$pg_port" status_diff
psql -h 127.0.0.1 -p "$pg_port" -d status_diff >/dev/null <<'SQL'
CREATE ROLE lmm_status_runtime LOGIN; CREATE TABLE lmm_schema_contract(singleton BOOLEAN PRIMARY KEY,min_reader_version BIGINT NOT NULL,max_reader_version BIGINT NOT NULL); INSERT INTO lmm_schema_contract VALUES(true,1,1); CREATE TABLE options(key TEXT PRIMARY KEY,value TEXT); CREATE TABLE custom_oauth_providers(id BIGINT PRIMARY KEY,name TEXT NOT NULL,slug TEXT NOT NULL,icon TEXT,enabled BOOLEAN,client_id TEXT,authorization_endpoint TEXT,scopes TEXT); CREATE TABLE setups(id BIGINT PRIMARY KEY); CREATE TABLE users(id BIGINT PRIMARY KEY,username TEXT,password TEXT NOT NULL,display_name TEXT,role BIGINT,status BIGINT,email TEXT,github_id TEXT,discord_id TEXT,oidc_id TEXT,wechat_id TEXT,telegram_id TEXT,"group" TEXT,quota BIGINT,used_quota BIGINT,request_count BIGINT,aff_code TEXT,aff_count BIGINT,aff_quota BIGINT,aff_history BIGINT,inviter_id BIGINT,linux_do_id TEXT,setting TEXT,stripe_customer TEXT,auth_version BIGINT,console_activated_at BIGINT,access_token TEXT,deleted_at TIMESTAMPTZ); CREATE TABLE user_sessions(sid TEXT PRIMARY KEY,user_id BIGINT,version BIGINT,user_auth_version BIGINT,status TEXT,refresh_hash CHAR(64),previous_refresh_hash TEXT,previous_valid_until BIGINT,login_method TEXT,ip TEXT,user_agent TEXT,created_at BIGINT,last_active_at BIGINT,expires_at BIGINT,revoked_at BIGINT,revoked_reason TEXT); CREATE TABLE two_fas(id BIGINT PRIMARY KEY,user_id BIGINT,is_enabled BOOLEAN,deleted_at TIMESTAMPTZ); CREATE TABLE casbin_rule(id BIGINT PRIMARY KEY,ptype TEXT,v0 TEXT,v1 TEXT,v2 TEXT,v3 TEXT); CREATE TABLE auth_flows(token_hash CHAR(64),purpose TEXT,user_id BIGINT,payload TEXT,created_at TIMESTAMPTZ,expires_at TIMESTAMPTZ,consumed_at TIMESTAMPTZ); CREATE SEQUENCE tokens_id_seq; CREATE TABLE tokens(id BIGINT PRIMARY KEY DEFAULT nextval('tokens_id_seq'),user_id BIGINT NOT NULL,key VARCHAR(128) UNIQUE,status INTEGER DEFAULT 1,name TEXT DEFAULT '',created_time BIGINT DEFAULT 0,accessed_time BIGINT DEFAULT 0,expired_time BIGINT DEFAULT -1,remain_quota BIGINT DEFAULT 0,unlimited_quota BOOLEAN DEFAULT false,model_limits_enabled BOOLEAN DEFAULT false,model_limits TEXT,allow_ips TEXT DEFAULT '',used_quota BIGINT DEFAULT 0,"group" TEXT DEFAULT '',cross_group_retry BOOLEAN DEFAULT false,deleted_at TIMESTAMPTZ); GRANT USAGE ON SCHEMA public TO lmm_status_runtime; GRANT SELECT, INSERT, UPDATE, DELETE ON lmm_schema_contract, options, custom_oauth_providers, setups, users, user_sessions, two_fas, casbin_rule, auth_flows TO lmm_status_runtime; GRANT SELECT,INSERT,UPDATE,DELETE ON tokens TO lmm_status_runtime; GRANT USAGE ON SEQUENCE tokens_id_seq TO lmm_status_runtime;
-- Empty subscription surface for the normal listener readiness probes only.
CREATE TABLE user_subscriptions (
  amount_total BIGINT, amount_used BIGINT,
  reset_amount BIGINT, renewal_amount BIGINT
);
GRANT SELECT, UPDATE ON user_subscriptions TO lmm_status_runtime;
SQL
sed "s/__LMM_APP_SCHEMA__/public/g" \
  "$repo_root/apps/api-rust/migrations/0002_open_source_bounty_schema.sql" \
  >"$runtime/bounty-forward.sql"
psql -h 127.0.0.1 -p "$pg_port" -d status_diff -v ON_ERROR_STOP=1 <<SQL
\i $runtime/bounty-forward.sql
GRANT SELECT, INSERT, UPDATE, DELETE ON
  open_source_bounty_projects,
  open_source_bounty_challenges,
  open_source_bounty_ledgers,
  open_source_bounty_disputes,
  open_source_bounty_mcp_tokens,
  open_source_bounty_mcp_confirmations,
  open_source_bounty_mcp_operations,
  open_source_bounty_rest_operations
  TO lmm_status_runtime;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE
  open_source_bounty_projects_id_seq,
  open_source_bounty_challenges_id_seq,
  open_source_bounty_ledgers_id_seq,
  open_source_bounty_disputes_id_seq,
  open_source_bounty_mcp_tokens_id_seq,
  open_source_bounty_rest_operations_id_seq
  TO lmm_status_runtime;
SQL
DATABASE_URL="postgresql://lmm_status_runtime@127.0.0.1:$pg_port/status_diff" VALKEY_URL="redis://:$rust_secret@127.0.0.1:$rust_valkey_port" LMM_RS_LISTEN_ADDR="127.0.0.1:$rust_port" LMM_RS_SLOT=blue LMM_SCHEMA_CONTRACT=1 CRYPTO_SECRET='status-differential-synthetic-X!FixedLongSecretKey0123456789' SESSION_SECRET='status-differential-synthetic-X!FixedLongSecretKey0123456789' PASSWORD_LOGIN_ENABLED=false GLOBAL_API_RATE_LIMIT_ENABLE=false VERSION=v0.0.0 "$repo_root/apps/api-rust/target/debug/lmm-api-rs" >"$runtime/rust.log" 2>&1 & keep rust_pid "$!"; wait_http "$rust_port" /readyz "$rust_pid"
db_snapshot(){ local engine=$1; if [[ $engine == go ]]; then sqlite3 -json "$runtime/go.db" 'SELECT key,value FROM options ORDER BY key'|jq -S .; else psql -h 127.0.0.1 -p "$pg_port" -d status_diff -qAt -c "SELECT COALESCE(json_agg(to_jsonb(x) ORDER BY x.key),'[]'::json) FROM (SELECT key,value FROM options)x"|jq -S .; fi; }; keys(){ valkey-cli --no-auth-warning -h 127.0.0.1 -p "$1" -a "$2" --scan|LC_ALL=C sort; }; db_snapshot go>"$runtime/go.db.before"; db_snapshot rust>"$runtime/rust.db.before"; keys "$go_valkey_port" "$go_secret">"$runtime/go.keys.before"; keys "$rust_valkey_port" "$rust_secret">"$runtime/rust.keys.before"; get(){ curl --connect-timeout "$curl_connect_timeout" --max-time "$curl_max_time" -sS -D "$2.h" -o "$2.b" -w '%{http_code}' "$1/api/status"; }; [[ $(get "http://127.0.0.1:$go_port" "$runtime/go") == 200 ]]; [[ $(get "http://127.0.0.1:$rust_port" "$runtime/rust") == 200 ]]; awk 'BEGIN{IGNORECASE=1} /^content-type:[[:space:]]*application\/json; charset=utf-8\r?$/ {c=1} /^x-new-api-version:[[:space:]]*v0\.0\.0\r?$/ {v=1} /^x-oneapi-request-id:[[:space:]]*[^[:space:]]+/ {r=1} END{exit !(c&&v&&r)}' "$runtime/go.h"; awk 'BEGIN{IGNORECASE=1} /^content-type:[[:space:]]*application\/json; charset=utf-8\r?$/ {c=1} /^x-new-api-version:[[:space:]]*v0\.0\.0\r?$/ {v=1} /^x-oneapi-request-id:[[:space:]]*[^[:space:]]+/ {r=1} END{exit !(c&&v&&r)}' "$runtime/rust.h"; jq -S 'if .data.start_time? then .data.start_time="<START_TIME>" else . end' "$runtime/go.b">"$runtime/go.json"; jq -S 'if .data.start_time? then .data.start_time="<START_TIME>" else . end' "$runtime/rust.b">"$runtime/rust.json"; diff -u "$runtime/go.json" "$runtime/rust.json"; db_snapshot go>"$runtime/go.db.after"; db_snapshot rust>"$runtime/rust.db.after"; diff -u "$runtime/go.db.before" "$runtime/go.db.after"; diff -u "$runtime/rust.db.before" "$runtime/rust.db.after"; keys "$go_valkey_port" "$go_secret">"$runtime/go.keys.after"; keys "$rust_valkey_port" "$rust_secret">"$runtime/rust.keys.after"; diff -u "$runtime/go.keys.before" "$runtime/go.keys.after"; diff -u "$runtime/rust.keys.before" "$runtime/rust.keys.after"; scenario_total=1; [[ $scenario_total == 1 ]] || exit 1
status_summary=$(jq -cn --arg go "$go_hash" --arg rust "$rust_hash" --arg binary "$rust_binary_sha256" --argjson approval "$approval_mode" '{test:"status-listener-differential",mode:"full",approval_eligible:($approval==1),real_tcp:true,scenario_count:1,routes:["GET /api/status"],frozen_go_manifest_sha256:$go,rust_source_sha256:$rust,rust_binary_sha256:$binary,result:"passed"}')
if [[ -n ${LMM_STATUS_RESULT_DIR:-} ]]; then
  [[ $LMM_STATUS_RESULT_DIR == /* && $LMM_STATUS_RESULT_DIR != *..* ]] || {
    echo 'LMM_STATUS_RESULT_DIR must be absolute and contain no ..' >&2
    exit 2
  }
  mkdir -p "$LMM_STATUS_RESULT_DIR"
  printf '%s\n' "$status_summary" >"$LMM_STATUS_RESULT_DIR/status-listener-summary.json"
  jq -cn --arg suite "status-listener-summary.json" \
    '{method:"GET",path:"/api/status",differential_verified:true,differential_scope:"status-listener",cases:1,suite_scenarios:1,suite_summary:$suite,real_tcp:true,production_access:true,approval_credit:false,differences:null,mismatch_names:[]}' \
    >"$LMM_STATUS_RESULT_DIR/status-listener-1.json"
fi
printf '%s\n' "$status_summary"
