/*
Copyright (C) 2026 LIghtJUNction

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.
*/
// Scoped copy; other pages keep their existing translations.
const en = {
  greeting: 'What will you make?',
  prompt: 'Ask a question. Start an idea.',
  explore: 'Explore',
  access: 'Unlock',
  navigation: 'Workspace views',
  unlockTitle: 'Make room for your next idea.',
  modelsNote: 'Find a model for your next request.',
  toolsNote: 'Bring LMM into the tools you use.',
  challengesNote: 'Build something together.',
  browseModels: 'Browse models',
  browseTools: 'Explore tools',
  browseChallenges: 'View challenges',
  previous: 'Previous destination',
  next: 'Next destination',
  carousel: 'carousel',
  support: 'Contact support',
  plans: 'Plans & top-ups',
  privacyNote: 'Keep passwords and API keys out of this conversation.',
  connectPi: 'Connect Pi',
  aboutYou: 'About you',
  toggleMotion: 'Pause or resume animation',
  title: 'Skip the review',
  description: 'Eligible credit unlocks L1 once the payment is credited.',
  topup: 'Top up · L1',
  apply: 'Apply for access',
  check: 'Already paid',
  remaining: 'Eligible credit needed',
  minimum: 'One eligible top-up',
  eligibility:
    'External paid top-ups only. LinuxDO Credit is excluded. Checkout shows the amount you pay.',
  review: 'Apply for access',
  reviewNote: 'Automatic paid activation is unavailable for this account.',
  unknown: 'Refresh access conditions before paying for an upgrade.',
  sync: 'No more top-ups needed',
  syncNote: 'Credit requirement met. Refresh to confirm access.',
  checking: 'Checking access…',
  waiting: 'Waiting for confirmation. Do not pay again.',
  error: 'Refresh failed. Retrying; do not pay again.',
  timeout: 'Checks stopped. Contact support before paying again.',
  help: 'Help',
  models: 'Models',
  tools: 'Tools',
  connect: 'Connect',
  challenges: 'Open source',
  conditions: 'Access details',
  privacy: 'Privacy',
  conversation: 'Conversation',
  newChat: 'New conversation',
  responding: 'Responding…',
  chatError: 'The response was interrupted. Try again or contact support.',
  stopped: 'Stopped',
  stop: 'Stop response',
  continueAction: 'Continue with assistant',
}

type Copy = typeof en
const zhCN: Copy = {
  greeting: '想做点什么？',
  prompt: '问个问题，或说说你的想法',
  explore: '探索',
  access: '开通',
  navigation: '工作区视图',
  unlockTitle: '开通开发者权限',
  modelsNote: '为下一次调用，选一个模型。',
  toolsNote: '接入你惯用的工具。',
  challengesNote: '一起把想法做出来。',
  browseModels: '查看模型',
  browseTools: '发现工具',
  browseChallenges: '参与挑战',
  previous: '上一个入口',
  next: '下一个入口',
  carousel: '轮播',
  support: '联系支持',
  plans: '套餐与充值',
  privacyNote: '请勿发送密码、API 密钥等敏感信息。',
  connectPi: '连接 Pi',
  aboutYou: '关于你',
  toggleMotion: '暂停或继续动效',
  title: '免审核',
  description: '有效充值到账并达标后，自动开通 L1。',
  topup: '充值开通 L1',
  apply: '申请开通',
  check: '我已充值',
  remaining: '还需有效额度',
  minimum: '一笔有效充值',
  eligibility:
    '仅外部付费充值计入，不含 LinuxDO Credit。实际支付金额以收银台为准。',
  review: '申请开通',
  reviewNote: '当前账户不适用充值自动开通。',
  unknown: '请先刷新开通条件，不要为升级重复付款。',
  sync: '无需继续充值',
  syncNote: '已达到额度要求，刷新确认开通状态。',
  checking: '正在确认…',
  waiting: '等待到账确认，请勿重复付款。',
  error: '刷新失败，正在重试，请勿重复付款。',
  timeout: '检查已停止，请联系客服，勿重复付款。',
  help: '帮助',
  models: '模型',
  tools: '工具',
  connect: '连接工具',
  challenges: '开源',
  conditions: '开通说明',
  privacy: '隐私',
  conversation: '对话',
  newChat: '新对话',
  responding: '正在回复…',
  chatError: '回复中断，请重试或联系支持。',
  stopped: '已停止',
  stop: '停止回复',
  continueAction: '继续办理',
}
const zhTW: Copy = {
  greeting: '想做點什麼？',
  prompt: '問個問題，或說說你的想法',
  explore: '探索',
  access: '開通',
  navigation: '工作區檢視',
  unlockTitle: '開通開發者權限',
  modelsNote: '為下一次呼叫，選一個模型。',
  toolsNote: '接入你慣用的工具。',
  challengesNote: '一起把想法做出來。',
  browseModels: '查看模型',
  browseTools: '發現工具',
  browseChallenges: '參與挑戰',
  previous: '上一個入口',
  next: '下一個入口',
  carousel: '輪播',
  support: '聯絡支援',
  plans: '方案與儲值',
  privacyNote: '請勿傳送密碼、API 金鑰等敏感資訊。',
  connectPi: '連接 Pi',
  aboutYou: '關於你',
  toggleMotion: '暫停或繼續動效',
  title: '免審核',
  description: '有效儲值到帳並達標後，自動開通 L1。',
  topup: '儲值開通 L1',
  apply: '申請開通',
  check: '我已儲值',
  remaining: '仍需有效額度',
  minimum: '一筆有效儲值',
  eligibility:
    '僅外部付費儲值計入，不含 LinuxDO Credit。實際支付金額以結帳頁為準。',
  review: '申請開通',
  reviewNote: '目前帳戶不適用儲值自動開通。',
  unknown: '請先更新開通條件，不要為升級重複付款。',
  sync: '無需繼續儲值',
  syncNote: '已達到額度要求，重新整理確認開通狀態。',
  checking: '正在確認…',
  waiting: '等待到帳確認，請勿重複付款。',
  error: '更新失敗，正在重試，請勿重複付款。',
  timeout: '檢查已停止，請聯絡客服，勿重複付款。',
  help: '幫助',
  models: '模型',
  tools: '工具',
  connect: '連接工具',
  challenges: '開源',
  conditions: '開通說明',
  privacy: '隱私',
  conversation: '對話',
  newChat: '新對話',
  responding: '正在回覆…',
  chatError: '回覆中斷，請重試或聯絡支援。',
  stopped: '已停止',
  stop: '停止回覆',
  continueAction: '繼續辦理',
}
export function getL0AccessCopy(language: string): Copy {
  const locale = language.toLowerCase().replaceAll('-', '')
  if (['zhtw', 'zhhk', 'zhhant'].includes(locale)) return zhTW
  if (locale.startsWith('zh')) return zhCN
  return en
}
