/*
Copyright (C) 2026 LIghtJUNction

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.
*/
/** Keep the reading anchor across keyboard, tab and markdown size changes. */
export function observeL0Transcript(
  pane: HTMLElement,
  onAway: (away: boolean) => void,
  content?: HTMLElement | null
) {
  let following = true
  let anchor = pane.scrollTop
  let top = pane.scrollTop
  let height = pane.clientHeight
  let extent = pane.scrollHeight
  let away = false
  const notify = () => {
    if (away === !following) return
    away = !following
    onAway(away)
  }
  const sync = () => {
    // A hidden scene is not a user scroll and must not erase its anchor.
    if (pane.clientHeight === 0) return
    pane.scrollTop = following ? pane.scrollHeight : anchor
    top = pane.scrollTop
    height = pane.clientHeight
    extent = pane.scrollHeight
    notify()
  }
  const onScroll = () => {
    if (pane.clientHeight === 0) return
    // Resizing can clamp scrollTop and dispatch scroll before ResizeObserver.
    if (height !== pane.clientHeight || extent !== pane.scrollHeight) {
      sync()
      return
    }
    // Ignore the scroll generated by our own correction. Keep the unclamped
    // anchor so closing the keyboard can restore the same reading position.
    if (pane.scrollTop === top) return
    top = anchor = pane.scrollTop
    following = pane.scrollHeight - top - pane.clientHeight < 48
    notify()
  }
  const observer =
    typeof ResizeObserver === 'undefined' ? null : new ResizeObserver(sync)
  observer?.observe(pane)
  if (content) observer?.observe(content)
  pane.addEventListener('scroll', onScroll, { passive: true })
  sync()
  return {
    sync,
    latest() {
      following = true
      sync()
    },
    dispose() {
      observer?.disconnect()
      pane.removeEventListener('scroll', onScroll)
    },
  }
}
