//! Loss-aware, ordered provider-neutral relay intermediate representation.
//!
//! The IR deliberately keeps `Vec` order visible in its public data model.
//! Converters may remove, merge, or reorder values only through the mutation
//! methods on [`Envelope`], each of which requires a structured [`Loss`].
//! Unknown provider fields are retained in [`ExtensionBag`] values instead of
//! being discarded while decoding.

use std::{collections::BTreeMap, error::Error, fmt};

use serde::{Deserialize, Deserializer, Serialize, Serializer};

use super::{
    JsonData, Loss, LossLedger, OpaqueProviderState, OpaqueStateProvenance, Protocol, Role,
};

/// Provider or gateway extension fields which are not part of the stable IR.
///
/// A sorted map gives deterministic serialization while retaining the complete
/// value of an unknown field.  Extension values must not contain request text
/// merely for diagnostic convenience; callers should store only protocol data.
pub type ExtensionBag = BTreeMap<String, JsonData>;

/// Whether an opaque identifier came from a provider or was generated by a
/// compatibility layer.
///
/// This marker is deliberately explicit.  The IR never guesses provenance
/// from the identifier's spelling, because a synthetic value can be
/// byte-for-byte identical to an authentic value.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OpaqueIdProvenance {
    /// Bytes received from the source protocol.
    Authentic,
    /// A value generated by an adapter for compatibility.
    Synthetic,
}

/// An identifier carried opaquely between provider boundaries.
///
/// The IR never parses, normalizes, generates, or otherwise interprets the
/// string inside this type.  This is important for provider call identifiers
/// whose exact bytes are required by a later tool result.  The source and
/// provenance are kept alongside the value so exact-round-trip checks do not
/// have to infer them from a string.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct OpaqueId {
    /// Identifier bytes as supplied by the source.
    pub value: String,
    /// Whether the value is authentic source data or adapter-generated.
    pub provenance: OpaqueIdProvenance,
    /// Protocol which owns the identifier.
    pub source: Protocol,
}

impl OpaqueId {
    /// Creates an authentic identifier without changing its contents.
    #[must_use]
    pub fn authentic(value: impl Into<String>, source: Protocol) -> Self {
        Self {
            value: value.into(),
            provenance: OpaqueIdProvenance::Authentic,
            source,
        }
    }

    /// Creates an adapter-generated identifier without changing its contents.
    #[must_use]
    pub fn synthetic(value: impl Into<String>, source: Protocol) -> Self {
        Self {
            value: value.into(),
            provenance: OpaqueIdProvenance::Synthetic,
            source,
        }
    }

    /// Borrows the identifier exactly as supplied.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.value
    }

    /// Returns the owned identifier without normalization.
    #[must_use]
    pub fn into_string(self) -> String {
        self.value
    }

    /// Returns whether this identifier has no bytes.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.value.is_empty()
    }

    /// Returns whether this identifier came from the source protocol.
    #[must_use]
    pub fn provenance(&self) -> OpaqueIdProvenance {
        self.provenance
    }

    /// Returns the protocol which supplied or owns this identifier.
    #[must_use]
    pub fn source(&self) -> Protocol {
        self.source
    }
}

impl fmt::Display for OpaqueId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

/// The semantic kind of an ordered IR item.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ItemKind {
    /// A normal conversational message.
    Message,
    /// A function/tool invocation emitted by the model.
    ToolCall,
    /// A function/tool result supplied by the caller.
    ToolResult,
    /// A provider reasoning item which is not ordinary visible text.
    Reasoning,
    /// A provider-defined item kind retained by name.
    Unknown(String),
}

impl ItemKind {
    /// Returns the stable wire spelling, preserving an unknown spelling.
    #[must_use]
    pub fn as_str(&self) -> &str {
        match self {
            Self::Message => "message",
            Self::ToolCall => "tool_call",
            Self::ToolResult => "tool_result",
            Self::Reasoning => "reasoning",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for ItemKind {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for ItemKind {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "message" => Self::Message,
            "tool_call" => Self::ToolCall,
            "tool_result" => Self::ToolResult,
            "reasoning" => Self::Reasoning,
            _ => Self::Unknown(value),
        })
    }
}

/// The semantic kind of an ordered content part.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum PartKind {
    /// Visible text.
    Text,
    /// Image, audio, video, or file content.
    Media,
    /// A function call or function result.
    Function,
    /// Opaque provider state kept adjacent to its source part.
    Opaque,
    /// A provider-defined part kind retained by name.
    Unknown(String),
}

impl PartKind {
    /// Returns the stable wire spelling, preserving an unknown spelling.
    #[must_use]
    pub fn as_str(&self) -> &str {
        match self {
            Self::Text => "text",
            Self::Media => "media",
            Self::Function => "function",
            Self::Opaque => "opaque",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for PartKind {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for PartKind {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "text" => Self::Text,
            "media" => Self::Media,
            "function" => Self::Function,
            "opaque" => Self::Opaque,
            _ => Self::Unknown(value),
        })
    }
}

/// The semantic kind of a tool declaration.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ToolKind {
    /// A user-defined function tool.
    Function,
    /// A provider built-in tool.
    Builtin,
    /// A Model Context Protocol tool.
    Mcp,
    /// A provider-defined custom tool.
    Custom,
    /// A tool kind introduced by a newer provider.
    Unknown(String),
}

impl ToolKind {
    /// Returns the stable wire spelling, preserving an unknown spelling.
    #[must_use]
    pub fn as_str(&self) -> &str {
        match self {
            Self::Function => "function",
            Self::Builtin => "builtin",
            Self::Mcp => "mcp",
            Self::Custom => "custom",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for ToolKind {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for ToolKind {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "function" => Self::Function,
            "builtin" => Self::Builtin,
            "mcp" => Self::Mcp,
            "custom" => Self::Custom,
            _ => Self::Unknown(value),
        })
    }
}

/// The semantic operation represented by [`FunctionData`].
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum FunctionKind {
    /// A model-issued function call.
    Call,
    /// A caller-issued function result.
    Result,
    /// A provider-defined function operation.
    Unknown(String),
}

impl FunctionKind {
    /// Returns the stable wire spelling, preserving an unknown spelling.
    #[must_use]
    pub fn as_str(&self) -> &str {
        match self {
            Self::Call => "call",
            Self::Result => "result",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for FunctionKind {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for FunctionKind {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "call" => Self::Call,
            "result" => Self::Result,
            _ => Self::Unknown(value),
        })
    }
}

/// The semantic kind of media content.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum MediaKind {
    /// An image.
    Image,
    /// Audio input or output.
    Audio,
    /// Video input or output.
    Video,
    /// A file reference or file payload.
    File,
    /// A provider-defined media kind.
    Unknown(String),
}

impl MediaKind {
    /// Returns the stable wire spelling, preserving an unknown spelling.
    #[must_use]
    pub fn as_str(&self) -> &str {
        match self {
            Self::Image => "image",
            Self::Audio => "audio",
            Self::Video => "video",
            Self::File => "file",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for MediaKind {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for MediaKind {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "image" => Self::Image,
            "audio" => Self::Audio,
            "video" => Self::Video,
            "file" => Self::File,
            _ => Self::Unknown(value),
        })
    }
}

/// Provenance attached to every ordered item.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Provenance {
    /// Protocol which originally supplied the item.
    pub source: Protocol,
    /// Safe source path, such as `messages[2].content[1]`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_path: Option<String>,
    /// Converter or adapter identifier which last touched the item.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub converter: Option<String>,
    /// Provider fields not yet modeled by the IR.
    #[serde(flatten)]
    #[serde(default)]
    pub extensions: ExtensionBag,
}

impl Provenance {
    /// Creates provenance for an item received from `source`.
    #[must_use]
    pub fn new(source: Protocol) -> Self {
        Self {
            source,
            source_path: None,
            converter: None,
            extensions: ExtensionBag::new(),
        }
    }
}

/// Media data which remains semantic while provider-specific fields stay in
/// the extension bag.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Media {
    /// Media family.
    pub kind: MediaKind,
    /// URL or provider file reference, when one exists.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    /// MIME type supplied by the source provider.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    /// Provider-specific inline payload or reference object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<JsonData>,
    /// Unknown media fields retained for round trips.
    #[serde(flatten)]
    #[serde(default)]
    pub extensions: ExtensionBag,
}

impl Media {
    /// Creates a media value with no provider-specific payload.
    #[must_use]
    pub fn new(kind: MediaKind) -> Self {
        Self {
            kind,
            uri: None,
            mime_type: None,
            data: None,
            extensions: ExtensionBag::new(),
        }
    }
}

/// Function call or function result payload attached to an ordered Part.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionData {
    /// Function operation kind.
    pub kind: FunctionKind,
    /// Function name, when supplied by the provider.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// JSON arguments for a call.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arguments: Option<JsonData>,
    /// JSON result for a result operation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output: Option<JsonData>,
    /// Provider-specific function fields.
    #[serde(flatten)]
    #[serde(default)]
    pub extensions: ExtensionBag,
}

impl FunctionData {
    /// Creates a function call without interpreting its arguments.
    #[must_use]
    pub fn call(name: impl Into<String>, arguments: JsonData) -> Self {
        Self {
            kind: FunctionKind::Call,
            name: Some(name.into()),
            arguments: Some(arguments),
            output: None,
            extensions: ExtensionBag::new(),
        }
    }

    /// Creates a function result without changing its JSON output.
    #[must_use]
    pub fn result(name: Option<String>, output: JsonData) -> Self {
        Self {
            kind: FunctionKind::Result,
            name,
            arguments: None,
            output: Some(output),
            extensions: ExtensionBag::new(),
        }
    }
}

/// One ordered content Part.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Part {
    /// Part semantic kind.
    pub kind: PartKind,
    /// Visible text, when this is a text part.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    /// Media payload, when this is a media part.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub media: Option<Media>,
    /// Function payload, when this is a function part.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub function: Option<FunctionData>,
    /// Opaque provider state kept adjacent to this Part.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub opaque: Option<OpaqueProviderState>,
    /// Unknown fields retained without interpretation.
    #[serde(flatten)]
    #[serde(default)]
    pub extensions: ExtensionBag,
}

impl Part {
    /// Creates an empty Part of the requested kind.
    #[must_use]
    pub fn new(kind: PartKind) -> Self {
        Self {
            kind,
            text: None,
            media: None,
            function: None,
            opaque: None,
            extensions: ExtensionBag::new(),
        }
    }

    /// Creates an ordered text Part without trimming or normalizing it.
    #[must_use]
    pub fn text(value: impl Into<String>) -> Self {
        let mut part = Self::new(PartKind::Text);
        part.text = Some(value.into());
        part
    }

    /// Creates an ordered media Part.
    #[must_use]
    pub fn media(value: Media) -> Self {
        let mut part = Self::new(PartKind::Media);
        part.media = Some(value);
        part
    }

    /// Creates an ordered function Part.
    #[must_use]
    pub fn function(value: FunctionData) -> Self {
        let mut part = Self::new(PartKind::Function);
        part.function = Some(value);
        part
    }

    /// Creates an ordered opaque-state Part.
    #[must_use]
    pub fn opaque(value: OpaqueProviderState) -> Self {
        let mut part = Self::new(PartKind::Opaque);
        part.opaque = Some(value);
        part
    }
}

/// One ordered semantic item in an [`Envelope`].
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Item {
    /// Item semantic kind.
    pub kind: ItemKind,
    /// Provider-neutral role.
    pub role: Role,
    /// Opaque item identifier, if supplied.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<OpaqueId>,
    /// Function call identifier used by a tool result.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub call_id: Option<OpaqueId>,
    /// Ordered content Parts; order is semantic and never rewritten by IR.
    #[serde(default)]
    parts: Vec<Part>,
    /// Source provenance for this item.
    pub provenance: Provenance,
    /// Original structured item, retained when no typed representation exists.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub raw: Option<JsonData>,
    /// Unknown item fields retained for round trips.
    #[serde(flatten)]
    #[serde(default)]
    pub extensions: ExtensionBag,
}

impl Item {
    /// Creates an item with an empty ordered Part list.
    #[must_use]
    pub fn new(kind: ItemKind, role: Role, provenance: Provenance) -> Self {
        Self {
            kind,
            role,
            id: None,
            call_id: None,
            parts: Vec::new(),
            provenance,
            raw: None,
            extensions: ExtensionBag::new(),
        }
    }

    /// Creates a tool-call item whose opaque call id is preserved exactly.
    #[must_use]
    pub fn tool_call(call_id: OpaqueId, parts: Vec<Part>, provenance: Provenance) -> Self {
        let mut item = Self::new(ItemKind::ToolCall, Role::Assistant, provenance);
        item.call_id = Some(call_id);
        item.parts = parts;
        item
    }

    /// Creates a tool-result item linked to a prior tool call.
    #[must_use]
    pub fn tool_result(call_id: OpaqueId, parts: Vec<Part>, provenance: Provenance) -> Self {
        let mut item = Self::new(ItemKind::ToolResult, Role::Tool, provenance);
        item.call_id = Some(call_id);
        item.parts = parts;
        item
    }

    /// Returns the ordered Part slice without exposing mutable reordering.
    #[must_use]
    pub fn ordered_parts(&self) -> &[Part] {
        &self.parts
    }

    /// Appends a Part while preserving all existing Part order.
    pub fn push_part(&mut self, part: Part) {
        self.parts.push(part);
    }
}

/// A tool declaration carried by an [`Envelope`].
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tool {
    /// Tool semantic kind.
    pub kind: ToolKind,
    /// Tool name, when the provider gives one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Human-readable description.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// JSON schema or provider-defined input declaration.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input_schema: Option<JsonData>,
    /// Unknown tool fields retained without interpretation.
    #[serde(flatten)]
    #[serde(default)]
    pub extensions: ExtensionBag,
}

impl Tool {
    /// Creates a named function tool.
    #[must_use]
    pub fn function(name: impl Into<String>, input_schema: JsonData) -> Self {
        Self {
            kind: ToolKind::Function,
            name: Some(name.into()),
            description: None,
            input_schema: Some(input_schema),
            extensions: ExtensionBag::new(),
        }
    }
}

/// Selection policy for tools on an envelope.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum ToolChoice {
    /// Let the provider choose whether to call a tool.
    #[default]
    Auto,
    /// Disable tool calls.
    None,
    /// Require a tool call.
    Required,
    /// Require a named tool.
    Named {
        /// Required tool name.
        name: String,
    },
    /// Preserve a provider-specific choice object.
    Provider {
        /// Original provider choice value.
        raw: JsonData,
    },
}

/// Generation controls which have stable cross-provider semantics.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct GenerationControls {
    /// Maximum number of generated output tokens.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_output_tokens: Option<u64>,
    /// Sampling temperature.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f64>,
    /// Nucleus sampling probability.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub top_p: Option<f64>,
    /// Whether the response is streamed.
    #[serde(default)]
    pub stream: bool,
    /// Provider-neutral reasoning effort label.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning_effort: Option<String>,
    /// Requested response format or schema.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response_format: Option<JsonData>,
    /// Whether parallel tool calls are allowed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parallel_tool_calls: Option<bool>,
    /// Unknown generation controls retained for an exact semantic round trip.
    #[serde(flatten)]
    #[serde(default)]
    pub extensions: ExtensionBag,
}

/// Stateful conversation references carried without provider-specific storage.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct StateRefs {
    /// Gateway conversation identifier.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<OpaqueId>,
    /// OpenAI Responses continuation identifier.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub previous_response_id: Option<OpaqueId>,
    /// Provider which owns the state, when known.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    /// Unknown state references retained for an explicit state policy.
    #[serde(flatten)]
    #[serde(default)]
    pub extensions: ExtensionBag,
}

/// Cache-token accounting with explicit read/write semantics.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct CacheUsage {
    /// Tokens read from an existing prompt cache.
    #[serde(default)]
    pub read_input_tokens: u64,
    /// Tokens written into a prompt cache.
    #[serde(default)]
    pub write_input_tokens: u64,
    /// Tokens created by provider-side cache materialization.
    #[serde(default)]
    pub creation_input_tokens: u64,
    /// Provider cache counters not yet normalized.
    #[serde(flatten)]
    #[serde(default)]
    pub extensions: ExtensionBag,
}

/// A decimal monetary amount kept as text to avoid floating-point billing loss.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct Money {
    /// Decimal amount in the specified currency.
    pub amount: String,
    /// ISO-like currency code or provider billing unit.
    pub currency: String,
}

/// Semantic billing counters associated with one usage snapshot.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct SemanticBillingUsage {
    /// Provider or gateway which supplied the billing snapshot.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    /// Stable semantic billing scheme name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub semantic: Option<String>,
    /// Input tokens billed.
    #[serde(default)]
    pub input_tokens: u64,
    /// Output tokens billed.
    #[serde(default)]
    pub output_tokens: u64,
    /// Cached input tokens billed.
    #[serde(default)]
    pub cached_input_tokens: u64,
    /// Total tokens billed.
    #[serde(default)]
    pub total_tokens: u64,
    /// Monetary amount when the provider reports one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost: Option<Money>,
    /// Provider billing fields not yet normalized.
    #[serde(flatten)]
    #[serde(default)]
    pub extensions: ExtensionBag,
}

/// Provider-neutral usage snapshot kept separate from wire-specific counters.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct SemanticUsage {
    /// Prompt/input tokens.
    #[serde(default)]
    pub input_tokens: u64,
    /// Completion/output tokens.
    #[serde(default)]
    pub output_tokens: u64,
    /// Total tokens as reported by the provider or derived by the adapter.
    #[serde(default)]
    pub total_tokens: u64,
    /// Reasoning tokens when the source exposes them semantically.
    #[serde(default)]
    pub reasoning_tokens: u64,
    /// Explicit cache accounting.
    #[serde(default)]
    pub cache: CacheUsage,
    /// Optional semantic billing accounting.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub billing: Option<SemanticBillingUsage>,
    /// Usage fields introduced by a provider but not yet normalized.
    #[serde(flatten)]
    #[serde(default)]
    pub extensions: ExtensionBag,
}

/// An ordered provider-neutral envelope.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Envelope {
    /// Protocol which supplied this envelope.
    pub source: Protocol,
    /// Model identifier retained exactly as supplied by the caller.
    pub model: String,
    /// Ordered semantic items.  Position is part of the protocol meaning.
    #[serde(default)]
    items: Vec<Item>,
    /// Ordered tool declarations.
    #[serde(default)]
    pub tools: Vec<Tool>,
    /// Tool selection policy.
    #[serde(default)]
    pub tool_choice: ToolChoice,
    /// Stable generation controls.
    #[serde(default)]
    pub controls: GenerationControls,
    /// Stateful continuation references.
    #[serde(default)]
    pub state: StateRefs,
    /// Semantic usage and cache/billing counters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage: Option<SemanticUsage>,
    /// Losses accumulated by explicit IR mutations.
    #[serde(default)]
    losses: LossLedger,
    /// Unknown envelope fields retained for round trips.
    #[serde(flatten)]
    #[serde(default)]
    pub extensions: ExtensionBag,
}

impl Envelope {
    /// Creates an empty envelope with deterministic default controls and state.
    #[must_use]
    pub fn new(source: Protocol, model: impl Into<String>) -> Self {
        Self {
            source,
            model: model.into(),
            items: Vec::new(),
            tools: Vec::new(),
            tool_choice: ToolChoice::default(),
            controls: GenerationControls::default(),
            state: StateRefs::default(),
            usage: None,
            losses: LossLedger::new(),
            extensions: ExtensionBag::new(),
        }
    }

    /// Returns the ordered item slice without copying or reindexing it.
    #[must_use]
    pub fn ordered_items(&self) -> &[Item] {
        &self.items
    }

    /// Records a structured loss exactly once in the envelope ledger.
    pub fn record_loss(&mut self, loss: Loss) {
        self.losses.record(loss);
    }

    /// Returns the automatically accumulated loss ledger.
    #[must_use]
    pub fn loss_ledger(&self) -> &LossLedger {
        &self.losses
    }

    /// Adds an item while rejecting an orphan tool result or invalid opaque state.
    pub fn push_item(&mut self, item: Item) -> Result<(), IrValidationError> {
        self.items.push(item);
        if let Err(error) = self.validate() {
            let new_len = self.items.len().saturating_sub(1);
            self.items.truncate(new_len);
            return Err(error);
        }
        Ok(())
    }

    /// Adds a Part to an existing item while retaining its position.
    pub fn push_part(&mut self, item_index: usize, part: Part) -> Result<(), IrMutationError> {
        if item_index >= self.items.len() {
            return Err(IrMutationError::IndexOutOfBounds {
                collection: OrderedCollection::Parts,
                index: item_index,
                len: self.items.len(),
            });
        }
        self.items[item_index].parts.push(part);
        if let Err(error) = self.validate() {
            let _ = self.items[item_index].parts.pop();
            return Err(error.into());
        }
        Ok(())
    }

    /// Removes one item only when the caller supplies the corresponding loss.
    pub fn remove_item(
        &mut self,
        index: usize,
        loss: Option<Loss>,
    ) -> Result<Item, IrMutationError> {
        let loss = require_loss(loss, MutationKind::RemoveItem)?;
        if index >= self.items.len() {
            return Err(IrMutationError::IndexOutOfBounds {
                collection: OrderedCollection::Items,
                index,
                len: self.items.len(),
            });
        }
        let removed = self.items.remove(index);
        if let Err(error) = self.validate() {
            self.items.insert(index, removed);
            return Err(error.into());
        }
        self.losses.record(loss);
        Ok(removed)
    }

    /// Removes one Part only when the caller supplies the corresponding loss.
    pub fn remove_part(
        &mut self,
        item_index: usize,
        part_index: usize,
        loss: Option<Loss>,
    ) -> Result<Part, IrMutationError> {
        let loss = require_loss(loss, MutationKind::RemovePart)?;
        if item_index >= self.items.len() {
            return Err(IrMutationError::IndexOutOfBounds {
                collection: OrderedCollection::Items,
                index: item_index,
                len: self.items.len(),
            });
        }
        let item_part_len = self.items[item_index].parts.len();
        if part_index >= item_part_len {
            return Err(IrMutationError::IndexOutOfBounds {
                collection: OrderedCollection::Parts,
                index: part_index,
                len: item_part_len,
            });
        }
        let removed = self.items[item_index].parts.remove(part_index);
        if let Err(error) = self.validate() {
            self.items[item_index].parts.insert(part_index, removed);
            return Err(error.into());
        }
        self.losses.record(loss);
        Ok(removed)
    }

    /// Reorders two items only with an explicit content-order loss.
    pub fn reorder_items(
        &mut self,
        from: usize,
        to: usize,
        loss: Option<Loss>,
    ) -> Result<(), IrMutationError> {
        let loss = require_loss(loss, MutationKind::ReorderItems)?;
        check_index(from, OrderedCollection::Items, self.items.len())?;
        check_index(to, OrderedCollection::Items, self.items.len())?;
        let items_before = self.items.clone();
        if from != to {
            let item = self.items.remove(from);
            self.items.insert(to, item);
        }
        if let Err(error) = self.validate() {
            self.items = items_before;
            return Err(error.into());
        }
        self.losses.record(loss);
        Ok(())
    }

    /// Reorders two Parts only with an explicit content-order loss.
    pub fn reorder_parts(
        &mut self,
        item_index: usize,
        from: usize,
        to: usize,
        loss: Option<Loss>,
    ) -> Result<(), IrMutationError> {
        let loss = require_loss(loss, MutationKind::ReorderParts)?;
        if item_index >= self.items.len() {
            return Err(IrMutationError::IndexOutOfBounds {
                collection: OrderedCollection::Items,
                index: item_index,
                len: self.items.len(),
            });
        }
        let part_len = self.items[item_index].parts.len();
        check_index(from, OrderedCollection::Parts, part_len)?;
        check_index(to, OrderedCollection::Parts, part_len)?;
        let item_before = self.items[item_index].clone();
        if from != to {
            let part = self.items[item_index].parts.remove(from);
            self.items[item_index].parts.insert(to, part);
        }
        if let Err(error) = self.validate() {
            self.items[item_index] = item_before;
            return Err(error.into());
        }
        self.losses.record(loss);
        Ok(())
    }

    /// Merges adjacent items only when a structured merge loss is supplied.
    ///
    /// Items must have the same kind, role, provenance, and no competing
    /// identity/raw fields.  Rejecting incompatible values prevents the merge
    /// API from silently discarding fields even after a loss is recorded.
    pub fn merge_items(
        &mut self,
        left: usize,
        right: usize,
        loss: Option<Loss>,
    ) -> Result<(), IrMutationError> {
        let loss = require_loss(loss, MutationKind::MergeItems)?;
        check_adjacent(left, right, OrderedCollection::Items, self.items.len())?;
        let left_before = self.items[left].clone();
        let right_before = self.items[right].clone();
        validate_item_merge(&left_before, &right_before)?;
        let right_item = self.items.remove(right);
        self.items[left].parts.extend(right_item.parts);
        self.items[left].extensions.extend(right_item.extensions);
        if let Err(error) = self.validate() {
            let _merged = self.items.remove(left);
            self.items.insert(left, left_before);
            self.items.insert(right, right_before);
            return Err(error.into());
        }
        self.losses.record(loss);
        Ok(())
    }

    /// Merges adjacent compatible Parts only with an explicit merge loss.
    pub fn merge_parts(
        &mut self,
        item_index: usize,
        left: usize,
        right: usize,
        loss: Option<Loss>,
    ) -> Result<(), IrMutationError> {
        let loss = require_loss(loss, MutationKind::MergeParts)?;
        if item_index >= self.items.len() {
            return Err(IrMutationError::IndexOutOfBounds {
                collection: OrderedCollection::Items,
                index: item_index,
                len: self.items.len(),
            });
        }
        let part_len = self.items[item_index].parts.len();
        check_adjacent(left, right, OrderedCollection::Parts, part_len)?;
        let merged = merge_part_values(
            &self.items[item_index].parts[left],
            &self.items[item_index].parts[right],
        )?;
        let item_before = self.items[item_index].clone();
        self.items[item_index].parts[left] = merged;
        self.items[item_index].parts.remove(right);
        if let Err(error) = self.validate() {
            self.items[item_index] = item_before;
            return Err(error.into());
        }
        self.losses.record(loss);
        Ok(())
    }

    /// Validates tool-result references and opaque-state invariants.
    pub fn validate(&self) -> Result<(), IrValidationError> {
        let mut calls = BTreeMap::<String, usize>::new();
        let mut results = BTreeMap::<String, usize>::new();
        for (field, identifier) in [
            ("conversation_id", self.state.conversation_id.as_ref()),
            (
                "previous_response_id",
                self.state.previous_response_id.as_ref(),
            ),
        ] {
            if identifier.is_some_and(|value| value.is_empty()) {
                return Err(IrValidationError::EmptyStateId {
                    field: field.to_owned(),
                });
            }
        }
        for (index, item) in self.items.iter().enumerate() {
            validate_item(item, index)?;
            if let Some(id) = item.id.as_ref()
                && id.is_empty()
            {
                return Err(IrValidationError::EmptyOpaqueId {
                    item_index: index,
                    field: "id".to_owned(),
                });
            }
            if let Some(call_id) = item.call_id.as_ref()
                && call_id.is_empty()
            {
                return Err(IrValidationError::EmptyOpaqueId {
                    item_index: index,
                    field: "call_id".to_owned(),
                });
            }
            match &item.kind {
                ItemKind::ToolCall => {
                    let Some(call_id) = item.call_id.as_ref() else {
                        return Err(IrValidationError::MissingToolCallId { item_index: index });
                    };
                    let call_key = call_id.as_str().to_owned();
                    if let Some(first_item_index) = calls.insert(call_key, index) {
                        return Err(IrValidationError::DuplicateToolCallId {
                            first_item_index,
                            second_item_index: index,
                            call_id: call_id.clone(),
                        });
                    }
                }
                ItemKind::ToolResult => {
                    let Some(call_id) = item.call_id.as_ref() else {
                        return Err(IrValidationError::MissingToolCallId { item_index: index });
                    };
                    let call_key = call_id.as_str();
                    if !calls.contains_key(call_key) {
                        return Err(IrValidationError::OrphanToolResult {
                            item_index: index,
                            call_id: call_id.clone(),
                        });
                    }
                    if let Some(first_item_index) = results.insert(call_key.to_owned(), index) {
                        return Err(IrValidationError::DuplicateToolResult {
                            first_item_index,
                            second_item_index: index,
                            call_id: call_id.clone(),
                        });
                    }
                }
                _ => {}
            }
        }
        Ok(())
    }

    /// Checks whether this envelope belongs to the exact, lossless subset.
    pub fn validate_exact_round_trip(&self) -> Result<(), ExactRoundTripError> {
        if !self.losses.is_empty() {
            return Err(ExactRoundTripError::LossesPresent {
                losses: self.losses.clone(),
            });
        }
        self.validate().map_err(ExactRoundTripError::Validation)?;
        if let Some(error) = exact_synthetic_id_error(self) {
            return Err(error);
        }
        for (item_index, item) in self.items.iter().enumerate() {
            if matches!(&item.kind, ItemKind::Unknown(_)) {
                return Err(ExactRoundTripError::UnmodeledField {
                    path: format!("items[{item_index}].kind"),
                });
            }
            if item.raw.is_some() {
                return Err(ExactRoundTripError::UnmodeledField {
                    path: format!("items[{item_index}].raw"),
                });
            }
            if !item.extensions.is_empty() || !item.provenance.extensions.is_empty() {
                return Err(ExactRoundTripError::UnmodeledField {
                    path: format!("items[{item_index}].extensions"),
                });
            }
            for (part_index, part) in item.parts.iter().enumerate() {
                if matches!(&part.kind, PartKind::Unknown(_)) || !part.extensions.is_empty() {
                    return Err(ExactRoundTripError::UnmodeledField {
                        path: format!("items[{item_index}].parts[{part_index}]"),
                    });
                }
                if part
                    .opaque
                    .as_ref()
                    .is_some_and(|state| state.provenance == OpaqueStateProvenance::Synthetic)
                {
                    return Err(ExactRoundTripError::SyntheticOpaqueState {
                        item_index,
                        part_index,
                    });
                }
                if let Some(media) = part.media.as_ref()
                    && (matches!(&media.kind, MediaKind::Unknown(_))
                        || media.data.is_some()
                        || !media.extensions.is_empty())
                {
                    return Err(ExactRoundTripError::UnmodeledField {
                        path: format!("items[{item_index}].parts[{part_index}].media"),
                    });
                }
                if let Some(function) = part.function.as_ref()
                    && (matches!(&function.kind, FunctionKind::Unknown(_))
                        || !function.extensions.is_empty())
                {
                    return Err(ExactRoundTripError::UnmodeledField {
                        path: format!("items[{item_index}].parts[{part_index}].function"),
                    });
                }
            }
        }
        if !self.extensions.is_empty()
            || !self.controls.extensions.is_empty()
            || !self.state.extensions.is_empty()
            || self.tools.iter().any(|tool| {
                matches!(&tool.kind, ToolKind::Unknown(_)) || !tool.extensions.is_empty()
            })
        {
            return Err(ExactRoundTripError::UnmodeledField {
                path: "envelope.extensions".to_owned(),
            });
        }
        if matches!(&self.tool_choice, ToolChoice::Provider { .. }) {
            return Err(ExactRoundTripError::UnmodeledField {
                path: "tool_choice.provider".to_owned(),
            });
        }
        if let Some(usage) = self.usage.as_ref()
            && (!usage.extensions.is_empty()
                || !usage.cache.extensions.is_empty()
                || usage
                    .billing
                    .as_ref()
                    .is_some_and(|billing| !billing.extensions.is_empty()))
        {
            return Err(ExactRoundTripError::UnmodeledField {
                path: "usage.extensions".to_owned(),
            });
        }
        Ok(())
    }

    /// Returns whether exact round-trip invariants currently hold.
    #[must_use]
    pub fn is_exact_round_trip_safe(&self) -> bool {
        self.validate_exact_round_trip().is_ok()
    }
}

/// A mutation operation which requires an accompanying loss entry.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MutationKind {
    /// Remove an ordered item.
    RemoveItem,
    /// Remove an ordered Part.
    RemovePart,
    /// Merge adjacent ordered items.
    MergeItems,
    /// Merge adjacent ordered Parts.
    MergeParts,
    /// Reorder ordered items.
    ReorderItems,
    /// Reorder ordered Parts.
    ReorderParts,
}

/// Which ordered collection produced an index error or merge error.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OrderedCollection {
    /// The envelope item vector.
    Items,
    /// An item Part vector.
    Parts,
}

/// Errors returned by explicit ordered mutations.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub enum IrMutationError {
    /// The caller attempted a lossy mutation without a structured Loss.
    MissingLoss {
        /// Mutation which was refused.
        operation: MutationKind,
    },
    /// An item or Part index is outside its ordered vector.
    IndexOutOfBounds {
        /// Collection being addressed.
        collection: OrderedCollection,
        /// Requested index.
        index: usize,
        /// Current collection length.
        len: usize,
    },
    /// A merge requires adjacent values so their order is unambiguous.
    NonAdjacent {
        /// Collection being merged.
        collection: OrderedCollection,
        /// Left index supplied by the caller.
        left: usize,
        /// Right index supplied by the caller.
        right: usize,
    },
    /// The values have fields whose semantic ownership cannot be merged safely.
    MergeConflict {
        /// Collection being merged.
        collection: OrderedCollection,
        /// Safe reason code, without source content.
        reason: String,
    },
    /// The proposed mutation would violate a tool-link or opaque-state invariant.
    Validation(IrValidationError),
}

/// Validation failures for ordered tool links and provider state.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub enum IrValidationError {
    /// A tool call or result does not have an opaque call identifier.
    MissingToolCallId {
        /// Item whose identifier is missing.
        item_index: usize,
    },
    /// A tool result points to no ordered tool call.
    OrphanToolResult {
        /// Orphan result item.
        item_index: usize,
        /// Unmatched call identifier.
        call_id: OpaqueId,
    },
    /// A tool result reuses a call identifier which already has a result.
    DuplicateToolResult {
        /// First result item using the identifier.
        first_item_index: usize,
        /// Later result item reusing the identifier.
        second_item_index: usize,
        /// Duplicated identifier.
        call_id: OpaqueId,
    },
    /// Two tool calls reused one opaque identifier.
    DuplicateToolCallId {
        /// First item using the identifier.
        first_item_index: usize,
        /// Later item reusing the identifier.
        second_item_index: usize,
        /// Duplicated identifier.
        call_id: OpaqueId,
    },
    /// An item or tool link contains an empty opaque identifier.
    EmptyOpaqueId {
        /// Item containing the empty identifier.
        item_index: usize,
        /// Identifier field which was empty.
        field: String,
    },
    /// An envelope state reference contains an empty opaque identifier.
    EmptyStateId {
        /// State field which was empty.
        field: String,
    },
    /// A Part carries a payload which does not match its declared kind.
    InvalidPartShape {
        /// Item containing the malformed Part.
        item_index: usize,
        /// Malformed Part index.
        part_index: usize,
        /// Stable reason code, without source content.
        reason: String,
    },
    /// A function Part has incompatible or incomplete operation fields.
    InvalidFunctionShape {
        /// Item containing the malformed Part.
        item_index: usize,
        /// Malformed Part index.
        part_index: usize,
        /// Stable reason code, without source content.
        reason: String,
    },
    /// An ordered item has an invalid relationship to its function Parts.
    InvalidItemShape {
        /// Item containing the malformed function relationship.
        item_index: usize,
        /// Stable reason code, without source content.
        reason: String,
    },
    /// An opaque state provider or kind is empty.
    InvalidOpaqueState {
        /// Item containing the invalid state.
        item_index: usize,
        /// Part containing the invalid state.
        part_index: usize,
        /// Field which failed validation.
        field: String,
    },
}

/// Failures returned by the exact round-trip invariant helper.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub enum ExactRoundTripError {
    /// The envelope already contains a structured loss.
    LossesPresent {
        /// Losses preventing an exact claim.
        losses: LossLedger,
    },
    /// The ordered envelope has an invalid tool or opaque-state relation.
    Validation(IrValidationError),
    /// Synthetic provider state is not exact source state.
    SyntheticOpaqueState {
        /// Item containing the synthetic state.
        item_index: usize,
        /// Part containing the synthetic state.
        part_index: usize,
    },
    /// A synthetic identifier cannot claim exact source provenance.
    SyntheticOpaqueId {
        /// Item containing the identifier, when the identifier belongs to an
        /// item rather than envelope state.
        item_index: Option<usize>,
        /// Stable field path, without identifier contents.
        field: String,
    },
    /// A raw, unknown, or extension field is outside the typed exact subset.
    UnmodeledField {
        /// Structural field path, without source payload contents.
        path: String,
    },
}

/// A malformed opaque provider state independent of any item location.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OpaqueStateError {
    /// Provider name is empty.
    EmptyProvider,
    /// Provider state kind is empty.
    EmptyKind,
}

/// Checks the invariant that authentic and synthetic provider state remains
/// explicitly distinguished and has a stable provider/kind identity.
pub fn validate_opaque_state_invariant(
    state: &OpaqueProviderState,
) -> Result<(), OpaqueStateError> {
    if state.provider.trim().is_empty() {
        return Err(OpaqueStateError::EmptyProvider);
    }
    if state.kind.trim().is_empty() {
        return Err(OpaqueStateError::EmptyKind);
    }
    Ok(())
}

fn exact_synthetic_id_error(envelope: &Envelope) -> Option<ExactRoundTripError> {
    let state_ids = [
        (
            "state.conversation_id",
            envelope.state.conversation_id.as_ref(),
        ),
        (
            "state.previous_response_id",
            envelope.state.previous_response_id.as_ref(),
        ),
    ];
    for (field, identifier) in state_ids {
        if identifier.is_some_and(|value| value.provenance == OpaqueIdProvenance::Synthetic) {
            return Some(ExactRoundTripError::SyntheticOpaqueId {
                item_index: None,
                field: field.to_owned(),
            });
        }
    }
    for (item_index, item) in envelope.items.iter().enumerate() {
        for (field, identifier) in [
            ("items[].id", item.id.as_ref()),
            ("items[].call_id", item.call_id.as_ref()),
        ] {
            if identifier.is_some_and(|value| value.provenance == OpaqueIdProvenance::Synthetic) {
                return Some(ExactRoundTripError::SyntheticOpaqueId {
                    item_index: Some(item_index),
                    field: field.to_owned(),
                });
            }
        }
    }
    None
}

fn require_loss(loss: Option<Loss>, operation: MutationKind) -> Result<Loss, IrMutationError> {
    loss.ok_or(IrMutationError::MissingLoss { operation })
}

fn check_index(
    index: usize,
    collection: OrderedCollection,
    len: usize,
) -> Result<(), IrMutationError> {
    if index >= len {
        Err(IrMutationError::IndexOutOfBounds {
            collection,
            index,
            len,
        })
    } else {
        Ok(())
    }
}

fn check_adjacent(
    left: usize,
    right: usize,
    collection: OrderedCollection,
    len: usize,
) -> Result<(), IrMutationError> {
    check_index(left, collection, len)?;
    check_index(right, collection, len)?;
    if left.checked_add(1) != Some(right) {
        return Err(IrMutationError::NonAdjacent {
            collection,
            left,
            right,
        });
    }
    Ok(())
}

fn validate_item(item: &Item, item_index: usize) -> Result<(), IrValidationError> {
    let mut function_calls = 0_usize;
    let mut function_results = 0_usize;
    let mut has_non_function_payload = false;
    for (part_index, part) in item.parts.iter().enumerate() {
        validate_part(part, item_index, part_index)?;
        if let Some(function) = part.function.as_ref() {
            match &function.kind {
                FunctionKind::Call => function_calls += 1,
                FunctionKind::Result => function_results += 1,
                FunctionKind::Unknown(_) => {}
            }
        } else if !matches!(&part.kind, PartKind::Opaque) {
            has_non_function_payload = true;
        }
        let Some(state) = part.opaque.as_ref() else {
            continue;
        };
        if let Err(error) = validate_opaque_state_invariant(state) {
            let field = match error {
                OpaqueStateError::EmptyProvider => "provider",
                OpaqueStateError::EmptyKind => "kind",
            };
            return Err(IrValidationError::InvalidOpaqueState {
                item_index,
                part_index,
                field: field.to_owned(),
            });
        }
    }
    match &item.kind {
        ItemKind::ToolCall => {
            if function_calls != 1 || function_results != 0 || has_non_function_payload {
                return Err(IrValidationError::InvalidItemShape {
                    item_index,
                    reason: "tool_call_requires_one_call_function".to_owned(),
                });
            }
        }
        ItemKind::ToolResult => {
            if function_results != 1 || function_calls != 0 || has_non_function_payload {
                return Err(IrValidationError::InvalidItemShape {
                    item_index,
                    reason: "tool_result_requires_one_result_function".to_owned(),
                });
            }
        }
        ItemKind::Message | ItemKind::Reasoning | ItemKind::Unknown(_) => {
            if function_calls != 0 || function_results != 0 {
                return Err(IrValidationError::InvalidItemShape {
                    item_index,
                    reason: "ordinary_item_cannot_carry_function".to_owned(),
                });
            }
        }
    }
    Ok(())
}

fn validate_part(
    part: &Part,
    item_index: usize,
    part_index: usize,
) -> Result<(), IrValidationError> {
    let invalid_shape = |reason: &'static str| {
        Err(IrValidationError::InvalidPartShape {
            item_index,
            part_index,
            reason: reason.to_owned(),
        })
    };
    match &part.kind {
        PartKind::Text => {
            if part.text.is_none()
                || part.media.is_some()
                || part.function.is_some()
                || part.opaque.is_some()
            {
                return invalid_shape("text_payload");
            }
        }
        PartKind::Media => {
            if part.media.is_none()
                || part.text.is_some()
                || part.function.is_some()
                || part.opaque.is_some()
            {
                return invalid_shape("media_payload");
            }
        }
        PartKind::Function => {
            if part.function.is_none()
                || part.text.is_some()
                || part.media.is_some()
                || part.opaque.is_some()
            {
                return invalid_shape("function_payload");
            }
            if let Some(function) = part.function.as_ref() {
                validate_function(function, item_index, part_index)?;
            }
        }
        PartKind::Opaque => {
            if part.opaque.is_none()
                || part.text.is_some()
                || part.media.is_some()
                || part.function.is_some()
            {
                return invalid_shape("opaque_payload");
            }
        }
        PartKind::Unknown(_) => {
            if part.text.is_some()
                || part.media.is_some()
                || part.function.is_some()
                || part.opaque.is_some()
            {
                return invalid_shape("unknown_payload");
            }
        }
    }
    Ok(())
}

fn validate_function(
    function: &FunctionData,
    item_index: usize,
    part_index: usize,
) -> Result<(), IrValidationError> {
    let invalid = |reason: &'static str| {
        Err(IrValidationError::InvalidFunctionShape {
            item_index,
            part_index,
            reason: reason.to_owned(),
        })
    };
    match &function.kind {
        FunctionKind::Call => {
            let Some(name) = function.name.as_ref() else {
                return invalid("call_name_required");
            };
            if name.is_empty() || function.arguments.is_none() || function.output.is_some() {
                return invalid("call_fields");
            }
        }
        FunctionKind::Result => {
            if function.output.is_none() || function.arguments.is_some() {
                return invalid("result_fields");
            }
        }
        FunctionKind::Unknown(_) => return invalid("unknown_function_kind"),
    }
    Ok(())
}

fn validate_item_merge(left: &Item, right: &Item) -> Result<(), IrMutationError> {
    if left.kind != right.kind || left.role != right.role {
        return Err(IrMutationError::MergeConflict {
            collection: OrderedCollection::Items,
            reason: "kind_or_role".to_owned(),
        });
    }
    if left.id.is_some() || left.call_id.is_some() || right.id.is_some() || right.call_id.is_some()
    {
        return Err(IrMutationError::MergeConflict {
            collection: OrderedCollection::Items,
            reason: "identity".to_owned(),
        });
    }
    if left.raw.is_some() || right.raw.is_some() {
        return Err(IrMutationError::MergeConflict {
            collection: OrderedCollection::Items,
            reason: "raw".to_owned(),
        });
    }
    if left.provenance != right.provenance {
        return Err(IrMutationError::MergeConflict {
            collection: OrderedCollection::Items,
            reason: "provenance".to_owned(),
        });
    }
    if left
        .extensions
        .keys()
        .any(|key| right.extensions.contains_key(key))
    {
        return Err(IrMutationError::MergeConflict {
            collection: OrderedCollection::Items,
            reason: "extension_collision".to_owned(),
        });
    }
    Ok(())
}

fn merge_part_values(left: &Part, right: &Part) -> Result<Part, IrMutationError> {
    if left.kind != right.kind {
        return Err(IrMutationError::MergeConflict {
            collection: OrderedCollection::Parts,
            reason: "kind".to_owned(),
        });
    }
    if left.media.is_some() && right.media.is_some()
        || left.function.is_some() && right.function.is_some()
        || left.opaque.is_some() && right.opaque.is_some()
    {
        return Err(IrMutationError::MergeConflict {
            collection: OrderedCollection::Parts,
            reason: "payload_collision".to_owned(),
        });
    }
    if left
        .extensions
        .keys()
        .any(|key| right.extensions.contains_key(key))
    {
        return Err(IrMutationError::MergeConflict {
            collection: OrderedCollection::Parts,
            reason: "extension_collision".to_owned(),
        });
    }
    let mut merged = left.clone();
    if let (Some(left_text), Some(right_text)) = (&left.text, &right.text) {
        merged.text = Some(format!("{left_text}{right_text}"));
    } else if merged.text.is_none() {
        merged.text = right.text.clone();
    }
    if merged.media.is_none() {
        merged.media = right.media.clone();
    }
    if merged.function.is_none() {
        merged.function = right.function.clone();
    }
    if merged.opaque.is_none() {
        merged.opaque = right.opaque.clone();
    }
    merged.extensions.extend(right.extensions.clone());
    Ok(merged)
}

impl From<IrValidationError> for IrMutationError {
    fn from(error: IrValidationError) -> Self {
        Self::Validation(error)
    }
}

impl fmt::Display for IrMutationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MissingLoss { operation } => write!(
                formatter,
                "loss entry required before {operation:?} mutation"
            ),
            Self::IndexOutOfBounds {
                collection,
                index,
                len,
            } => write!(
                formatter,
                "{collection:?} index {index} is outside length {len}"
            ),
            Self::NonAdjacent {
                collection,
                left,
                right,
            } => write!(
                formatter,
                "{collection:?} merge requires adjacent indices, got {left} and {right}"
            ),
            Self::MergeConflict { collection, reason } => {
                write!(formatter, "cannot merge {collection:?}: {reason}")
            }
            Self::Validation(error) => error.fmt(formatter),
        }
    }
}

impl Error for IrMutationError {}

impl fmt::Display for IrValidationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MissingToolCallId { item_index } => {
                write!(formatter, "tool item {item_index} has no call id")
            }
            Self::OrphanToolResult {
                item_index,
                call_id,
            } => write!(
                formatter,
                "tool result {item_index} has orphan call id {call_id}"
            ),
            Self::DuplicateToolCallId {
                first_item_index,
                second_item_index,
                call_id,
            } => write!(
                formatter,
                "tool call id {call_id} is reused by items {first_item_index} and {second_item_index}"
            ),
            Self::DuplicateToolResult {
                first_item_index,
                second_item_index,
                call_id,
            } => write!(
                formatter,
                "tool result call id {call_id} is reused by items {first_item_index} and {second_item_index}"
            ),
            Self::EmptyOpaqueId { item_index, field } => {
                write!(
                    formatter,
                    "item {item_index} has empty opaque id field {field}"
                )
            }
            Self::EmptyStateId { field } => {
                write!(formatter, "state field {field} has an empty opaque id")
            }
            Self::InvalidPartShape {
                item_index,
                part_index,
                reason,
            } => write!(
                formatter,
                "part at item {item_index}, part {part_index} has invalid shape: {reason}"
            ),
            Self::InvalidFunctionShape {
                item_index,
                part_index,
                reason,
            } => write!(
                formatter,
                "function at item {item_index}, part {part_index} has invalid shape: {reason}"
            ),
            Self::InvalidItemShape { item_index, reason } => write!(
                formatter,
                "item {item_index} has invalid function relationship: {reason}"
            ),
            Self::InvalidOpaqueState {
                item_index,
                part_index,
                field,
            } => write!(
                formatter,
                "opaque state at item {item_index}, part {part_index} has empty {field}"
            ),
        }
    }
}

impl Error for IrValidationError {}

impl fmt::Display for ExactRoundTripError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::LossesPresent { losses } => {
                write!(
                    formatter,
                    "exact round trip has {} loss entries",
                    losses.len()
                )
            }
            Self::Validation(error) => error.fmt(formatter),
            Self::SyntheticOpaqueState {
                item_index,
                part_index,
            } => write!(
                formatter,
                "synthetic opaque state at item {item_index}, part {part_index} is not exact"
            ),
            Self::SyntheticOpaqueId { item_index, field } => write!(
                formatter,
                "synthetic opaque id in {field} at item {item_index:?} is not exact"
            ),
            Self::UnmodeledField { path } => {
                write!(
                    formatter,
                    "unmodeled field at {path} prevents exact round trip"
                )
            }
        }
    }
}

impl Error for ExactRoundTripError {}

#[cfg(test)]
mod tests {
    use super::*;

    fn provenance() -> Provenance {
        Provenance::new(Protocol::Gemini)
    }

    fn text_item(value: &str) -> Item {
        let mut item = Item::new(ItemKind::Message, Role::User, provenance());
        item.push_part(Part::text(value));
        item
    }

    fn content_loss() -> Loss {
        Loss::new(
            super::super::LossCode::LossContentOrder,
            Some(super::super::Feature::Text),
        )
    }

    fn tool_call_part() -> Part {
        Part::function(FunctionData::call("lookup", JsonData::Null))
    }

    fn tool_result_part() -> Part {
        Part::function(FunctionData::result(None, JsonData::Null))
    }

    #[test]
    fn ordered_items_and_parts_are_preserved_without_reindexing() {
        let mut envelope = Envelope::new(Protocol::Gemini, "gemini-test");
        envelope.push_item(text_item("first")).expect("valid item");
        envelope.push_item(text_item("second")).expect("valid item");
        envelope
            .reorder_items(0, 1, Some(content_loss()))
            .expect("ordered mutation");
        assert_eq!(envelope.items[0].parts[0].text.as_deref(), Some("second"));
        assert_eq!(envelope.items[1].parts[0].text.as_deref(), Some("first"));
        assert_eq!(envelope.losses.len(), 1);
    }

    #[test]
    fn opaque_id_and_signature_provenance_remain_distinct() {
        let authentic = OpaqueProviderState::authentic_gemini_thought_signature(
            "sig-raw".to_owned(),
            Some("gemini-3".to_owned()),
        );
        let synthetic = OpaqueProviderState::synthetic_gemini_thought_signature(None);
        let authentic_id = OpaqueId::authentic("call-raw", Protocol::Gemini);
        let synthetic_id = OpaqueId::synthetic("call-raw", Protocol::Gemini);
        assert_eq!(authentic_id.as_str(), "call-raw");
        assert_eq!(authentic_id.provenance(), OpaqueIdProvenance::Authentic);
        assert_eq!(synthetic_id.provenance(), OpaqueIdProvenance::Synthetic);
        assert_eq!(authentic_id.source(), Protocol::Gemini);
        assert_eq!(synthetic_id.source(), Protocol::Gemini);
        let encoded = serde_json::to_string(&authentic_id).expect("serialize opaque id");
        let decoded: OpaqueId = serde_json::from_str(&encoded).expect("deserialize opaque id");
        assert_eq!(decoded, authentic_id);
        assert_eq!(authentic.provenance, OpaqueStateProvenance::Authentic);
        assert_eq!(synthetic.provenance, OpaqueStateProvenance::Synthetic);
        assert!(validate_opaque_state_invariant(&authentic).is_ok());
        assert!(validate_opaque_state_invariant(&synthetic).is_ok());
    }

    #[test]
    fn unknown_fields_round_trip_through_extension_bags() {
        let mut envelope = Envelope::new(Protocol::Claude, "claude-test");
        envelope.extensions.insert(
            "future_control".to_owned(),
            JsonData::String("retained".to_owned()),
        );
        let encoded = serde_json::to_string(&envelope).expect("serialize envelope");
        let decoded: Envelope = serde_json::from_str(&encoded).expect("deserialize envelope");
        assert_eq!(
            decoded.extensions.get("future_control"),
            Some(&JsonData::String("retained".to_owned()))
        );
    }

    #[test]
    fn lossy_mutation_requires_loss_and_accumulates_it() {
        let mut envelope = Envelope::new(Protocol::OpenAi, "gpt-test");
        envelope.push_item(text_item("only")).expect("valid item");
        assert_eq!(
            envelope.remove_item(0, None),
            Err(IrMutationError::MissingLoss {
                operation: MutationKind::RemoveItem
            })
        );
        assert!(envelope.remove_item(0, Some(content_loss())).is_ok());
        assert_eq!(envelope.losses.len(), 1);
    }

    #[test]
    fn orphan_tool_results_are_rejected() {
        let envelope = Envelope::new(Protocol::OpenAi, "gpt-test");
        let mut invalid = envelope;
        invalid.items.push(Item::tool_result(
            OpaqueId::authentic("missing", Protocol::OpenAi),
            vec![tool_result_part()],
            provenance(),
        ));
        assert!(matches!(
            invalid.validate(),
            Err(IrValidationError::OrphanToolResult { .. })
        ));
    }

    #[test]
    fn tool_links_are_ordered_and_item_id_differs_from_call_id() {
        let mut envelope = Envelope::new(Protocol::OpenAiResponses, "responses-test");
        let mut call = Item::tool_call(
            OpaqueId::authentic("call-1", Protocol::OpenAiResponses),
            vec![tool_call_part()],
            provenance(),
        );
        call.id = Some(OpaqueId::authentic("item-1", Protocol::OpenAiResponses));
        envelope.items.push(call);
        envelope.items.push(Item::tool_result(
            OpaqueId::authentic("call-1", Protocol::OpenAiResponses),
            vec![tool_result_part()],
            provenance(),
        ));
        assert!(envelope.validate().is_ok());

        let mut empty_id = text_item("empty");
        empty_id.id = Some(OpaqueId::authentic("", Protocol::OpenAiResponses));
        let mut invalid = Envelope::new(Protocol::OpenAiResponses, "responses-test");
        invalid.items.push(empty_id);
        assert!(matches!(
            invalid.validate(),
            Err(IrValidationError::EmptyOpaqueId { field, .. }) if field == "id"
        ));
    }

    #[test]
    fn tool_items_require_exactly_one_matching_function_part() {
        let call_id = || OpaqueId::authentic("call-1", Protocol::OpenAi);

        let mut absent_call = Envelope::new(Protocol::OpenAi, "gpt-test");
        absent_call
            .items
            .push(Item::tool_call(call_id(), Vec::new(), provenance()));
        assert!(matches!(
            absent_call.validate(),
            Err(IrValidationError::InvalidItemShape { reason, .. })
                if reason == "tool_call_requires_one_call_function"
        ));

        let mut absent_result = Envelope::new(Protocol::OpenAi, "gpt-test");
        absent_result.items.push(Item::tool_call(
            call_id(),
            vec![tool_call_part()],
            provenance(),
        ));
        absent_result
            .items
            .push(Item::tool_result(call_id(), Vec::new(), provenance()));
        assert!(matches!(
            absent_result.validate(),
            Err(IrValidationError::InvalidItemShape { reason, .. })
                if reason == "tool_result_requires_one_result_function"
        ));

        let mut duplicate_call = Envelope::new(Protocol::OpenAi, "gpt-test");
        duplicate_call.items.push(Item::tool_call(
            call_id(),
            vec![tool_call_part(), tool_call_part()],
            provenance(),
        ));
        assert!(matches!(
            duplicate_call.validate(),
            Err(IrValidationError::InvalidItemShape { reason, .. })
                if reason == "tool_call_requires_one_call_function"
        ));

        let mut mismatched = Envelope::new(Protocol::OpenAi, "gpt-test");
        mismatched.items.push(Item::tool_call(
            call_id(),
            vec![tool_result_part()],
            provenance(),
        ));
        assert!(matches!(
            mismatched.validate(),
            Err(IrValidationError::InvalidItemShape { reason, .. })
                if reason == "tool_call_requires_one_call_function"
        ));

        let mut ordinary = Envelope::new(Protocol::OpenAi, "gpt-test");
        let mut ordinary_item = Item::new(ItemKind::Message, Role::Assistant, provenance());
        ordinary_item.push_part(tool_call_part());
        ordinary.items.push(ordinary_item);
        assert!(matches!(
            ordinary.validate(),
            Err(IrValidationError::InvalidItemShape { reason, .. })
                if reason == "ordinary_item_cannot_carry_function"
        ));
    }

    #[test]
    fn future_and_duplicate_tool_results_are_rejected() {
        let call_id = || OpaqueId::authentic("call-1", Protocol::OpenAi);
        let mut future = Envelope::new(Protocol::OpenAi, "gpt-test");
        future.items.push(Item::tool_result(
            call_id(),
            vec![tool_result_part()],
            provenance(),
        ));
        future.items.push(Item::tool_call(
            call_id(),
            vec![tool_call_part()],
            provenance(),
        ));
        assert!(matches!(
            future.validate(),
            Err(IrValidationError::OrphanToolResult { item_index: 0, .. })
        ));

        let mut duplicate = Envelope::new(Protocol::OpenAi, "gpt-test");
        duplicate.items.push(Item::tool_call(
            call_id(),
            vec![tool_call_part()],
            provenance(),
        ));
        duplicate.items.push(Item::tool_result(
            call_id(),
            vec![tool_result_part()],
            provenance(),
        ));
        duplicate.items.push(Item::tool_result(
            call_id(),
            vec![tool_result_part()],
            provenance(),
        ));
        assert!(matches!(
            duplicate.validate(),
            Err(IrValidationError::DuplicateToolResult {
                first_item_index: 1,
                second_item_index: 2,
                ..
            })
        ));

        let mut duplicate_calls = Envelope::new(Protocol::OpenAi, "gpt-test");
        duplicate_calls.items.push(Item::tool_call(
            call_id(),
            vec![tool_call_part()],
            provenance(),
        ));
        duplicate_calls.items.push(Item::tool_call(
            call_id(),
            vec![tool_call_part()],
            provenance(),
        ));
        assert!(matches!(
            duplicate_calls.validate(),
            Err(IrValidationError::DuplicateToolCallId {
                first_item_index: 0,
                second_item_index: 1,
                ..
            })
        ));
    }

    #[test]
    fn part_and_function_shapes_are_validated() {
        let mut envelope = Envelope::new(Protocol::Gemini, "gemini-test");
        let mut malformed = text_item("text");
        malformed.parts[0].media = Some(Media::new(MediaKind::Image));
        envelope.items.push(malformed);
        assert!(matches!(
            envelope.validate(),
            Err(IrValidationError::InvalidPartShape { reason, .. }) if reason == "text_payload"
        ));

        let mut opaque_payload = text_item("text");
        opaque_payload.parts[0].opaque =
            Some(OpaqueProviderState::authentic_gemini_thought_signature(
                "sig".to_owned(),
                Some("gemini-2.5-pro".to_owned()),
            ));
        let mut opaque_envelope = Envelope::new(Protocol::Gemini, "gemini-test");
        opaque_envelope.items.push(opaque_payload);
        assert!(matches!(
            opaque_envelope.validate(),
            Err(IrValidationError::InvalidPartShape { reason, .. }) if reason == "text_payload"
        ));

        let mut function_item = Item::new(ItemKind::Message, Role::Assistant, provenance());
        let mut function_part = Part::new(PartKind::Function);
        function_part.function = Some(FunctionData {
            kind: FunctionKind::Call,
            name: None,
            arguments: None,
            output: Some(JsonData::Null),
            extensions: ExtensionBag::new(),
        });
        function_item.parts.push(function_part);
        let mut function_envelope = Envelope::new(Protocol::Gemini, "gemini-test");
        function_envelope.items.push(function_item);
        assert!(matches!(
            function_envelope.validate(),
            Err(IrValidationError::InvalidFunctionShape { .. })
        ));

        let mut mismatched_item = Item::new(ItemKind::ToolResult, Role::Tool, provenance());
        mismatched_item
            .parts
            .push(Part::function(FunctionData::call("lookup", JsonData::Null)));
        let mut mismatched_envelope = Envelope::new(Protocol::Gemini, "gemini-test");
        mismatched_envelope.items.push(mismatched_item);
        assert!(matches!(
            mismatched_envelope.validate(),
            Err(IrValidationError::InvalidItemShape { reason, .. })
                if reason == "tool_result_requires_one_result_function"
        ));
    }

    #[test]
    fn reorder_failures_restore_the_original_order() {
        let mut envelope = Envelope::new(Protocol::Gemini, "gemini-test");
        envelope.items.push(text_item("first"));
        envelope.items.push(text_item("second"));
        envelope.items[1].parts[0].text = None;
        let before = envelope.items.clone();
        assert!(matches!(
            envelope.reorder_items(0, 1, Some(content_loss())),
            Err(IrMutationError::Validation(
                IrValidationError::InvalidPartShape { .. }
            ))
        ));
        assert_eq!(envelope.items, before);

        let mut parts = text_item("first");
        parts.push_part(Part::text("second"));
        parts.parts[1].text = None;
        let mut part_envelope = Envelope::new(Protocol::Gemini, "gemini-test");
        part_envelope.items.push(parts);
        let before_parts = part_envelope.items.clone();
        assert!(matches!(
            part_envelope.reorder_parts(0, 0, 1, Some(content_loss())),
            Err(IrMutationError::Validation(
                IrValidationError::InvalidPartShape { .. }
            ))
        ));
        assert_eq!(part_envelope.items, before_parts);
    }

    #[test]
    fn merge_failure_restores_both_items() {
        let mut left = text_item("left");
        left.push_part(Part::opaque(OpaqueProviderState {
            provider: String::new(),
            kind: "thought_signature".to_owned(),
            raw: JsonData::String("sig".to_owned()),
            provenance: OpaqueStateProvenance::Authentic,
            model: None,
        }));
        let right = text_item("right");
        let mut envelope = Envelope::new(Protocol::Gemini, "gemini-test");
        envelope.items.push(left);
        envelope.items.push(right);
        let before = envelope.items.clone();
        assert!(matches!(
            envelope.merge_items(0, 1, Some(content_loss())),
            Err(IrMutationError::Validation(
                IrValidationError::InvalidOpaqueState { .. }
            ))
        ));
        assert_eq!(envelope.items, before);
    }

    #[test]
    fn synthetic_state_is_not_claimed_exact() {
        let mut envelope = Envelope::new(Protocol::Gemini, "gemini-test");
        let mut item = text_item("stateful");
        item.push_part(Part::opaque(
            OpaqueProviderState::synthetic_gemini_thought_signature(None),
        ));
        envelope.push_item(item).expect("valid state");
        assert!(matches!(
            envelope.validate_exact_round_trip(),
            Err(ExactRoundTripError::SyntheticOpaqueState { .. })
        ));
    }

    #[test]
    fn synthetic_ids_and_unmodeled_fields_are_not_exact() {
        let mut envelope = Envelope::new(Protocol::OpenAi, "gpt-test");
        let mut item = text_item("id");
        item.id = Some(OpaqueId::synthetic("generated", Protocol::OpenAi));
        envelope.push_item(item).expect("valid synthetic id");
        assert!(matches!(
            envelope.validate_exact_round_trip(),
            Err(ExactRoundTripError::SyntheticOpaqueId { .. })
        ));

        let mut unknown = Envelope::new(Protocol::OpenAi, "gpt-test");
        let mut unknown_item = text_item("unknown");
        unknown_item.kind = ItemKind::Unknown("future_item".to_owned());
        unknown.items.push(unknown_item);
        assert!(matches!(
            unknown.validate_exact_round_trip(),
            Err(ExactRoundTripError::UnmodeledField { .. })
        ));
    }
}
