/* Copyright (C) 2026 LIghtJUNction. AGPL-3.0-or-later. */
import type { i18n } from 'i18next'
import { useTranslation } from 'react-i18next'

export const testKeyNamespace = 'test-key'
const languages = ['en', 'zhCN', 'zhTW', 'fr', 'ja', 'ru', 'vi'] as const
const rows = {
  downloadBookmark: [
    "Download bookmark with icon",
    "下载带图标书签",
    "下載含圖示的書籤",
    "Télécharger le favori avec son icône",
    "アイコン付きブックマークをダウンロード",
    "Скачать закладку со значком",
    "Tải dấu trang có biểu tượng",
  ],
  testPopup: [
    "Test popup",
    "测试弹窗",
    "測試彈出視窗",
    "Tester la fenêtre",
    "ポップアップを試す",
    "Проверить окно",
    "Thử cửa sổ bật lên",
  ],
  iconImportHelp: [
    "Dragging may not keep the icon. In Chrome, download this file, then use Import bookmarks in Bookmark manager. Existing bookmarks do not update automatically.",
    "拖拽不一定保留图标。Chrome 用户可下载此文件，再到书签管理器导入。已有书签不会自动更新。",
    "拖曳不一定保留圖示。Chrome 使用者可下載此檔案，再到書籤管理員匯入。現有書籤不會自動更新。",
    "Le glisser-déposer peut perdre l’icône. Dans Chrome, téléchargez ce fichier, puis importez-le dans le gestionnaire de favoris. Les anciens favoris ne sont pas mis à jour automatiquement.",
    "ドラッグではアイコンが保存されない場合があります。Chrome ではファイルをダウンロードし、ブックマーク マネージャからインポートしてください。既存のブックマークは自動更新されません。",
    "При перетаскивании значок может не сохраниться. В Chrome скачайте файл и импортируйте его через диспетчер закладок. Старые закладки не обновляются автоматически.",
    "Kéo thả có thể không giữ biểu tượng. Trong Chrome, tải tệp này rồi nhập trong Trình quản lý dấu trang. Dấu trang cũ không tự cập nhật.",
  ],
  installationCheck: [
    "After adding it, click the saved bookmark on a regular web page. If it opens a full page, check that its address starts with javascript:. If nothing opens, check the popup setting or use Open now.",
    "添加后，在普通网页点击保存的书签。若打开整页，请检查书签地址是否以 javascript: 开头；若没有反应，检查弹窗设置或使用“直接打开”。",
    "新增後，在一般網頁點擊儲存的書籤。若開啟整頁，請檢查書籤網址是否以 javascript: 開頭；若沒有反應，檢查彈出視窗設定或使用「直接開啟」。",
    "Après l’ajout, cliquez sur le favori enregistré depuis une page web. Si une page entière s’ouvre, vérifiez que son adresse commence par javascript:. Sinon, vérifiez le réglage des fenêtres ou utilisez Ouvrir maintenant.",
    "追加後、通常のウェブページで保存したブックマークをクリックしてください。ページ全体が開く場合は、URL が javascript: で始まるか確認してください。何も開かない場合はポップアップ設定を確認するか「今すぐ開く」を使用してください。",
    "После добавления нажмите сохранённую закладку на обычной веб-странице. Если открывается целая страница, проверьте, начинается ли адрес с javascript:. Если ничего не открывается, проверьте настройки всплывающих окон или нажмите «Открыть сейчас».",
    "Sau khi thêm, nhấn dấu trang đã lưu trên một trang web thông thường. Nếu mở cả trang, kiểm tra địa chỉ có bắt đầu bằng javascript: không. Nếu không có cửa sổ, kiểm tra cài đặt cửa sổ bật lên hoặc dùng Mở ngay.",
  ],
  title: [
    'Test API key',
    '测试 Key',
    '測試 Key',
    'Clé API de test',
    'テスト用 API キー',
    'Тестовый API-ключ',
    'Khóa API thử nghiệm',
  ],
  installTitle: [
    'A spare key, one bookmark away.',
    '要试个新工具？点一下书签。',
    '想試新工具？點一下書籤。',
    'Une clé de test dans vos favoris.',
    '新しいツールには、ブックマークからキーを。',
    'Ключ для теста — в закладке.',
    'Khóa thử nghiệm ngay trên dấu trang.',
  ],
  installBody: [
    'Drag this button to your bookmarks bar. Open it whenever a tool asks for an API key.',
    '把按钮拖到书签栏。下次遇到要填 API Key 的地方，点它就行。',
    '把按鈕拖到書籤列。下次需要填 API Key 時，點它就行。',
    'Glissez ce bouton dans la barre de favoris. Ouvrez-le quand un outil demande une clé API.',
    'ボタンをブックマークバーへドラッグ。API キーを求められたときに開けます。',
    'Перетащите кнопку на панель закладок. Открывайте её, когда инструмент запросит API-ключ.',
    'Kéo nút này lên thanh dấu trang. Mở khi công cụ yêu cầu khóa API.',
  ],
  bookmark: [
    'LMM Test Key',
    'LMM 测试 Key',
    'LMM 測試 Key',
    'Clé test LMM',
    'LMM テストキー',
    'Тестовый ключ LMM',
    'Khóa thử LMM',
  ],
  drag: [
    'Drag to bookmarks bar',
    '拖到书签栏',
    '拖到書籤列',
    'Glisser vers les favoris',
    'ブックマークバーへドラッグ',
    'Перетащить в закладки',
    'Kéo lên thanh dấu trang',
  ],
  open: [
    'Open now',
    '直接打开',
    '直接開啟',
    'Ouvrir maintenant',
    '今すぐ開く',
    'Открыть сейчас',
    'Mở ngay',
  ],
  tutorial: [
    'How to add it',
    '怎么放进书签栏',
    '怎麼放進書籤列',
    'Comment l’ajouter',
    '追加する方法',
    'Как добавить',
    'Cách thêm dấu trang',
  ],
  stepOne: [
    'Show the bookmarks bar',
    '打开书签栏',
    '開啟書籤列',
    'Afficher la barre de favoris',
    'ブックマークバーを表示',
    'Покажите панель закладок',
    'Hiện thanh dấu trang',
  ],
  shortcut: [
    'Chrome: Ctrl + Shift + B. On Mac: ⌘ + Shift + B.',
    'Chrome 按 Ctrl + Shift + B；Mac 按 ⌘ + Shift + B。',
    'Chrome 按 Ctrl + Shift + B；Mac 按 ⌘ + Shift + B。',
    'Chrome : Ctrl + Maj + B. Sur Mac : ⌘ + Maj + B.',
    'Chrome：Ctrl + Shift + B。Mac：⌘ + Shift + B。',
    'Chrome: Ctrl + Shift + B. На Mac: ⌘ + Shift + B.',
    'Chrome: Ctrl + Shift + B. Trên Mac: ⌘ + Shift + B.',
  ],
  stepTwo: [
    'Drag the button up',
    '把按钮往上拖',
    '把按鈕往上拖',
    'Glisser le bouton vers le haut',
    'ボタンを上にドラッグ',
    'Перетащите кнопку вверх',
    'Kéo nút lên trên',
  ],
  dragHelp: [
    'Drop it on the real bookmarks bar above this page, not on the demo.',
    '拖到浏览器真正的书签栏，不是右边的演示画面。',
    '拖到瀏覽器真正的書籤列，不是右邊的示範畫面。',
    'Déposez-le dans la vraie barre du navigateur, pas dans la démonstration.',
    'デモではなく、ブラウザーの実際のバーにドロップします。',
    'Отпустите на настоящей панели браузера, а не на демонстрации.',
    'Thả lên thanh dấu trang thật của trình duyệt, không phải hình minh họa.',
  ],
  stepThree: [
    'Need a key? Open the bookmark.',
    '要用 Key 时，点书签',
    '要用 Key 時，點書籤',
    'Besoin d’une clé ? Ouvrir le favori.',
    'キーが必要になったら開く',
    'Нужен ключ? Откройте закладку.',
    'Cần khóa? Mở dấu trang.',
  ],
  createHelp: [
    'In the popup, choose a budget, create a key and copy it back to the tool.',
    '在弹窗里设好额度，创建并复制，再粘贴回工具。',
    '在彈出視窗設定額度，建立並複製，再貼回工具。',
    'Dans la fenêtre, choisissez un quota, créez la clé puis collez-la dans l’outil.',
    '小窓で利用枠を設定してキーを作成・コピーし、ツールに貼り付けます。',
    'В окне задайте квоту, создайте ключ и вставьте его в инструмент.',
    'Trong cửa sổ, chọn hạn mức, tạo khóa rồi dán lại vào công cụ.',
  ],
  compatibility: [
    'Use desktop Chrome to drag. On mobile, blocked popups or browser settings pages, use Open now instead.',
    '拖拽请用电脑 Chrome。手机、弹窗被拦截或浏览器设置页打不开时，用“直接打开”。',
    '拖曳請用電腦 Chrome。手機、彈窗遭封鎖或瀏覽器設定頁無法開啟時，使用「直接開啟」。',
    'Utilisez Chrome sur ordinateur pour glisser. Sur mobile ou si la fenêtre est bloquée, utilisez Ouvrir maintenant.',
    'ドラッグは PC 版 Chrome で。スマホやポップアップが開かない場合は「今すぐ開く」を使ってください。',
    'Перетаскивание работает в Chrome на компьютере. На телефоне или при блокировке окна нажмите «Открыть сейчас».',
    'Dùng Chrome máy tính để kéo. Trên điện thoại hoặc khi cửa sổ bị chặn, chọn Mở ngay.',
  ],
  demo: [
    'Demo: drag the bookmark, then create and paste a test key.',
    '演示：拖入书签，再创建并粘贴测试 Key。',
    '示範：拖入書籤，再建立並貼上測試 Key。',
    'Démo : ajouter le favori, créer puis coller une clé de test.',
    'デモ：ブックマークを追加し、テストキーを作成して貼り付け。',
    'Демо: добавьте закладку, создайте и вставьте тестовый ключ.',
    'Minh họa: kéo dấu trang, tạo rồi dán khóa thử.',
  ],
  pause: [
    'Pause demo',
    '暂停演示',
    '暫停示範',
    'Mettre en pause',
    'デモを一時停止',
    'Приостановить демо',
    'Tạm dừng minh họa',
  ],
  play: [
    'Play demo',
    '播放演示',
    '播放示範',
    'Lancer la démo',
    'デモを再生',
    'Воспроизвести демо',
    'Phát minh họa',
  ],
  privacy: [
    'The bookmark stores no key and reads nothing from the page you are visiting.',
    '书签不保存 Key，也不读取你正在浏览的网页。',
    '書籤不儲存 Key，也不讀取你正在瀏覽的網頁。',
    'Le favori ne stocke aucune clé et ne lit pas la page visitée.',
    'ブックマークにキーを保存せず、閲覧中のページも読み取りません。',
    'Закладка не хранит ключ и не читает открытую страницу.',
    'Dấu trang không lưu khóa hay đọc trang đang xem.',
  ],
  budget: [
    'Spending limit ({{currency}})',
    '额度上限（{{currency}}）',
    '額度上限（{{currency}}）',
    'Quota maximal ({{currency}})',
    '利用上限（{{currency}}）',
    'Лимит расходов ({{currency}})',
    'Hạn mức ({{currency}})',
  ],
  scope: [
    'A separate key for testing. Charged to your account as usual; creating a key does not add credit.',
    '单独拿一个 Key 测试，调用照常从账户扣费。创建 Key 不会增加余额。',
    '用獨立 Key 測試，呼叫照常從帳戶扣費。建立 Key 不會增加餘額。',
    'Une clé séparée pour tester. Les appels sont facturés normalement ; créer une clé n’ajoute aucun crédit.',
    'テスト用に分けたキーです。通常どおり課金され、作成しても残高は増えません。',
    'Отдельный ключ для тестирования. Вызовы оплачиваются как обычно; создание не пополняет баланс.',
    'Khóa riêng để thử. Lần gọi vẫn tính phí bình thường; tạo khóa không thêm số dư.',
  ],
  lifetime: [
    'Quota-limited, not single-use. It does not expire automatically. Delete it from API Keys when finished.',
    '只限制额度，不是一次性 Key，也不会自动过期。用完到密钥页删除。',
    '僅限制額度，不是一次性 Key，也不會自動到期。用完到金鑰頁刪除。',
    'Limité par quota, pas à usage unique. Pas d’expiration automatique ; supprimez-le après usage.',
    '利用枠のみの制限で、使い捨てや自動失効ではありません。使い終わったら削除してください。',
    'Ограничен квотой, не одноразовый. Автоматически не истекает. Удалите после теста.',
    'Chỉ giới hạn hạn mức, không dùng một lần hay tự hết hạn. Xóa sau khi thử xong.',
  ],
  create: [
    'Create and copy',
    '创建并复制',
    '建立並複製',
    'Créer et copier',
    '作成してコピー',
    'Создать и скопировать',
    'Tạo và sao chép',
  ],
  saved: [
    'Created and copied. Paste it into your tool.',
    '已创建并复制，粘贴到工具里就行。',
    '已建立並複製，貼到工具裡就行。',
    'Créée et copiée. Collez-la dans votre outil.',
    '作成・コピーしました。ツールに貼り付けてください。',
    'Создан и скопирован. Вставьте в инструмент.',
    'Đã tạo và sao chép. Dán vào công cụ.',
  ],
  manualCopy: [
    'Key created. Copy it below; your browser did not allow clipboard access.',
    'Key 已创建。浏览器没允许复制，请点下面的复制按钮或手动复制。',
    'Key 已建立。瀏覽器未允許複製，請按下方複製按鈕或手動複製。',
    'Clé créée. Copiez-la ci-dessous : le presse-papiers est bloqué.',
    'キーを作成しました。クリップボードが使えないため、下からコピーしてください。',
    'Ключ создан. Скопируйте ниже: доступ к буферу обмена заблокирован.',
    'Đã tạo khóa. Hãy sao chép bên dưới vì trình duyệt chặn bộ nhớ tạm.',
  ],
  invalidBudget: [
    'Enter a positive, finite quota.',
    '填一个大于 0 的有效额度。',
    '填入大於 0 的有效額度。',
    'Saisissez un quota positif et valide.',
    '0 より大きい有効な利用枠を入力してください。',
    'Введите допустимую квоту больше нуля.',
    'Nhập hạn mức hợp lệ lớn hơn 0.',
  ],
  groupsFailed: [
    'Could not load available groups.',
    '分组没加载出来，请重试。',
    '分組未載入，請重試。',
    'Impossible de charger les groupes.',
    'グループを読み込めませんでした。',
    'Не удалось загрузить группы.',
    'Không tải được nhóm.',
  ],
  noGroups: [
    'No groups are available for this account.',
    '这个账户暂时没有可用分组。',
    '此帳戶暫時沒有可用分組。',
    'Aucun groupe disponible pour ce compte.',
    'このアカウントで使えるグループがありません。',
    'Для этого аккаунта нет доступных групп.',
    'Tài khoản chưa có nhóm khả dụng.',
  ],
  failed: [
    'Could not create the key. Check the message and try again.',
    'Key 没创建成功，检查提示后再试。',
    'Key 未建立成功，請檢查提示後再試。',
    'Impossible de créer la clé. Vérifiez le message.',
    'キーを作成できませんでした。表示内容を確認してください。',
    'Не удалось создать ключ. Проверьте сообщение.',
    'Không tạo được khóa. Kiểm tra thông báo rồi thử lại.',
  ],
  uncertain: [
    'Creation could not be confirmed. Check API Keys before trying again; a key may already exist.',
    '没能确认创建结果。先到密钥页检查，避免重复创建。',
    '無法確認建立結果。請先到金鑰頁檢查，避免重複建立。',
    'Création non confirmée. Vérifiez vos clés avant de réessayer.',
    '作成結果を確認できません。再試行前にキー一覧を確認してください。',
    'Результат неизвестен. Проверьте список ключей перед повтором.',
    'Chưa xác nhận được kết quả. Kiểm tra danh sách khóa trước khi thử lại.',
  ],
  login: [
    'Sign in to create a test key.',
    '先登录，再创建测试 Key。',
    '先登入，再建立測試 Key。',
    'Connectez-vous pour créer une clé de test.',
    'ログインしてテストキーを作成してください。',
    'Войдите, чтобы создать тестовый ключ.',
    'Đăng nhập để tạo khóa thử.',
  ],
  access: [
    'API access is not enabled yet. Complete account setup first.',
    '账户还没开通 API，先完成开通。',
    '帳戶尚未開通 API，請先完成開通。',
    'L’accès API n’est pas encore activé. Terminez la configuration.',
    'API 利用が未有効です。先にアカウントを設定してください。',
    'Доступ к API ещё не включён. Завершите настройку.',
    'Chưa bật truy cập API. Hoàn tất thiết lập trước.',
  ],
  frame: [
    'Open this page in its own window to create a key.',
    '请在独立窗口打开，再创建 Key。',
    '請在獨立視窗開啟，再建立 Key。',
    'Ouvrez cette page dans sa propre fenêtre.',
    '別のウィンドウで開いてください。',
    'Откройте страницу в отдельном окне.',
    'Mở trang này trong cửa sổ riêng.',
  ],
  oneTime: [
    'Copy it before closing. The full key is shown only here.',
    '关窗口前复制好，完整 Key 只在这里显示一次。',
    '關閉前請先複製，完整 Key 僅在此顯示一次。',
    'Copiez avant de fermer. La clé complète n’est affichée qu’ici.',
    '閉じる前にコピーしてください。完全なキーはここだけに表示されます。',
    'Скопируйте перед закрытием. Полный ключ показан только здесь.',
    'Sao chép trước khi đóng. Khóa đầy đủ chỉ hiện tại đây.',
  ],
  hidden: [
    'The key was hidden when you left this page. Manage it from API Keys.',
    '离开页面后已隐藏 Key，可到密钥页管理。',
    '離開頁面後已隱藏 Key，可到金鑰頁管理。',
    'La clé a été masquée en quittant la page. Gérez-la dans la liste des clés.',
    'ページを離れたためキーを非表示にしました。キー一覧で管理できます。',
    'Ключ скрыт после ухода со страницы. Управляйте им в списке ключей.',
    'Khóa đã ẩn khi rời trang. Quản lý trong danh sách khóa.',
  ],
  confirmGroup: [
    'I understand ({{current}}/{{total}})',
    '已了解（{{current}}/{{total}}）',
    '已瞭解（{{current}}/{{total}}）',
    'J’ai compris ({{current}}/{{total}})',
    '確認しました（{{current}}/{{total}}）',
    'Понятно ({{current}}/{{total}})',
    'Đã hiểu ({{current}}/{{total}})',
  ],
  setupTitle: [
    'Connect your first client.',
    '把客户端连上。',
    '把用戶端連上。',
    'Connectez votre premier client.',
    'クライアントを接続する。',
    'Подключите первый клиент.',
    'Kết nối ứng dụng đầu tiên.',
  ],
  setupBody: [
    'Create a key, copy the address, then choose your client. No conversation required.',
    '创建 Key，复制地址，再按你用的工具完成配置。',
    '建立 Key、複製位址，再依使用的工具完成設定。',
    'Créez une clé, copiez l’adresse et choisissez votre client.',
    'キーを作成し、アドレスをコピーして、ツールを設定します。',
    'Создайте ключ, скопируйте адрес и настройте нужный инструмент.',
    'Tạo khóa, sao chép địa chỉ rồi thiết lập công cụ.',
  ],
  keyStep: [
    'Start with a separate key',
    '先建一个 Key',
    '先建一個 Key',
    'Créer une clé séparée',
    'まずキーを作る',
    'Создайте отдельный ключ',
    'Tạo khóa riêng',
  ],
  keyBody: [
    'Just testing? Use a quota-limited key. Manage regular keys from API Keys.',
    '只是试用工具，就用小额度的测试 Key。长期使用的 Key 到密钥页创建。',
    '只是試用工具，可用小額度測試 Key。長期使用的 Key 請到金鑰頁建立。',
    'Pour un essai, utilisez un quota limité. Gérez les clés habituelles dans la liste des clés.',
    'お試しには少額のテストキーを。普段使うキーはキー一覧で作成できます。',
    'Для теста используйте небольшую квоту. Постоянные ключи создавайте в списке ключей.',
    'Dùng khóa hạn mức nhỏ để thử. Tạo khóa lâu dài trong danh sách khóa.',
  ],
  addressStep: [
    'Copy the API address',
    '复制接口地址',
    '複製介面位址',
    'Copier l’adresse API',
    'API アドレスをコピー',
    'Скопируйте адрес API',
    'Sao chép địa chỉ API',
  ],
  clientStep: [
    'Set up your client',
    '按工具完成配置',
    '依工具完成設定',
    'Configurer votre client',
    'ツールを設定',
    'Настройте клиент',
    'Thiết lập ứng dụng',
  ],
  clientBody: [
    'The guide covers Pi, DSH, Codewhale, SDKs and other clients. Get model IDs from Models and pricing.',
    'Pi、DSH、Codewhale、SDK 等都有配置步骤。模型名称到“模型与价格”里复制。',
    'Pi、DSH、Codewhale、SDK 等都有設定步驟。模型名稱可到「模型與價格」複製。',
    'Le guide couvre Pi, DSH, Codewhale et les SDK. Les identifiants sont dans Modèles et tarifs.',
    'Pi、DSH、Codewhale、SDK などの手順を用意。モデル名は「モデルと料金」で確認できます。',
    'В руководстве есть Pi, DSH, Codewhale и SDK. Названия моделей — в разделе моделей и цен.',
    'Hướng dẫn có Pi, DSH, Codewhale và SDK. Sao chép tên mô hình từ mục mô hình và giá.',
  ],
  help: [
    'Need help with setup?',
    '配置卡住了？',
    '設定遇到問題？',
    'Besoin d’aide ?',
    '設定で困ったら',
    'Нужна помощь?',
    'Cần trợ giúp thiết lập?',
  ],
} satisfies Record<
  string,
  readonly [string, string, string, string, string, string, string]
>

export type TestKeyCopyKey = keyof typeof rows
export const testKeyTranslations = Object.fromEntries(
  languages.map((language, index) => [
    language,
    Object.fromEntries(
      Object.entries(rows).map(([key, values]) => [key, values[index]])
    ),
  ])
) as Record<(typeof languages)[number], Record<TestKeyCopyKey, string>>
const registered = new WeakSet<i18n>()
export function registerTestKeyTranslations(instance: i18n) {
  if (registered.has(instance)) return
  for (const language of languages) {
    instance.addResourceBundle(
      language,
      testKeyNamespace,
      testKeyTranslations[language],
      true,
      false
    )
  }
  registered.add(instance)
}
export function useTestKeyCopy() {
  const { t, i18n: instance } = useTranslation()
  registerTestKeyTranslations(instance)
  return (key: TestKeyCopyKey, values?: Record<string, string | number>) =>
    String(t(key, { ...values, ns: testKeyNamespace }))
}
